### ISSUE TITLE
No such file or directory: '/etc/resolv.conf'

### ISSUE THREAD

**Issue by felipellrocha** [telepresenceio/telepresence#1000]
### What were you trying to do?

(please tell us)

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--run-shell', '--swap-deployment', 'master-api']`
Version: `0.99`
Python version: `3.7.3 (default, Mar 27 2019, 09:23:15) 
[Clang 10.0.1 (clang-1001.0.46.3)]`
kubectl version: `Client Version: v1.13.4 // Server Version: v1.13.4`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin fllr-pro-15.local 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 136, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 60, in main
    remote_info = start_proxy(runner)
  File "/usr/local/bin/telepresence/telepresence/proxy/__init__.py", line 89, in start_proxy
    runner_, deployment_arg, args.expose, add_custom_ns
  File "/usr/local/bin/telepresence/telepresence/proxy/deployment.py", line 173, in supplant_deployment
    add_custom_nameserver,
  File "/usr/local/bin/telepresence/telepresence/proxy/deployment.py", line 292, in new_swapped_deployment
    get_alternate_nameserver()
  File "/usr/local/bin/telepresence/telepresence/utilities.py", line 56, in get_alternate_nameserver
    banned = get_resolv_conf_namservers()
  File "/usr/local/bin/telepresence/telepresence/utilities.py", line 46, in get_resolv_conf_namservers
    with open("/etc/resolv.conf") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/etc/resolv.conf'

```

Logs:

```
ations see https://telepresence.io/reference/methods.html
   0.3 TEL | Found sshfs -> /usr/local/bin/sshfs
   0.3 TEL | Found umount -> /sbin/umount
   0.3 >>> | Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.
   0.3 TEL | [8] Running: kubectl --context minikube --namespace default get pods telepresence-connectivity-check --ignore-not-found
   0.4 TEL | [8] ran in 0.07 secs.
   0.4 TEL | Scout info: {'latest_version': '0.99', 'FAILED': '<urlopen error [Errno 8] nodename nor servname provided, or not known>'}
   0.4 TEL | BEGIN SPAN deployment.py:152(supplant_deployment)
   0.4 >>> | Starting network proxy to cluster by swapping out Deployment master-api with a proxy
   0.4 TEL | BEGIN SPAN remote.py:78(get_deployment_json)
   0.4 TEL | [9] Capturing: kubectl --context minikube --namespace default get deployment -o json master-api
   0.5 TEL | [9] captured in 0.07 secs.
   0.5 TEL | END SPAN remote.py:78(get_deployment_json)    0.1s

```

**Comment by ark3** [comment]
Sorry about the crash. Did you recently update MacOS?

**Comment by felipellrocha** [comment]
Have not. If it helps, things worked just fine by just try to run telepresence again without any other changes.
