### ISSUE TITLE
Failed to swap deployment for a go service

### ISSUE THREAD

**Issue by the-gigi** [telepresenceio/telepresence#1002]
### What were you trying to do?

I was trying to swap a deployment in a minikube cluster to run a Go service locally. Following the instructions in: https://www.telepresence.io/howto/golanghttps://www.telepresence.io/howto/golang

### What did you expect to happen?

I expected it to work :-)

### What happened instead?

It failed with the trace information you see below

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--swap-deployment', 'link-manager', '--expose', '8080', '--run', './link_service', '--port=8080']`
Version: `0.99`
Python version: `3.7.3 (default, Mar 27 2019, 09:23:15) 
[Clang 10.0.1 (clang-1001.0.46.3)]`
kubectl version: `Client Version: v1.14.0 // Server Version: v1.14.0`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin laptop.local 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 136, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 60, in main
    remote_info = start_proxy(runner)
  File "/usr/local/bin/telepresence/telepresence/proxy/__init__.py", line 95, in start_proxy
    run_id=run_id,
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 202, in get_remote_info
    wait_for_pod(runner, remote_info)
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 134, in wait_for_pod
    "Pod isn't starting or can't be found: {}".format(pod["status"])
RuntimeError: Pod isn't starting or can't be found: {'conditions': [{'lastProbeTime': None, 'lastTransitionTime': '2019-04-20T07:50:52Z', 'status': 'True', 'type': 'Initialized'}, {'lastProbeTime': None, 'lastTransitionTime': '2019-04-20T07:50:52Z', 'message': 'containers with unready status: [link-manager]', 'reason': 'ContainersNotReady', 'status': 'False', 'type': 'Ready'}, {'lastProbeTime': None, 'lastTransitionTime': '2019-04-20T07:50:52Z', 'message': 'containers with unready status: [link-manager]', 'reason': 'ContainersNotReady', 'status': 'False', 'type': 'ContainersReady'}, {'lastProbeTime': None, 'lastTransitionTime': '2019-04-20T07:50:52Z', 'status': 'True', 'type': 'PodScheduled'}], 'containerStatuses': [{'image': 'datawire/telepresence-k8s:0.99', 'imageID': '', 'lastState': {}, 'name': 'link-manager', 'ready': False, 'restartCount': 0, 'state': {'terminated': {'exitCode': 0, 'finishedAt': None, 'startedAt': None}}}], 'hostIP': '10.0.2.15', 'phase': 'Pending', 'qosClass': 'BestEffort', 'startTime': '2019-04-20T07:50:52Z'}

```

Logs:

```
81] Capturing: kubectl --context minikube --namespace default get pod link-manager-290d114b931c4cbeb4d8fc996d4728a5-5c566c84dc-x8vtz -o json
5000.3 281 | Error from server (NotFound): pods "link-manager-290d114b931c4cbeb4d8fc996d4728a5-5c566c84dc-x8vtz" not found
5000.3 TEL | [281] exit 1 in 0.73 secs.
5000.6 TEL | [282] Capturing: kubectl --context minikube --namespace default get pod link-manager-290d114b931c4cbeb4d8fc996d4728a5-5c566c84dc-x8vtz -o json
5000.7 282 | Error from server (NotFound): pods "link-manager-290d114b931c4cbeb4d8fc996d4728a5-5c566c84dc-x8vtz" not found
5000.7 TEL | [282] exit 1 in 0.18 secs.
5001.0 TEL | [283] Capturing: kubectl --context minikube --namespace default get pod link-manager-290d114b931c4cbeb4d8fc996d4728a5-5c566c84dc-x8vtz -o json
5005.8 283 | Error from server (NotFound): pods "link-manager-290d114b931c4cbeb4d8fc996d4728a5-5c566c84dc-x8vtz" not found
5005.8 TEL | [283] exit 1 in 4.83 secs.
5005.8 TEL | END SPAN remote.py:113(wait_for_pod)  122.2s

```

**Comment by the-gigi** [comment]
It seems to work now. When trying a 3td time a dialog box popped up asking to allow FUSE access to the system and then everything worked.

**Comment by the-gigi** [comment]
Here is the output:
```
$ telepresence --swap-deployment link-manager --expose 8080 --run ./link_service --port=8080
T: How Telepresence uses sudo: https://www.telepresence.io/reference/install#dependencies
T: Invoking sudo. Please enter your sudo password.
Password:
T: Starting proxy with method 'vpn-tcp', which has the following limitations: All processes are affected, only one telepresence can run per machine, and you can't use other VPNs. You may need to add cloud hosts and headless services with --also-proxy.
T: For a full list of method limitations see https://telepresence.io/reference/methods.html
T: Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.
T: Starting network proxy to cluster by swapping out Deployment link-manager with a proxy
T: Forwarding remote port 8080 to local port 8080.

T: Mounting remote volumes failed, they will be unavailable in this session. If you are running on Windows Subystem for Linux then see https://github.com/datawire/telepresence/issues/115, otherwise please report a bug, attaching telepresence.log to the
T:  bug report: https://github.com/datawire/telepresence/issues/new

T: Mount error was: mount_osxfuse: the file system is not available (1)
T: Guessing that Services IP range is 10.96.0.0/12. Services started after this point will be inaccessible if are outside this range; restart telepresence if you can't access a new Service.
T: Setup complete. Launching your command.
2019/04/20 01:07:05 DB host: 10.100.193.162 DB port: 5432
2019/04/20 01:07:05 Listening on port 8080...
