### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by robbybowler** [telepresenceio/telepresence#1018]
### What were you trying to do?

(please tell us)

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--swap-deployment', 'matrix-ana-reportjobs-api', '--expose', '80', '--docker-run', '-it', '-v', '/Users/robert.bowler/git.tcncloud.net/m/neo/services/ana/static/:/srv/http', '-p', '80:80', 'ana-reportjobs-api-telepresence', 'start', 'reportjobs-api']`
Version: `0.97`
Python version: `3.7.2 (default, Feb 12 2019, 08:15:36) 
[Clang 10.0.0 (clang-1000.11.45.5)]`
kubectl version: `Client Version: v1.13.3 // Server Version: v1.12.6-gke.10`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin TCN-10456.local 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 130, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 60, in main
    remote_info = start_proxy(runner)
  File "/usr/local/bin/telepresence/telepresence/proxy/__init__.py", line 104, in start_proxy
    run_id=run_id,
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 205, in get_remote_info
    wait_for_pod(runner, remote_info)
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 137, in wait_for_pod
    "Pod isn't starting or can't be found: {}".format(pod["status"])
RuntimeError: Pod isn't starting or can't be found: {'conditions': [{'lastProbeTime': None, 'lastTransitionTime': '2019-04-29T18:05:03Z', 'status': 'True', 'type': 'Initialized'}, {'lastProbeTime': None, 'lastTransitionTime': '2019-04-29T18:03:58Z', 'message': 'containers with unready status: [matrix-ana-reportjobs-api]', 'reason': 'ContainersNotReady', 'status': 'False', 'type': 'Ready'}, {'lastProbeTime': None, 'lastTransitionTime': '2019-04-29T18:03:58Z', 'message': 'containers with unready status: [matrix-ana-reportjobs-api]', 'reason': 'ContainersNotReady', 'status': 'False', 'type': 'ContainersReady'}, {'lastProbeTime': None, 'lastTransitionTime': '2019-04-29T18:03:58Z', 'status': 'True', 'type': 'PodScheduled'}], 'containerStatuses': [{'image': 'datawire/telepresence-k8s-priv:0.97', 'imageID': '', 'lastState': {}, 'name': 'matrix-ana-reportjobs-api', 'ready': False, 'restartCount': 0, 'state': {'waiting': {'reason': 'PodInitializing'}}}], 'hostIP': '10.128.0.75', 'initContainerStatuses': [{'containerID': 'docker://a890ed540dfedd4ce38c6b40169a973e15cc0bcdcc2ca53c648460bd14a74678', 'image': 'postgres:11.2', 'imageID': 'docker-pullable://postgres@sha256:e002abfaf7b0f1015b7510f66b709e2bacbecc7762c428634c27a3c5e58ffbae', 'lastState': {}, 'name': 'db-ready', 'ready': True, 'restartCount': 0, 'state': {'terminated': {'containerID': 'docker://a890ed540dfedd4ce38c6b40169a973e15cc0bcdcc2ca53c648460bd14a74678', 'exitCode': 0, 'finishedAt': '2019-04-29T18:05:03Z', 'reason': 'Completed', 'startedAt': '2019-04-29T18:05:03Z'}}}], 'phase': 'Pending', 'podIP': '10.76.3.112', 'qosClass': 'Burstable', 'startTime': '2019-04-29T18:03:58Z'}

```

Logs:

```
 -n echo -n
 121.3 TEL | [232] Capturing: kubectl --context gke_tcn-cloud-dev_us-central1-a_dev-1 --namespace default get pod matrix-ana-report-a761cc473d5a4af2993c73f89dc1e693-786dd55vv74w -o json
 121.9 TEL | [233] Capturing: kubectl --context gke_tcn-cloud-dev_us-central1-a_dev-1 --namespace default get pod matrix-ana-report-a761cc473d5a4af2993c73f89dc1e693-786dd55vv74w -o json
 122.4 TEL | [234] Capturing: kubectl --context gke_tcn-cloud-dev_us-central1-a_dev-1 --namespace default get pod matrix-ana-report-a761cc473d5a4af2993c73f89dc1e693-786dd55vv74w -o json
 122.9 TEL | [235] Capturing: kubectl --context gke_tcn-cloud-dev_us-central1-a_dev-1 --name

**Comment by ark3** [comment]
Sorry about the crash. Something about the deployment you're swapping appears to keep the Telepresence Kubernetes proxy from starting. Can you share information about the original deployment? Does a simpler command work okay, e.g., `telepresence --docker-run --rm -it fedora curl -k https://kubernetes.default/api/`?
