### ISSUE TITLE
Swap deployment issue

### ISSUE THREAD

**Issue by NicolaiSchmid** [telepresenceio/telepresence#1032]
### What were you trying to do?

(please tell us)

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below)

### Automatically included information

Command line: `['/usr/bin/telepresence', '--swap-deployment', 'dev-wasc-io-cloud', '--expose', '80:80', '--docker-run', '--rm', '-it', '-v', '/home/jerty/git/wasc/apis.wasc.io:/app', 'registry.nicolaischmid.de/wasc/apis.wasc.io:development-latest']`
Version: `0.93-9-g2b6114f`
Python version: `3.7.3 (default, Mar 26 2019, 21:43:19) 
[GCC 8.2.1 20181127]`
kubectl version: `Client Version: v1.14.0 // Server Version: v1.14.0`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux 987g8 4.14.113-1-MANJARO #1 SMP PREEMPT Sun Apr 21 12:03:01 UTC 2019 x86_64 GNU/Linux`
Traceback:

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 129, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 61, in main
    remote_info = start_proxy(runner)
  File "/usr/bin/telepresence/telepresence/proxy/__init__.py", line 84, in start_proxy
    runner_, deployment_arg, image_name, args.expose, add_custom_ns
  File "/usr/bin/telepresence/telepresence/proxy/deployment.py", line 127, in supplant_deployment
    "deployment",
  File "/usr/bin/telepresence/telepresence/proxy/remote.py", line 86, in get_deployment_json
    stderr=STDOUT
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

Logs:

```
nt-context
   0.3 TEL | [4] Capturing: kubectl config view -o json
   0.4 TEL | [5] Capturing: kubectl get ns default
   0.8 TEL | Command: kubectl 1.14.0
   0.8 TEL | Context: wasc, namespace: default, version: 1.14.0
   0.8 TEL | END SPAN startup.py:58(__init__)    0.8s
   0.8 TEL | [6] Capturing: ssh -V
   0.9 TEL | [7] Running: sudo -n echo -n
   0.9 >>> | Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.
   0.9 TEL | [8] Capturing: kubectl --context wasc --namespace default get pods telepresence-connectivity-check --ignore-not-found
   1.9 TEL | Scout info: {'latest_version': '0.99', 'application': 'telepresence', 'notices': []}
   1.9 TEL | BEGIN SPAN deployment.py:120(supplant_deployment)
   1.9 TEL | BEGIN SPAN remote.py:73(get_deployment_json)
   1.9 TEL | [9] Capturing: kubectl --context wasc --namespace default get deployment -o json --export dev-wasc-io-cloud
   2.2 TEL | END SPAN remote.py:73(get_deployment_json)    0.3s

```

**Comment by ark3** [comment]
Sorry about the crash. Can you please try again with the latest version?

**Comment by NicolaiSchmid** [comment]
Sorry about that! Works with v0.99
