### ISSUE TITLE
Telepresence in helloworkd

### ISSUE THREAD

**Issue by pius-ho** [telepresenceio/telepresence#1048]
### What were you trying to do?

(please tell us)

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/bin/telepresence', '--swap-deployment', 'hello-world', '--docker-run', '--rm', '-it', '-v', '/home/chungathp/workspace/hello-world:/usr/src/app', 'hello-d']`
Version: `0.99`
Python version: `3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609]`
kubectl version: `Client Version: v1.9.3 // Server Version: v1.8.0`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Linux dadmin-workstation.dsab.eud-000894.homeoffice.gov.uk 4.4.0-150-generic #176-Ubuntu SMP Wed May 29 18:56:26 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 136, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 77, in main
    runner, remote_info, env, socks_port, ssh, mount_dir, pod_info
  File "/usr/bin/telepresence/telepresence/outbound/setup.py", line 95, in launch
    mount_dir, pod_info
  File "/usr/bin/telepresence/telepresence/outbound/container.py", line 169, in run_docker_command
    TELEPRESENCE_LOCAL_IMAGE, "wait"
  File "/usr/bin/telepresence/telepresence/runner/runner.py", line 424, in check_call
    env,
  File "/usr/bin/telepresence/telepresence/runner/runner.py", line 399, in _run_command_sync
    None if stderr_to_stdout else err_logger.get_captured(),
subprocess.CalledProcessError: Command '['docker', 'run', '--network=container:telepresence-1560247232-3365257-14066', '--rm', 'datawire/telepresence-local:0.99', 'wait']' returned non-zero exit status 1

```

Logs:

```
est from ('172.17.0.2', 45009) to None: 62 bytes
  15.9  23 | c : DNS request from ('172.17.0.2', 55244) to None: 62 bytes
  18.4  23 | c : DNS request from ('172.17.0.2', 55244) to None: 62 bytes
  21.0  23 | c : DNS request from ('172.17.0.2', 40345) to None: 62 bytes
  23.5  23 | c : DNS request from ('172.17.0.2', 40345) to None: 62 bytes
  26.1  23 | c : DNS request from ('172.17.0.2', 48844) to None: 62 bytes
  28.6  23 | c : DNS request from ('172.17.0.2', 48844) to None: 62 bytes
  30.4 TEL | [28] Running: sudo -n echo -n
  30.4 TEL | [28] ran in 0.03 secs.
  31.2  23 | c : DNS request from ('172.17.0.2', 51704) to None: 62 bytes
  32.9 TEL | (proxy checking local liveness)
  32.9  16 | 2019-06-11T10:01:03+0000 [Poll#info] Checkpoint
  33.7  23 | c : DNS request from ('172.17.0.2', 51704) to None: 62 bytes
  36.3  27 | Failed to connect to proxy in remote cluster.
  36.3  27 | [INFO  tini (1)] Main child exited normally (with status '1')
  36.5 TEL | [27] exit 1 in 31.35 secs.

```

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
