### ISSUE TITLE
Telepresence does not work in containerized development environments

### ISSUE THREAD

**Issue by ZacharyJoswick** [telepresenceio/telepresence#1053]
### What were you trying to do?
At my company we attempt to containerize all development environments to ensure consistency. To accomplish this we use the vscode remote development extension, specifically utilizing the devcontainer feature. We are starting a new project using kubernetes, and telepresence solves many of the reservations we were having with development speed and hot reload. 

My command is:
```telepresence --swap-deployment frontend-v1:nginx --run <my dev server command>```
On my machine nativley this works perfectly

### What did you expect to happen?
I expected that telepresence would behave similarly to my native environment.

### What happened instead?
Telepresence begins to initialize, but fails with the following info:
```
T: Starting proxy with method 'vpn-tcp', which has the following limitations: All processes are affected, only one telepresence can run per machine, and you can't use other VPNs. You may need to add 
T: cloud hosts and headless services with --also-proxy. For a full list of method limitations see https://telepresence.io/reference/methods.html
T: Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.
T: Starting network proxy to cluster by swapping out Deployment frontend-v1:nginx with a proxy
T: Forwarding remote port 8080 to local port 8080.

T: Mounting remote volumes failed, they will be unavailable in this session. If you are running on Windows Subystem for Linux then see https://github.com/datawire/telepresence/issues/115, otherwise 
T: please report a bug, attaching telepresence.log to the bug report: https://github.com/datawire/telepresence/issues/new

T: Mount error was: fuse: device not found, try 'modprobe fuse' first
T: Guessing that Services IP range is 10.43.0.0/16. Services started after this point will be inaccessible if are outside this range; restart telepresence if you can't access a new Service.

Looks like there's a bug in our code. Sorry about that!

Background process (sshuttle) exited with return code 99. Command was:
  sshuttle-telepresence -v --dns --method nat -e 'ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null' -r telepresence@127.0.0.1:44255 --to-ns 127.0.0.1:9053 10.42.0.0/24 10.43.0.0/16

Recent output was:
  firewall manager: ---> Traceback (most recent call last):
  firewall manager: --->   File "/root/.pex/install/sshuttle_telepresence-0.78.2.dev45+gd250ccb-py2.py3-none-any.whl.73b9c6a0c49d6b6bf7533478d454b7be51b9d990/sshuttle_telepresence-0.78.2.dev45+gd250ccb-py2.py3-none-any.whl/sshuttle/firewall.py", line 274, in main
  firewall manager: --->     restore_etc_hosts(port_v6 or port_v4)
  firewall manager: --->   File "/root/.pex/install/sshuttle_telepresence-0.78.2.dev45+gd250ccb-py2.py3-none-any.whl.73b9c6a0c49d6b6bf7533478d454b7be51b9d990/sshuttle_telepresence-0.78.2.dev45+gd250ccb-py2.py3-none-any.whl/sshuttle/firewall.py", line 50, in restore_etc_hosts
  firewall manager: --->     rewrite_etc_hosts({}, port)
  firewall manager: --->   File "/root/.pex/install/sshuttle_telepresence-0.78.2.dev45+gd250ccb-py2.py3-none-any.whl.73b9c6a0c49d6b6bf7533478d454b7be51b9d990/sshuttle_telepresence-0.78.2.dev45+gd250ccb-py2.py3-none-any.whl/sshuttle/firewall.py", line 29, in rewrite_etc_hosts
  firewall manager: --->     os.link(HOSTSFILE, BAKFILE)
  firewall manager: ---> OSError: [Errno 18] Invalid cross-device link: '/etc/hosts' -> '/etc/hosts.sbak'
  fatal: ['iptables', '-t', 'nat', '-nL'] returned 3
  c : fatal: cleanup: ['/usr/bin/python3', '/usr/libexec/sshuttle-telepresence', '-v', '--method', 'nat', '--firewall'] returned 99

Here are the last few lines of the logfile (see /workspaces/radas_utilities_frontend/application/telepresence.log for the complete logs):

  18.1  69 | firewall manager: --->   File "/root/.pex/install/sshuttle_telepresence-0.78.2.dev45+gd250ccb-py2.py3-none-any.whl.73b9c6a0c49d6b6bf7533478d454b7be51b9d990/sshuttle_telepresence-0.78.2.dev45+gd250ccb-py2.py3-none-any.whl/sshuttle/firewall.py", line 29, in rewrite_etc_hosts
  18.1  69 | firewall manager: --->     os.link(HOSTSFILE, BAKFILE)
  18.1  69 | firewall manager: ---> OSError: [Errno 18] Invalid cross-device link: '/etc/hosts' -> '/etc/hosts.sbak'
  18.1  69 | fatal: ['iptables', '-t', 'nat', '-nL'] returned 3
  18.1 TEL | [77] exit 1 in 0.23 secs.
  18.2  69 | c : fatal: cleanup: ['/usr/bin/python3', '/usr/libexec/sshuttle-telepresence', '-v', '--method', 'nat', '--firewall'] returned 99
  18.2 TEL | [69] sshuttle: exit 99
  18.2 TEL | Wait for vpn-tcp connection: hellotelepresence-4
  18.2 TEL | [78] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-4")'
  18.4 TEL | [78] exit 1 in 0.12 secs.
  18.4 TEL | [79] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-4.a.sanity.check.telepresence.io")'
  18.5 TEL | [79] exit 1 in 0.12 secs.
```

### Other Information
Command line: ```telepresence --swap-deployment frontend-v1:nginx --run <my command>```
Version: ```0.100```
Python version: ```Python 3.5.3```
kubectl version: ```Client Version: v1.14.3 Server Version: v1.14.1-k3s.4```
OS: ```Linux 2c7e2a2f66e6 4.15.0-51-generic #55~16.04.1-Ubuntu SMP Thu May 16 09:24:37 UTC 2019 x86_64 GNU/Linux```

### Hypothesis
Form my 2 seconds of looking at the error and from a bit of background info on how docker works, it appears to be an issue with copying and editing the hosts file. Docker mounts the host file from the host machine, and as such it technically exists on a separate drive from where the copy would. The following is the output of a df command:
```
root@2c7e2a2f66e6:/etc# df -a
Filesystem     1K-blocks      Used Available Use% Mounted on
<truncated for conciseness>
/dev/nvme0n1p5 413842464 325189088  67608336  83% /etc/resolv.conf
/dev/nvme0n1p5 413842464 325189088  67608336  83% /etc/hostname
/dev/nvme0n1p5 413842464 325189088  67608336  83% /etc/hosts
shm                65536         0     65536   0% /dev/shm
tmpfs            1608584      1696   1606888   1% /run/docker.sock
<truncated for conciseness>
```
This falls in line with the output from telepresence in the error log above:
```
  firewall manager: --->     rewrite_etc_hosts({}, port)
  firewall manager: --->   File "/root/.pex/install/sshuttle_telepresence-0.78.2.dev45+gd250ccb-py2.py3-none-any.whl.73b9c6a0c49d6b6bf7533478d454b7be51b9d990/sshuttle_telepresence-0.78.2.dev45+gd250ccb-py2.py3-none-any.whl/sshuttle/firewall.py", line 29, in rewrite_etc_hosts
  firewall manager: --->     os.link(HOSTSFILE, BAKFILE)
  firewall manager: ---> OSError: [Errno 18] Invalid cross-device link: '/etc/hosts' -> '/etc/hosts.sbak'
```

From an additional 2 seconds of googling this appears to be a limitation of the python os.rename method [Relevant StackOverflow Link](https://stackoverflow.com/questions/42392600/oserror-errno-18-invalid-cross-device-link). 

I don't think that this perfectly explains the initial issues of mounting remote volumes failing, but it might be related. 

Ultimately it seems like using shutil.move (as mentioned in the StackOverflow post) could potentially solve some of the problems.

May be related to #965, #362

Log file for reference:
[telepresence.log](https://github.com/telepresenceio/telepresence/files/3302416/telepresence.log)

**Comment by ZacharyJoswick** [comment]
If desired I can provide a .devcontainer configuration and instructions for setting it up to reproduce a similar environment

**Comment by ark3** [comment]
Sorry about the crash. Being able to reproduce your setup would be very helpful. But perhaps even before that:

- The crash is from `sshuttle`; the volume mount error (`sshfs` and `fuse`) is a distraction. Maybe you need volume mounts to work, in which case we should resolve that too, but I suggest we fix the crash first.
- The `sshuttle` crash includes output from its attempt to clean up. The `Invalid cross-device link` traceback is part of that cleanup process; that too is not the real crash.
- The real crash is this: `fatal: ['iptables', '-t', 'nat', '-nL'] returned 3`. In other words, `iptables` is unable to adjust the network. Earlier in the telepresence.log there is:
  ```
  18.1  69 | iptables v1.6.0: can't initialize iptables table `nat': Permission denied (you must be root)
  18.1  69 | Perhaps iptables or your kernel needs to be upgraded.
  ```

Can you try running your development environment in a privileged container? 

Telepresence needs at least some additional some capabilities: `CAP_NET_ADMIN` for sure, maybe `CAP_NET_BIND_SERVICE`, and maybe others? I haven't had a chance to narrow this down properly, but it should be possible to construct a set of capabilities that doesn't go as far as a full privileged container.

**Comment by ZacharyJoswick** [comment]
Thank you for responding so quickly. I tried the container with the ```CAP_NET_ADMIN``` and ```CAP_NET_BIND_SERVICE``` options and can confirm that it is now working as expected. 

I setup an example repository with a minimal configuration to get telepresence to work in vscode remote containers. Feel free to use it as you guys see fit (may be useful to figure out the volume mount issue).

https://github.com/ZacharyJoswick/vscode-remote-telepresence

**Comment by ZacharyJoswick** [comment]
I'm going to close this issue for now. If I run into anything else I'll reopen or make a new one if its a different problem.

**Comment by ark3** [comment]
Thank you for the example repository. Would you like to write a blog post talking about this work?

**Comment by ZacharyJoswick** [comment]
Sure thing, I can write something up.

**Comment by dmitshap** [comment]
Sorry if I'm beating a dead horse here, this keeps happening for me:

```
Looks like there's a bug in our code. Sorry about that!

Background process (kubectl port-forward) exited with return code 0. Command was:
  kubectl --context <my_context> --namespace <my_namespace> port-forward myserver 37741:8022

Recent output was:
  Handling connection for 37741
  Handling connection for 37741
  Handling connection for 37741
  Handling connection for 37741
  Handling connection for 37741
  Handling connection for 37741
  Handling connection for 37741
  Handling connection for 37741
  E0301 15:46:18.241804    1128 portforward.go:385] error copying from local connection to remote stream: write tcp 172.17.0.3:45140->10.20.151.48:6443: write: connection reset by peer
  E0301 15:46:18.242213    1128 portforward.go:233] lost connection to pod

Background process (SSH port forward (socks and proxy poll)) exited with return code 255. Command was:
  ssh -N -oServerAliveInterval=1 -oServerAliveCountMax=10 -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oConnectTimeout=5 -vv -p 37741 telepresence@127.0.0.1 -L127.0.0.1:35647:127.0.0.1:9050 -R9055:127.0.0.1:34041

Recent output was:
  debug2: channel 1: is dead
  debug2: channel 1: garbage collecting
  debug1: channel 1: free: 127.0.0.1, nchannels 2
  debug1: client_input_global_request: rtype keepalive@openssh.com want_reply 1
  debug1: client_input_global_request: rtype keepalive@openssh.com want_reply 1
  debug1: channel 0: free: port listener, nchannels 1
  Connection to 127.0.0.1 closed by remote host.
  Transferred: sent 2904, received 3780 bytes, in 29.5 seconds
  Bytes per second: sent 98.3, received 128.0
  debug1: Exit status -1

Background process (sshuttle) exited with return code 99. Command was:
  sshuttle-telepresence -v --dns --method nat -e 'ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oConnectTimeout=5' -r telepresence@127.0.0.1:37741 --to-ns 127.0.0.1:9053 10.96.0.0/12 10.20.128.0/17

Recent output was:
  firewall manager: Error trying to undo /etc/hosts changes.
  firewall manager: ---> Traceback (most recent call last):
  firewall manager: --->   File "/root/.pex/installed_wheels/b9a99f237adb2ba53a57e284de2521655b6ed14e/sshuttle_telepresence-0.78.2.dev45+gd250ccb-py2.py3-none-any.whl/sshuttle/firewall.py", line 274, in main
  firewall manager: --->     restore_etc_hosts(port_v6 or port_v4)
  firewall manager: --->   File "/root/.pex/installed_wheels/b9a99f237adb2ba53a57e284de2521655b6ed14e/sshuttle_telepresence-0.78.2.dev45+gd250ccb-py2.py3-none-any.whl/sshuttle/firewall.py", line 50, in restore_etc_hosts
  firewall manager: --->     rewrite_etc_hosts({}, port)
  firewall manager: --->   File "/root/.pex/installed_wheels/b9a99f237adb2ba53a57e284de2521655b6ed14e/sshuttle_telepresence-0.78.2.dev45+gd250ccb-py2.py3-none-any.whl/sshuttle/firewall.py", line 29, in rewrite_etc_hosts
  firewall manager: --->     os.link(HOSTSFILE, BAKFILE)
  firewall manager: ---> OSError: [Errno 18] Invalid cross-device link: '/etc/hosts' -> '/etc/hosts.sbak'
  c : fatal: server died with error code 255

Here are the last few lines of the logfile (see /workspaces/myproject/telepresence.log for the complete logs):

  45.3  44 | firewall manager: Error trying to undo /etc/hosts changes.
  45.3  44 | firewall manager: ---> Traceback (most recent call last):
  45.3  44 | firewall manager: --->   File "/root/.pex/installed_wheels/b9a99f237adb2ba53a57e284de2521655b6ed14e/sshuttle_telepresence-0.78.2.dev45+gd250ccb-py2.py3-none-any.whl/sshuttle/firewall.py", line 274, in main
  45.3  44 | firewall manager: --->     restore_etc_hosts(port_v6 or port_v4)
  45.3  44 | firewall manager: --->   File "/root/.pex/installed_wheels/b9a99f237adb2ba53a57e284de2521655b6ed14e/sshuttle_telepresence-0.78.2.dev45+gd250ccb-py2.py3-none-any.whl/sshuttle/firewall.py", line 50, in restore_etc_hosts
  45.3  44 | firewall manager: --->     rewrite_etc_hosts({}, port)
  45.3  44 | firewall manager: --->   File "/root/.pex/installed_wheels/b9a99f237adb2ba53a57e284de2521655b6ed14e/sshuttle_telepresence-0.78.2.dev45+gd250ccb-py2.py3-none-any.whl/sshuttle/firewall.py", line 29, in rewrite_etc_hosts
  45.3  44 | firewall manager: --->     os.link(HOSTSFILE, BAKFILE)
  45.3  44 | firewall manager: ---> OSError: [Errno 18] Invalid cross-device link: '/etc/hosts' -> '/etc/hosts.sbak'
  45.3  44 | c : fatal: server died with error code 255
  45.4 TEL | [44] sshuttle: exit 99
  46.2 TEL | [46] timed out after 1.01 secs.
```

My `runArgs` are same as @ZacharyJoswick recommended. 
Dev container is `FROM mcr.microsoft.com/vscode/devcontainers/go`
Command: `env TELEPRESENCE_REGISTRY=path/to/docker/registry \
telepresence --namespace <my_namespace> --verbose --new-deployment myserver --run-shell`
Telepresence version: `0.109`
Python version: `3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]`
