### ISSUE TITLE
Some bug on openshift with swap-deployment

### ISSUE THREAD

**Issue by dbazhal** [telepresenceio/telepresence#1068]
### What were you trying to do?

```
telepresence --verbose --swap-deployment gogo --method inject-tcp --run-shell
```

### What did you expect to happen?

expect it to work

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--verbose', '--swap-deployment', 'gogo', '--method', 'inject-tcp', '--run-shell']`
Version: `0.101`
Python version: `3.6.5 (default, Mar 31 2018, 19:45:04) [GCC]`
kubectl version: `Client Version: v1.11.0+d4cacc0 // Server Version: v1.11.0+d4cacc0`
oc version: `oc v3.11.0+0cbc58b // kubernetes v1.11.0+d4cacc0 // features: Basic-Auth GSSAPI Kerberos SPNEGO //  // Server https://mts-preprod-platform.tutu.ru:443 // openshift v3.11.0+3a34b96-217 // kubernetes v1.11.0+d4cacc0`
OS: `Linux bajal 4.12.14-lp151.28.4-default #1 SMP Fri May 24 07:57:46 UTC 2019 (af35fd1) x86_64 x86_64 x86_64 GNU/Linux`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 136, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 60, in main
    remote_info = start_proxy(runner)
  File "/usr/local/bin/telepresence/telepresence/proxy/__init__.py", line 96, in start_proxy
    runner_, deployment_arg, args.expose, add_custom_ns
  File "/usr/local/bin/telepresence/telepresence/proxy/deployment.py", line 409, in swap_deployment_openshift
    apply_json(new_dc_json)
  File "/usr/local/bin/telepresence/telepresence/proxy/deployment.py", line 381, in apply_json
    input=json.dumps(json_config).encode("utf-8")
  File "/usr/local/bin/telepresence/telepresence/runner/runner.py", line 424, in check_call
    env,
  File "/usr/local/bin/telepresence/telepresence/runner/runner.py", line 399, in _run_command_sync
    None if stderr_to_stdout else err_logger.get_captured(),
subprocess.CalledProcessError: Command '['oc', '--context', 'mtp-testing/mts-preprod-platform-tutu-ru:443/bajal', '--namespace', 'mtp-testing', 'replace', '-f', '-']' returned non-zero exit status 1.

```

Logs:

```
  2.8  13 |                 "securityContext": {},
   2.8  13 |                 "terminationGracePeriodSeconds": 30
   2.8  13 |             }
   2.8  13 |         },
   2.8  13 |         "test": false,
   2.8  13 |         "triggers": []
   2.8  13 |     },
   2.8  13 |     "status": {
   2.8  13 |         "availableReplicas": 0,
   2.8  13 |         "latestVersion": 0,
   2.8  13 |         "observedGeneration": 0,
   2.8  13 |         "replicas": 0,
   2.8  13 |         "unavailableReplicas": 0,
   2.8  13 |         "updatedReplicas": 0
   2.8  13 |     }
   2.8  13 | }
   2.8 TEL | [13] captured in 0.20 secs.
   2.8 TEL | [14] Running: oc --context mtp-testing/mts-preprod-platform-tutu-ru:443/bajal --namespace mtp-testing replace -f -
   3.0  14 | The DeploymentConfig "gogo" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"telepresence":"f41d8e206cee4a11a131cea9630c5519"}: `selector` does not match template `labels`
   3.0 TEL | [14] exit 1 in 0.19 secs.

```

**Comment by ark3** [comment]
Sorry about the crash. I will need to investigate further. Can you please pass along the full telepresence.log as a GitHub Gist? Thank you.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
