### ISSUE TITLE
Telepresence crashes on (new) ssh timeout

### ISSUE THREAD

**Issue by wittfeldt** [telepresenceio/telepresence#1075]
### What were you trying to do?

Start telepresence shell with "telepresence" command

### What did you expect to happen?

A new telepresence shell to be started

### What happened instead?

It crashed.

### Automatically included information

Command line: `['/usr/local/bin/telepresence']`
Version: `0.101`
Python version: `3.7.4 (default, Jul  9 2019, 18:15:00) 
[Clang 10.0.0 (clang-1000.11.45.5)]`
kubectl version: `Client Version: v1.14.1 // Server Version: v1.12.7-gke.25`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin Anderss-MBP 17.7.0 Darwin Kernel Version 17.7.0: Wed Feb 27 00:43:23 PST 2019; root:xnu-4570.71.35~1/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 136, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 63, in main
    socks_port, ssh = do_connect(runner, remote_info)
  File "/usr/local/bin/telepresence/telepresence/connect/connect.py", line 104, in do_connect
    return connect(runner_, remote_info, is_container_mode, args.expose)
  File "/usr/local/bin/telepresence/telepresence/connect/connect.py", line 59, in connect
    if not ssh.wait():
  File "/usr/local/bin/telepresence/telepresence/connect/ssh.py", line 80, in wait
    self.runner.check_call(self.command(["/bin/true"]), timeout=5)
  File "/usr/local/bin/telepresence/telepresence/runner/runner.py", line 424, in check_call
    env,
  File "/usr/local/bin/telepresence/telepresence/runner/runner.py", line 388, in _run_command_sync
    None if stderr_to_stdout else err_logger.get_captured(),
subprocess.TimeoutExpired: Command '['ssh', '-F', '/dev/null', '-oStrictHostKeyChecking=no', '-oUserKnownHostsFile=/dev/null', '-q', '-p', '61433', 'telepresence@127.0.0.1', '/bin/true']' timed out after 5 seconds

```

Logs:

```
le=/dev/null -q -p 61433 telepresence@127.0.0.1 /bin/true
  45.2 TEL | [37] exit 255 in 0.03 secs.
  45.5 TEL | [38] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 61433 telepresence@127.0.0.1 /bin/true
  45.5 TEL | [38] exit 255 in 0.02 secs.
  45.7 TEL | [39] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 61433 telepresence@127.0.0.1 /bin/true
  45.8 TEL | [39] exit 255 in 0.02 secs.
  46.0 TEL | [40] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 61433 telepresence@127.0.0.1 /bin/true
  46.0 TEL | [40] exit 255 in 0.02 secs.
  46.3 TEL | [41] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 61433 telepresence@127.0.0.1 /bin/true
  46.3  16 | Forwarding from 127.0.0.1:61433 -> 8022
  46.3  16 | Forwarding from [::1]:61433 -> 8022
  46.3  16 | Handling connection for 61433
  51.3 TEL | [41] timed out after 5.01 secs.

```

**Comment by ark3** [comment]
Sorry about the crash! We'll have the fixed in the next release.
