### ISSUE TITLE
Unable to swap-deployment, SSH failed

### ISSUE THREAD

**Issue by aayushthakkaryouco** [telepresenceio/telepresence#1081]
### What were you trying to do?

Swapping the binary from local machine to the pod in cluster

### What did you expect to happen?

Expected the swap

### What happened instead?

Cannot deploy. Here is: [telepresence.log](https://gist.github.com/aayushthakkaryouco/3dc6414ec579b67b8eabdc073af7ee61)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--expose', '8888', '--namespace', 'app', '--swap-deployment', 'my-dev-deployment', '--run', './my-app-binary']`
Version: `0.100`
Python version: `3.7.3 (default, Mar 27 2019, 09:23:15) 
[Clang 10.0.1 (clang-1001.0.46.3)]`
kubectl version: `Client Version: v1.12.2 // Server Version: v1.12.8`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin mys-MacBook-Pro.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 136, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 63, in main
    socks_port, ssh = do_connect(runner, remote_info)
  File "/usr/local/bin/telepresence/telepresence/connect/connect.py", line 104, in do_connect
    return connect(runner_, remote_info, is_container_mode, args.expose)
  File "/usr/local/bin/telepresence/telepresence/connect/connect.py", line 60, in connect
    raise RuntimeError("SSH to the cluster failed to start.")
RuntimeError: SSH to the cluster failed to start.

```

Logs:

```
ling connection for 60776
  43.6  47 | Connection to 127.0.0.1 closed by remote host.
  43.6 TEL | [47] exit 255 in 0.88 secs.
  43.8 TEL | [48] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 60776 telepresence@127.0.0.1 /bin/true
  43.8  19 | Handling connection for 60776
  44.7  48 | Connection to 127.0.0.1 closed by remote host.
  44.7 TEL | [48] exit 255 in 0.89 secs.
  45.0 TEL | [49] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 60776 telepresence@127.0.0.1 /bin/true
  45.0  19 | Handling connection for 60776
  45.8  49 | Connection to 127.0.0.1 closed by remote host.
  45.8 TEL | [49] exit 255 in 0.87 secs.
  46.1 TEL | [50] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 60776 telepresence@127.0.0.1 /bin/true
  46.1  19 | Handling connection for 60776
  47.0  50 | Connection to 127.0.0.1 closed by remote host.
  47.0 TEL | [50] exit 255 in 0.89 secs.

```

**Comment by aayushthakkaryouco** [comment]
Actually the SecurityContext has been updated in the newer version of k8s server. I removed "runAsUser" from SecurityContext and it worked fine.
