### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by yangyang919** [telepresenceio/telepresence#1090]
### What were you trying to do?
I was trying to launch telepresence to proxy remote cluster

### What did you expect to happen?

Proxy success

### What happened instead?
Telepresence get crashed

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence']`
Version: `0.101`
Python version: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21) 
[Clang 6.0 (clang-600.0.57)]`
kubectl version: `Client Version: v1.10.5 // Server Version: v1.10.11`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin C02YW2X4LVDQ 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 136, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 63, in main
    socks_port, ssh = do_connect(runner, remote_info)
  File "/usr/local/bin/telepresence/telepresence/connect/connect.py", line 104, in do_connect
    return connect(runner_, remote_info, is_container_mode, args.expose)
  File "/usr/local/bin/telepresence/telepresence/connect/connect.py", line 59, in connect
    if not ssh.wait():
  File "/usr/local/bin/telepresence/telepresence/connect/ssh.py", line 80, in wait
    self.runner.check_call(self.command(["/bin/true"]), timeout=5)
  File "/usr/local/bin/telepresence/telepresence/runner/runner.py", line 424, in check_call
    env,
  File "/usr/local/bin/telepresence/telepresence/runner/runner.py", line 388, in _run_command_sync
    None if stderr_to_stdout else err_logger.get_captured(),
subprocess.TimeoutExpired: Command '['ssh', '-F', '/dev/null', '-oStrictHostKeyChecking=no', '-oUserKnownHostsFile=/dev/null', '-q', '-p', '50640', 'telepresence@127.0.0.1', '/bin/true']' timed out after 5 seconds

```

Logs:

```
t 255 in 0.01 secs.
  59.6 TEL | [36] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 50640 telepresence@127.0.0.1 /bin/true
  59.6 TEL | [36] exit 255 in 0.01 secs.
  59.9 TEL | [37] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 50640 telepresence@127.0.0.1 /bin/true
  59.9 TEL | [37] exit 255 in 0.01 secs.
  60.1 TEL | [38] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 50640 telepresence@127.0.0.1 /bin/true
  60.2 TEL | [38] exit 255 in 0.01 secs.
  60.2  16 | Forwarding from 127.0.0.1:50640 -> 8022
  60.2  16 | Forwarding from [::1]:50640 -> 8022
  60.4 TEL | [39] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 50640 telepresence@127.0.0.1 /bin/true
  60.4  16 | Handling connection for 50640
  61.7 TEL | [40] Running: sudo -n echo -n
  61.7 TEL | [40] ran in 0.03 secs.
  65.4 TEL | [39] timed out after 5.01 secs.

```

**Comment by thallgren** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
