### ISSUE TITLE
Swap deployment with --namespace fails

### ISSUE THREAD

**Issue by knordman** [telepresenceio/telepresence#1092]
I'm able get `--new-deployment` to work in the default namespace and in another namespace. But `--swap-deployment` only works in the default namespace, if I specify another namespace it crashes like this:
```
[kristian@knd]$ telepresence --swap-deployment blobs --expose 9087 --namespace newdev --run-shell
T: Starting proxy with method 'vpn-tcp', which has the following limitations: All processes are affected, only one telepresence can run per machine, and you can't use 
T: other VPNs. You may need to add cloud hosts and headless services with --also-proxy. For a full list of method limitations see 
T: https://telepresence.io/reference/methods.html
T: Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.
T: Starting network proxy to cluster by swapping out Deployment blobs with a proxy

Looks like there's a bug in our code. Sorry about that!

Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 136, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 60, in main
    remote_info = start_proxy(runner)
  File "/usr/bin/telepresence/telepresence/proxy/__init__.py", line 102, in start_proxy
    run_id=run_id,
  File "/usr/bin/telepresence/telepresence/proxy/remote.py", line 153, in get_remote_info
    runner, deployment_name, deployment_type, run_id=run_id
  File "/usr/bin/telepresence/telepresence/proxy/remote.py", line 100, in get_deployment_json
    )["items"][0]
IndexError: list index out of range


Here are the last few lines of the logfile (see /home/kristian/private/limber/v2/limber-projects/telepresence.log for the complete logs):

   3.9 TEL | [12] Running: kubectl --context gke_mytestproj_europe-west1-b_dev --namespace newdev apply -f -
   4.7  12 | deployment.extensions/blobs-fbd7f5d7fd4e49af88fa9b7d8632a7ef created
   4.7 TEL | [12] ran in 0.75 secs.
   4.7 TEL | [13] Running: kubectl --context gke_mytestproj_europe-west1-b_dev --namespace newdev scale deployment blobs --replicas=0
   5.2  13 | deployment.extensions/blobs scaled
   5.2 TEL | [13] ran in 0.53 secs.
   5.2 TEL | END SPAN deployment.py:179(supplant_deployment)    2.6s
   5.2 TEL | BEGIN SPAN remote.py:151(get_remote_info)
   5.2 TEL | BEGIN SPAN remote.py:78(get_deployment_json)
   5.2 TEL | [14] Capturing: kubectl --context gke_mytestproj_europe-west1-b_dev --namespace newdev get deployment -o json --selector=telepresence=fbd7f5d7fd4e49af88fa9b7d8632a7ef
   5.6 TEL | [14] captured in 0.44 secs.
   5.6 TEL | END SPAN remote.py:78(get_deployment_json)    0.4s
```

**Comment by knordman** [comment]
Sorry, my mistake. The deployment that was being swapped was restored by a custom  controller. No problem in telepresence.
