### ISSUE TITLE
failure to deploy

### ISSUE THREAD

**Issue by nathanshurte** [telepresenceio/telepresence#1113]
### What were you trying to do?
proxy in a service to a dev k8s cluster after rebuilding it with a minor change
(please tell us)

### What did you expect to happen?
It to spool up and swap out the deployment
(please tell us)

### What happened instead?
It looks like it timed out, I got the runtimeError in the stacktrace below. A second call to teleprescense worked without issue.

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--also-proxy', 'db.perf.k8s.aapedb2.com', '--namespace', 'edb', '--swap-deployment', 'store-view-service', '--expose', '8080:8080', '--docker-run', '-it', '--rm', 'aap/store-view-service:latest']`
Version: `0.99`
Python version: `3.7.3 (default, Mar 27 2019, 09:23:15) 
[Clang 10.0.1 (clang-1001.0.46.3)]`
kubectl version: `Client Version: v1.11.2 // Server Version: v1.13.10-eks-5ac0f1`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin RTSLabs-L1222.local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 136, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 60, in main
    remote_info = start_proxy(runner)
  File "/usr/local/bin/telepresence/telepresence/proxy/__init__.py", line 95, in start_proxy
    run_id=run_id,
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 202, in get_remote_info
    wait_for_pod(runner, remote_info)
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 134, in wait_for_pod
    "Pod isn't starting or can't be found: {}".format(pod["status"])
RuntimeError: Pod isn't starting or can't be found: {'conditions': [{'lastProbeTime': None, 'lastTransitionTime': '2019-09-10T17:52:02Z', 'message': 'containers with incomplete status: [init-rabbitmq init-dependency istio-init]', 'reason': 'ContainersNotInitialized', 'status': 'False', 'type': 'Initialized'}, {'lastProbeTime': None, 'lastTransitionTime': '2019-09-10T17:52:02Z', 'message': 'containers with unready status: [store-view-service istio-proxy]', 'reason': 'ContainersNotReady', 'status': 'False', 'type': 'Ready'}, {'lastProbeTime': None, 'lastTransitionTime': '2019-09-10T17:52:02Z', 'message': 'containers with unready status: [store-view-service istio-proxy]', 'reason': 'ContainersNotReady', 'status': 'False', 'type': 'ContainersReady'}, {'lastProbeTime': None, 'lastTransitionTime': '2019-09-10T17:52:02Z', 'status': 'True', 'type': 'PodScheduled'}], 'containerStatuses': [{'image': 'docker.io/istio/proxyv2:1.2.3', 'imageID': '', 'lastState': {}, 'name': 'istio-proxy', 'ready': False, 'restartCount': 0, 'state': {'waiting': {'reason': 'PodInitializing'}}}, {'image': 'datawire/telepresence-k8s:0.99', 'imageID': '', 'lastState': {}, 'name': 'store-view-service', 'ready': False, 'restartCount': 0, 'state': {'waiting': {'reason': 'PodInitializing'}}}], 'hostIP': '10.121.23.178', 'initContainerStatuses': [{'image': 'tutum/dnsutils', 'imageID': '', 'lastState': {}, 'name': 'init-rabbitmq', 'ready': False, 'restartCount': 0, 'state': {'waiting': {'reason': 'PodInitializing'}}}, {'image': 'byrnedo/alpine-curl', 'imageID': '', 'lastState': {}, 'name': 'init-dependency', 'ready': False, 'restartCount': 0, 'state': {'waiting': {'reason': 'PodInitializing'}}}, {'image': 'docker.io/istio/proxy_init:1.2.3', 'imageID': '', 'lastState': {}, 'name': 'istio-init', 'ready': False, 'restartCount': 0, 'state': {'waiting': {'reason': 'PodInitializing'}}}], 'phase': 'Pending', 'qosClass': 'Guaranteed', 'startTime': '2019-09-10T17:52:02Z'}

```

Logs:

```
] captured in 0.33 secs.
 121.2 TEL | [237] Capturing: kubectl --context aap-eks-dev.kubeconfig --namespace edb get pod store-view-servic-897f957e7d47465493c5f2728d4d4bf5-5f758cb54b7m -o json
 121.2 TEL | [238] Running: sudo -n echo -n
 121.3 TEL | [238] ran in 0.04 secs.
 121.5 TEL | [237] captured in 0.26 secs.
 121.7 TEL | [239] Capturing: kubectl --context aap-eks-dev.kubeconfig --namespace edb get

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
