### ISSUE TITLE
Running telepresence on deployemnt fails on kubectl exec command

### ISSUE THREAD

**Issue by azinneera** [telepresenceio/telepresence#1134]
I am getting the following error when trying to run telepresence on an existing deployment. My cluster is on gcp and my machine is a mac os. What can be the possible cause for this? 

```
Traceback (most recent call last):
 File "/Library/Project/telepresence-0.101/bin/telepresence/telepresence/cli.py", line 136, in crash_reporting
   yield
 File "/Library/Project/telepresence-0.101/bin/telepresence/telepresence/main.py", line 66, in main
   env, pod_info = get_remote_env(runner, ssh, remote_info)
 File "/Library/Project/telepresence-0.101/bin/telepresence/telepresence/remote_env.py", line 34, in get_remote_env
   remote_info.container_name, "--", "python3", "podinfo.py"
 File "/Library/Project/telepresence-0.101/bin/telepresence/telepresence/runner/runner.py", line 445, in get_output
   env,
 File "/Library/Project/telepresence-0.101/bin/telepresence/telepresence/runner/runner.py", line 399, in _run_command_sync
   None if stderr_to_stdout else err_logger.get_captured(),
subprocess.CalledProcessError: Command '['kubectl', '--context', 'cluster444', '--namespace', 'default', 'exec', 'telepresence--telepresence-deployment-d7948c9cb-8khwj', '--container', 'telepresence', '--', 'python3', 'podinfo.py']' returned non-zero exit status 1.


Here are the last few lines of the logfile (see telepresence.log for the complete logs):

 12.1 TEL |
 12.1 TEL | Recent output was:
 12.1 TEL |   2019-10-01T16:32:11+0000 [socks.SOCKSv5Factory#info] Starting factory <socks.SOCKSv5Factory object at 0x7f810f233668>
 12.1 TEL |   2019-10-01T16:32:11+0000 [-] DNSDatagramProtocol starting on 9053
 12.1 TEL |   2019-10-01T16:32:11+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7f810f233908>
 12.1 TEL |   2019-10-01T16:32:11+0000 [-] Loaded.
 12.1 TEL |   2019-10-01T16:32:11+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 19.2.1 (/usr/bin/python3.6 3.6.8) starting up.
 12.1 TEL |   2019-10-01T16:32:11+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.epollreactor.EPollReactor.
```

**Comment by ark3** [comment]
This is not quite enough information to see what is going on. If you use the built-in crash reporter, it would be easier. Note that you will have the opportunity to see and edit the post before it gets submitted; everything is in your control.

Anyhow, can you pass along the telepresence.log file as a Gist?

**Comment by azinneera** [comment]
Closing this since this was not reproducible. Will reopen if I come across the same issue again. Thank you for the response.
