### ISSUE TITLE
error: unable to upgrade connection: Forbidden

### ISSUE THREAD

**Issue by Pishtiko** [telepresenceio/telepresence#1140]
### What were you trying to do?

(please tell us)

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/bin/telepresence', '--swap-deployment', 'muvigame', '--env-json', 'muvigame-env.json']`
Version: `0.102`
Python version: `3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0]`
kubectl version: `Client Version: v1.16.0 // Server Version: v1.16.0`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux n15 5.0.0-29-generic #31-Ubuntu SMP Thu Sep 12 13:05:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 66, in main
    env, pod_info = get_remote_env(runner, ssh, remote_info)
  File "/usr/bin/telepresence/telepresence/remote_env.py", line 34, in get_remote_env
    remote_info.container_name, "--", "python3", "podinfo.py"
  File "/usr/bin/telepresence/telepresence/runner/runner.py", line 464, in get_output
    env,
  File "/usr/bin/telepresence/telepresence/runner/runner.py", line 418, in _run_command_sync
    None if stderr_to_stdout else err_logger.get_captured(),
subprocess.CalledProcessError: Command '['kubectl', '--context', 'microk8s', '--namespace', 'muvi', 'exec', 'muvigame-dd1faec026324e55b5778283aaf444bf-694dc6c5d4-n7p7m', '--container', 'muvigame-app', '--', 'python3', 'podinfo.py']' returned non-zero exit status 1.

```

Logs:

```
KeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 38705 telepresence@127.0.0.1 -R '*:8080:127.0.0.1:8080'
  21.3 >>> | 
  21.3 TEL | Launching Web server for proxy poll
  21.3 TEL | [33] Launching SSH port forward (socks and proxy poll): ssh -N -oServerAliveInterval=1 -oServerAliveCountMax=10 -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 38705 telepresence@127.0.0.1 -L127.0.0.1:41119:127.0.0.1:9050 -R9055:127.0.0.1:44185
  21.3  28 | Handling connection for 38705
  21.3 TEL | END SPAN connect.py:36(connect)    1.3s
  21.3 TEL | BEGIN SPAN remote_env.py:28(get_remote_env)
  21.3 TEL | [34] Capturing: kubectl --context microk8s --namespace muvi exec muvigame-dd1faec026324e55b5778283aaf444bf-694dc6c5d4-n7p7m --container muvigame-app -- python3 podinfo.py
  21.3  28 | Handling connection for 38705
  21.6  34 | error: unable to upgrade connection: Forbidden
  21.6 TEL | [34] exit 1 in 0.31 secs.
  21.6 TEL | END SPAN remote_env.py:28(get_remote_env)    0.3s

```

**Comment by ark3** [comment]
Sorry about the crash! 

It seems there is an RBAC problem with `kubectl exec` to the Telepresence proxy pod. Can you help me debug this in your cluster? If you spin up a Telepresence proxy pod [manually](https://www.telepresence.io/reference/connecting#running-telepresence-manually), what RBAC modifications do you need to successfully `kubectl exec` onto the pod?

Thank you for your help.

**Comment by Pishtiko** [comment]
Thank You for the response.
I've just figured out that it might have been my fault.
I was using kubectl configuration with localhost adress via ssh tunnel to my Kubernetes API server.
It used to work for me for simple kubectl use cases, but apparently didn't work for Telepresence.
So when I switched to external adress configuration with cluster-admin credentials - everything worked just fine 😀
Thanks again!

**Comment by Pishtiko** [comment]
@ark3
I'm not much into the process. Should I close the issue myself?
