### ISSUE TITLE
Fast dev workflow with Docker/K8s fails with minikube on mac

### ISSUE THREAD

**Issue by chuan137** [telepresenceio/telepresence#1156]
### What were you trying to do?

telepresence --docker-run --rm -it pstauffer/curl curl http://hello-world:8000/

### What did you expect to happen?

telepresence setup complete

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--docker-run', '--rm', '-it', 'pstauffer/curl', 'curl', 'http://hello-world:8000/']`
Version: `0.102`
Python version: `3.7.4 (default, Oct 12 2019, 19:06:48) 
[Clang 11.0.0 (clang-1100.0.33.8)]`
kubectl version: `Client Version: v1.10.9 // Server Version: v1.16.0`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin C02WF06UHTD6 19.0.0 Darwin Kernel Version 19.0.0: Wed Sep 25 20:18:50 PDT 2019; root:xnu-6153.11.26~2/RELEASE_X86_64 x86_64 i386 MacBookPro14,3 Darwin`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 60, in main
    remote_info = start_proxy(runner)
  File "/usr/local/bin/telepresence/telepresence/proxy/__init__.py", line 125, in start_proxy
    run_id=run_id,
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 152, in get_remote_info
    runner, deployment_name, deployment_type, run_id=run_id
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 99, in get_deployment_json
    )["items"][0]
IndexError: list index out of range

```

Logs:

```
-not-found svc,deploy --selector=telepresence=6f06075fa3c94c1e8a189709199d4277
   3.0  10 | No resources found
   3.0 TEL | [10] ran in 0.10 secs.
   3.0 TEL | [11] Running: kubectl --context minikube --namespace default run --restart=Always --limits=cpu=1000m,memory=256Mi --requests=cpu=25m,memory=64Mi telepresence-1571515832-4457002-1470 --image=datawire/telepresence-k8s:0.102 --labels=telepresence=6f06075fa3c94c1e8a189709199d4277
   3.1  11 | replicationcontroller "telepresence-1571515832-4457002-1470" created
   3.1 TEL | [11] ran in 0.11 secs.
   3.1 TEL | END SPAN deployment.py:105(create_new_deployment)    0.2s
   3.1 TEL | BEGIN SPAN remote.py:150(get_remote_info)
   3.1 TEL | BEGIN SPAN remote.py:77(get_deployment_json)
   3.1 TEL | [12] Capturing: kubectl --context minikube --namespace default get deployment -o json --selector=telepresence=6f06075fa3c94c1e8a189709199d4277
   3.2 TEL | [12] captured in 0.09 secs.
   3.2 TEL | END SPAN remote.py:77(get_deployment_json)    0.1s

```

**Comment by ark3** [comment]
Sorry about the crash!

This caught my eye:

```
   3.0 TEL | [11] Running: kubectl --context minikube --namespace default run --restart=Always --limits=cpu=1000m,memory=256Mi --requests=cpu=25m,memory=64Mi telepresence-1571515832-4457002-1470 --image=datawire/telepresence-k8s:0.102 --labels=telepresence=6f06075fa3c94c1e8a189709199d4277
   3.1  11 | replicationcontroller "telepresence-1571515832-4457002-1470" created
```

I would expect to see `deployment "..." created` or similar, not `replicationcontroller`. Could you try this with a newer version of `kubectl`? Ultimately fixing #1041 will fix this too.
