### ISSUE TITLE
Exception while running Telepresence

### ISSUE THREAD

**Issue by sarkaramrit2** [telepresenceio/telepresence#1163]
### What were you trying to do?

(please tell us)

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--swap-deployment', 'master-managed-search-k8s-worker', '--expose', '5000', '--run', '../gradlew', 'bootRun']`
Version: `0.101`
Python version: `3.7.4 (default, Sep  7 2019, 18:27:02) 
[Clang 10.0.1 (clang-1001.0.46.4)]`
kubectl version: `Client Version: v1.13.11-dispatcher // Server Version: v1.13.7-gke.24`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin Apples-MacBook-Air-2.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 136, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 63, in main
    socks_port, ssh = do_connect(runner, remote_info)
  File "/usr/local/bin/telepresence/telepresence/connect/connect.py", line 104, in do_connect
    return connect(runner_, remote_info, is_container_mode, args.expose)
  File "/usr/local/bin/telepresence/telepresence/connect/connect.py", line 59, in connect
    if not ssh.wait():
  File "/usr/local/bin/telepresence/telepresence/connect/ssh.py", line 80, in wait
    self.runner.check_call(self.command(["/bin/true"]), timeout=5)
  File "/usr/local/bin/telepresence/telepresence/runner/runner.py", line 424, in check_call
    env,
  File "/usr/local/bin/telepresence/telepresence/runner/runner.py", line 388, in _run_command_sync
    None if stderr_to_stdout else err_logger.get_captured(),
subprocess.TimeoutExpired: Command '['ssh', '-F', '/dev/null', '-oStrictHostKeyChecking=no', '-oUserKnownHostsFile=/dev/null', '-q', '-p', '61256', 'telepresence@127.0.0.1', '/bin/true']' timed out after 5 seconds

```

Logs:

```
le=/dev/null -q -p 61256 telepresence@127.0.0.1 /bin/true
  25.0 TEL | [28] exit 255 in 0.02 secs.
  25.3 TEL | [29] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 61256 telepresence@127.0.0.1 /bin/true
  25.3 TEL | [29] exit 255 in 0.02 secs.
  25.5 TEL | [30] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 61256 telepresence@127.0.0.1 /bin/true
  25.6 TEL | [30] exit 255 in 0.02 secs.
  25.8 TEL | [31] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 61256 telepresence@127.0.0.1 /bin/true
  25.9 TEL | [31] exit 255 in 0.02 secs.
  26.0  17 | Forwarding from 127.0.0.1:61256 -> 8022
  26.0  17 | Forwarding from [::1]:61256 -> 8022
  26.1 TEL | [32] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 61256 telepresence@127.0.0.1 /bin/true
  26.1  17 | Handling connection for 61256
  31.1 TEL | [32] timed out after 5.01 secs.

```

**Comment by ark3** [comment]
Sorry about the crash. This was fixed in the next release, version 0.102.
