### ISSUE TITLE
Telepresence crashing when used for openshift cluster

### ISSUE THREAD

**Issue by cryptox31** [telepresenceio/telepresence#1164]
### What were you trying to do?

1. Tried running `sudo telepresence` for an openshift cluster
2. Tried running `sudo telepresence --swap-deployment some-container --env-json some.json`

### What happened instead?

Creates the telepresence container and then crashes.
For both the methods, it keeps giving `RuntimeError: SSH to the cluster failed to start.` error

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--swap-deployment', 'omag', '--env-json', 'wkcenv.json']`
Version: `0.102`
Python version: `3.7.4 (default, Sep  7 2019, 18:27:02) 
[Clang 10.0.1 (clang-1001.0.46.4)]`
kubectl version: `Client Version: v1.14.6 // Server Version: v1.11.0+d4cacc0`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin  18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 63, in main
    socks_port, ssh = do_connect(runner, remote_info)
  File "/usr/local/bin/telepresence/telepresence/connect/connect.py", line 113, in do_connect
    return connect(runner_, remote_info, is_container_mode, args.expose)
  File "/usr/local/bin/telepresence/telepresence/connect/connect.py", line 69, in connect
    raise RuntimeError("SSH to the cluster failed to start. See logfile.")
RuntimeError: SSH to the cluster failed to start. See logfile.

```

Logs:

```
  Container image "some-image" already present on machine
 110.3 139 |   Normal  Created    97s   kubelet, some-cluster  Created container
 110.3 139 |   Normal  Started    97s   kubelet, some-cluster  Started container
 110.3 139 |   Normal  Pulling    36s   kubelet, some-cluster  pulling image "datawire/telepresence-k8s:0.102"
 110.3 139 |   Normal  Pulled     31s   kubelet, some-cluster  Successfully pulled image "datawire/telepresence-k8s:0.102"
 110.3 139 |   Normal  Created    31s   kubelet, some-cluster  Created container
 110.3 139 |   Normal  Started    31s   kubelet, some-cluster  Started cont

**Comment by cryptox31** [comment]
I looked at this error and installed `oc`
`(error: [Errno 2] No such file or directory: 'oc': 'oc')`

Running telepresence gives me this issue now https://github.com/telepresenceio/telepresence/issues/1077

**Comment by cryptox31** [comment]
Starting working with the telepresence version
```
0.105
```
for
```
openshift v3.11.216
kubernetes v1.11.0+d4cacc0
```
after looking at
https://github.com/telepresenceio/telepresence/issues/1309#issuecomment-622230333
