### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by zryfish** [telepresenceio/telepresence#1178]
### What were you trying to do?
Just run normally
```
telepresence
```
### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence']`
Version: `0.103`
Python version: `3.7.5 (default, Nov  1 2019, 02:16:23) 
[Clang 11.0.0 (clang-1100.0.33.8)]`
kubectl version: `Client Version: v1.15.3 // Server Version: v1.15.5`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin ZRYdeMacBook-Pro.local 19.0.0 Darwin Kernel Version 19.0.0: Wed Sep 25 20:18:50 PDT 2019; root:xnu-6153.11.26~2/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 65, in main
    remote_info = start_proxy(runner)
  File "/usr/local/bin/telepresence/telepresence/proxy/__init__.py", line 138, in start_proxy
    run_id=run_id,
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 193, in get_remote_info
    wait_for_pod(runner, remote_info)
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 125, in wait_for_pod
    "Pod isn't starting or can't be found: {}".format(pod["status"])
RuntimeError: Pod isn't starting or can't be found: {'conditions': [{'lastProbeTime': None, 'lastTransitionTime': '2019-11-05T13:49:44Z', 'status': 'True', 'type': 'Initialized'}, {'lastProbeTime': None, 'lastTransitionTime': '2019-11-05T13:49:44Z', 'message': 'containers with unready status: [telepresence-1572961774-8690078-62013]', 'reason': 'ContainersNotReady', 'status': 'False', 'type': 'Ready'}, {'lastProbeTime': None, 'lastTransitionTime': '2019-11-05T13:49:44Z', 'message': 'containers with unready status: [telepresence-1572961774-8690078-62013]', 'reason': 'ContainersNotReady', 'status': 'False', 'type': 'ContainersReady'}, {'lastProbeTime': None, 'lastTransitionTime': '2019-11-05T13:49:44Z', 'status': 'True', 'type': 'PodScheduled'}], 'containerStatuses': [{'image': 'datawire/telepresence-k8s:0.103', 'imageID': '', 'lastState': {}, 'name': 'telepresence-1572961774-8690078-62013', 'ready': False, 'restartCount': 0, 'state': {'waiting': {'message': 'Back-off pulling image "datawire/telepresence-k8s:0.103"', 'reason': 'ImagePullBackOff'}}}], 'hostIP': '192.168.100.6', 'phase': 'Pending', 'podIP': '10.233.96.35', 'qosClass': 'Burstable', 'startTime': '2019-11-05T13:49:44Z'}

```

Logs:

```
udo -n echo -n
 126.8 TEL | [155] ran in 0.04 secs.
 127.3 TEL | [154] captured in 0.74 secs.
 127.6 TEL | [156] Capturing: kubectl --context kubernetes-admin@cluster.local --namespace default get pod telepresence-1572961774-8690078-62013-6f6d888b4c-tdbcg -o json
 128.1 TEL | [156] captured in 0.57 secs.
 128.4 TEL | [157] Capturing: kubectl --context kubernetes-admin@cluster.local --namespace default get pod telepresence-1572961774-8690078-62013-6f6d888b4c-tdbcg -o json
 128.9 TEL | [157] captured in 0.57 secs.
 129.2 TEL | [158] Capturing: kubectl --context kubernetes-admin@cluster.local --namespace default get pod telepresence-1572961774-8690078-62013-6f6d888b4c-tdbcg -o json
 129.8 TEL | [158] captured in 0.57 secs.
 130.0 TEL | [159] Capturing: kubectl --context kubernetes-admin@cluster.local --namespace default get pod telepresence-1572961774-8690078-62013-6f6d888b4c-tdbcg -o json
 130.6 TEL | [159] captured in 0.59 secs.
 130.6 TEL | END SPAN remote.py:104(wait_for_pod)  119.8s

```

**Comment by ark3** [comment]
Sorry about the crash! Telepresence should give you a much better error message here. In this case, I see

    'Back-off pulling image "datawire/telepresence-k8s:0.103"'

in the crash message blob. Is your cluster able to pull images from Docker Hub?

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
