### ISSUE TITLE
Install 0.102 using homebrew

### ISSUE THREAD

**Issue by atif089** [telepresenceio/telepresence#1186]
Hi,

Is it possible to install an older version using homebrew? I tried something like this and I'm pretty sure it's incorrect.

```bash
brew tap -d telepresenceio/telepresence https://github.com/telepresenceio/telepresence
TELEPRESENCE_VERSION=0.102 brew install telepresenceio/telepresence
```

**Comment by ark3** [comment]
Why do you want to do this? Please help us understand and fix the real problem.

[This StackOverflow answer](https://stackoverflow.com/a/17757092/8060653) will probably get you there. Use

    https://github.com/datawire/homebrew-blackbird/commits/master

for the "commit history" step.

**Comment by atif089** [comment]
Thanks @ark3 . 

The reason is actually very specific to my company / work environment. We are using this on a kubernetes cluster with an internal artifactory for docker images.

To use 0.103 I need to create and add an image to the artifactory which I don't know how to do. And once a new version is released, I might run into the same problem again.

**Comment by codechaitu** [comment]
`brew install https://raw.githubusercontent.com/datawire/homebrew-blackbird/40942f59ddbe792111457e265d545c11b0f53bb1/Formula/telepresence.rb`

**Comment by rcgeorge23** [comment]
I'm trying to install 0.108 and using the same approach I just get:

```
$ brew install https://raw.githubusercontent.com/datawire/homebrew-blackbird/1797069a468a4b056edbfcaf63e9ac665470cdaf/Formula/telepresence.rb
Traceback (most recent call last):
	9: from /usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
	8: from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:132:in `install'
	7: from /usr/local/Homebrew/Library/Homebrew/cli/parser.rb:301:in `parse'
	6: from /usr/local/Homebrew/Library/Homebrew/cli/parser.rb:644:in `formulae'
	5: from /usr/local/Homebrew/Library/Homebrew/cli/parser.rb:644:in `map'
	4: from /usr/local/Homebrew/Library/Homebrew/cli/parser.rb:648:in `block in formulae'
	3: from /usr/local/Homebrew/Library/Homebrew/formulary.rb:351:in `factory'
	2: from /usr/local/Homebrew/Library/Homebrew/formulary.rb:138:in `get_formula'
	1: from /usr/local/Homebrew/Library/Homebrew/formulary.rb:142:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:227:in `load_file': Invalid usage: Installation of telepresence from a GitHub commit URL is unsupported! `brew extract telepresence` to a stable tap on GitHub instead. (UsageError)
	12: from /usr/local/Homebrew/Library/Homebrew/brew.rb:155:in `<main>'
	11: from /usr/local/Homebrew/Library/Homebrew/brew.rb:157:in `rescue in <main>'
	10: from /usr/local/Homebrew/Library/Homebrew/help.rb:64:in `help'
	 9: from /usr/local/Homebrew/Library/Homebrew/help.rb:83:in `command_help'
	 8: from /usr/local/Homebrew/Library/Homebrew/help.rb:103:in `parser_help'
	 7: from /usr/local/Homebrew/Library/Homebrew/cli/parser.rb:301:in `parse'
	 6: from /usr/local/Homebrew/Library/Homebrew/cli/parser.rb:644:in `formulae'
	 5: from /usr/local/Homebrew/Library/Homebrew/cli/parser.rb:644:in `map'
	 4: from /usr/local/Homebrew/Library/Homebrew/cli/parser.rb:648:in `block in formulae'
	 3: from /usr/local/Homebrew/Library/Homebrew/formulary.rb:351:in `factory'
	 2: from /usr/local/Homebrew/Library/Homebrew/formulary.rb:138:in `get_formula'
	 1: from /usr/local/Homebrew/Library/Homebrew/formulary.rb:142:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:227:in `load_file': Invalid usage: Installation of telepresence from a GitHub commit URL is unsupported! `brew extract telepresence` to a stable tap on GitHub instead. (UsageError)
```
