### ISSUE TITLE
Hello World example error

### ISSUE THREAD

**Issue by surfdog** [telepresenceio/telepresence#1191]
Use Telepresence to swap the hello-world deployment with the local Docker image command fails in tutorial.

telepresence --swap-deployment hello-world --docker-run --rm -it -v $(pwd):/usr/src/app hello-dev

Error message:
`Traceback (most recent call last):
  File "./server.py", line 6, in <module>
    app = Flask(__name__)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 558, in __init__
    self.add_url_rule(
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 66, in wrapper_func
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1216, in add_url_rule
    self.url_map.add(rule)
  File "/usr/local/lib/python3.8/site-packages/werkzeug/routing.py", line 1562, in add
    rule.bind(self)
  File "/usr/local/lib/python3.8/site-packages/werkzeug/routing.py", line 711, in bind
    self.compile()
  File "/usr/local/lib/python3.8/site-packages/werkzeug/routing.py", line 767, in compile
    self._build = self._compile_builder(False)
  File "/usr/local/lib/python3.8/site-packages/werkzeug/routing.py", line 1128, in _compile_builder
    return self.BuilderCompiler(self).compile(append_unknown)
  File "/usr/local/lib/python3.8/site-packages/werkzeug/routing.py", line 1119, in compile
    co = types.CodeType(*code_args)
TypeError: code() takes at least 14 arguments (13 given)
T: Your process exited with return code 1.
T: Exit cleanup in progress
T: Swapping Deployment hello-world back to its original state`

**Comment by jessebye** [comment]
@surfdog I opened a PR on that repo to fix it: https://github.com/datawire/hello-world/pull/4

**Comment by surfdog** [comment]
@jessebye Thanks!  I was able to complete the quick example.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
