### ISSUE TITLE
telepresence --deployment <name of deployment> raises an exception

### ISSUE THREAD

**Issue by Nitaym** [telepresenceio/telepresence#1192]
### What were you trying to do?

telepresence --deployment <name of deployment>
( I meant to write telepresence -s <name of deployment>)

### What did you expect to happen?

swap a deployment

### What happened instead?

Got an exception

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--deployment', 'admin-frontend']`
Version: `0.103`
Python version: `3.7.3 (default, Mar 27 2019, 09:23:15) 
[Clang 10.0.1 (clang-1001.0.46.3)]`
kubectl version: `Client Version: v1.14.7 // Server Version: v1.16.2-k3s.1`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin Nitays-MacBook-Pro.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 65, in main
    remote_info = start_proxy(runner)
  File "/usr/local/bin/telepresence/telepresence/proxy/__init__.py", line 138, in start_proxy
    run_id=run_id,
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 179, in get_remote_info
    deployment,
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 50, in __init__
    "'datawire/telepresence-k8s' in pod {}.".format(pod_name)
RuntimeError: Could not find container with image 'datawire/telepresence-k8s' in pod admin-frontend-79fd67fbc5-jswf8.

```

Logs:

```
 TEL | --> Name does not match
   4.6 TEL | Checking first-react-5b89884b89-5xbxr
   4.6 TEL | --> Name does not match
   4.6 TEL | Checking cv-engine-7cf54f4dd8-rtw7w
   4.6 TEL | --> Name does not match
   4.6 TEL | Checking mapping-engine-785ffccb4f-sjbj6
   4.6 TEL | --> Name does not match
   4.6 TEL | Checking mysql-76dffb8d5d-d65sw
   4.6 TEL | --> Name does not match
   4.6 TEL | Checking auth-7866f464b9-9h8q6
   4.6 TEL | --> Name does not match
   4.6 TEL | Checking rethinkdb-59c9cfdf88-cl9cf
   4.6 TEL | --> Name does not match
   4.6 TEL | Checking dapperdox-844b67c8c7-zk5lc
   4.6 TEL | --> Name does not match
   4.6 TEL | Checking first-react-backend-69c5c8656-dk8rj
   4.6 TEL | --> Name does not match
   4.6 TEL | Checking argus-api-849dcd8c96-gtqkm
   4.6 TEL | --> Name does not match
   4.6 TEL | Checking admin-backend-fcdf598bb-dqkz5
   4.6 TEL | --> Name does not match
   4.6 TEL | Checking admin-frontend-79fd67fbc5-jswf8
   4.6 TEL | Looks like we've found our pod!

```

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
