### ISSUE TITLE
Does not work on catalina 

### ISSUE THREAD

**Issue by tonit** [telepresenceio/telepresence#1195]
### What were you trying to do?

(please tell us)

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence']`
Version: `0.103`
Python version: `3.7.5 (default, Nov  1 2019, 02:16:23) 
[Clang 11.0.0 (clang-1100.0.33.8)]`
kubectl version: `Client Version: v1.16.3 // Server Version: v1.14.7-gke.23`
oc version: `(error: Command '['oc', 'version']' died with <Signals.SIGKILL: 9>.)`
OS: `Darwin riddler.local 19.0.0 Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 82, in main
    runner, remote_info, env, socks_port, ssh, mount_dir, pod_info
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 112, in launch
    runner_, remote_info, command, args.also_proxy, env, ssh
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 126, in launch_vpn
    connect_sshuttle(runner, remote_info, also_proxy, ssh)
  File "/usr/local/bin/telepresence/telepresence/outbound/vpn.py", line 310, in connect_sshuttle
    raise RuntimeError("vpn-tcp tunnel did not connect")
RuntimeError: vpn-tcp tunnel did not connect

```

Logs:

```
 [stdout#info] A query: b'osxdaily.com'
  55.8  34 | 2019-11-15T10:13:45+0000 [stdout#info] Result for b'osxdaily.com' is ['209.58.137.71']
  55.8  34 | 2019-11-15T10:13:45+0000 [stdout#info] A query: b'osxdaily.com'
  55.8  34 | 2019-11-15T10:13:45+0000 [stdout#info] Result for b'osxdaily.com' is ['207.244.78.26']
  55.9  44 | c : DNS request from ('192.168.188.48', 58160) to None: 37 bytes
  55.9  44 | c : DNS request from ('192.168.188.48', 61300) to None: 37 bytes
  55.9  34 | 2019-11-15T10:13:45+0000 [stdout#info] AAAA query, sending back A instead: b'cdn.smoot.apple.com'
  55.9  34 | 2019-11-15T10:13:45+0000 [stdout#info] A query: b'cdn.smoot.apple.com'
  55.9  34 | 2019-11-15T10:13:45+0000 [stdout#info] A query: b'cdn.smoot.apple.com'
  55.9  34 | 2019-11-15T10:13:45+0000 [stdout#info] Result for b'cdn.smoot.apple.com' is ['17.253.37.204', '17.253.37.203']
  55.9  34 | 2019-11-15T10:13:45+0000 [stdout#info] Result for b'cdn.smoot.apple.com' is ['17.253.37.210', '17.253.37.204']

```

**Comment by tonit** [comment]
works after reinstalling osxfuse:
> brew cask reinstall osxfuse
