### ISSUE TITLE
Bug when activating a telepresence session

### ISSUE THREAD

**Issue by smk508** [telepresenceio/telepresence#1209]
### What were you trying to do?

Start telepresence

### What did you expect to happen?

Start telepresence

### What happened instead?

It did not connect and asked to file an issue.

### Automatically included information

Command line: `['/usr/bin/telepresence']`
Version: `0.103`
Python version: `3.6.8 (default, Apr  9 2019, 04:59:38) 
[GCC 8.3.0]`
kubectl version: `Client Version: v1.16.3 // Server Version: v1.12.10-gke.17`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux cube 4.18.0-25-generic #26-Ubuntu SMP Mon Jun 24 09:32:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 65, in main
    remote_info = start_proxy(runner)
  File "/usr/bin/telepresence/telepresence/proxy/__init__.py", line 138, in start_proxy
    run_id=run_id,
  File "/usr/bin/telepresence/telepresence/proxy/remote.py", line 193, in get_remote_info
    wait_for_pod(runner, remote_info)
  File "/usr/bin/telepresence/telepresence/proxy/remote.py", line 125, in wait_for_pod
    "Pod isn't starting or can't be found: {}".format(pod["status"])
RuntimeError: Pod isn't starting or can't be found: {'conditions': [{'lastProbeTime': None, 'lastTransitionTime': '2019-12-04T04:07:55Z', 'status': 'True', 'type': 'PodScheduled'}], 'phase': 'Pending', 'qosClass': 'Burstable'}

```

Logs:

```
 138.8 TEL | [152] captured in 0.46 secs.
 139.0 TEL | [153] Capturing: kubectl --context gke_my-project-1513049286924_us-east1-b_dbv --namespace default get pod telepresence-1575432456-0659115-15101-67c8f65bc4-tvl4b -o json
 139.7 TEL | [153] captured in 0.66 secs.
 139.9 TEL | [154] Capturing: kubectl --context gke_my-project-1513049286924_us-east1-b_dbv --namespace default get pod telepresence-1575432456-0659115-15101-67c8f65bc4-tvl4b -o json
 140.3 TEL | [154] captured in 0.33 secs.
 140.5 TEL | [155] Capturing: kubectl --context gke_my-project-1513049286924_us-east1-b_dbv --namespace default get pod telepresence-1575432456-0659115-15101-67c8f65bc4-tvl4b -o json
 140.8 TEL | [155] captured in 0.32 secs.
 141.1 TEL | [156] Capturing: kubectl --context gke_my-project-1513049286924_us-east1-b_dbv --namespace default get pod telepresence-1575432456-0659115-15101-67c8f65bc4-tvl4b -o json
 142.1 TEL | [156] captured in 0.98 secs.
 142.1 TEL | END SPAN remote.py:104(wait_for_pod)  120.6s

```

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
