### ISSUE TITLE
Telepresence throws error 

### ISSUE THREAD

**Issue by guangwenz** [telepresenceio/telepresence#1216]
### What were you trying to do?

just run `telepresence`

### What did you expect to happen?

start a shell

### What happened instead?

error shows up RuntimeError: vpn-tcp tunnel did not connect

### Automatically included information

Command line: `['/usr/local/bin/telepresence']`
Version: `0.103`
Python version: `3.7.5 (default, Nov  1 2019, 02:16:32) 
[Clang 11.0.0 (clang-1100.0.33.8)]`
kubectl version: `Client Version: v1.14.8 // Server Version: v1.13.12-eks-c500e1`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin ip-192-168-1-135.ec2.internal 18.7.0 Darwin Kernel Version 18.7.0: Sat Oct 12 00:02:19 PDT 2019; root:xnu-4903.278.12~1/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 82, in main
    runner, remote_info, env, socks_port, ssh, mount_dir, pod_info
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 112, in launch
    runner_, remote_info, command, args.also_proxy, env, ssh
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 126, in launch_vpn
    connect_sshuttle(runner, remote_info, also_proxy, ssh)
  File "/usr/local/bin/telepresence/telepresence/outbound/vpn.py", line 310, in connect_sshuttle
    raise RuntimeError("vpn-tcp tunnel did not connect")
RuntimeError: vpn-tcp tunnel did not connect

```

Logs:

```
2019-12-12T17:12:37+0000 [DNSDatagramProtocol (UDP)] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7f9754ea4d68>
  56.8  14 | 2019-12-12T17:12:37+0000 [-] (UDP Port 43467 Closed)
  56.8  14 | 2019-12-12T17:12:37+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7f9754ea4d68>
  56.8  14 | 2019-12-12T17:12:37+0000 [stdout#info] Sanity check: b'hellotelepresence-7.a.sanity.check.telepresence.io'
  56.9 TEL | [47] exit 1 in 0.23 secs.
  56.9  14 | 2019-12-12T17:12:37+0000 [stdout#info] 6 query: b'local'
  56.9  14 | 2019-12-12T17:12:37+0000 [DNSDatagramProtocol (UDP)] DNSDatagramProtocol starting on 27843
  57.0  14 | 2019-12-12T17:12:37+0000 [DNSDatagramProtocol (UDP)] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7f9754ea4c88>
  57.0  14 | 2019-12-12T17:12:37+0000 [-] (UDP Port 27843 Closed)
  57.0  14 | 2019-12-12T17:12:37+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7f9754ea4c88>

```

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2, since we don't have the vpn-tcp method. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
