### ISSUE TITLE
ssh from telepresence client unable to connect to the telepresence container

### ISSUE THREAD

**Issue by jarleaase** [telepresenceio/telepresence#1219]
When I try to connect to an existing `datawire/telepresence-k8s:0.103` Deployment in GCP, or swap deployments, I get this on my console:

```
Looks like there's a bug in our code. Sorry about that!

Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 68, in main
    socks_port, ssh = do_connect(runner, remote_info)
  File "/usr/bin/telepresence/telepresence/connect/connect.py", line 119, in do_connect
    args.from_pod
  File "/usr/bin/telepresence/telepresence/connect/connect.py", line 70, in connect
    raise RuntimeError("SSH to the cluster failed to start. See logfile.")
RuntimeError: SSH to the cluster failed to start. See logfile.
```

Looking closer at what goes on on on the telepresence container by running sshd in debug mode, I see these sshd messages when I run `ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -p 40807 telepresence@127.0.0.1 /bin/true`:
```
debug1: userauth-request for user telepresence service ssh-connection method none [preauth]
debug1: attempt 0 failures 0 [preauth]
debug1: Config token is authorizedkeysfile
debug1: Config token is subsystem
debug1: Config token is clientaliveinterval
debug1: Config token is gatewayports
debug1: Config token is permitemptypasswords
debug1: Config token is port
debug1: Config token is clientalivecountmax
debug1: Config token is permitrootlogin
Could not get shadow information for telepresence
Accepted none for telepresence from 127.0.0.1 port 38246 ssh2
debug1: monitor_child_preauth: telepresence has been authenticated by privileged process
debug1: monitor_read_log: child log fd closed
User child is on pid 261
Failed to set uids to 1000.
```
**Could not get shadow information for telepresence** is as far as I know an absolute *no no* from sshd, and will deny login.

**Comment by jarleaase** [comment]
It seems the problem is related to a securityContext set by the operator that deployed telepresence in my k8 cluster. So, not a bug.
