### ISSUE TITLE
Telepresence doesn't start with nftables (Debian)

### ISSUE THREAD

**Issue by analytik** [telepresenceio/telepresence#1234]
Sorry, automated reporting doesn't work, so let me try my best.

Telepresence version: `0.103` and `0.104`
Host OS: `Microsoft Windows [Version 10.0.19041.21]` (Current "slow" Insider Preview)
WSL OS: Debian `Linux 4.19.84-microsoft-standard #1 SMP Wed Nov 13 11:44:37 UTC 2019 x86_64 GNU/Linux`
WSL version: 2
Python version: `Python 3.7.3`
Command: `telepresence` or `telepresence --namespace=foo`

Log:

```
T: Starting proxy with method 'vpn-tcp', which has the following limitations: All processes are affected, only one telepresence can run per machine, and you can't use other VPNs. You may need to add cloud hosts and headless services with T:  --also-proxy. For a full list of method limitations see https://telepresence.io/reference/methods.html
T: Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.
T: Starting network proxy to cluster using new Deployment telepresence-1579857793-782214-2768

T: No traffic is being forwarded from the remote Deployment to your local machine. You can use the --expose option to specify which ports you want to forward.


Looks like there's a bug in our code. Sorry about that!

Background process (sshuttle) exited with return code 99. Command was:
  sshuttle-telepresence -v --dns --method nat -e 'ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null' -r telepresence@127.0.0.1:44315 --to-ns 127.0.0.1:9053 10.244.0.0/21 10.96.0.0/12

Recent output was:
  firewall manager: ---> Traceback (most recent call last):
  firewall manager: --->   File "/root/.pex/installed_wheels/0d9e68051641ddb11ae2a297ad09cac33277ceac/sshuttle_telepresence-0.78.2.dev45+gd250ccb-py2.py3-none-any.whl/sshuttle/firewall.py", line 262, in main
  firewall manager: --->     method.restore_firewall(port_v4, socket.AF_INET, udp)
  firewall manager: --->   File "/root/.pex/installed_wheels/0d9e68051641ddb11ae2a297ad09cac33277ceac/sshuttle_telepresence-0.78.2.dev45+gd250ccb-py2.py3-none-any.whl/sshuttle/methods/nat.py", line 115, in restore_firewall
  firewall manager: --->     if ipt_chain_exists(family, table, chain):
  firewall manager: --->   File "/root/.pex/installed_wheels/0d9e68051641ddb11ae2a297ad09cac33277ceac/sshuttle_telepresence-0.78.2.dev45+gd250ccb-py2.py3-none-any.whl/sshuttle/linux.py", line 32, in ipt_chain_exists
  firewall manager: --->     raise Fatal('%r returned %d' % (argv, rv))
  firewall manager: ---> sshuttle.helpers.Fatal: ['iptables', '-t', 'nat', '-nL'] returned 4
  fatal: ['iptables', '-t', 'nat', '-nL'] returned 4
  c : fatal: cleanup: ['sudo', '-p', '[local sudo] Password: ', 'PYTHONPATH=/home/milan/.pex/installed_wheels/0d9e68051641ddb11ae2a297ad09cac33277ceac/sshuttle_telepresence-0.78.2.dev45+gd250ccb-py2.py3-none-any.whl', '--', '/usr/bin/python3', '/usr/libexec/sshuttle-telepresence', '-v', '--method', 'nat', '--firewall'] returned 99

Here are the last few lines of the logfile (see /mnt/c/www/kubernetes-vagrant/telepresence.log for the complete logs):

   7.2  25 | firewall manager: --->     method.restore_firewall(port_v4, socket.AF_INET, udp)
   7.2  25 | firewall manager: --->   File "/root/.pex/installed_wheels/0d9e68051641ddb11ae2a297ad09cac33277ceac/sshuttle_telepresence-0.78.2.dev45+gd250ccb-py2.py3-none-any.whl/sshuttle/methods/nat.py", line 115, in restore_firewall
   7.2  25 | firewall manager: --->     if ipt_chain_exists(family, table, chain):
   7.2  25 | firewall manager: --->   File "/root/.pex/installed_wheels/0d9e68051641ddb11ae2a297ad09cac33277ceac/sshuttle_telepresence-0.78.2.dev45+gd250ccb-py2.py3-none-any.whl/sshuttle/linux.py", line 32, in ipt_chain_exists
   7.2  25 | firewall manager: --->     raise Fatal('%r returned %d' % (argv, rv))
   7.2  25 | firewall manager: ---> sshuttle.helpers.Fatal: ['iptables', '-t', 'nat', '-nL'] returned 4
   7.2  25 | fatal: ['iptables', '-t', 'nat', '-nL'] returned 4
   7.2  25 | c : fatal: cleanup: ['sudo', '-p', '[local sudo] Password: ', 'PYTHONPATH=/home/milan/.pex/installed_wheels/0d9e68051641ddb11ae2a297ad09cac33277ceac/sshuttle_telepresence-0.78.2.dev45+gd250ccb-py2.py3-none-any.whl', '--', '/usr/bin/python3', '/usr/libexec/sshuttle-telepresence', '-v', '--method', 'nat', '--firewall'] returned 99
   7.3 TEL | [25] sshuttle: exit 99
   7.9 TEL | [26] exit 1 in 2.07 secs.
   7.9 TEL | [27] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-0.a.sanity.check.telepresence.io")'
   8.0 TEL | [27] exit 1 in 0.03 secs.

Would you like to file an issue in our issue tracker? You'll be able to review and edit before anything is posted to the public. We'd really appreciate the help improving our product. [Y/n]: Y
T: Exit cleanup in progress
T: Cleaning up Deployment telepresence-1579857793-782214-2768
```

This is the first time. It didn't work before, it's a fresh install of this Debian + telepresence + kubectl.

When I try just `sudo iptables -t nat -nL` I get
`iptables v1.8.2 (nf_tables):  CHAIN_ADD failed (No such file or directory): chain PREROUTING`

After some searching, it seems to be because Debian is using nftables instead of legacy iptables.

Running 

```
sudo update-alternatives --set iptables /usr/sbin/iptables-legacy
sudo update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
```

fixed the problem and Telepresence starts afterwards:

```
telepresence --namespace foo
T: Starting proxy with method 'vpn-tcp', which has the following limitations: All processes are affected, only one telepresence can run per machine, and you can't use other VPNs. You may need to add cloud hosts and headless services with T:  --also-proxy. For a full list of method limitations see https://telepresence.io/reference/methods.html
T: Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.
T: Starting network proxy to cluster using new Deployment telepresence-1579858265-7273467-3170

T: No traffic is being forwarded from the remote Deployment to your local machine. You can use the --expose option to specify which ports you want to forward.

T: Setup complete. Launching your command.
```

**Comment by ark3** [comment]
Hey, that's cool. I've not seen vpn-tcp work on Windows until now. Thank you! 

Anyhow, it sounds like we (or our `sshuttle`) should detect `nftables` and do something smarter. At the very least, reporting a clear error message with your workaround suggested would be an improvement.

**Comment by analytik** [comment]
Coincidentally, Windows 10 version 2004 was released yesterday-ish, so WSL2 will become more widespread, although of course it still depends on which distro they choose to download.

**Comment by donnyyung** [comment]
We've recently released a developer preview of Telepresence 2 for windows, and we no longer use iptables, so I think it should work for.  Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please open a new issue if you encounter any problems or have feature requests!
