### ISSUE TITLE
Telepresence + Ubuntu 18 + k3s - vpn-tcp method doesn't work

### ISSUE THREAD

**Issue by iirekm** [telepresenceio/telepresence#1248]
Telepresence + Ubuntu 18 + k3s - vpn-tcp method doesn't work.
`inject-tcp` method works normally.

Logs from telepresence pod:
```
kubectl logs -f pod/telepresence-1580969470-7945724-18138-84c7d7f68b-t4mn8 
Retrieving this pod's namespace from the process environment
Failed: TELEPRESENCE_CONTAINER_NAMESPACE not set
Reading this pod's namespace from the k8s service account
Pod's namespace is 'default'
Listening...
2020-02-06T06:11:14+0000 [-] Loading ./forwarder.py...
2020-02-06T06:11:14+0000 [-] SOCKSv5Factory starting on 9050
2020-02-06T06:11:14+0000 [socks.SOCKSv5Factory#info] Starting factory <socks.SOCKSv5Factory object at 0x7fd660c65a20>
2020-02-06T06:11:14+0000 [-] DNSDatagramProtocol starting on 9053
2020-02-06T06:11:14+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7fd660c65cc0>
2020-02-06T06:11:14+0000 [-] Loaded.
2020-02-06T06:11:14+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 19.10.0 (/usr/bin/python3.6 3.6.8) starting up.
2020-02-06T06:11:14+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.epollreactor.EPollReactor.
2020-02-06T06:11:44+0000 [Poll#info] Checkpoint
2020-02-06T06:12:14+0000 [Poll#info] Checkpoint
```

### Automatically included information

Command line: `['/usr/bin/telepresence', '--run', 'echo', 'ok!']`
Version: `0.104`
Python version: `3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0]`
kubectl version: `Client Version: v1.17.0 // Server Version: v1.17.2+k3s1`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux irek-xnote 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 82, in main
    runner, remote_info, env, socks_port, ssh, mount_dir, pod_info
  File "/usr/bin/telepresence/telepresence/outbound/setup.py", line 112, in launch
    runner_, remote_info, command, args.also_proxy, env, ssh
  File "/usr/bin/telepresence/telepresence/outbound/local.py", line 126, in launch_vpn
    connect_sshuttle(runner, remote_info, also_proxy, ssh)
  File "/usr/bin/telepresence/telepresence/outbound/vpn.py", line 319, in connect_sshuttle
    raise RuntimeError("vpn-tcp tunnel did not connect")
RuntimeError: vpn-tcp tunnel did not connect

```

Logs:

```
39.1 TEL | [202] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-85.a.sanity.check.telepresence.io")'
  39.2 TEL | [202] exit 1 in 0.12 secs.
  39.3 TEL | Wait for vpn-tcp connection: hellotelepresence-86
  39.3 TEL | [203] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-86")'
  39.5 TEL | [203] exit 1 in 0.17 secs.
  39.5 TEL | [204] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-86.a.sanity.check.telepresence.io")'
  39.7 TEL | [204] exit 1 in 0.17 secs.
  39.8 TEL | Wait for vpn-tcp connection: hellotelepresence-87
  39.8 TEL | [205] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-87")'
  39.9 TEL | [205] exit 1 in 0.17 secs.
  39.9 TEL | [206] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-87.a.sanity.check.telepresence.io")'
  40.1 TEL | [206] exit 1 in 0.18 secs.
  41.2  29 | c : Accept TCP: 192.168.0.171:60949 -> 10.42.0.2:8181.

```

**Comment by ark3** [comment]
Interesting. I use Telepresence with k3s regularly. Can you pass along the entire log as a Gist? The snipped captured by the crash reporter doesn't show any DNS requests making it to the proxy pod, which is odd. Are you running another VPN?

**Comment by iirekm** [comment]
The log file: https://gist.github.com/iirekm/4e9f0395869799020aca789d8d0e1873

There's no another VPN.
I have similar configuration (Ubuntu 18 + k3s) on other computer, and it works there. Very strange.

**Comment by ark3** [comment]
One more experiment. Can you temporarily configure your network so that DNS is handled by a DNS server that is not running on your machine? E.g., point DNS to Google (8.8.8.8) or CloudFlare (1.1.1.1).

How different is `/etc/resolv.conf` on the machine that works? Does the non-working machine move between networks (i.e. is it a laptop)?
