### ISSUE TITLE
Problem running tutorial

### ISSUE THREAD

**Issue by lewijw** [telepresenceio/telepresence#1254]
### What were you trying to do?

Trying this tutorial:

https://www.telepresence.io/tutorials/docker

Got to this command:
telepresence --docker-run --rm -it pstauffer/curl curl http://hello-world:8000

### What did you expect to happen?

Not the message "Looks like there's a bug".

### Automatically included information

Command line: `['/usr/bin/telepresence', '--docker-run', '--rm', '-it', 'pstauffer/curl', 'curl', 'http://hello-world:8000/', '-n', 'mynamespace']`
Version: `0.104`
Python version: `3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0]`
kubectl version: `Client Version: v1.17.3 // Server Version: v1.16.3`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux d7c065 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux`

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 39, in main
    runner = Runner(args.logfile, args.verbose)
  File "/usr/bin/telepresence/telepresence/runner/runner.py", line 134, in __init__
    os.makedirs(tmp_dir)
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/c'

```

Logs:

```
Not available
```

**Comment by lewijw** [comment]
Using Ubuntu 18 in WSL.
