### ISSUE TITLE
Error when running --swap-deployment

### ISSUE THREAD

**Issue by benjaminhuo** [telepresenceio/telepresence#1275]
### What were you trying to do?

Run --swap-deployment

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--namespace', 'kubesphere-monitoring-system', '--swap-deployment', 'kubesphere-monitoring-controller-manager:notification-manager-operator', '--run', 'bin/notification-manager-operator']`
Version: `0.104`
Python version: `3.7.7 (default, Mar 10 2020, 15:43:03) 
[Clang 11.0.0 (clang-1100.0.33.17)]`
kubectl version: `Client Version: v1.17.4 // Server Version: v1.17.3`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin huobingjiedeMacBook-Pro.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 65, in main
    remote_info = start_proxy(runner)
  File "/usr/local/bin/telepresence/telepresence/proxy/__init__.py", line 138, in start_proxy
    run_id=run_id,
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 193, in get_remote_info
    wait_for_pod(runner, remote_info)
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 125, in wait_for_pod
    "Pod isn't starting or can't be found: {}".format(pod["status"])
RuntimeError: Pod isn't starting or can't be found: {'conditions': [{'lastProbeTime': None, 'lastTransitionTime': '2020-03-26T07:36:26Z', 'status': 'True', 'type': 'Initialized'}, {'lastProbeTime': None, 'lastTransitionTime': '2020-03-26T07:36:26Z', 'message': 'containers with unready status: [kube-rbac-proxy notification-manager-operator]', 'reason': 'ContainersNotReady', 'status': 'False', 'type': 'Ready'}, {'lastProbeTime': None, 'lastTransitionTime': '2020-03-26T07:36:26Z', 'message': 'containers with unready status: [kube-rbac-proxy notification-manager-operator]', 'reason': 'ContainersNotReady', 'status': 'False', 'type': 'ContainersReady'}, {'lastProbeTime': None, 'lastTransitionTime': '2020-03-26T07:36:26Z', 'status': 'True', 'type': 'PodScheduled'}], 'containerStatuses': [{'image': 'gcr.azk8s.cn/kubebuilder/kube-rbac-proxy:v0.4.1', 'imageID': '', 'lastState': {}, 'name': 'kube-rbac-proxy', 'ready': False, 'restartCount': 0, 'started': False, 'state': {'waiting': {'reason': 'ContainerCreating'}}}, {'image': 'datawire/telepresence-k8s:0.104', 'imageID': '', 'lastState': {}, 'name': 'notification-manager-operator', 'ready': False, 'restartCount': 0, 'started': False, 'state': {'waiting': {'reason': 'ContainerCreating'}}}], 'hostIP': '192.168.0.18', 'phase': 'Pending', 'qosClass': 'Burstable', 'startTime': '2020-03-26T07:36:26Z'}

```

Logs:

```
ng: kubectl --context kubernetes-admin@cluster.local --namespace kubesphere-monitoring-system get pod kubesphere-monito-c7f61fefcaee47728374849eccdac678-5799c8fsqdlt -o json
 125.7 TEL | [184] captured in 0.44 secs.
 125.9 TEL | [185] Capturing: kubectl --context kubernetes-admin@cluster.local --namespace kubesphere-monitoring-system get pod kubesphere-monito-c7f61fefcaee47728374849eccdac678-5799c8fsqdlt -o json
 126.4 TEL | [185] captured in 0.44 secs.
 126.6 TEL | [186] Capturing: kubectl --context kubernetes-admin@cluster.local --namespace kubesphere-monitoring-system get pod kubesphere-monito-c7f61fefcaee47728374849eccdac678-5799c8fsqdlt -o json
 127.0 TEL | [186] captured in 0.44 secs.
 127.3 TEL | [187] Capturing: kubectl --context kubernetes-admin@cluster.local --namespace kubesphere-monitoring-system get pod kubesphere-monito-c7f61fefcaee47728374849eccdac678-5799c8fsqdlt -o json
 127.7 TEL | [187] captured in 0.44 secs.
 127.7 TEL | END SPAN remote.py:104(wait_for_pod)  120.0s

```

**Comment by benjaminhuo** [comment]
/
