### ISSUE TITLE
problemas telepresence

### ISSUE THREAD

**Issue by samerbite** [telepresenceio/telepresence#1278]
### What were you trying to do?

(please tell us)

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/bin/telepresence']`
Version: `0.104`
Python version: `3.7.6 (default, Jan 30 2020, 10:29:04) 
[GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]`
kubectl version: `Client Version: v1.18.0 // Server Version: v1.15.7`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux everis-fvenegar 5.5.10-100.fc30.x86_64 #1 SMP Wed Mar 18 14:34:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 65, in main
    remote_info = start_proxy(runner)
  File "/usr/bin/telepresence/telepresence/proxy/__init__.py", line 138, in start_proxy
    run_id=run_id,
  File "/usr/bin/telepresence/telepresence/proxy/remote.py", line 144, in get_remote_info
    runner, deployment_name, deployment_type, run_id=run_id
  File "/usr/bin/telepresence/telepresence/proxy/remote.py", line 91, in get_deployment_json
    return json.loads(output)["items"][0]
IndexError: list index out of range

```

Logs:

```
ignore-not-found svc,deploy --selector=telepresence=706e26beb27846cf8af8ddde77ae1548
   9.4  10 | No resources found
   9.4 TEL | [10] ran in 0.84 secs.
   9.4 TEL | [11] Running: kubectl --context bci-api-desa001 --namespace default run --restart=Always --limits=cpu=1000m,memory=256Mi --requests=cpu=25m,memory=64Mi telepresence-1585321562-9735575-5518 --image=datawire/telepresence-k8s:0.104 --labels=telepresence=706e26beb27846cf8af8ddde77ae1548
  10.2  11 | pod/telepresence-1585321562-9735575-5518 created
  10.2 TEL | [11] ran in 0.78 secs.
  10.2 TEL | END SPAN deployment.py:108(create_new_deployment)    1.6s
  10.2 TEL | BEGIN SPAN remote.py:142(get_remote_info)
  10.2 TEL | BEGIN SPAN remote.py:75(get_deployment_json)
  10.2 TEL | [12] Capturing: kubectl --context bci-api-desa001 --namespace default get deployment -o json --selector=telepresence=706e26beb27846cf8af8ddde77ae1548
  10.8 TEL | [12] captured in 0.62 secs.
  10.8 TEL | END SPAN remote.py:75(get_deployment_json)    0.6s

```

**Comment by samerbite** [comment]
Solved! my problem was the update in my kubectl. I did a downgrade in my version and telepresence working again.
kubectl-1.17.4-0.x86_64 si
kubectl-1.18.0-0.x86_64 NO!
