### ISSUE TITLE
when i run telepresence not working

### ISSUE THREAD

**Issue by heweizhen0822** [telepresenceio/telepresence#1288]
### What were you trying to do?

(please tell us)

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence']`
Version: `0.104`
Python version: `3.7.4 (v3.7.4:e09359112e, Jul  8 2019, 14:54:52) 
[Clang 6.0 (clang-600.0.57)]`
kubectl version: `Client Version: v1.18.0 // Server Version: v1.15.0`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin hewz.local 18.2.0 Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 65, in main
    remote_info = start_proxy(runner)
  File "/usr/local/bin/telepresence/telepresence/proxy/__init__.py", line 138, in start_proxy
    run_id=run_id,
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 144, in get_remote_info
    runner, deployment_name, deployment_type, run_id=run_id
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 91, in get_deployment_json
    return json.loads(output)["items"][0]
IndexError: list index out of range

```

Logs:

```
und svc,deploy --selector=telepresence=f597554a8b444ad7b7f3751c2f823b6d
   2.1   9 | No resources found
   2.1 TEL | [9] ran in 0.12 secs.
   2.1 TEL | [10] Running: kubectl --context context-cluster1-admin --namespace default run --restart=Always --limits=cpu=1000m,memory=256Mi --requests=cpu=25m,memory=64Mi telepresence-1585733449-369625-27580 --image=datawire/telepresence-k8s:0.104 --labels=telepresence=f597554a8b444ad7b7f3751c2f823b6d
   2.2  10 | pod/telepresence-1585733449-369625-27580 created
   2.2 TEL | [10] ran in 0.10 secs.
   2.2 TEL | END SPAN deployment.py:108(create_new_deployment)    0.2s
   2.2 TEL | BEGIN SPAN remote.py:142(get_remote_info)
   2.2 TEL | BEGIN SPAN remote.py:75(get_deployment_json)
   2.2 TEL | [11] Capturing: kubectl --context context-cluster1-admin --namespace default get deployment -o json --selector=telepresence=f597554a8b444ad7b7f3751c2f823b6d
   2.5 TEL | [11] captured in 0.31 secs.
   2.5 TEL | END SPAN remote.py:75(get_deployment_json)    0.3s

```

**Comment by heweizhen0822** [comment]
执行 kubectl version 查看客户端和服务端的版本号。客户端不能高于服务端。我的就是服务端是v1.17.4而客户端是最新的，导致异常。
