### ISSUE TITLE
Failed to connect to google cloud kubernetes clusted

### ISSUE THREAD

**Issue by Deimantas-Saltis** [telepresenceio/telepresence#1291]
### What were you trying to do?

Trying to use telepresence by connecting into Google cloud kubernetes cluster.

### What did you expect to happen?

After connection to google cloud, there should be created kubernetes pod.

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/bin/telepresence', '--new-deployment', 'z-deimantas-presence', '--also-proxy', 'cloudsql.default']`
Version: `0.104`
Python version: `3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0]`
kubectl version: `Client Version: v1.18.0 // Server Version: v1.15.9-gke.24`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux Deimantas 5.3.0-45-generic #37~18.04.1-Ubuntu SMP Fri Mar 27 15:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 65, in main
    remote_info = start_proxy(runner)
  File "/usr/bin/telepresence/telepresence/proxy/__init__.py", line 138, in start_proxy
    run_id=run_id,
  File "/usr/bin/telepresence/telepresence/proxy/remote.py", line 144, in get_remote_info
    runner, deployment_name, deployment_type, run_id=run_id
  File "/usr/bin/telepresence/telepresence/proxy/remote.py", line 91, in get_deployment_json
    return json.loads(output)["items"][0]
IndexError: list index out of range

```

Logs:

Looks like there's a bug in our code. Sorry about that!

Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 65, in main
    remote_info = start_proxy(runner)
  File "/usr/bin/telepresence/telepresence/proxy/__init__.py", line 138, in start_proxy
    run_id=run_id,
  File "/usr/bin/telepresence/telepresence/proxy/remote.py", line 144, in get_remote_info
    runner, deployment_name, deployment_type, run_id=run_id
  File "/usr/bin/telepresence/telepresence/proxy/remote.py", line 91, in get_deployment_json
    return json.loads(output)["items"][0]
IndexError: list index out of range

Here are the last few lines of the logfile (see /home/deimantas/IdeaProjects/SME/sme-ops/telepresence.log for the complete logs):

   1.6 TEL | [10] Running: kubectl --context TEST --namespace default delete --ignore-not-found svc,deploy --selector=telepresence=413ea613365041fea9f8bb98feb74637
   1.9  10 | No resources found
   1.9 TEL | [10] ran in 0.29 secs.
   1.9 TEL | [11] Running: kubectl --context TEST --namespace default run --restart=Always --limits=cpu=1000m,memory=256Mi --requests=cpu=25m,memory=64Mi z-deimantas-presence --image=datawire/telepresence-k8s:0.104 --labels=telepresence=413ea613365041fea9f8bb98feb74637
   2.1  11 | pod/z-deimantas-presence created
   2.1 TEL | [11] ran in 0.23 secs.
   2.1 TEL | END SPAN deployment.py:108(create_new_deployment)    0.5s
   2.1 TEL | BEGIN SPAN remote.py:142(get_remote_info)
   2.1 TEL | BEGIN SPAN remote.py:75(get_deployment_json)
   2.1 TEL | [12] Capturing: kubectl --context TEST --namespace default get deployment -o json --selector=telepresence=413ea613365041fea9f8bb98feb74637
   2.4 TEL | [12] captured in 0.26 secs.
   2.4 TEL | END SPAN remote.py:75(get_deployment_json)    0.3s

```
: kubectl --context TEST --namespace default delete --ignore-not-found svc,deploy --selector=telepresence=413ea613365041fea9f8bb98feb74637
   1.9  10 | No resources found
   1.9 TEL | [10] ran in 0.29 secs.
   1.9 TEL | [11] Running: kubectl --context TEST --namespace default run --restart=Always --limits=cpu=1000m,memory=256Mi --requests=cpu=25m,memory=64Mi z-deimantas-presence --image=datawire/telepresence-k8s:0.104 --labels=telepresence=413ea613365041fea9f8bb98feb74637
   2.1  11 | pod/z-deimantas-presence created
   2.1 TEL | [11] ran in 0.23 secs.
   2.1 TEL | END SPAN deployment.py:108(create_new_deployment)    0.5s
   2.1 TEL | BEGIN SPAN remote.py:142(get_remote_info)
   2.1 TEL | BEGIN SPAN remote.py:75(get_deployment_json)
   2.1 TEL | [12] Capturing: kubectl --context TEST --namespace default get deployment -o json --selector=telepresence=413ea613365041fea9f8bb98feb74637
   2.4 TEL | [12] captured in 0.26 secs.
   2.4 TEL | END SPAN remote.py:75(get_deployment_json)    0.3s

```

**Comment by Deimantas-Saltis** [comment]
Closed for no actions taken
