### ISSUE TITLE
just starting from command line

### ISSUE THREAD

**Issue by kgignatyev** [telepresenceio/telepresence#1295]
### What were you trying to do?

(please tell us)

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence']`
Version: `0.104`
Python version: `3.7.7 (default, Mar 10 2020, 15:43:03) 
[Clang 11.0.0 (clang-1100.0.33.17)]`
kubectl version: `Client Version: v1.18.0 // Server Version: v1.14.9-eks-502bfb`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin Konstantins-iMac.local 18.7.0 Darwin Kernel Version 18.7.0: Mon Feb 10 21:08:45 PST 2020; root:xnu-4903.278.28~1/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 65, in main
    remote_info = start_proxy(runner)
  File "/usr/local/bin/telepresence/telepresence/proxy/__init__.py", line 138, in start_proxy
    run_id=run_id,
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 144, in get_remote_info
    runner, deployment_name, deployment_type, run_id=run_id
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 91, in get_deployment_json
    return json.loads(output)["items"][0]
IndexError: list index out of range

```

Logs:

```
o resources found
   4.5 TEL | [9] ran in 0.61 secs.
   4.5 TEL | [10] Running: kubectl --context arn:aws:eks:us-west-2:483387794659:cluster/dev01-us-west-2-cluster --namespace default run --restart=Always --limits=cpu=1000m,memory=256Mi --requests=cpu=25m,memory=64Mi telepresence-1586225567-848067-6796 --image=datawire/telepresence-k8s:0.104 --labels=telepresence=c21373bd077f43749d9ac51e3e535857
   5.0  10 | pod/telepresence-1586225567-848067-6796 created
   5.0 TEL | [10] ran in 0.54 secs.
   5.0 TEL | END SPAN deployment.py:108(create_new_deployment)    1.2s
   5.0 TEL | BEGIN SPAN remote.py:142(get_remote_info)
   5.0 TEL | BEGIN SPAN remote.py:75(get_deployment_json)
   5.0 TEL | [11] Capturing: kubectl --context arn:aws:eks:us-west-2:483387794659:cluster/dev01-us-west-2-cluster --namespace default get deployment -o json --selector=telepresence=c21373bd077f43749d9ac51e3e535857
   5.5 TEL | [11] captured in 0.55 secs.
   5.5 TEL | END SPAN remote.py:75(get_deployment_json)    0.5s

```

**Comment by jtyers** [comment]
see workaround in #1297
