### ISSUE TITLE
Unable to telepresence

### ISSUE THREAD

**Issue by mt-rahul** [telepresenceio/telepresence#1298]
### What were you trying to do?

I was trying to telepresence one of the service which was used to work earlier. 

### What did you expect to happen?

I expected to successfully telepresence that service.

### What happened instead?

It returned an error with following trace which was not expected. Please find below link to complete logs from telepresence. 

https://gist.github.com/mt-rahul/fec3f4719ad604965e7ae7549a4ed14f

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--namespace', 'dev', '--swap-deployment', 'asr', '--env-file', '/Users/rahul/tmp.env']`
Version: `0.97`
Python version: `3.7.0 (v3.7.0:1bf9cc5093, Jun 26 2018, 23:26:24) 
[Clang 6.0 (clang-600.0.57)]`
kubectl version: `Client Version: v1.16.3 // Server Version: v1.14.9-eks-502bfb`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin Rahul-Agrawal.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 130, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 60, in main
    remote_info = start_proxy(runner)
  File "/usr/local/bin/telepresence/telepresence/proxy/__init__.py", line 98, in start_proxy
    runner_, deployment_arg, image_name, args.expose, add_custom_ns
  File "/usr/local/bin/telepresence/telepresence/proxy/deployment.py", line 162, in supplant_deployment
    "deployment",
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 91, in get_deployment_json
    stderr=STDOUT
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

Logs:

```
d sshfs -> /usr/local/bin/sshfs
   6.5 TEL | Found umount -> /sbin/umount
   6.5 >>> | Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.
   6.5 TEL | [9] Capturing: kubectl --context <cluster-context> --namespace dev get pods telepresence-connectivity-check --ignore-not-found
   8.0 TEL | Scout info: {'latest_version': '0.97', 'FAILED': '<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)>'}
   8.0 TEL | BEGIN SPAN deployment.py:150(supplant_deployment)
   8.0 >>> | Starting network proxy to cluster by swapping out Deployment asr with a proxy
   8.0 TEL | BEGIN SPAN remote.py:78(get_deployment_json)
   8.0 TEL | [10] Capturing: kubectl --context <cluster-context> --namespace dev get deployment -o json --export asr
   8.7 TEL | END SPAN remote.py:78(get_deployment_json)    0.7s

```

**Comment by jtyers** [comment]
see workaround in #1297
