### ISSUE TITLE
ocp image not configured for password-less sudo

### ISSUE THREAD

**Issue by marun** [telepresenceio/telepresence#1305]
Attempting to invoke telepresence against an ocp cluster results in the output that follows, indicating that password-less sudo is not configured correctly. Using the default remote image works fine against the same cluster.

```
telepresence --namespace=openshift-authentication-operator --swap-deployment authentication-operator --run run-local-operator.sh
T: Failed to find OpenShift deploymentconfig authentication-operator:
T:   Error from server (NotFound): deploymentconfigs.apps.openshift.io "authentication-operator" not found
T: Will try regular Kubernetes Deployment.
T: Starting proxy with method 'vpn-tcp', which has the following limitations: All processes are affected, only one telepresence can run per machine, and you can't use other VPNs. You may need to add cloud hosts and headless services with --also-proxy. For a full list of
T: method limitations see https://telepresence.io/reference/methods.html
T: Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.
T: Starting network proxy to cluster by swapping out Deployment authentication-operator with a proxy
telepresence@127.0.0.1's password:
telepresence@127.0.0.1's password:
telepresence@127.0.0.1's password:
telepresence@127.0.0.1's password:
telepresence@127.0.0.1's password:
telepresence@127.0.0.1's password:

Looks like there's a bug in our code. Sorry about that!

Traceback (most recent call last):
  File "/home/maru/src/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/home/maru/src/telepresence/telepresence/main.py", line 68, in main
    socks_port, ssh = do_connect(runner, remote_info)
  File "/home/maru/src/telepresence/telepresence/connect/connect.py", line 119, in do_connect
    args.from_pod
  File "/home/maru/src/telepresence/telepresence/connect/connect.py", line 70, in connect
    raise RuntimeError("SSH to the cluster failed to start. See logfile.")
RuntimeError: SSH to the cluster failed to start. See logfile.
```

**Comment by thallgren** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
