### ISSUE TITLE
SSH connection fails with OpenShift 4.3 - prompting for password

### ISSUE THREAD

**Issue by bszeti** [telepresenceio/telepresence#1309]
### What were you trying to do?

Running _telepresence_ on Mac for an OpenShift 4.3 cluster, getting ssh connection error. The same works for an OpenShift 3.11 cluster.

The root cause of the problem is ssh connection failure to the _telepresence-ocp:0.104_ image in OpenShift 4 (tried OCP 4.3 and 4.2 too). If I try to create a pod directly, I can't _ssh_ to the container's 8022 port. The same works if I start the same image in OpenShift 3.11 (also in Minishift).

Steps to reproduce:
1. Have an OpenShift 4.3 cluster or use Red Hat CodeReady Containers on a laptop
2. Create a Pod:
```
apiVersion: v1
kind: Pod
metadata:
  name: telepresence
spec:
  containers:
  - image: datawire/telepresence-ocp:0.104
    imagePullPolicy: Always
    name: telepresence
```
3. Port-forward port 8022
`oc port-forward pod/telepresence 12345:8022`
4. Try to connect using ssh
`ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -p 12345 telepresence@127.0.0.1`

The connection fails if the _telepresence_ container is running in OpenShift 4.3, but works if it's an OpenShift 3.11 cluster.
 
### What did you expect to happen?

Getting a shell prompt from Telepresence.

### What happened instead?

The SSH connection ask for password:
T: Starting network proxy to cluster using new Deployment telepresence-1587094547-8981361-4430
telepresence@127.0.0.1's password:
telepresence@127.0.0.1's password:
telepresence@127.0.0.1's password:

### Automatically included information

Command line: `['/usr/local/bin/telepresence']`
Version: `0.104`
Python version: `3.7.7 (default, Mar 10 2020, 15:43:33) 
[Clang 11.0.0 (clang-1100.0.33.17)]`
kubectl version: `Client Version: v1.16.2 // Server Version: v1.16.2`
oc version: `Client Version: v4.3.0 // Server Version: 4.3.5 // Kubernetes Version: v1.16.2`
OS: `Darwin bszeti-mac 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 68, in main
    socks_port, ssh = do_connect(runner, remote_info)
  File "/usr/local/bin/telepresence/telepresence/connect/connect.py", line 119, in do_connect
    args.from_pod
  File "/usr/local/bin/telepresence/telepresence/connect/connect.py", line 70, in connect
    raise RuntimeError("SSH to the cluster failed to start. See logfile.")
RuntimeError: SSH to the cluster failed to start. See logfile.

```

Logs:

```
      node.kubernetes.io/not-ready:NoExecute for 300s
  43.7  33 |                  node.kubernetes.io/unreachable:NoExecute for 300s
  43.7  33 | Events:
  43.7  33 |   Type    Reason     Age        From                                  Message
  43.7  33 |   ----    ------     ----       ----                                  -------
  43.7  33 |   Normal  Scheduled  <unknown>  default-scheduler                     Successfully assigned myproject/telepresence-1587094547-8981361-4430-1-mwdd4 to ip-10-0-154-16.ec2.internal
  43.7  33 |   Normal  Pulled     33s        kubelet, ip-10-0-154-16.ec2.internal  Container image "datawire/telepresence-ocp:0.104" already present on machine
  43.7  33 |   Normal  Created    33s        kubelet, ip-10-0-154-16.ec2.internal  Created container telepresence-1587094547-8981361-4430
  43.7  33 |   Normal  Started    33s        kubelet, ip-10-0-154-16.ec2.internal  Started container telepresence-1587094547-8981361-4430
  43.7 TEL | [33] ran in 0.28 secs.

```

**Comment by bszeti** [comment]
Also tried with _anyuid_ SCC.
Also tried the latest image: telepresence-ocp:0.104-13-g44a720f

**Comment by bszeti** [comment]
Log attached:
[telepresence.log](https://github.com/telepresenceio/telepresence/files/4490842/telepresence.log)

**Comment by bszeti** [comment]
Telepresence pod log:
```
   0.0 TEL | Telepresence 0.104 launched at Thu Apr 16 23:35:47 2020
   0.0 TEL |   /usr/local/bin/telepresence
   0.0 TEL | uname: uname_result(system='Darwin', node='bszeti-mac', release='19.3.0', version='Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64', machine='x86_64', processor='i386')
   0.0 TEL | Platform: darwin
   0.0 TEL | WSL: False
   0.0 TEL | Python 3.7.7 (default, Mar 10 2020, 15:43:33)
   0.0 TEL | [Clang 11.0.0 (clang-1100.0.33.17)]
   0.0 TEL | BEGIN SPAN main.py:40(main)
   0.0 TEL | BEGIN SPAN startup.py:83(set_kube_command)
   0.0 TEL | Found kubectl -> /usr/local/bin/kubectl
   0.0 TEL | Found oc -> /usr/local/bin/oc
   0.0 TEL | [1] Capturing: kubectl config current-context
   0.1 TEL | [1] captured in 0.06 secs.
   0.1 TEL | [2] Capturing: kubectl --context myproject/api-cluster-newyork-12c6-newyork-12c6-example-opentlc-com:6443/opentlc-mgr version --short
   0.3 TEL | [2] captured in 0.18 secs.
   0.3 TEL | [3] Capturing: kubectl --context myproject/api-cluster-newyork-12c6-newyork-12c6-example-opentlc-com:6443/opentlc-mgr config view -o json
   0.3 TEL | [3] captured in 0.06 secs.
   0.3 TEL | [4] Capturing: kubectl --context myproject/api-cluster-newyork-12c6-newyork-12c6-example-opentlc-com:6443/opentlc-mgr get ns myproject
   0.5 TEL | [4] captured in 0.16 secs.
   0.5 TEL | [5] Capturing: kubectl --context myproject/api-cluster-newyork-12c6-newyork-12c6-example-opentlc-com:6443/opentlc-mgr api-versions
   0.7 TEL | [5] captured in 0.21 secs.
   0.7 TEL | Command: oc 1.16.2
   0.7 TEL | Context: myproject/api-cluster-newyork-12c6-newyork-12c6-example-opentlc-com:6443/opentlc-mgr, namespace: myproject, version: 1.16.2
   0.7 TEL | [6] Capturing: minishift ip
   1.1 TEL | [6] captured in 0.35 secs.
   1.1 TEL | END SPAN startup.py:83(set_kube_command)    1.0s
   1.1 TEL | Found ssh -> /usr/bin/ssh
   1.1 TEL | [7] Capturing: ssh -V
   1.1 TEL | [7] captured in 0.02 secs.
   1.1 TEL | Found bash -> /bin/bash
   1.1 TEL | Found sshuttle-telepresence -> /usr/local/Cellar/telepresence/0.104/libexec/sshuttle-telepresence
   1.1 TEL | Found pfctl -> /sbin/pfctl
   1.1 TEL | Found sudo -> /usr/bin/sudo
   1.1 TEL | [8] Running: sudo -n echo -n
   1.2   8 | sudo: a password is required
   1.2 TEL | [8] exit 1 in 0.09 secs.
   1.2 >>> | How Telepresence uses sudo: https://www.telepresence.io/reference/install#dependencies
   1.2 >>> | Invoking sudo. Please enter your sudo password.
   1.2 TEL | [9] Running: sudo echo -n
   4.5 TEL | [9] ran in 3.37 secs.
   4.5 >>> | Starting proxy with method 'vpn-tcp', which has the following limitations: All processes are affected, only one telepresence can run per machine, and you can't use other VPNs. You may need to add cloud hosts and headless services with --also-proxy. For a full list of method limitations see https://telepresence.io/reference/methods.html
   4.5 TEL | Found sshfs -> /usr/local/bin/sshfs
   4.5 TEL | Found umount -> /sbin/umount
   4.5 >>> | Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.
   4.5 TEL | [10] Running: oc --context myproject/api-cluster-newyork-12c6-newyork-12c6-example-opentlc-com:6443/opentlc-mgr --namespace myproject get pods telepresence-connectivity-check --ignore-not-found
   4.8 TEL | [10] ran in 0.24 secs.
   5.3 TEL | Scout info: {'latest_version': '0.104', 'application': 'telepresence', 'notices': []}
   5.3 TEL | BEGIN SPAN deployment.py:108(create_new_deployment)
   5.3 >>> | Starting network proxy to cluster using new Deployment telepresence-1587094547-8981361-4430
   5.3 TEL | [11] Running: oc --context myproject/api-cluster-newyork-12c6-newyork-12c6-example-opentlc-com:6443/opentlc-mgr --namespace myproject delete --ignore-not-found svc,deploy --selector=telepresence=526477c950a2437389e8f31c16f3f71d
   5.5  11 | No resources found
   5.5 TEL | [11] ran in 0.27 secs.
   5.5 TEL | [12] Running: oc --context myproject/api-cluster-newyork-12c6-newyork-12c6-example-opentlc-com:6443/opentlc-mgr --namespace myproject run --restart=Always --limits=cpu=1000m,memory=256Mi --requests=cpu=25m,memory=64Mi telepresence-1587094547-8981361-4430 --image=datawire/telepresence-ocp:0.104 --labels=telepresence=526477c950a2437389e8f31c16f3f71d
   5.6  12 | kubectl run --generator=deploymentconfig/v1 is DEPRECATED and will be removed in a future version. Use kubectl run --generator=run-pod/v1 or kubectl create instead.
   5.7  12 | deploymentconfig.apps.openshift.io/telepresence-1587094547-8981361-4430 created
   5.7 TEL | [12] ran in 0.22 secs.
   5.7 TEL | END SPAN deployment.py:108(create_new_deployment)    0.5s
   5.7 TEL | BEGIN SPAN remote.py:142(get_remote_info)
   5.7 TEL | BEGIN SPAN remote.py:75(get_deployment_json)
   5.7 TEL | [13] Capturing: oc --context myproject/api-cluster-newyork-12c6-newyork-12c6-example-opentlc-com:6443/opentlc-mgr --namespace myproject get deploymentconfig -o json --selector=telepresence=526477c950a2437389e8f31c16f3f71d
   6.0 TEL | [13] captured in 0.21 secs.
   6.0 TEL | END SPAN remote.py:75(get_deployment_json)    0.2s
   6.0 TEL | Searching for Telepresence pod:
   6.0 TEL |   with name telepresence-1587094547-8981361-4430-*
   6.0 TEL |   with labels {'telepresence': '526477c950a2437389e8f31c16f3f71d'}
   6.0 TEL | [14] Capturing: oc --context myproject/api-cluster-newyork-12c6-newyork-12c6-example-opentlc-com:6443/opentlc-mgr --namespace myproject get pod -o json --selector=telepresence=526477c950a2437389e8f31c16f3f71d
   6.2 TEL | [14] captured in 0.21 secs.
   7.2 TEL | [15] Capturing: oc --context myproject/api-cluster-newyork-12c6-newyork-12c6-example-opentlc-com:6443/opentlc-mgr --namespace myproject get pod -o json --selector=telepresence=526477c950a2437389e8f31c16f3f71d
   7.4 TEL | [15] captured in 0.21 secs.
   8.4 TEL | [16] Capturing: oc --context myproject/api-cluster-newyork-12c6-newyork-12c6-example-opentlc-com:6443/opentlc-mgr --namespace myproject get pod -o json --selector=telepresence=526477c950a2437389e8f31c16f3f71d
   8.7 TEL | [16] captured in 0.30 secs.
   9.7 TEL | [17] Capturing: oc --context myproject/api-cluster-newyork-12c6-newyork-12c6-example-opentlc-com:6443/opentlc-mgr --namespace myproject get pod -o json --selector=telepresence=526477c950a2437389e8f31c16f3f71d
   9.9 TEL | [17] captured in 0.24 secs.
   9.9 TEL | Checking telepresence-1587094547-8981361-4430-1-mwdd4
   9.9 TEL | Looks like we've found our pod!
   9.9 TEL | BEGIN SPAN remote.py:104(wait_for_pod)
   9.9 TEL | [18] Capturing: oc --context myproject/api-cluster-newyork-12c6-newyork-12c6-example-opentlc-com:6443/opentlc-mgr --namespace myproject get pod telepresence-1587094547-8981361-4430-1-mwdd4 -o json
  10.1 TEL | [18] captured in 0.19 secs.
  10.4 TEL | [19] Capturing: oc --context myproject/api-cluster-newyork-12c6-newyork-12c6-example-opentlc-com:6443/opentlc-mgr --namespace myproject get pod telepresence-1587094547-8981361-4430-1-mwdd4 -o json
  10.6 TEL | [19] captured in 0.21 secs.
  10.8 TEL | [20] Capturing: oc --context myproject/api-cluster-newyork-12c6-newyork-12c6-example-opentlc-com:6443/opentlc-mgr --namespace myproject get pod telepresence-1587094547-8981361-4430-1-mwdd4 -o json
  11.1 TEL | [20] captured in 0.22 secs.
  11.3 TEL | [21] Capturing: oc --context myproject/api-cluster-newyork-12c6-newyork-12c6-example-opentlc-com:6443/opentlc-mgr --namespace myproject get pod telepresence-1587094547-8981361-4430-1-mwdd4 -o json
  11.5 TEL | [21] captured in 0.21 secs.
  11.5 TEL | END SPAN remote.py:104(wait_for_pod)    1.6s
  11.5 TEL | END SPAN remote.py:142(get_remote_info)    5.8s
  11.5 TEL | BEGIN SPAN connect.py:37(connect)
  11.5 TEL | [22] Launching kubectl logs: oc --context myproject/api-cluster-newyork-12c6-newyork-12c6-example-opentlc-com:6443/opentlc-mgr --namespace myproject logs -f telepresence-1587094547-8981361-4430-1-mwdd4 --container telepresence-1587094547-8981361-4430 --tail=10
  11.5 TEL | [23] Launching kubectl port-forward: oc --context myproject/api-cluster-newyork-12c6-newyork-12c6-example-opentlc-com:6443/opentlc-mgr --namespace myproject port-forward telepresence-1587094547-8981361-4430-1-mwdd4 59237:8022
  11.5 TEL | [24] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 59237 telepresence@127.0.0.1 /bin/true
  11.6 TEL | [24] exit 255 in 0.02 secs.
  11.8  22 | 2020-04-17T03:35:58+0000 [-] Loading ./forwarder.py...
  11.8  22 | 2020-04-17T03:35:59+0000 [-] /etc/resolv.conf changed, reparsing
  11.8  22 | 2020-04-17T03:35:59+0000 [-] Resolver added ('172.30.0.10', 53) to server list
  11.8  22 | 2020-04-17T03:35:59+0000 [-] SOCKSv5Factory starting on 9050
  11.8  22 | 2020-04-17T03:35:59+0000 [socks.SOCKSv5Factory#info] Starting factory <socks.SOCKSv5Factory object at 0x7f211efef390>
  11.8  22 | 2020-04-17T03:35:59+0000 [-] DNSDatagramProtocol starting on 9053
  11.8  22 | 2020-04-17T03:35:59+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7f211efef6d8>
  11.8  22 | 2020-04-17T03:35:59+0000 [-] Loaded.
  11.8  22 | 2020-04-17T03:35:59+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 19.10.0 (/opt/rh/rh-python36/root/usr/bin/python3 3.6.9) starting up.
  11.8  22 | 2020-04-17T03:35:59+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.epollreactor.EPollReactor.
  11.8 TEL | [25] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 59237 telepresence@127.0.0.1 /bin/true
  11.8 TEL | [25] exit 255 in 0.03 secs.
  11.9  23 | Forwarding from 127.0.0.1:59237 -> 8022
  11.9  23 | Forwarding from [::1]:59237 -> 8022
  12.1 TEL | [26] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 59237 telepresence@127.0.0.1 /bin/true
  12.1  23 | Handling connection for 59237
  17.1 TEL | [26] timed out after 5.01 secs.
  17.4 TEL | [27] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 59237 telepresence@127.0.0.1 /bin/true
  17.4  23 | Handling connection for 59237
  22.4 TEL | [27] timed out after 5.01 secs.
  22.6 TEL | [28] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 59237 telepresence@127.0.0.1 /bin/true
  22.7  23 | Handling connection for 59237
  27.6 TEL | [28] timed out after 5.01 secs.
  27.9 TEL | [29] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 59237 telepresence@127.0.0.1 /bin/true
  27.9  23 | Handling connection for 59237
  32.9 TEL | [29] timed out after 5.01 secs.
  33.2 TEL | [30] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 59237 telepresence@127.0.0.1 /bin/true
  33.2  23 | Handling connection for 59237
  34.6 TEL | [31] Running: sudo -n echo -n
  34.7 TEL | [31] ran in 0.04 secs.
  38.2 TEL | [30] timed out after 5.01 secs.
  38.4 TEL | [32] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 59237 telepresence@127.0.0.1 /bin/true
  38.4  23 | Handling connection for 59237
  41.8  22 | 2020-04-17T03:36:29+0000 [Poll#error] Failed to contact Telepresence client:
  41.8  22 | 2020-04-17T03:36:29+0000 [Poll#error] Connection was refused by other side: 111: Connection refused.
  41.8  22 | 2020-04-17T03:36:29+0000 [Poll#warn] Perhaps it's time to exit?
  43.4 TEL | [32] timed out after 5.01 secs.
  43.4 TEL | SSH timed out. Pod info follows.
  43.4 TEL | [33] Running: oc --context myproject/api-cluster-newyork-12c6-newyork-12c6-example-opentlc-com:6443/opentlc-mgr --namespace myproject describe pod telepresence-1587094547-8981361-4430-1-mwdd4
  43.7  33 | Name:         telepresence-1587094547-8981361-4430-1-mwdd4
  43.7  33 | Namespace:    myproject
  43.7  33 | Priority:     0
  43.7  33 | Node:         ip-10-0-154-16.ec2.internal/10.0.154.16
  43.7  33 | Start Time:   Thu, 16 Apr 2020 23:35:56 -0400
  43.7  33 | Labels:       deployment=telepresence-1587094547-8981361-4430-1
  43.7  33 |               deploymentconfig=telepresence-1587094547-8981361-4430
  43.7  33 |               telepresence=526477c950a2437389e8f31c16f3f71d
  43.7  33 | Annotations:  k8s.v1.cni.cncf.io/networks-status:
  43.7  33 |                 [{
  43.7  33 |                     "name": "openshift-sdn",
  43.7  33 |                     "interface": "eth0",
  43.7  33 |                     "ips": [
  43.7  33 |                         "10.131.0.38"
  43.7  33 |                     ],
  43.7  33 |                     "dns": {},
  43.7  33 |                     "default-route": [
  43.7  33 |                         "10.131.0.1"
  43.7  33 |                     ]
  43.7  33 |                 }]
  43.7  33 |               openshift.io/deployment-config.latest-version: 1
  43.7  33 |               openshift.io/deployment-config.name: telepresence-1587094547-8981361-4430
  43.7  33 |               openshift.io/deployment.name: telepresence-1587094547-8981361-4430-1
  43.7  33 |               openshift.io/scc: anyuid
  43.7  33 | Status:       Running
  43.7  33 | IP:           10.131.0.38
  43.7  33 | IPs:
  43.7  33 |   IP:           10.131.0.38
  43.7  33 | Controlled By:  ReplicationController/telepresence-1587094547-8981361-4430-1
  43.7  33 | Containers:
  43.7  33 |   telepresence-1587094547-8981361-4430:
  43.7  33 |     Container ID:   cri-o://7d260806c15f896ab39e8a32ca20c9b3c1840ab4b0e57acfe79aa0935847b038
  43.7  33 |     Image:          datawire/telepresence-ocp:0.104
  43.7  33 |     Image ID:       docker.io/datawire/telepresence-ocp@sha256:b8b35d35cca77930f5b4e7163a0a3803a94e4058cab07c7d8ff231b66c888f12
  43.7  33 |     Port:           <none>
  43.7  33 |     Host Port:      <none>
  43.7  33 |     State:          Running
  43.7  33 |       Started:      Thu, 16 Apr 2020 23:35:58 -0400
  43.7  33 |     Ready:          True
  43.7  33 |     Restart Count:  0
  43.7  33 |     Limits:
  43.7  33 |       cpu:     1
  43.7  33 |       memory:  256Mi
  43.7  33 |     Requests:
  43.7  33 |       cpu:        25m
  43.7  33 |       memory:     64Mi
  43.7  33 |     Environment:  <none>
  43.7  33 |     Mounts:
  43.7  33 |       /var/run/secrets/kubernetes.io/serviceaccount from default-token-2gpdb (ro)
  43.7  33 | Conditions:
  43.7  33 |   Type              Status
  43.7  33 |   Initialized       True
  43.7  33 |   Ready             True
  43.7  33 |   ContainersReady   True
  43.7  33 |   PodScheduled      True
  43.7  33 | Volumes:
  43.7  33 |   default-token-2gpdb:
  43.7  33 |     Type:        Secret (a volume populated by a Secret)
  43.7  33 |     SecretName:  default-token-2gpdb
  43.7  33 |     Optional:    false
  43.7  33 | QoS Class:       Burstable
  43.7  33 | Node-Selectors:  <none>
  43.7  33 | Tolerations:     node.kubernetes.io/memory-pressure:NoSchedule
  43.7  33 |                  node.kubernetes.io/not-ready:NoExecute for 300s
  43.7  33 |                  node.kubernetes.io/unreachable:NoExecute for 300s
  43.7  33 | Events:
  43.7  33 |   Type    Reason     Age        From                                  Message
  43.7  33 |   ----    ------     ----       ----                                  -------
  43.7  33 |   Normal  Scheduled  <unknown>  default-scheduler                     Successfully assigned myproject/telepresence-1587094547-8981361-4430-1-mwdd4 to ip-10-0-154-16.ec2.internal
  43.7  33 |   Normal  Pulled     33s        kubelet, ip-10-0-154-16.ec2.internal  Container image "datawire/telepresence-ocp:0.104" already present on machine
  43.7  33 |   Normal  Created    33s        kubelet, ip-10-0-154-16.ec2.internal  Created container telepresence-1587094547-8981361-4430
  43.7  33 |   Normal  Started    33s        kubelet, ip-10-0-154-16.ec2.internal  Started container telepresence-1587094547-8981361-4430
  43.7 TEL | [33] ran in 0.28 secs.
  45.7 TEL | CRASH: SSH to the cluster failed to start. See logfile.
  45.7 TEL | Traceback (most recent call last):
  45.7 TEL |   File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
  45.7 TEL |     yield
  45.7 TEL |   File "/usr/local/bin/telepresence/telepresence/main.py", line 68, in main
  45.7 TEL |     socks_port, ssh = do_connect(runner, remote_info)
  45.7 TEL |   File "/usr/local/bin/telepresence/telepresence/connect/connect.py", line 119, in do_connect
  45.7 TEL |     args.from_pod
  45.7 TEL |   File "/usr/local/bin/telepresence/telepresence/connect/connect.py", line 70, in connect
  45.7 TEL |     raise RuntimeError("SSH to the cluster failed to start. See logfile.")
  45.7 TEL | RuntimeError: SSH to the cluster failed to start. See logfile.
  45.7 TEL | (calling crash reporter...)
  50.6 >>> | Exit cleanup in progress
  50.6 TEL | (Cleanup) Kill BG process [23] kubectl port-forward
  50.7 TEL | [23] kubectl port-forward: exit -15
  50.7 TEL | (Cleanup) Kill BG process [22] kubectl logs
  50.7 TEL | [22] kubectl logs: exit -15
  50.7 TEL | Background process (kubectl logs) exited with return code -15. Command was:
  50.7 TEL |   oc --context myproject/api-cluster-newyork-12c6-newyork-12c6-example-opentlc-com:6443/opentlc-mgr --namespace myproject logs -f telepresence-1587094547-8981361-4430-1-mwdd4 --container telepresence-1587094547-8981361-4430 --tail=10
  50.7 TEL | 
  50.7 TEL | Recent output was:
  50.7 TEL |   2020-04-17T03:35:59+0000 [-] SOCKSv5Factory starting on 9050
  50.7 TEL |   2020-04-17T03:35:59+0000 [socks.SOCKSv5Factory#info] Starting factory <socks.SOCKSv5Factory object at 0x7f211efef390>
  50.7 TEL |   2020-04-17T03:35:59+0000 [-] DNSDatagramProtocol starting on 9053
  50.7 TEL |   2020-04-17T03:35:59+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7f211efef6d8>
  50.7 TEL |   2020-04-17T03:35:59+0000 [-] Loaded.
  50.7 TEL |   2020-04-17T03:35:59+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 19.10.0 (/opt/rh/rh-python36/root/usr/bin/python3 3.6.9) starting up.
  50.7 TEL |   2020-04-17T03:35:59+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.epollreactor.EPollReactor.
  50.7 TEL |   2020-04-17T03:36:29+0000 [Poll#error] Failed to contact Telepresence client:
  50.7 TEL |   2020-04-17T03:36:29+0000 [Poll#error] Connection was refused by other side: 111: Connection refused.
  50.7 TEL |   2020-04-17T03:36:29+0000 [Poll#warn] Perhaps it's time to exit?
  50.7 TEL | (Cleanup) Delete new deployment
  50.7 >>> | Cleaning up Deployment telepresence-1587094547-8981361-4430
  50.7 TEL | [34] Running: oc --context myproject/api-cluster-newyork-12c6-newyork-12c6-example-opentlc-com:6443/opentlc-mgr --namespace myproject delete --ignore-not-found svc,deploy --selector=telepresence=526477c950a2437389e8f31c16f3f71d
  51.0  34 | No resources found
  51.0 TEL | [34] ran in 0.33 secs.
  51.0 TEL | (Cleanup) Kill sudo privileges holder
  51.0 TEL | (Cleanup) Stop time tracking
  51.0 TEL | END SPAN main.py:40(main)   51.0s
  51.0 TEL | (Cleanup) Remove temporary directory
  51.0 TEL | (Cleanup) Save caches
  51.7 TEL | (sudo privileges holder thread exiting)
```

**Comment by marun** [comment]
The default image works fine: https://github.com/telepresenceio/telepresence/pull/1306

**Comment by bszeti** [comment]
Thanks for response @marun 
As I understand the solution is to set env var _TELEPRESENCE_OCP_USE_DEFAULT_IMAGE=true_  
This feature was only added in your repo, so it only works if we install from the github.com/marun/telepresence.git source. Also the _telepresence-k8s_ image needs _anyuid_ SCC on OpenShift. 

I can confirm these steps worked for me with OCP 4.3:
```
git clone https://github.com/marun/telepresence.git
cd telepresence
sudo env PREFIX=/usr/local ./install.sh
export TELEPRESENCE_OCP_USE_DEFAULT_IMAGE=true
oc adm policy add-scc-to-user anyuid -z default
telepresence
```
I see the pull-request and will keep an eye on it when this will be merged into master and hopefully a new release (0.105?).

**Comment by bszeti** [comment]
Update for the ticket: v0.105 works with using the _telepresence-k8s_ image, but that requires _anyuid_ SCC:
```
$ oc new-project mytelepresence
$ oc adm policy add-scc-to-user anyuid -z default
$ export TELEPRESENCE_USE_OCP_IMAGE=NO
$ telepresence
```

**Comment by cryptox31** [comment]
@bszeti with telepresence 0.109 I'm getting the above error. 
```
T: Starting proxy with method 'vpn-tcp', which has the following limitations:
T:  All processes are affected, only one telepresence can run per machine,
T: and you can't use other VPNs. You may need to add cloud hosts and headless
T:  services with --also-proxy. For a full list of method limitations see
T: https://telepresence.io/reference/methods.html
T: Volumes are rooted at $TELEPRESENCE_ROOT. See
T: https://telepresence.io/howto/volumes.html for details.
T: Starting network proxy to cluster using new Pod
T: telepresence-1612288680-9404778-20956
telepresence@127.0.0.1's password:
telepresence@127.0.0.1's password:
telepresence@127.0.0.1's password:
telepresence@127.0.0.1's password:
telepresence@127.0.0.1's password:
telepresence@127.0.0.1's password:

Looks like there's a bug in our code. Sorry about that!

Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 68, in main
    socks_port, ssh = do_connect(runner, remote_info)
  File "/usr/local/bin/telepresence/telepresence/connect/connect.py", line 119, in do_connect
    args.from_pod
  File "/usr/local/bin/telepresence/telepresence/connect/connect.py", line 70, in connect
    raise RuntimeError("SSH to the cluster failed to start. See logfile.")
RuntimeError: SSH to the cluster failed to start. See logfile.
```

Also, I tried running the command
```
oc adm policy add-scc-to-user anyuid -z default
Error from server (NotFound): securitycontextconstraints.security.openshift.io "anyuid" not found
```

Any ideas to try here?

**Comment by bszeti** [comment]
The "anyuid" SCC may not be available in your cluster, or you're not having the required permissions to use that. It lets the processes in the Pod run with any user ID instead of the random generated (forced by "restricted" SCC).

On my cluster - logged is an cluster-admin - I see this for example:
```
$ oc get scc
NAME               PRIV    CAPS         SELINUX     RUNASUSER          FSGROUP     SUPGROUP    PRIORITY     READONLYROOTFS   VOLUMES
anyuid             false   <no value>   MustRunAs   RunAsAny           RunAsAny    RunAsAny    10           false            ["configMap","downwardAPI","emptyDir","persistentVolumeClaim","projected","secret"]
hostaccess         false   <no value>   MustRunAs   MustRunAsRange     MustRunAs   RunAsAny    <no value>   false            ["configMap","downwardAPI","emptyDir","hostPath","persistentVolumeClaim","projected","secret"]
hostmount-anyuid   false   <no value>   MustRunAs   RunAsAny           RunAsAny    RunAsAny    <no value>   false            ["configMap","downwardAPI","emptyDir","hostPath","nfs","persistentVolumeClaim","projected","secret"]
hostnetwork        false   <no value>   MustRunAs   MustRunAsRange     MustRunAs   MustRunAs   <no value>   false            ["configMap","downwardAPI","emptyDir","persistentVolumeClaim","projected","secret"]
node-exporter      true    <no value>   RunAsAny    RunAsAny           RunAsAny    RunAsAny    <no value>   false            ["*"]
nonroot            false   <no value>   MustRunAs   MustRunAsNonRoot   RunAsAny    RunAsAny    <no value>   false            ["configMap","downwardAPI","emptyDir","persistentVolumeClaim","projected","secret"]
privileged         true    ["*"]        RunAsAny    RunAsAny           RunAsAny    RunAsAny    <no value>   false            ["*"]
restricted         false   <no value>   MustRunAs   MustRunAsRange     MustRunAs   RunAsAny    <no value>   false            ["configMap","downwardAPI","emptyDir","persistentVolumeClaim","projected","secret"]
```

**Comment by cryptox31** [comment]
@bszeti I am logged in as admin. I do see a lot of SCCs similar to anyuid but don't see anyuid scc like you do. Can those be used instead?

**Comment by thallgren** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
