### ISSUE TITLE
Error trying to start api telepresence locally

### ISSUE THREAD

**Issue by karlschu13** [telepresenceio/telepresence#1319]
### What were you trying to do?
Start api locally:
```
❯ telepresence --new-deployment telepresence --verbose --also-proxy 10.0.0.0/16 --expose 23667 --namespace karls --run-shell
T: How Telepresence uses sudo: https://www.telepresence.io/reference/install#dependencies
T: Invoking sudo. Please enter your sudo password.
Password:
T: Starting proxy with method 'vpn-tcp', which has the following limitations: All processes are affected, only one telepresence can run per machine, and you can't use other VPNs.
T:  You may need to add cloud hosts and headless services with --also-proxy. For a full list of method limitations see https://telepresence.io/reference/methods.html
T: Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.
T: Starting network proxy to cluster using new Deployment telepresence
T: Forwarding remote port 23667 to local port 23667.

T: Connected. Flushing DNS cache.
T: Setup complete. Launching your command.

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
@arn:aws:eks:us-west-2:967376234080:cluster/dev|bash-3.2$ export EPHEMERAL_DEPLOYMENT=true
@arn:aws:eks:us-west-2:967376234080:cluster/dev|bash-3.2$ export TELEPRESENCE_SERVICE_HOST=$(kubectl get pods -l telepresence -n karls -o jsonpath='{range.items[*]}{.status.podIP}')
@arn:aws:eks:us-west-2:967376234080:cluster/dev|bash-3.2$ echo $TELEPRESENCE_SERVICE_HOST
10.0.109.244
@arn:aws:eks:us-west-2:967376234080:cluster/dev|bash-3.2$ bin/api zk-hs.karls.svc.cluster.local:2181
```

### What did you expect to happen?

Get logged into local telepresence.

### What happened instead?
Got a traceback:
```
MODULE_HOME: /Users/karl/git/sumo/sumologic/ops/assemblies/latest/api-20.1-SNAPSHOT-bin/api-20.1-SNAPSHOT
2020-04-21 16:54:33.579:INFO::main: Logging initialized @262ms to org.eclipse.jetty.util.log.StdErrLog
2020-04-21 16:54:33.642:INFO:oeju.TypeUtil:main: JVM Runtime does not support Modules
2020-04-21 16:54:33.814:INFO:oejs.Server:main: jetty-9.4.24.v20191120; built: 2019-11-20T21:37:49.771Z; git: 363d5f2df3a8a28de40604320230664b9c793c16; jvm 1.8.0_242-b08
2020-04-21 16:54:33.827:INFO:oejdp.ScanningAppProvider:main: Deployment monitor [file:///Users/karl/git/sumo/sumologic/ops/assemblies/latest/api-20.1-SNAPSHOT-bin/api-20.1-SNAPSHOT/webapps/] at interval 0
[GC (Allocation Failure)  65536K->9852K(251392K), 0.0059353 secs]
[GC (Allocation Failure)  75388K->7159K(251392K), 0.0042738 secs]
[GC (Allocation Failure)  72695K->12059K(251392K), 0.0054625 secs]
[GC (Allocation Failure)  77595K->11617K(251392K), 0.0036396 secs]
2020-04-21 16:54:34.988:INFO:oejs.session:main: DefaultSessionIdManager workerName=node0
2020-04-21 16:54:34.989:INFO:oejs.session:main: No SessionScavenger set, using defaults
2020-04-21 16:54:34.989:INFO:oejs.session:main: node0 Scavenging every 600000ms
[GC (Allocation Failure)  77153K->11438K(250880K), 0.0030967 secs]
[GC (Allocation Failure)  76974K->11804K(247808K), 0.0032155 secs]
[GC (Allocation Failure)  73244K->11704K(241152K), 0.0047344 secs]
[GC (Allocation Failure)  73144K->11942K(247296K), 0.0018144 secs]
[GC (Metadata GC Threshold)  36254K->11861K(235008K), 0.0010967 secs]
[Full GC (Metadata GC Threshold)  11861K->10072K(235008K), 0.0357302 secs]
[GC (Allocation Failure)  68440K->11552K(246784K), 0.0011433 secs]
[GC (Allocation Failure)  67872K->12096K(246784K), 0.0015453 secs]
2020-04-21 16:54:36,107 -0700 WARN  [module=API] [localUserName=karl] [logger=com.netflix.config.sources.URLConfigurationSource] [thread=main] No URLs will be polled as dynamic configuration sources.
2020-04-21 16:54:36,154 -0700 INFO  [module=API] [localUserName=karl] [logger=com.netflix.config.sources.URLConfigurationSource] [thread=main] To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.
2020-04-21 16:54:36,171 -0700 INFO  [module=API] [localUserName=karl] [logger=com.netflix.config.DynamicPropertyFactory] [thread=main] DynamicPropertyFactory is initialized with configuration sources: com.netflix.config.ConcurrentCompositeConfiguration@55f45b92
[GC (Allocation Failure)  68416K->12604K(246784K), 0.0010880 secs]
2020-04-21 16:54:36,188 -0700 INFO  [module=API] [localUserName=karl] [logger=assembly.app.AssemblyBootstrap$] [thread=main] Configured Hystrix event notifier.
2020-04-21 16:54:36,219 -0700 INFO  [module=API] [localUserName=karl] [logger=util.scala.configuration.AssemblyBootstrapConfigurationFactory] [thread=main] Loaded configuration file: /Users/karl/.sumo-props/api.properties
2020-04-21 16:54:36,228 -0700 INFO  [module=API] [localUserName=karl] [logger=util.scala.configuration.dynamic.DynamoDBDynamicPropertyInitialization] [thread=main] Install finalConfig
2020-04-21 16:54:36,307 -0700 WARN  [module=API] [localUserName=karl] [logger=com.amazonaws.auth.profile.internal.BasicProfileConfigLoader] [thread=main] Your profile name includes a 'profile ' prefix. This is considered part of the profile name in the Java SDK, so you will need to include this prefix in your profile name when you reference this profile from your Java code.
2020-04-21 16:54:36,307 -0700 WARN  [module=API] [localUserName=karl] [logger=com.amazonaws.auth.profile.internal.BasicProfileConfigLoader] [thread=main] Your profile name includes a 'profile ' prefix. This is considered part of the profile name in the Java SDK, so you will need to include this prefix in your profile name when you reference this profile from your Java code.
2020-04-21 16:54:36,307 -0700 WARN  [module=API] [localUserName=karl] [logger=com.amazonaws.auth.profile.internal.BasicProfileConfigLoader] [thread=main] Your profile name includes a 'profile ' prefix. This is considered part of the profile name in the Java SDK, so you will need to include this prefix in your profile name when you reference this profile from your Java code.
[GC (Allocation Failure)  68924K->13034K(246784K), 0.0013343 secs]
[GC (Allocation Failure)  69354K->13804K(247808K), 0.0015797 secs]
2020-04-21 16:54:36,559 -0700 WARN  [module=API] [localUserName=karl] [logger=com.amazonaws.auth.profile.internal.BasicProfileConfigLoader] [thread=main] Your profile name includes a 'profile ' prefix. This is considered part of the profile name in the Java SDK, so you will need to include this prefix in your profile name when you reference this profile from your Java code.
2020-04-21 16:54:36,559 -0700 WARN  [module=API] [localUserName=karl] [logger=com.amazonaws.auth.profile.internal.BasicProfileConfigLoader] [thread=main] Your profile name includes a 'profile ' prefix. This is considered part of the profile name in the Java SDK, so you will need to include this prefix in your profile name when you reference this profile from your Java code.
2020-04-21 16:54:36,560 -0700 WARN  [module=API] [localUserName=karl] [logger=com.amazonaws.auth.profile.internal.BasicProfileConfigLoader] [thread=main] Your profile name includes a 'profile ' prefix. This is considered part of the profile name in the Java SDK, so you will need to include this prefix in your profile name when you reference this profile from your Java code.
[GC (Allocation Failure)  71660K->13220K(247296K), 0.0013511 secs]
2020-04-21 16:54:36,748 -0700 WARN  [module=API] [localUserName=karl] [logger=com.amazonaws.auth.profile.internal.BasicProfileConfigLoader] [thread=main] Your profile name includes a 'profile ' prefix. This is considered part of the profile name in the Java SDK, so you will need to include this prefix in your profile name when you reference this profile from your Java code.
2020-04-21 16:54:36,748 -0700 WARN  [module=API] [localUserName=karl] [logger=com.amazonaws.auth.profile.internal.BasicProfileConfigLoader] [thread=main] Your profile name includes a 'profile ' prefix. This is considered part of the profile name in the Java SDK, so you will need to include this prefix in your profile name when you reference this profile from your Java code.
2020-04-21 16:54:36,748 -0700 WARN  [module=API] [localUserName=karl] [logger=com.amazonaws.auth.profile.internal.BasicProfileConfigLoader] [thread=main] Your profile name includes a 'profile ' prefix. This is considered part of the profile name in the Java SDK, so you will need to include this prefix in your profile name when you reference this profile from your Java code.
[GC (Allocation Failure)  71076K->15408K(248832K), 0.0019426 secs]
[GC (Allocation Failure)  74800K->16269K(247808K), 0.0023844 secs]
[GC (Metadata GC Threshold)  18635K->14914K(249856K), 0.0020600 secs]
[Full GC (Metadata GC Threshold)  14914K->14127K(249856K), 0.0260453 secs]
2020-04-21 16:54:37,510 -0700 INFO  [module=API] [localUserName=karl] [logger=util.scala.configuration.dynamic.DynamoDBDynamicPropertyInitialization] [thread=main] Added knobs configuration from local-knobs/knobs.properties
2020-04-21 16:54:37,515 -0700 INFO  [module=API] [localUserName=karl] [logger=util.scala.configuration.dynamic.DynamoDBDynamicPropertyInitialization] [thread=main] Loading dynamic properties from dynamo: table=karl-karl-macProperties, keyName=propertyName, valueName=propertyValue
2020-04-21 16:54:37,515 -0700 INFO  [module=API] [localUserName=karl] [logger=util.scala.configuration.dynamic.DynamoDBDynamicPropertyInitialization] [thread=main] Using DynamoDB region: us-east-1
2020-04-21 16:54:37,527 -0700 WARN  [module=API] [localUserName=karl] [logger=com.amazonaws.auth.profile.internal.BasicProfileConfigLoader] [thread=main] Your profile name includes a 'profile ' prefix. This is considered part of the profile name in the Java SDK, so you will need to include this prefix in your profile name when you reference this profile from your Java code.
2020-04-21 16:54:37,527 -0700 WARN  [module=API] [localUserName=karl] [logger=com.amazonaws.auth.profile.internal.BasicProfileConfigLoader] [thread=main] Your profile name includes a 'profile ' prefix. This is considered part of the profile name in the Java SDK, so you will need to include this prefix in your profile name when you reference this profile from your Java code.
2020-04-21 16:54:37,527 -0700 WARN  [module=API] [localUserName=karl] [logger=com.amazonaws.auth.profile.internal.BasicProfileConfigLoader] [thread=main] Your profile name includes a 'profile ' prefix. This is considered part of the profile name in the Java SDK, so you will need to include this prefix in your profile name when you reference this profile from your Java code.
2020-04-21 16:54:37,567 -0700 INFO  [module=API] [localUserName=karl] [logger=util.aws.dynamodb.DynamoDBTable] [thread=main] Using DynamoDB region: us-east-1
2020-04-21 16:54:37,568 -0700 WARN  [module=API] [localUserName=karl] [logger=com.amazonaws.auth.profile.internal.BasicProfileConfigLoader] [thread=main] Your profile name includes a 'profile ' prefix. This is considered part of the profile name in the Java SDK, so you will need to include this prefix in your profile name when you reference this profile from your Java code.
2020-04-21 16:54:37,568 -0700 WARN  [module=API] [localUserName=karl] [logger=com.amazonaws.auth.profile.internal.BasicProfileConfigLoader] [thread=main] Your profile name includes a 'profile ' prefix. This is considered part of the profile name in the Java SDK, so you will need to include this prefix in your profile name when you reference this profile from your Java code.
2020-04-21 16:54:37,568 -0700 WARN  [module=API] [localUserName=karl] [logger=com.amazonaws.auth.profile.internal.BasicProfileConfigLoader] [thread=main] Your profile name includes a 'profile ' prefix. This is considered part of the profile name in the Java SDK, so you will need to include this prefix in your profile name when you reference this profile from your Java code.
[GC (Allocation Failure)  76079K->17709K(249344K), 0.0018342 secs]
2020-04-21 16:54:52,186 -0700 ERROR [module=API] [localUserName=karl] [logger=assembly.webapp.DoOrDieContextLoaderListener] [thread=main] Exception while loading context com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to localhost:18000 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1201)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1147)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:796)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:764)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:738)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:698)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:680)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:544)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:524)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.doInvoke(AmazonDynamoDBClient.java:5110)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:5077)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.executeDescribeTable(AmazonDynamoDBClient.java:1981)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.describeTable(AmazonDynamoDBClient.java:1947)
	at com.sumologic.util.aws.dynamodb.DynamoDBTable.findTable(DynamoDBTable.scala:220)
	at com.sumologic.util.aws.dynamodb.DynamoDBTable.ensureExists(DynamoDBTable.scala:66)
	at com.sumologic.util.scala.configuration.dynamic.DynamoDBDynamicPropertyInitialization.createDynamoDBSource(DynamoDBDynamicPropertyInitialization.scala:137)
	at com.sumologic.util.scala.configuration.dynamic.DynamoDBDynamicPropertyInitialization.configure(DynamoDBDynamicPropertyInitialization.scala:70)
	at com.sumologic.util.scala.configuration.dynamic.DynamoDBDynamicPropertyInitialization.<init>(DynamoDBDynamicPropertyInitialization.scala:34)
	at com.sumologic.util.app.CommonInitialization$.initializeDynamicProperties(CommonInitialization.scala:35)
	at com.sumologic.assembly.webapp.DoOrDieContextLoaderListener.beforeSpringInitialization(DoOrDieContextLoaderListener.scala:88)
	at com.sumologic.assembly.webapp.DoOrDieContextLoaderListener.$anonfun$contextInitialized$1(DoOrDieContextLoaderListener.scala:34)
	at com.sumologic.util.scala.time.MeasureTime$.apply(MeasureTime.scala:8)
	at com.sumologic.assembly.webapp.DoOrDieContextLoaderListener.contextInitialized(DoOrDieContextLoaderListener.scala:33)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:930)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:553)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:889)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:356)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1445)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1409)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:822)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:275)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:46)
	at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:188)
	at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:513)
	at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:154)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:173)
	at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:427)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:66)
	at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:784)
	at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:753)
	at org.eclipse.jetty.util.Scanner.scan(Scanner.java:641)
	at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:540)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:146)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:599)
	at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:249)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.server.Server.start(Server.java:407)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:100)
	at org.eclipse.jetty.server.Server.doStart(Server.java:371)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.xml.XmlConfiguration.lambda$main$0(XmlConfiguration.java:1888)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1837)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jetty.start.Main.invokeMain(Main.java:218)
	at org.eclipse.jetty.start.Main.start(Main.java:491)
	at org.eclipse.jetty.start.Main.main(Main.java:77)
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:18000 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76)
	at com.amazonaws.http.conn.$Proxy23.connect(Unknown Source)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1323)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1139)
	... 64 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	... 80 more

@arn:aws:eks:us-west-2:967376234080:cluster/dev|bash-3.2$ echo $EPHEMERAL_DEPLOYMENT
true
@arn:aws:eks:us-west-2:967376234080:cluster/dev|bash-3.2$
T: Background process (SSH port forward (exposed ports)) exited with return code 255. Command was:
T:   ssh -N -oServerAliveInterval=1 -oServerAliveCountMax=10 -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -vv -p 61089 telepresence@127.0.0.1 -R '*:23667:127.0.0.1:23667'

T: Recent output was:
T:   debug1: client_input_global_request: rtype keepalive@openssh.com want_reply 1
T:   debug1: client_input_global_request: rtype keepalive@openssh.com want_reply 1
T:   debug1: client_input_global_request: rtype keepalive@openssh.com want_reply 1
T:   debug1: client_input_global_request: rtype keepalive@openssh.com want_reply 1
T:   debug1: client_input_global_request: rtype keepalive@openssh.com want_reply 1
T:   debug1: client_input_global_request: rtype keepalive@openssh.com want_reply 1
T:   debug1: client_input_global_request: rtype keepalive@openssh.com want_reply 1
T:   debug1: client_input_global_request: rtype keepalive@openssh.com want_reply 1
T:   debug1: client_input_global_request: rtype keepalive@openssh.com want_reply 1
T:   Timeout, server 127.0.0.1 not responding.


T: Proxy to Kubernetes exited. This is typically due to a lost connection.

T: Exit cleanup in progress
T: Cleaning up Deployment telepresence
```

**Comment by karlschu13** [comment]
Initial bug was erroneous as I was logged into Pritunl.  Once I logged out of that, I was able to start `telepresence`, but then launching the assembly locally failed with the new traceback pasted above.

**Comment by marun** [comment]
@karlschu13 The above traceback seems to indicate a connectivity issue. Does telepresence work for you with a bare invocation (i.e. can you get a local shell that has connectivity to the cluster by running `telepresence`)?
