### ISSUE TITLE
List index out of range while opening telepresence shell

### ISSUE THREAD

**Issue by arcana261** [telepresenceio/telepresence#1339]
### What were you trying to do?

I was trying to run a shell by invoking
```
telepresence -n <MY NAMESPACE> --method inject-tcp --run-shell
```

### What did you expect to happen?

Telepresence shell

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/bin/telepresence', '-n', 'divar-infra', '--method', 'inject-tcp', '--run-shell']`
Version: `0.104`
Python version: `3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0]`
kubectl version: `Client Version: v1.18.2 // Server Version: v1.14.8`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux arcana-ubuntu 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 65, in main
    remote_info = start_proxy(runner)
  File "/usr/bin/telepresence/telepresence/proxy/__init__.py", line 138, in start_proxy
    run_id=run_id,
  File "/usr/bin/telepresence/telepresence/proxy/remote.py", line 144, in get_remote_info
    runner, deployment_name, deployment_type, run_id=run_id
  File "/usr/bin/telepresence/telepresence/proxy/remote.py", line 91, in get_deployment_json
    return json.loads(output)["items"][0]
IndexError: list index out of range

```

Logs:

```
] Running: kubectl --context afra --namespace divar-infra delete --ignore-not-found svc,deploy --selector=telepresence=30b8844f037641ec8279d71152d165c4
   8.6   8 | No resources found
   8.6 TEL | [8] ran in 0.36 secs.
   8.6 TEL | [9] Running: kubectl --context afra --namespace divar-infra run --restart=Always --limits=cpu=1000m,memory=256Mi --requests=cpu=25m,memory=64Mi divar-infra --image=datawire/telepresence-k8s:0.104 --labels=telepresence=30b8844f037641ec8279d71152d165c4
  10.4   9 | pod/divar-infra created
  10.4 TEL | [9] ran in 1.80 secs.
  10.4 TEL | END SPAN deployment.py:108(create_new_deployment)    2.2s
  10.4 TEL | BEGIN SPAN remote.py:142(get_remote_info)
  10.4 TEL | BEGIN SPAN remote.py:75(get_deployment_json)
  10.4 TEL | [10] Capturing: kubectl --context afra --namespace divar-infra get deployment -o json --selector=telepresence=30b8844f037641ec8279d71152d165c4
  10.6 TEL | [10] captured in 0.27 secs.
  10.6 TEL | END SPAN remote.py:75(get_deployment_json)    0.3s

```

**Comment by arcana261** [comment]
Sorry.. seems a duplicate of #1297
