### ISSUE TITLE
How to downgrade telepresence to version 0.104- homebrew installed 0.105 version

### ISSUE THREAD

**Issue by lammh** [telepresenceio/telepresence#1346]
### What were you trying to do?

(please tell us)

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['./telepresence']`
Version: `0.104`
Python version: `3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0]`
kubectl version: `Client Version: v1.18.2 // Server Version: v1.15.2`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux kyalis-meher 5.3.0-51-generic #44~18.04.2-Ubuntu SMP Thu Apr 23 14:27:18 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

```
Traceback (most recent call last):
  File "./telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "./telepresence/telepresence/main.py", line 65, in main
    remote_info = start_proxy(runner)
  File "./telepresence/telepresence/proxy/__init__.py", line 138, in start_proxy
    run_id=run_id,
  File "./telepresence/telepresence/proxy/remote.py", line 144, in get_remote_info
    runner, deployment_name, deployment_type, run_id=run_id
  File "./telepresence/telepresence/proxy/remote.py", line 91, in get_deployment_json
    return json.loads(output)["items"][0]
IndexError: list index out of range

```

Logs:

```
loy --selector=telepresence=1b887961afba47e09a9f8c74ce6e7e09
   5.0  11 | No resources found
   5.0 TEL | [11] ran in 0.10 secs.
   5.0 TEL | [12] Running: kubectl --context minikube --namespace default run --restart=Always --limits=cpu=1000m,memory=256Mi --requests=cpu=25m,memory=64Mi telepresence-1588926599-873697-24617 --image=datawire/telepresence-k8s:0.104 --labels=telepresence=1b887961afba47e09a9f8c74ce6e7e09 --env=TELEPRESENCE_NAMESERVER=8.8.8.8
   5.1  12 | pod/telepresence-1588926599-873697-24617 created
   5.2 TEL | [12] ran in 0.11 secs.
   5.2 TEL | END SPAN deployment.py:108(create_new_deployment)    0.2s
   5.2 TEL | BEGIN SPAN remote.py:142(get_remote_info)
   5.2 TEL | BEGIN SPAN remote.py:75(get_deployment_json)
   5.2 TEL | [13] Capturing: kubectl --context minikube --namespace default get deployment -o json --selector=telepresence=1b887961afba47e09a9f8c74ce6e7e09
   5.3 TEL | [13] captured in 0.11 secs.
   5.3 TEL | END SPAN remote.py:75(get_deployment_json)    0.1s

```

**Comment by bszeti** [comment]
I didn't find a way to install v0.104 with brew, but installing from source was quick:
```
$ curl -L -o telepresence-0.104.tar.gz https://github.com/telepresenceio/telepresence/archive/0.104.tar.gz
$ tar -xzf telepresence-0.104.tar.gz
$ cd telepresence-0.104
$ sudo env PREFIX=/Users/myuser/tools/telepresence-v104 ./install.sh
$ /Users/myuser/tools/telepresence-v104/bin/telepresence --version
v0.104
```
For default location just use PREFIX=/usr/local

**Comment by lammh** [comment]
it's work thanks
