### ISSUE TITLE
telepresence crashed

### ISSUE THREAD

**Issue by tvvsatish** [telepresenceio/telepresence#1347]
### What were you trying to do?

(please tell us)

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--also-proxy', '10.250.0.0/16', '--deployment', 'telepresence-perm']`
Version: `0.104`
Python version: `3.7.7 (default, Mar 10 2020, 15:43:03) 
[Clang 11.0.0 (clang-1100.0.33.17)]`
kubectl version: `Client Version: v1.14.6 // Server Version: v1.14.9-eks-f459c0`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin CAP-LAP-991.local 18.7.0 Darwin Kernel Version 18.7.0: Mon Feb 10 21:08:45 PST 2020; root:xnu-4903.278.28~1/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 65, in main
    remote_info = start_proxy(runner)
  File "/usr/local/bin/telepresence/telepresence/proxy/__init__.py", line 138, in start_proxy
    run_id=run_id,
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 158, in get_remote_info
    pods = json.loads(runner.get_output(runner.kubectl(*cmd)))["items"]
  File "/usr/local/bin/telepresence/telepresence/runner/runner.py", line 483, in get_output
    env,
  File "/usr/local/bin/telepresence/telepresence/runner/runner.py", line 437, in _run_command_sync
    None if stderr_to_stdout else err_logger.get_captured(),
subprocess.CalledProcessError: Command '['kubectl', '--context', 'default-context', '--namespace', 'default', 'get', 'pod', '-o', 'json']' returned non-zero exit status 1.

```

Logs:

```
g: kubectl --context default-context --namespace default get deployment -o json telepresence-perm
  33.2 TEL | [11] captured in 1.62 secs.
  33.2 TEL | END SPAN remote.py:75(get_deployment_json)    1.6s
  33.2 TEL | Searching for Telepresence pod:
  33.2 TEL |   with name telepresence-perm-*
  33.2 TEL |   with labels {'telepresence': '8af560b8414c4803bc0fd0c1193139fb'}
  33.2 TEL | [12] Capturing: kubectl --context default-context --namespace default get pod -o json
  57.0 TEL | [13] Running: sudo -n echo -n
  57.1 TEL | [13] ran in 0.03 secs.
  87.2 TEL | [14] Running: sudo -n echo -n
  87.2 TEL | [14] ran in 0.03 secs.
 117.3 TEL | [15] Running: sudo -n echo -n
 117.3 TEL | [15] ran in 0.03 secs.
 147.4 TEL | [16] Running: sudo -n echo -n
 147.4 TEL | [16] ran in 0.03 secs.
 175.4  12 | error: Stream error http2.StreamError{StreamID:0x1, Code:0x2, Cause:error(nil)} when reading response body, may be caused by closed connection. Please retry.
 175.4 TEL | [12] exit 1 in 142.21 secs.

```

**Comment by marun** [comment]
@ark3 This appears to be a temporal error, and not actionable. Can it be closed?
