### ISSUE TITLE
 File "/usr/local/bin/telepresence/telepresence/cli.py", line 129, in crash_reporting     yield

### ISSUE THREAD

**Issue by zrqgood** [telepresenceio/telepresence#1348]
### What were you trying to do?

(please tell us)

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--namespace', 'team-s1']`
Version: `0.93`
Python version: `3.7.0 (default, Aug 22 2018, 15:22:33) 
[Clang 9.1.0 (clang-902.0.39.2)]`
kubectl version: `Client Version: v1.11.2 // Server Version: v1.15.7`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin zrqgooddeMacBook-Pro.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 129, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 61, in main
    remote_info = start_proxy(runner)
  File "/usr/local/bin/telepresence/telepresence/proxy/__init__.py", line 90, in start_proxy
    run_id=run_id,
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 200, in get_remote_info
    wait_for_pod(runner, remote_info)
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 132, in wait_for_pod
    "Pod isn't starting or can't be found: {}".format(pod["status"])
RuntimeError: Pod isn't starting or can't be found: {'conditions': [{'lastProbeTime': None, 'lastTransitionTime': '2020-05-11T12:09:06Z', 'status': 'True', 'type': 'Initialized'}, {'lastProbeTime': None, 'lastTransitionTime': '2020-05-11T12:09:06Z', 'message': 'containers with unready status: [telepresence-1589198939-502995-5936]', 'reason': 'ContainersNotReady', 'status': 'False', 'type': 'Ready'}, {'lastProbeTime': None, 'lastTransitionTime': '2020-05-11T12:09:06Z', 'message': 'containers with unready status: [telepresence-1589198939-502995-5936]', 'reason': 'ContainersNotReady', 'status': 'False', 'type': 'ContainersReady'}, {'lastProbeTime': None, 'lastTransitionTime': '2020-05-11T12:09:06Z', 'status': 'True', 'type': 'PodScheduled'}], 'containerStatuses': [{'image': 'datawire/telepresence-k8s:0.93', 'imageID': '', 'lastState': {}, 'name': 'telepresence-1589198939-502995-5936', 'ready': False, 'restartCount': 0, 'state': {'waiting': {'reason': 'ContainerCreating'}}}], 'hostIP': '10.240.0.4', 'phase': 'Pending', 'qosClass': 'Burstable', 'startTime': '2020-05-11T12:09:06Z'}

```

Logs:

```
24.6 TEL | [314] Capturing: kubectl --context ekb-dev-qhose --namespace team-s1 get pod telepresence-1589198939-502995-5936-dc7f894b4-6q9xk -o json
 124.8 TEL | [315] Running: sudo -n echo -n
 125.0 TEL | [316] Capturing: kubectl --context ekb-dev-qhose --namespace team-s1 get pod telepresence-1589198939-502995-5936-dc7f894b4-6q9xk -o json
 125.4 TEL | [317] Capturing: kubectl --context ekb-dev-qhose --namespace team-s1 get pod telepresence-1589198939-502995-5936-dc7f894b4-6q9xk -o json
 125.8 TEL | [318] Capturing: kubectl --context ekb-dev-qhose --namespace team-s1 get pod telepresence-1589198939-502995-5936-dc7f894b4-6q9xk -o json
 126.2 TEL | [319] Capturing: kubectl --context ekb-dev-qhose --namespace team-s1 get pod telepresence-1589198939-502995-5936-dc7f894b4-6q9xk -o json
 126.6 TEL | [320] Capturing: kubectl --context ekb-dev-qhose --namespace team-s1 get pod telepresence-1589198939-502995-5936-dc7f894b4-6q9xk -o json
 126.7 TEL | END SPAN remote.py:111(wait_for_pod)  119.9s

```

**Comment by machine424** [comment]
Telepresence raised an exception because it timed out (after 120s) waiting for the proxy pod to get ready, I see  at the end of the last line of the traceback, that `'imageID'` is empty, maybe that pulling the image `datawire/telepresence-k8s:0.93` takes more than 120s.
you can run `kubectl describe pod POD_NAME -n NAMESPACE` to get more details.
I will see if we can add the output of this command in the logs before raising.
