### ISSUE TITLE
error

### ISSUE THREAD

**Issue by withqingshao** [telepresenceio/telepresence#1353]
### What were you trying to do?

(please tell us)

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--new-deployment', 'test', '--expose', '8085']`
Version: `0.104`
Python version: `3.7.7 (default, Mar 10 2020, 15:43:33) 
[Clang 11.0.0 (clang-1100.0.33.17)]`
kubectl version: `Client Version: v1.18.0 // Server Version: v1.18.2-41+b5cdb79a4060a3`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin P_SQQZHANG-MB0 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 65, in main
    remote_info = start_proxy(runner)
  File "/usr/local/bin/telepresence/telepresence/proxy/__init__.py", line 138, in start_proxy
    run_id=run_id,
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 144, in get_remote_info
    runner, deployment_name, deployment_type, run_id=run_id
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 91, in get_deployment_json
    return json.loads(output)["items"][0]
IndexError: list index out of range

```

Logs:

```
space default delete --ignore-not-found svc,deploy --selector=telepresence=5670272e99b941b0885953f58a57f303
   6.6  10 | No resources found
   6.6 TEL | [10] ran in 0.24 secs.
   6.6 TEL | [11] Running: kubectl --context sharek8s --namespace default run --restart=Always --limits=cpu=1000m,memory=256Mi --requests=cpu=25m,memory=64Mi test --image=datawire/telepresence-k8s:0.104 --labels=telepresence=5670272e99b941b0885953f58a57f303 --port=8085 --expose
   6.9  11 | service/test created
   6.9  11 | pod/test created
   6.9 TEL | [11] ran in 0.28 secs.
   6.9 TEL | END SPAN deployment.py:108(create_new_deployment)    0.5s
   6.9 TEL | BEGIN SPAN remote.py:142(get_remote_info)
   6.9 TEL | BEGIN SPAN remote.py:75(get_deployment_json)
   6.9 TEL | [12] Capturing: kubectl --context sharek8s --namespace default get deployment -o json --selector=telepresence=5670272e99b941b0885953f58a57f303
   7.1 TEL | [12] captured in 0.19 secs.
   7.1 TEL | END SPAN remote.py:75(get_deployment_json)    0.2s

```

**Comment by dhruvrnaik** [comment]
Facing the same issue today.

**Comment by marun** [comment]
@dhruvrnaik @withqingshao The reported issue represents a compatibility problem between telepresence 0.104 and kube >= 1.18 (see #1297). Please update to 0.105.
