### ISSUE TITLE
'Unable to parse version' running telepresence when installed from source

### ISSUE THREAD

**Issue by MFAshby** [telepresenceio/telepresence#1387]
### What were you trying to do?

Run telepresence when installed from source as per documentation:  https://www.telepresence.io/reference/install#install-from-source

### What did you expect to happen?

telepresence executes successfully and starts shell in cluster

### What happened instead?

Error with backtrace 'Unable to parse version'.

### Automatically included information

Command line: `['/usr/local/bin/telepresence']`
Version: `ed4f9ad`
Python version: `3.8.3 (default, May 14 2020, 11:03:12) 
[GCC 9.3.0]`
kubectl version: `Client Version: v1.18.3 // Server Version: v1.18.3+k3s1`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Linux martin-pinebook 5.5.0-1-pinebookpro-arm64 #1 SMP PREEMPT Wed Jun 10 05:23:29 UTC 2020 aarch64 GNU/Linux`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 58, in main
    call_scout(runner, args)
  File "/usr/local/bin/telepresence/telepresence/usage_tracking.py", line 154, in call_scout
    my_version = get_numeric_version(__version__)
  File "/usr/local/bin/telepresence/telepresence/usage_tracking.py", line 123, in get_numeric_version
    raise ValueError("Unable to parse version: {}".format(version_str))
ValueError: Unable to parse version: ed4f9ad

```

Logs:

```
/sudo
   2.0 TEL | [7] Running: sudo -n echo -n
   2.1 TEL | [7] ran in 0.12 secs.
   2.1 TEL | [8] Capturing: sudo iptables --list
   2.2 TEL | [8] captured in 0.14 secs.
   2.2 >>> | Starting proxy with method 'vpn-tcp', which has the following limitations: All processes are affected, only one telepresence can run per machine, and you can't use other VPNs. You may need to add cloud hosts and headless services with --also-proxy. For a full list of method limitations see https://telepresence.io/reference/methods.html
   2.2 TEL | Found sshfs -> /usr/bin/sshfs
   2.2 TEL | Found fusermount -> /usr/bin/fusermount
   2.2 >>> | Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.
   2.2 TEL | [9] Running: kubectl --context default --namespace default get pods telepresence-connectivity-check --ignore-not-found
   2.6 TEL | [9] ran in 0.39 secs.
   3.2 TEL | Scout info: {'latest_version': '0.105', 'application': 'telepresence', 'notices': []}

```

**Comment by MFAshby** [comment]
You can work around this by commenting this line https://github.com/telepresenceio/telepresence/blob/ed4f9ad54a765bf3019c4517676052dad9c9be7d/telepresence/main.py#L58

The correct fix would be to handle a git commit hash given as version string, probably.
