### ISSUE TITLE
Telepresence installed from source can't deploy pod in cluster

### ISSUE THREAD

**Issue by MFAshby** [telepresenceio/telepresence#1388]
### What were you trying to do?

Install and run telepresence  from source

### What did you expect to happen?

telepresence shell starts

### What happened instead?

Attached error with backtrace. The deployment fails because it's trying to deploy a container image which doesn't exist: 
```
martin@martin-pinebook:~$ kubectl describe pod/telepresence-1592341327-6694174-5262-dbb8f57ff-mzzht
Name:         telepresence-1592341327-6694174-5262-dbb8f57ff-mzzht
Namespace:    default
Priority:     0
Node:         martin-intel-z370/192.168.1.107
Start Time:   Tue, 16 Jun 2020 22:02:11 +0100
Labels:       pod-template-hash=dbb8f57ff
              telepresence=9ea7a0ce983f487b9690b2d642373087
Annotations:  <none>
Status:       Pending
IP:           10.42.0.223
IPs:
  IP:           10.42.0.223
Controlled By:  ReplicaSet/telepresence-1592341327-6694174-5262-dbb8f57ff
Containers:
  telepresence-1592341327-6694174-5262:
    Container ID:   
    Image:          datawire/telepresence-k8s:ed4f9ad
    Image ID:       
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     1
      memory:  256Mi
    Requests:
      cpu:     25m
      memory:  64Mi
    Environment:
      TELEPRESENCE_NAMESERVER:  8.8.8.8
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-pcqtq (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  default-token-pcqtq:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-pcqtq
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                  From                        Message
  ----     ------     ----                 ----                        -------
  Normal   Scheduled  <unknown>            default-scheduler           Successfully assigned default/telepresence-1592341327-6694174-5262-dbb8f57ff-mzzht to martin-intel-z370
  Normal   Pulling    44s (x4 over 2m19s)  kubelet, martin-intel-z370  Pulling image "datawire/telepresence-k8s:ed4f9ad"
  Warning  Failed     42s (x4 over 2m17s)  kubelet, martin-intel-z370  Failed to pull image "datawire/telepresence-k8s:ed4f9ad": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/datawire/telepresence-k8s:ed4f9ad": failed to resolve reference "docker.io/datawire/telepresence-k8s:ed4f9ad": docker.io/datawire/telepresence-k8s:ed4f9ad: not found
  Warning  Failed     42s (x4 over 2m17s)  kubelet, martin-intel-z370  Error: ErrImagePull
  Normal   BackOff    28s (x6 over 2m17s)  kubelet, martin-intel-z370  Back-off pulling image "datawire/telepresence-k8s:ed4f9ad"
  Warning  Failed     16s (x7 over 2m17s)  kubelet, martin-intel-z370  Error: ImagePullBackOff
```

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence']`
Version: `ed4f9ad-dirty`
Python version: `3.8.3 (default, May 14 2020, 11:03:12) 
[GCC 9.3.0]`
kubectl version: `Client Version: v1.18.3 // Server Version: v1.18.3+k3s1`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Linux martin-pinebook 5.5.0-1-pinebookpro-arm64 #1 SMP PREEMPT Wed Jun 10 05:23:29 UTC 2020 aarch64 GNU/Linux`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 66, in main
    remote_info = start_proxy(runner)
  File "/usr/local/bin/telepresence/telepresence/proxy/__init__.py", line 130, in start_proxy
    remote_info = get_remote_info(
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 193, in get_remote_info
    wait_for_pod(runner, remote_info)
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 124, in wait_for_pod
    raise RuntimeError(
RuntimeError: Pod isn't starting or can't be found: {'conditions': [{'lastProbeTime': None, 'lastTransitionTime': '2020-06-16T21:02:11Z', 'status': 'True', 'type': 'Initialized'}, {'lastProbeTime': None, 'lastTransitionTime': '2020-06-16T21:02:11Z', 'message': 'containers with unready status: [telepresence-1592341327-6694174-5262]', 'reason': 'ContainersNotReady', 'status': 'False', 'type': 'Ready'}, {'lastProbeTime': None, 'lastTransitionTime': '2020-06-16T21:02:11Z', 'message': 'containers with unready status: [telepresence-1592341327-6694174-5262]', 'reason': 'ContainersNotReady', 'status': 'False', 'type': 'ContainersReady'}, {'lastProbeTime': None, 'lastTransitionTime': '2020-06-16T21:02:11Z', 'status': 'True', 'type': 'PodScheduled'}], 'containerStatuses': [{'image': 'datawire/telepresence-k8s:ed4f9ad', 'imageID': '', 'lastState': {}, 'name': 'telepresence-1592341327-6694174-5262', 'ready': False, 'restartCount': 0, 'started': False, 'state': {'waiting': {'message': 'rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/datawire/telepresence-k8s:ed4f9ad": failed to resolve reference "docker.io/datawire/telepresence-k8s:ed4f9ad": docker.io/datawire/telepresence-k8s:ed4f9ad: not found', 'reason': 'ErrImagePull'}}}], 'hostIP': '192.168.1.107', 'phase': 'Pending', 'podIP': '10.42.0.223', 'podIPs': [{'ip': '10.42.0.223'}], 'qosClass': 'Burstable', 'startTime': '2020-06-16T21:02:11Z'}

```

Logs:

```
t get pod telepresence-1592341327-6694174-5262-dbb8f57ff-mzzht -o json
 122.2 TEL | [199] captured in 0.38 secs.
 122.4 TEL | [200] Capturing: kubectl --context default --namespace default get pod telepresence-1592341327-6694174-5262-dbb8f57ff-mzzht -o json
 122.7 TEL | [201] Running: sudo -n echo -n
 122.8 TEL | [201] ran in 0.10 secs.
 122.9 TEL | [200] captured in 0.44 secs.
 123.1 TEL | [202] Capturing: kubectl --context default --namespace default get pod telepresence-1592341327-6694174-5262-dbb8f57ff-mzzht -o json
 123.5 TEL | [202] captured in 0.36 secs.
 123.7 TEL | [203] Capturing: kubectl --context default --namespace default get pod telepresence-1592341327-6694174-5262-dbb8f57ff-mzzht -o json
 124.1 TEL | [203] captured in 0.38 secs.
 124.4 TEL | [204] Capturing: kubectl --context default --namespace default get pod telepresence-1592341327-6694174-5262-dbb8f57ff-mzzht -o json
 124.7 TEL | [204] captured in 0.36 secs.
 124.8 TEL | END SPAN remote.py:104(wait_for_pod)  120.0s

```

**Comment by MFAshby** [comment]
You can work around it by configuring the version of telepresence to be deployed in an environment variable: 
```
TELEPRESENCE_VERSION=0.105 telepresence
```
works as expected.
