### ISSUE TITLE
Strange behavior

### ISSUE THREAD

**Issue by gep** [telepresenceio/telepresence#1403]
### What were you trying to do?

(please tell us)

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--swap-deployment', 'backend', '--docker-run', '-it', '--user', 'app', '--rm', '--env-file', './.env.local', '-e', ]`
Version: `0.105`
Python version: `3.8.2 (default, Mar 11 2020, 00:29:50) 
[Clang 11.0.0 (clang-1100.0.33.17)]`
kubectl version: `Client Version: v1.18.2 // Server Version: v1.16.8-eks-e16311`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Darwin Andrey-Semikov.local 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 65, in main
    remote_info = start_proxy(runner)
  File "/usr/local/bin/telepresence/telepresence/proxy/__init__.py", line 130, in start_proxy
    remote_info = get_remote_info(
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 193, in get_remote_info
    wait_for_pod(runner, remote_info)
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 124, in wait_for_pod
    raise RuntimeError(
RuntimeError: Pod isn't starting or can't be found: {'conditions': [{'lastProbeTime': None, 'lastTransitionTime': '2020-07-17T12:52:49Z', 'status': 'True', 'type': 'Initialized'}, {'lastProbeTime': None, 'lastTransitionTime': '2020-07-17T12:52:49Z', 'message': 'containers with unready status: [c]', 'reason': 'ContainersNotReady', 'status': 'False', 'type': 'Ready'}, {'lastProbeTime': None, 'lastTransitionTime': '2020-07-17T12:52:49Z', 'message': 'containers with unready status: [c]', 'reason': 'ContainersNotReady', 'status': 'False', 'type': 'ContainersReady'}, {'lastProbeTime': None, 'lastTransitionTime': '2020-07-17T12:52:49Z', 'status': 'True', 'type': 'PodScheduled'}], 'containerStatuses': [{'containerID': 'docker://c5f007acbde36923bf770427b8851ff1b00623be26bd97c52975bda1a23c1de6', 'image': 'datawire/telepresence-k8s:0.105', 'imageID': 'docker-pullable://datawire/telepresence-k8s@sha256:10a54af912ee904c3ee3f8a44d9b2991db8a1744cb75810e54ba08de1e93aba7', 'lastState': {'terminated': {'containerID': 'docker://c5f007acbde36923bf770427b8851ff1b00623be26bd97c52975bda1a23c1de6', 'exitCode': 1, 'finishedAt': '2020-07-17T12:54:18Z', 'message': 'Could not load host key: /etc/ssh/ssh_host_rsa_key\r\nCould not load host key: /etc/ssh/ssh_host_dsa_key\r\nCould not load host key: /etc/ssh/ssh_host_ecdsa_key\r\nCould not load host key: /etc/ssh/ssh_host_ed25519_key\r\nsshd: no hostkeys available -- exiting.\r\n', 'reason': 'Error', 'startedAt': '2020-07-17T12:54:18Z'}}, 'name': 'c', 'ready': False, 'restartCount': 4, 'started': False, 'state': {'waiting': {'message': 'back-off 1m20s restarting failed container=c pod=backend-d45201529e454d24a306b5475cf96407-67cb4f5d47-lg82x_andrey-semikov(6d4788d8-c263-4fe8-bc98-030560c4d20e)', 'reason': 'CrashLoopBackOff'}}}], 'hostIP': '10.150.11.191', 'phase': 'Running', 'podIP': '10.150.11.164', 'podIPs': [{'ip': '10.150.11.164'}], 'qosClass': 'BestEffort', 'startTime': '2020-07-17T12:52:49Z'}

```

Logs:

```
 | [131] Capturing: kubectl --context  get pod backend-d45201529e454d24a306b5475cf96407-67cb4f5d47-lg82x -o json
 130.4 TEL | [131] captured in 1.25 secs.
 130.7 TEL | [132] Capturing: kubectl --context :cluster/dev --namespace andrey-semikov get pod backend-d45201529e454d24

**Comment by ipleten** [comment]
I believe it's the same as #1413.

**Comment by gep** [comment]
I think so too
