### ISSUE TITLE
Cannot telepresence deployment

### ISSUE THREAD

**Issue by nmiculinic** [telepresenceio/telepresence#1406]
### What were you trying to do?

telepresence into the deployment

### What did you expect to happen?

success

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

well..it blew up. As can be seen from the logs. 

### Automatically included information

Command line: `['/usr/bin/telepresence', '--swap-deployment', 'certificates-svc-3-catapult-manager', '--namespace', 'provider-2', '--mount', '/tmp/sut-290105591/rootfs', '--env-json', '/tmp/sut-290105591/env.json', '--logfile', '/tmp/sut-290105591/telepresence.log', '--expose', '9443', '--expose', '9440', '--run', 'bash', '-c', 'while true; do sleep 3600; done']`
Version: `0.104`
Python version: `3.8.3 (default, May 17 2020, 18:15:42) 
[GCC 10.1.0]`
kubectl version: `Client Version: v1.18.3 // Server Version: v1.17.3`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Linux odyssey 5.4.44-1-MANJARO #1 SMP PREEMPT Wed Jun 3 14:48:07 UTC 2020 x86_64 GNU/Linux`

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 65, in main
    remote_info = start_proxy(runner)
  File "/usr/bin/telepresence/telepresence/proxy/__init__.py", line 134, in start_proxy
    remote_info = get_remote_info(
  File "/usr/bin/telepresence/telepresence/proxy/remote.py", line 193, in get_remote_info
    wait_for_pod(runner, remote_info)
  File "/usr/bin/telepresence/telepresence/proxy/remote.py", line 124, in wait_for_pod
    raise RuntimeError(
RuntimeError: Pod isn't starting or can't be found: {'conditions': [{'lastProbeTime': None, 'lastTransitionTime': '2020-07-22T13:12:17Z', 'status': 'True', 'type': 'Initialized'}, {'lastProbeTime': None, 'lastTransitionTime': '2020-07-22T13:12:17Z', 'message': 'containers with unready status: [manager]', 'reason': 'ContainersNotReady', 'status': 'False', 'type': 'Ready'}, {'lastProbeTime': None, 'lastTransitionTime': '2020-07-22T13:12:17Z', 'message': 'containers with unready status: [manager]', 'reason': 'ContainersNotReady', 'status': 'False', 'type': 'ContainersReady'}, {'lastProbeTime': None, 'lastTransitionTime': '2020-07-22T13:12:17Z', 'status': 'True', 'type': 'PodScheduled'}], 'containerStatuses': [{'image': 'datawire/telepresence-k8s:0.104', 'imageID': '', 'lastState': {}, 'name': 'manager', 'ready': False, 'restartCount': 0, 'started': False, 'state': {'terminated': {'exitCode': 0, 'finishedAt': None, 'startedAt': None}}}], 'hostIP': '172.31.40.182', 'phase': 'Pending', 'qosClass': 'Burstable', 'startTime': '2020-07-22T13:12:17Z'}

```

Logs:

```
-namespace provider-2 get pod certificates-svc--ae10dddc50da4595998694d52d3f9121-7976bd4rjhl8 -o json
 138.0 216 | Error from server (NotFound): pods "certificates-svc--ae10dddc50da4595998694d52d3f9121-7976bd4rjhl8" not found
 138.0 TEL | [216] exit 1 in 0.29 secs.
 138.2 TEL | [217] Capturing: kubectl --context kubecarrier-management --namespace provider-2 get pod certificates-svc--ae10dddc50da4595998694d52d3f9121-7976bd4rjhl8 -o json
 138.7 217 | Error from server (NotFound): pods "certificates-svc--ae10dddc50da4595998694d52d3f9121-7976bd4rjhl8" not found
 138.7 TEL | [217] exit 1 in 0.42 secs.
 138.9 TEL | [218] Capturing: kubectl --context kubecarrier-management --namespace provider-2 get pod certificates-svc--ae10dddc50da4595998694d52d3f9121-7976bd4rjhl8 -o json
 139.2 218 | Error from server (NotFound): pods "certificates-svc--ae10dddc50da4595998694d52d3f9121-7976bd4rjhl8" not found
 139.2 TEL | [218] exit 1 in 0.30 secs.
 139.2 TEL | END SPAN remote.py:104(wait_for_pod)  120.1s

```

**Comment by ipleten** [comment]
Could you provide more details please. Was it local cluster? Any logs from pods? Looks like pod wasn't able to start and some logs or events from it would be helpful.
Have you tried 0.105 version?

**Comment by nmiculinic** [comment]
This doesn't happen every time, it's non-deterministic. It happened on both local cluster (via kind) and remote ones (GKE). Next time it happens I'll report more details, logs from pod, etc.
