### ISSUE TITLE
Error on swapping the deployment: Telepresence shouldn't crash if deployment GID is not 0

### ISSUE THREAD

**Issue by gep** [telepresenceio/telepresence#1413]
### What were you trying to do?

Swap telepresence deployment

### What did you expect to happen?

Swap the deployment

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--swap-deployment', 'backend', '--docker-run', '-it', '--rm', '--user', 'app', '--env-file', './.env.local', ...]`
Version: `0.105`
Python version: `3.8.5 (default, Jul 21 2020, 10:48:26) 
[Clang 11.0.3 (clang-1103.0.32.62)]`
kubectl version: `Client Version: v1.18.6 // Server Version: v1.17.6-eks-4e7f64`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Darwin local 19.6.0 Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 65, in main
    remote_info = start_proxy(runner)
  File "/usr/local/bin/telepresence/telepresence/proxy/__init__.py", line 130, in start_proxy
    remote_info = get_remote_info(
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 193, in get_remote_info
    wait_for_pod(runner, remote_info)
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 124, in wait_for_pod
    raise RuntimeError(
RuntimeError: Pod isn't starting or can't be found: {'conditions': [{'lastProbeTime': None, 'lastTransitionTime': '2020-08-12T06:53:35Z', 'status': 'True', 'type': 'Initialized'}, {'lastProbeTime': None, 'lastTransitionTime': '2020-08-12T06:53:35Z', 'message': 'containers with unready status: [c]', 'reason': 'ContainersNotReady', 'status': 'False', 'type': 'Ready'}, {'lastProbeTime': None, 'lastTransitionTime': '2020-08-12T06:53:35Z', 'message': 'containers with unready status: [c]', 'reason': 'ContainersNotReady', 'status': 'False', 'type': 'ContainersReady'}, {'lastProbeTime': None, 'lastTransitionTime': '2020-08-12T06:53:35Z', 'status': 'True', 'type': 'PodScheduled'}], 'containerStatuses': [{'containerID': 'docker://884346c9cdb6d2d6e34ea3dcb39d6cabc92f39b06f6739560b7b7d69334ed08a', 'image': 'datawire/telepresence-k8s:0.105', 'imageID': 'docker-pullable://datawire/telepresence-k8s@sha256:10a54af912ee904c3ee3f8a44d9b2991db8a1744cb75810e54ba08de1e93aba7', 'lastState': {'terminated': {'containerID': 'docker://884346c9cdb6d2d6e34ea3dcb39d6cabc92f39b06f6739560b7b7d69334ed08a', 'exitCode': 1, 'finishedAt': '2020-08-12T06:55:14Z', 'message': 'Could not load host key: /etc/ssh/ssh_host_rsa_key\r\nCould not load host key: /etc/ssh/ssh_host_dsa_key\r\nCould not load host key: /etc/ssh/ssh_host_ecdsa_key\r\nCould not load host key: /etc/ssh/ssh_host_ed25519_key\r\nsshd: no hostkeys available -- exiting.\r\n', 'reason': 'Error', 'startedAt': '2020-08-12T06:55:14Z'}}, 'name': 'c', 'ready': False, 'restartCount': 4, 'started': False, 'state': {'waiting': {'message': 'back-off 1m20s restarting failed container=c pod=backend-a823788da29845d9a63a1469922900d9-9767f6c89-ps4v6_andrey-semikov(294fe80d-e7af-4dfd-89a9-6ef3e3f93ef4)', 'reason': 'CrashLoopBackOff'}}}], 'hostIP': '10.150.13.73', 'phase': 'Running', 'podIP': '10.150.13.87', 'podIPs': [{'ip': '10.150.13.87'}], 'qosClass': 'Burstable', 'startTime': '2020-08-12T06:53:35Z'}

```

Logs:

```
 TEL | [138] Capturing: kubectl --context .../dev --namespace andrey-semikov get pod backend-a823788da29845d9a63a1469922900d9-9767f6c89-ps4v6 -o json
 128.5 TEL | [138] captured in 0.71 secs.
 128.7 TEL | [139] Capturing: kubectl ...:cluster/dev --namespace andrey-semikov get pod backend-a823788da29845d9a63a14699

**Comment by ipleten** [comment]
Does you deployment have any mount points (especially to '/etc/ssh/')

**Comment by gep** [comment]
@ipleten it turned out that deployment had a security user group `1000` and user `1000`.

I changed the security group to `0`, then it started to work as expected.

You may close the issue if needed.

Thanks!

**Comment by ipleten** [comment]
Could you please change description of issue to something like 'Telepresence shouldn't crash if deployment UID/GID is not 0'
or just close it.
I don't have permissions to do that ¯\_(ツ)_/¯.
