### ISSUE TITLE
Will Telepresence supports the HTTPS protocol

### ISSUE THREAD

**Issue by Vinay328** [telepresenceio/telepresence#1415]
### What were you trying to do?

I am running Kubernetes single node cluster in minikube(OS is ubuntu 18.04), and I am trying to swap an https container written in node js for debugging purpose instead of relying on print logs in the container

Why this is required:
A use case is the nodejs container acts as webhook , this is for Kubernetes validatingadmissioncontroller purpose, whenever any kubectl command is applied, Kubernetes API-server will call my webhook and it will send the JSON object and I need to see this JSON object in my Webstorm editor

Will Telepresence supports the https protocol

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/bin/telepresence', '--verbose', '--swap-deployment', 'node', '--expose', '8080:8080', '--run-shell', '--method', 'inject-tcp']`
Version: `0.105`
Python version: `3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0]`
kubectl version: `Client Version: v1.18.6 // Server Version: v1.18.0`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux inctvinaykoti 5.4.0-42-generic #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 65, in main
    remote_info = start_proxy(runner)
  File "/usr/bin/telepresence/telepresence/proxy/__init__.py", line 128, in start_proxy
    args.service_account
  File "/usr/bin/telepresence/telepresence/proxy/deployment.py", line 349, in supplant_deployment
    input=json.dumps(new_deployment_json).encode("utf-8")
  File "/usr/bin/telepresence/telepresence/runner/runner.py", line 463, in check_call
    env,
  File "/usr/bin/telepresence/telepresence/runner/runner.py", line 438, in _run_command_sync
    None if stderr_to_stdout else err_logger.get_captured(),
subprocess.CalledProcessError: Command '['kubectl', '--context', 'minikube', '--namespace', 'default', 'apply', '-f', '-']' returned non-zero exit status 1.

```

Logs:

```
sed.",
   1.5   8 |                 "reason": "NewReplicaSetAvailable",
   1.5   8 |                 "status": "True",
   1.5   8 |                 "type": "Progressing"
   1.5   8 |             }
   1.5   8 |         ],
   1.5   8 |         "observedGeneration": 1,
   1.5   8 |         "readyReplicas": 1,
   1.5   8 |         "replicas": 1,
   1.5   8 |         "updatedReplicas": 1
   1.5   8 |     }
   1.5   8 | }
   1.5 TEL | [8] captured in 0.09 secs.
   1.5 TEL | END SPAN remote.py:75(get_deployment_json)    0.1s
   1.5 TEL | [9] Running: kubectl --context minikube --namespace default delete deployment node-7e8491c72a6d45bbacfe1c474c8a251d --ignore-not-found
   1.6 TEL | [9] ran in 0.05 secs.
   1.6 TEL | [10] Running: kubectl --context minikube --namespace default apply -f -
   1.7  10 | Error from server: error when creating "STDIN": admission webhook "node.default.svc" denied the request: Bad request - every pod should at least 2 replicas
   1.7 TEL | [10] exit 1 in 0.15 secs.

```

**Comment by Vinay328** [comment]
Hi, I just changed the approach now https protocol is working
new approach is :
a) deployed https pod with single container
b) Applied telepresence swap command
c) Using kubectl created ValidatingWebhookConfiguration resource
Finally I am able to debug

Previous approach was 
a) deployed https pod with single container
b) Using kubectl created ValidatingWebhookConfiguration resource
c) Applied telepresence swap command 

I think due to new policy which I applied for example every deployment should have 2 replicas rules -> telepresence throwed an error.
