### ISSUE TITLE
help

### ISSUE THREAD

**Issue by newctech** [telepresenceio/telepresence#1418]
### What were you trying to do?

(please tell us)

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--swap-deployment', 'aliyun-service-broker-aliyun-service-broker', '--namespace', 'ark-system', '--expose', '80', '--run', './open-service-broker-ark', '-logtostderr', '--port=8005']`
Version: `0.105`
Python version: `3.8.5 (v3.8.5:580fbb018f, Jul 20 2020, 12:11:27) 
[Clang 6.0 (clang-600.0.57)]`
kubectl version: `Client Version: v1.18.6 // Server Version: v1.14.8-aliyun.1`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Darwin ali-6c96cfe0631f.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 81, in main
    user_process = launch(
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 111, in launch
    return launch_vpn(
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 126, in launch_vpn
    connect_sshuttle(runner, remote_info, also_proxy, ssh)
  File "/usr/local/bin/telepresence/telepresence/outbound/vpn.py", line 291, in connect_sshuttle
    ] + get_proxy_cidrs(runner, remote_info, hosts_or_ips),
  File "/usr/local/bin/telepresence/telepresence/outbound/vpn.py", line 84, in get_proxy_cidrs
    result.update(context_cache.lookup("podCIDRs", lambda: podCIDRs(runner)))
  File "/usr/local/bin/telepresence/telepresence/runner/cache.py", line 102, in lookup
    value = function()
  File "/usr/local/bin/telepresence/telepresence/outbound/vpn.py", line 84, in <lambda>
    result.update(context_cache.lookup("podCIDRs", lambda: podCIDRs(runner)))
  File "/usr/local/bin/telepresence/telepresence/outbound/vpn.py", line 192, in podCIDRs
    cidrs.add(covering_cidr(pod_ips))
  File "/usr/local/bin/telepresence/telepresence/outbound/vpn.py", line 36, in covering_cidr
    networks = collapse([
  File "/usr/local/bin/telepresence/telepresence/outbound/vpn.py", line 37, in <listcomp>
    ipaddress.IPv4Interface(ip + "/24").network for ip in ips
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ipaddress.py", line 1335, in __init__
    IPv4Address.__init__(self, addr)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ipaddress.py", line 1252, in __init__
    self._ip = self._ip_int_from_string(addr_str)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ipaddress.py", line 1144, in _ip_int_from_string
    raise AddressValueError("Expected 4 octets in %r" % ip_str)
ipaddress.AddressValueError: Expected 4 octets in '<nil>'

```

Logs:

```
hon3 podinfo.py
  11.2  19 | Handling connection for 55836
  11.2  19 | Handling connection for 55836
  12.4 TEL | [26] captured in 1.20 secs.
  12.4 TEL | END SPAN remote_env.py:29(get_remote_env)    1.2s
  12.4 TEL | BEGIN SPAN mount.py:30(mount_remote_volumes)
  12.4 TEL | [27] Running: sshfs -p 55836 -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null telepresence@127.0.0.1:/ /tmp/tel-gk9ncx_0/fs
  12.5  19 | Handling connection for 55836
  13.3 TEL | [27] ran in 0.85 secs.
  13.3 TEL | END SPAN mount.py:30(mount_remote_volumes)    0.9s
  13.3 TEL | BEGIN SPAN vpn.py:280(connect_sshuttle)
  13.3 TEL | BEGIN SPAN vpn.py:77(get_proxy_cidrs)
  13.3 TEL | [28] Capturing: kubectl --context kubernetes-admin@k8s-A-6011 --namespace ark-system get nodes -o json
  13.8 TEL | [28] captured in 0.57 secs.
  13.8 TEL | [29] Capturing: kubectl --context kubernetes-admin@k8s-A-6011 --namespace ark-system get pods --all-namespaces -o json
  18.3 TEL | [29] cap

**Comment by ark3** [comment]
Sorry about the crash. I would guess that Tel is tripping over some IPv6 addresses that it doesn't understand. Does your Kubernetes cluster use IPv6 address spaces?
