### ISSUE TITLE
Unexpedted crash on start of telepresence session with envfile

### ISSUE THREAD

**Issue by twothumbs** [telepresenceio/telepresence#1435]
### What were you trying to do?

Start telepresence session for Go servlet

### What did you expect to happen?

Expected JSON env file to be written so I could use Goland to debug servlet

### What happened instead?

Waited, waited, waited ... this form popped up.  Didn't get a chance to start debugging.

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--namespace', 'ns1', '--swap-deployment', 'beam', '--env-json', 'beam-server-env.json']`
Version: `0.107`
Python version: `3.7.4 (v3.7.4:e09359112e, Jul  8 2019, 14:54:52) 
[Clang 6.0 (clang-600.0.57)]`
kubectl version: `Client Version: v1.16.6-beta.0 // Server Version: v1.18.8`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin MBP-400053026 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 65, in main
    remote_info = start_proxy(runner)
  File "/usr/local/bin/telepresence/telepresence/proxy/operation.py", line 265, in act
    wait_for_pod(runner, self.remote_info)
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 141, in wait_for_pod
    "Pod isn't starting or can't be found: {}".format(pod["status"])
RuntimeError: Pod isn't starting or can't be found: {'conditions': [{'lastProbeTime': None, 'lastTransitionTime': '2020-09-09T17:50:41Z', 'status': 'True', 'type': 'Initialized'}, {'lastProbeTime': None, 'lastTransitionTime': '2020-09-09T17:50:41Z', 'message': 'containers with unready status: [beam]', 'reason': 'ContainersNotReady', 'status': 'False', 'type': 'Ready'}, {'lastProbeTime': None, 'lastTransitionTime': '2020-09-09T17:50:41Z', 'message': 'containers with unready status: [beam]', 'reason': 'ContainersNotReady', 'status': 'False', 'type': 'ContainersReady'}, {'lastProbeTime': None, 'lastTransitionTime': '2020-09-09T17:50:06Z', 'status': 'True', 'type': 'PodScheduled'}], 'containerStatuses': [{'image': 'datawire/telepresence-k8s:0.107', 'imageID': '', 'lastState': {}, 'name': 'beam', 'ready': False, 'restartCount': 0, 'started': False, 'state': {'waiting': {'reason': 'ContainerCreating'}}}], 'hostIP': '192.168.212.30', 'phase': 'Pending', 'qosClass': 'Burstable', 'startTime': '2020-09-09T17:50:41Z'}

```

Logs:

```
ctl --context kubernetes-admin --namespace ns1 get pod beam-0926eb01c2e14038b0deded5ecf849cc -o json
 187.3 TEL | [162] captured in 0.34 secs.
 187.6 TEL | [163] Capturing: kubectl --context kubernetes-admin --namespace ns1 get pod beam-0926eb01c2e14038b0deded5ecf849cc -o json
 187.9 TEL | [163] captured in 0.33 secs.
 188.1 TEL | [164] Running: sudo -n echo -n
 188.2 TEL | [164] ran in 0.03 secs.
 188.2 TEL | [165] Capturing: kubectl --context kubernetes-admin --namespace ns1 get pod beam-0926eb01c2e14038b0deded5ecf849cc -o json
 188.5 TEL | [165] captured in 0.35 secs.
 188.8 TEL | [166] Capturing: kubectl --context kubernetes-admin --namespace ns1 get pod beam-0926eb01c2e14038b0deded5ecf849cc -o json
 189.1 TEL | [166] captured in 0.31 secs.
 189.3 TEL | [167] Capturing: kubectl --context kubernetes-admin --namespace ns1 get pod beam-0926eb01c2e14038b0deded5ecf849cc -o json
 189.7 TEL | [167] captured in 0.34 secs.
 189.7 TEL | END SPAN remote.py:109(wait_for_pod)  180.4s

```

**Comment by ark3** [comment]
The error message says that the container did not start. It might have just been slow to pull the image or something. Does it fail every time?

Yes, the error message is absolutely awful. Telepresence should do a better job of explaining what went wrong (the Telepresence proxy Pod did not start) and showing the status of the Pod, if it can. Crashing, as it does now, is unacceptable. We'll improve this.

**Comment by twothumbs** [comment]
The next attempt to start did indeed start.  Timing, I guess. :shrug:
