### ISSUE TITLE
 telepresence --swap-deployment failed to swap out service from GKE

### ISSUE THREAD

**Issue by biwenxu** [telepresenceio/telepresence#1441]
### What were you trying to do?
Swap out a service from GKE for debugging 
MacBook OS version: 10.15.6

### What did you expect to happen?

Swap out the service so that I can debug on my dev machine

### What happened instead?
https://gist.github.com/biwenxu/c5a6a77a7bdc6dce5574c12a5c6ebbee

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--swap-deployment', 'tenant-process-manager', '--expose', '8080:5000', '--namespace', 'feature-bxu-ms17']`
Version: `0.108`
Python version: `3.8.2 (default, Sep 18 2020, 10:05:49) 
[Clang 12.0.0 (clang-1200.0.32.2)]`
kubectl version: `Client Version: v1.14.3 // Server Version: v1.14.10-gke.42`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Darwin C02DC7JBMD6T 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 81, in main
    user_process = launch(
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 111, in launch
    return launch_vpn(
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 126, in launch_vpn
    connect_sshuttle(runner, remote_info, also_proxy, ssh)
  File "/usr/local/bin/telepresence/telepresence/outbound/vpn.py", line 110, in connect_sshuttle
    raise RuntimeError("vpn-tcp tunnel did not connect")
RuntimeError: vpn-tcp tunnel did not connect

```

Logs:

```

  42.4 TEL | [45] timed out after 5.01 secs.
  42.4 TEL | [46] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-10.a.sanity.check.telepresence.io")'
  43.4 TEL | [46] timed out after 1.01 secs.
  43.5 TEL | Wait for vpn-tcp connection: hellotelepresence-11
  43.5 TEL | [47] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-11")'
  48.5 TEL | [47] timed out after 5.01 secs.
  48.5 TEL | [48] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-11.a.sanity.check.telepresence.io")'
  49.5 TEL | [48] timed out after 1.01 secs.
  49.6 TEL | Wait for vpn-tcp connection: hellotelepresence-12
  49.6 TEL | [49] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-12")'
  54.6 TEL | [49] timed out after 5.01 secs.
  54.6 TEL | [50] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-12.a.sanity.check.telepresence.io")'
  55.7 TEL | [50] timed out after 1.01 secs.

```

**Comment by biwenxu** [comment]
It is working on my older MacBook (os version: 10.14.6), with exact same version of Telepresence and networking env
