### ISSUE TITLE
llls

### ISSUE THREAD

**Issue by yeqqmatlab** [telepresenceio/telepresence#1443]
### What were you trying to do?

(please tell us)

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/bin/telepresence', '--swap-deployment', 'zsy-business-service-deployment', '--env-json', 'zsy-business-service_env.json']`
Version: `0.108`
Python version: `3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0]`
kubectl version: `Client Version: v1.18.6 // Server Version: v1.18.6`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux PC-20191218MRJE 4.4.0-17763-Microsoft #1217-Microsoft Mon May 05 16:09:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux`

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 82, in main
    runner, remote_info, env, socks_port, ssh, mount_dir, pod_info
  File "/usr/bin/telepresence/telepresence/outbound/setup.py", line 112, in launch
    runner_, remote_info, command, args.also_proxy, env, ssh
  File "/usr/bin/telepresence/telepresence/outbound/local.py", line 126, in launch_vpn
    connect_sshuttle(runner, remote_info, also_proxy, ssh)
  File "/usr/bin/telepresence/telepresence/outbound/vpn.py", line 110, in connect_sshuttle
    raise RuntimeError("vpn-tcp tunnel did not connect")
RuntimeError: vpn-tcp tunnel did not connect

```

Logs:

```
ostbyname("hellotelepresence-36")'
  42.4 TEL | [95] exit 1 in 0.45 secs.
  42.4 TEL | [96] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-36.a.sanity.check.telepresence.io")'
  42.7 TEL | [96] exit 1 in 0.35 secs.
  42.8 TEL | Wait for vpn-tcp connection: hellotelepresence-37
  42.8 TEL | [97] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-37")'
  43.1 TEL | [97] exit 1 in 0.25 secs.
  43.1 TEL | [98] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-37.a.sanity.check.telepresence.io")'
  43.5 TEL | [98] exit 1 in 0.40 secs.
  43.6 TEL | Wait for vpn-tcp connection: hellotelepresence-38
  43.6 TEL | [99] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-38")'
  44.0 TEL | [99] exit 1 in 0.40 secs.
  44.0 TEL | [100] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-38.a.sanity.check.telepresence.io")'
  44.4 TEL | [100] exit 1 in 0.40 secs.

```

**Comment by yeqqmatlab** [comment]
json
