### ISSUE TITLE
telepresence return traceback every time i tried

### ISSUE THREAD

**Issue by Osuichiro** [telepresenceio/telepresence#1451]
### What were you trying to do?

build new pods with telepresence

### What did you expect to happen?

complete to telepresence

### What happened instead?

WiFi hung up while running test-tools using telepresence.
i tried to telepresence again.
but just export below traceback every time i tried.
please give me advice.

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence']`
Version: `0.104`
Python version: `3.7.6 (default, Dec 30 2019, 19:38:28) 
[Clang 11.0.0 (clang-1100.0.33.16)]`
kubectl version: `(error: [Errno 8] Exec format error: 'kubectl')`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin PC2647 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 42, in main
    set_kube_command(runner, args)
  File "/usr/local/bin/telepresence/telepresence/startup.py", line 103, in set_kube_command
    prelim_command, "config", "current-context"
  File "/usr/local/bin/telepresence/telepresence/runner/runner.py", line 483, in get_output
    env,
  File "/usr/local/bin/telepresence/telepresence/runner/runner.py", line 395, in _run_command_sync
    process = _launch_command(args, out_logger, err_logger, **kwargs)
  File "/usr/local/bin/telepresence/telepresence/runner/launch.py", line 96, in _launch_command
    process = Popen(args, **kwargs)  # type: Popen[str]
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: 'kubectl'

```

Logs:

```
Not available
```

**Comment by Osuichiro** [comment]
this issue is fixed!
it's my fault. 
kubectl has wrong PATH, due to change bash to zsh.
thanks.
