### ISSUE TITLE
telepresence cannot connect

### ISSUE THREAD

**Issue by Theog75** [telepresenceio/telepresence#1481]
### What were you trying to do?

(please tell us)

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/bin/telepresence']`
Version: `0.108`
Python version: `3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0]`
kubectl version: `Client Version: v1.11.0+d4cacc0 // Server Version: v1.19.0`
oc version: `oc v3.11.0+0cbc58b // kubernetes v1.11.0+d4cacc0 // features: Basic-Auth GSSAPI Kerberos SPNEGO //  // Server https://192.168.20.130:6443 // kubernetes v1.19.0`
OS: `Linux chaviko 5.4.0-54-generic #60-Ubuntu SMP Fri Nov 6 10:37:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 65, in main
    remote_info = start_proxy(runner)
  File "/usr/bin/telepresence/telepresence/proxy/operation.py", line 135, in act
    wait_for_pod(runner, self.remote_info)
  File "/usr/bin/telepresence/telepresence/proxy/remote.py", line 140, in wait_for_pod
    raise RuntimeError(
RuntimeError: Pod isn't starting or can't be found: {'conditions': [{'lastProbeTime': None, 'lastTransitionTime': '2020-11-29T11:24:38Z', 'status': 'True', 'type': 'Initialized'}, {'lastProbeTime': None, 'lastTransitionTime': '2020-11-29T11:24:38Z', 'message': 'containers with unready status: [telepresence]', 'reason': 'ContainersNotReady', 'status': 'False', 'type': 'Ready'}, {'lastProbeTime': None, 'lastTransitionTime': '2020-11-29T11:24:38Z', 'message': 'containers with unready status: [telepresence]', 'reason': 'ContainersNotReady', 'status': 'False', 'type': 'ContainersReady'}, {'lastProbeTime': None, 'lastTransitionTime': '2020-11-29T11:24:38Z', 'status': 'True', 'type': 'PodScheduled'}], 'containerStatuses': [{'image': 'datawire/telepresence-k8s:0.108', 'imageID': '', 'lastState': {}, 'name': 'telepresence', 'ready': False, 'restartCount': 0, 'started': False, 'state': {'waiting': {'message': 'Back-off pulling image "datawire/telepresence-k8s:0.108"', 'reason': 'ImagePullBackOff'}}}], 'hostIP': '192.168.20.185', 'phase': 'Pending', 'podIP': '10.233.88.137', 'podIPs': [{'ip': '10.233.88.137'}], 'qosClass': 'Burstable', 'startTime': '2020-11-29T11:24:38Z'}

```

Logs:

```
5 secs.
 181.7 TEL | [72] Capturing: kubectl --context etcdtest --namespace etcdtest get pod telepresence-1606649068-898069-17057 -o json
 183.5 TEL | [72] captured in 1.77 secs.
 183.8 TEL | [73] Capturing: kubectl --context etcdtest --namespace etcdtest get pod telepresence-1606649068-898069-17057 -o json
 184.2 TEL | [74] Running: sudo -n echo -n
 184.2 TEL | [74] ran in 0.01 secs.
 185.3 TEL | [73] captured in 1.56 secs.
 185.6 TEL | [75] Capturing: kubectl --context etcdtest --namespace etcdtest get pod telepresence-1606649068-898069-17057 -o json
 187.0 TEL | [75] captured in 1.47 secs.
 187.3 TEL | [76] Capturing: kubectl --context etcdtest --namespace etcdtest get pod telepresence-1606649068-898069-17057 -o json
 188.7 TEL | [76] captured in 1.38 secs.
 188.9 TEL | [77] Capturing: kubectl --context etcdtest --namespace etcdtest get pod telepresence-1606649068-898069-17057 -o json
 192.5 TEL | [77] captured in 3.62 secs.
 192.5 TEL | END SPAN remote.py:109(wait_for_pod)  182.6s

```

**Comment by antontroshin** [comment]
Looks like few recently submitted issues, mine included, see #1467 (workaround) and #1477.
