### ISSUE TITLE
telepresence --method vpn-tcp --mount false fails stops with a traceback

### ISSUE THREAD

**Issue by grzn** [telepresenceio/telepresence#1482]
### What were you trying to do?

run telepresence --method vpn-tcp --mount false
on a Mac with minikube, parallels driver
### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--method', 'vpn-tcp', '--mount', 'false']`
Version: `0.108`
Python version: `3.9.0 (default, Nov 21 2020, 14:55:42) 
[Clang 12.0.0 (clang-1200.0.32.27)]`
kubectl version: `Client Version: v1.19.4 // Server Version: v1.19.4`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Darwin guys-macbook.local 20.1.0 Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64 x86_64 i386 MacBookPro16,2 Darwin`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 81, in main
    user_process = launch(
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 111, in launch
    return launch_vpn(
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 126, in launch_vpn
    connect_sshuttle(runner, remote_info, also_proxy, ssh)
  File "/usr/local/bin/telepresence/telepresence/outbound/vpn.py", line 110, in connect_sshuttle
    raise RuntimeError("vpn-tcp tunnel did not connect")
RuntimeError: vpn-tcp tunnel did not connect

```

Logs:

```
ect at 0x7f5371731630>
  41.2  18 | c : DNS request from ('192.168.1.100', 62885) to None: 71 bytes
  41.2  18 | c : DNS request from ('192.168.1.100', 53595) to None: 71 bytes
  41.2  11 | 2020-11-29T18:32:08+0000 [stdout#info] AAAA query, sending back A instead: b'github-production-container-registry.s3.amazonaws.com'
  41.2  11 | 2020-11-29T18:32:08+0000 [stdout#info] A query: b'github-production-container-registry.s3.amazonaws.com'
  41.2  11 | 2020-11-29T18:32:08+0000 [DNSDatagramProtocol (UDP)] DNSDatagramProtocol starting on 3846
  41.2  11 | 2020-11-29T18:32:08+0000 [DNSDatagramProtocol (UDP)] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7f537172de80>
  41.2  11 | 2020-11-29T18:32:08+0000 [stdout#info] A query: b'github-production-container-registry.s3.amazonaws.com'
  41.3  11 | 2020-11-29T18:32:08+0000 [-] (UDP Port 3846 Closed)
  41.3  11 | 2020-11-29T18:32:08+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7f537172de80>

```

**Comment by grzn** [comment]
found the issue, it conflicts with nextdns profile.
