### ISSUE TITLE
Can not start the telepresence using inject-tcp method

### ISSUE THREAD

**Issue by Zhuoqin** [telepresenceio/telepresence#1487]
### What were you trying to do?

Trying to swap deployment using
telepresence --method=inject-tcp --swap-deployment xxx-service 
### What did you expect to happen?

Expecting the service is swapped, but errors showed and exited.

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--method=inject-tcp', '--swap-deployment', 'xxx-auth-service']`
Version: `0.108`
Python version: `3.7.3 (default, Apr 24 2020, 18:51:23) 
[Clang 11.0.3 (clang-1103.0.32.62)]`
kubectl version: `Client Version: v1.19.3 // Server Version: v1.19.4`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin Erics-MacBook-Pro.local 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 82, in main
    runner, remote_info, env, socks_port, ssh, mount_dir, pod_info
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 64, in launch
    return launch_inject(runner_, command, socks_port, env)
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 104, in launch_inject
    torsocks_env = set_up_torsocks(runner, socks_port)
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 71, in set_up_torsocks
    raise RuntimeError("SOCKS network proxying failed to start...")
RuntimeError: SOCKS network proxying failed to start...

```

Logs:

```
n a directory protected by Apple's System Integrity Protection.
  18.6 TEL | [133] exit 1 in 0.02 secs.
  18.7 TEL | [134] Running: torsocks python3 -c 'import socket; socket.socket().connect(('"'"'kubernetes.default'"'"', 443))'
  18.7 134 | ERROR: /usr/bin/python3 is located in a directory protected by Apple's System Integrity Protection.
  18.7 TEL | [134] exit 1 in 0.02 secs.
  18.8 TEL | [135] Running: torsocks python3 -c 'import socket; socket.socket().connect(('"'"'kubernetes.default'"'"', 443))'
  18.8 135 | ERROR: /usr/bin/python3 is located in a directory protected by Apple's System Integrity Protection.
  18.8 TEL | [135] exit 1 in 0.02 secs.
  18.9 TEL | [136] Running: torsocks python3 -c 'import socket; socket.socket().connect(('"'"'kubernetes.default'"'"', 443))'
  18.9 136 | ERROR: /usr/bin/python3 is located in a directory protected by Apple's System Integrity Protection.
  18.9 TEL | [136] exit 1 in 0.02 secs.
  18.9 TEL | END SPAN local.py:42(set_up_torsocks)   15.0s

```

**Comment by Maartz** [comment]
Got the same issue on #1491
