### ISSUE TITLE
Problem with telepresence

### ISSUE THREAD

**Issue by shachardevops** [telepresenceio/telepresence#1523]
### What were you trying to do?

trying to connect to telepresence
### What did you expect to happen?

connect to telepresence

### What happened instead?

not connected

### Automatically included information

Command line: `['/usr/local/bin/telepresence']`
Version: `0.102`
Python version: `3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0]`
kubectl version: `Client Version: v1.20.2 // Server Version: v1.11.0+d4cacc0`
oc version: `Client Version: 4.6.0-0.okd-2021-01-17-185703 // Kubernetes Version: v1.11.0+d4cacc0`
OS: `Linux shachar-sosivio 5.8.0-40-generic #45~20.04.1-Ubuntu SMP Fri Jan 15 11:35:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 60, in main
    remote_info = start_proxy(runner)
  File "/usr/local/bin/telepresence/telepresence/proxy/__init__.py", line 121, in start_proxy
    remote_info = get_remote_info(
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 151, in get_remote_info
    deployment = get_deployment_json(
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 93, in get_deployment_json
    return json.loads(
IndexError: list index out of range

```

Logs:

```
46d2125e43efb8b4a6e8d10a97b3
  11.6  12 | No resources found
  11.6 TEL | [12] ran in 1.58 secs.
  11.6 TEL | [13] Running: oc --context sosivio-rc-dev/ocp-rct-co-il:8443/shachar --namespace sosivio-rc-dev run --restart=Always --limits=cpu=1000m,memory=256Mi --requests=cpu=25m,memory=64Mi telepresence-1612111518-1067646-5569 --image=datawire/telepresence-k8s:0.102 --labels=telepresence=a18e46d2125e43efb8b4a6e8d10a97b3
  12.9  13 | pod/telepresence-1612111518-1067646-5569 created
  12.9 TEL | [13] ran in 1.38 secs.
  12.9 TEL | END SPAN deployment.py:105(create_new_deployment)    3.0s
  13.0 TEL | BEGIN SPAN remote.py:150(get_remote_info)
  13.0 TEL | BEGIN SPAN remote.py:77(get_deployment_json)
  13.0 TEL | [14] Capturing: oc --context sosivio-rc-dev/ocp-rct-co-il:8443/shachar --namespace sosivio-rc-dev get deployment -o json --selector=telepresence=a18e46d2125e43efb8b4a6e8d10a97b3
  15.3 TEL | [14] captured in 2.33 secs.
  15.3 TEL | END SPAN remote.py:77(get_deployment_json)    2.3s

```

**Comment by shachardevops** [comment]
when I upgrade the version to 0.109 everything works
