### ISSUE TITLE
telepresence --swap-deployment failure

### ISSUE THREAD

**Issue by ggcode1** [telepresenceio/telepresence#1555]
### What were you trying to do?

Execute: `telepresence --swap-deployment reporting-api --method inject-tcp --env-file reporting-api.env`

I have just upgraded telepresence via `brew upgrade`

### What did you expect to happen?

Normal session.

### What happened instead?

Immediate process exit with backtrace.

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--swap-deployment', 'reporting-api', '--method', 'inject-tcp', '--env-file', 'reporting-api.env']`
Version: `0.109`
Python version: `3.9.2 (default, Feb 24 2021, 13:26:09) 
[Clang 12.0.0 (clang-1200.0.32.29)]`
kubectl version: `Client Version: v1.14.0 // Server Version: v1.14.0`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Darwin grantminer-C02X35WTJGH6 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 42, in main
    set_kube_command(runner, args)
  File "/usr/local/bin/telepresence/telepresence/startup.py", line 141, in set_kube_command
    runner.get_output([
  File "/usr/local/bin/telepresence/telepresence/runner/runner.py", line 479, in get_output
    output = self._run_command_sync(
  File "/usr/local/bin/telepresence/telepresence/runner/runner.py", line 437, in _run_command_sync
    raise CalledProcessError(
subprocess.CalledProcessError: Command '['kubectl', '--context', 'minikube', 'config', 'view', '-o', 'json']' returned non-zero exit status 1.

```

Logs:

```
Not available
```

**Comment by ggcode1** [comment]
```
➜  dev git:(develop) kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
➜  dev git:(develop) kubectl --context minikube config view -o json
error: converting  to : type names don't match (Unknown, RawExtension), and no conversion 'func (runtime.Unknown, runtime.RawExtension) error' registered.
                                                                                                                                                                                                                                            
➜  dev git:(develop) 
➜  dev git:(develop) kubectl --context minikube config view        
error: converting  to : type names don't match (Unknown, RawExtension), and no conversion 'func (runtime.Unknown, runtime.RawExtension) error' registered.
```

**Comment by ggcode1** [comment]
I think it is due to my `kubectl` version. However, I need to use that version for compatibility with kubernetes v1.14.
