### ISSUE TITLE
telepresence --method vpn-tcp crashes

### ISSUE THREAD

**Issue by torniker** [telepresenceio/telepresence#1648]
### What were you trying to do?

telepresence --method vpn-tcp

### What did you expect to happen?

open connection to cluster

### What happened instead?

crashed

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--method', 'vpn-tcp']`
Version: `0.109`
Python version: `3.9.2 (default, Mar 26 2021, 23:22:38) 
[Clang 12.0.0 (clang-1200.0.32.29)]`
kubectl version: `Client Version: v1.20.4-dirty // Server Version: v1.20.2`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Darwin MacBook-Pro-2.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 81, in main
    user_process = launch(
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 111, in launch
    return launch_vpn(
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 136, in launch_vpn
    connect_sshuttle(runner, remote_info, also_proxy, ssh)
  File "/usr/local/bin/telepresence/telepresence/outbound/vpn.py", line 110, in connect_sshuttle
    raise RuntimeError("vpn-tcp tunnel did not connect")
RuntimeError: vpn-tcp tunnel did not connect

```

Logs:

```
2 | 2021-04-07T17:50:56+0000 [stdout#info] A query: b'app.slack.com'
  51.8  12 | 2021-04-07T17:50:56+0000 [stdout#info] Result for b'app.slack.com' is ['3.10.95.11']
  51.9 TEL | [49] timed out after 1.01 secs.
  51.9  22 | c : DNS request from ('10.10.24.3', 50159) to None: 69 bytes
  52.0  12 | 2021-04-07T17:50:57+0000 [stdout#info] Sanity check: b'hellotelepresence-12.a.sanity.check.telepresence.io'
  52.8  22 | c : DNS request from ('10.10.24.3', 54393) to None: 95 bytes
  52.9  12 | 2021-04-07T17:50:58+0000 [stdout#info] A query: b'a745ad5611ff8465882dfb7e82ac162c-58c0f3c3ae074dcf.elb.eu-west-1.amazonaws.com'
  52.9  12 | 2021-04-07T17:50:58+0000 [stdout#info] Result for b'a745ad5611ff8465882dfb7e82ac162c-58c0f3c3ae074dcf.elb.eu-west-1.amazonaws.com' is ['52.48.241.189', '54.78.113.92', '52.209.209.247']
  53.1  22 | c : DNS request from ('10.10.24.3', 59418) to None: 38 bytes
  53.2  12 | 2021-04-07T17:50:58+0000 [stdout#info] Result for b'hellotelepresence-12' is ['127.0.0.1']

```

**Comment by thallgren** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
