### ISSUE TITLE
Telepresence generating error everytime.

### ISSUE THREAD

**Issue by Sanjit-Prasad** [telepresenceio/telepresence#1665]
### What were you trying to do?

Run a service using Telepresence.

### What did you expect to happen?

Starting network proxy to cluster by swapping out Deployment cart with a proxy Pod

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--swap-deployment', 'cart:nginx', '--namespace', 'mft-sp', '--expose', '5000:80', '--to-pod', '6432', '--docker-run', '--rm', '-it', '-e', 'FLASK_APP=interface.http.server', '-e', 'FLASK_DEBUG=1', '-p', '5000:5000', '-v', '/Users/sanjit/Desktop/Grofers/cart:/code', 'cart', 'python', '-m', 'flask', 'run', '--host', '0.0.0.0', '--port', '5000']`
Version: `0.109`
Python version: `3.9.4 (default, Apr  5 2021, 01:50:46) 
[Clang 12.0.0 (clang-1200.0.32.29)]`
kubectl version: `Client Version: v1.21.0 // Server Version: v1.15.12-eks-31566f`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Darwin Admins-MacBook-Pro.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 65, in main
    remote_info = start_proxy(runner)
  File "/usr/local/bin/telepresence/telepresence/proxy/operation.py", line 271, in act
    wait_for_pod(runner, self.remote_info)
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 140, in wait_for_pod
    raise RuntimeError(
RuntimeError: Pod isn't starting or can't be found: {'conditions': [{'lastProbeTime': None, 'lastTransitionTime': '2021-04-14T11:25:23Z', 'message': 'containers with incomplete status: [consul-template]', 'reason': 'ContainersNotInitialized', 'status': 'False', 'type': 'Initialized'}, {'lastProbeTime': None, 'lastTransitionTime': '2021-04-14T11:25:23Z', 'message': 'containers with unready status: [nginx cart pgbouncer pgbouncer-exporter]', 'reason': 'ContainersNotReady', 'status': 'False', 'type': 'Ready'}, {'lastProbeTime': None, 'lastTransitionTime': '2021-04-14T11:25:23Z', 'message': 'containers with unready status: [nginx cart pgbouncer pgbouncer-exporter]', 'reason': 'ContainersNotReady', 'status': 'False', 'type': 'ContainersReady'}, {'lastProbeTime': None, 'lastTransitionTime': '2021-04-14T11:25:22Z', 'status': 'True', 'type': 'PodScheduled'}], 'containerStatuses': [{'image': 'docker-cache.grofer.io/test/cart:master-f182895', 'imageID': '', 'lastState': {}, 'name': 'cart', 'ready': False, 'restartCount': 0, 'state': {'waiting': {'reason': 'PodInitializing'}}}, {'image': 'datawire/telepresence-k8s-priv:0.109', 'imageID': '', 'lastState': {}, 'name': 'nginx', 'ready': False, 'restartCount': 0, 'state': {'waiting': {'reason': 'PodInitializing'}}}, {'image': 'brainsam/pgbouncer:1.12.0', 'imageID': '', 'lastState': {}, 'name': 'pgbouncer', 'ready': False, 'restartCount': 0, 'state': {'waiting': {'reason': 'PodInitializing'}}}, {'image': 'spreaker/prometheus-pgbouncer-exporter:2.0.3', 'imageID': '', 'lastState': {}, 'name': 'pgbouncer-exporter', 'ready': False, 'restartCount': 0, 'state': {'waiting': {'reason': 'PodInitializing'}}}], 'hostIP': '10.1.176.102', 'initContainerStatuses': [{'containerID': 'docker://7ff9b0f923f372314077fc53633edf131a2d8d8e5e2f517fdf860b0f383d0247', 'image': 'docker-cache.grofer.io/consumer/consul-template:grofers', 'imageID': 'docker-pullable://docker-cache.grofer.io/consumer/consul-template@sha256:4e336c306186f93e9caf8751334eb2e29982bd3154aed7d8c1166a2d29404e54', 'lastState': {}, 'name': 'consul-template', 'ready': False, 'restartCount': 0, 'state': {'running': {'startedAt': '2021-04-14T11:25:25Z'}}}], 'phase': 'Pending', 'podIP': '10.1.174.143', 'qosClass': 'Burstable', 'startTime': '2021-04-14T11:25:23Z'}

```

Logs:

```
5 secs.
 206.8 TEL | [37] Capturing: kubectl --context stage-ore --namespace mft-sp get pod cart-52

**Comment by cindymullins-dw** [comment]
V1 (legacy Telepresence) has been deprecated. You can try the latest version at our [QuickStart here](https://www.getambassador.io/docs/telepresence/latest/quick-start).
