### ISSUE TITLE
instalation on M1: An unsatisfied requirement failed this build.

### ISSUE THREAD

**Issue by d7561985** [telepresenceio/telepresence#1683]
OS: MacOS BigSur 11.2.3 (20D91)
CPU: ARM m1

unable to instal telepresence

`➜  ~ brew install datawire/blackbird/telepresence -d
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /opt/homebrew/Library/Taps/datawire/homebrew-blackbird/Formula/telepresence.rb
==> Installing telepresence from datawire/blackbird
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::AliasLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/python@3.9.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/pkg-config.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/gdbm.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/mpdecimal.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/readline.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/sqlite.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/xz.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/torsocks.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/autoconf.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/m4.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/automake.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/libtool.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/sshfs.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/meson.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/ninja.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/glib.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/gettext.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/libffi.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/pcre.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/libfuse.rb
libfuse: Linux is required for this software.
Error: An unsatisfied requirement failed this build.
/opt/homebrew/Library/Homebrew/formula_installer.rb:538:in `check_requirements'
/opt/homebrew/Library/Homebrew/formula_installer.rb:504:in `compute_dependencies'
/opt/homebrew/Library/Homebrew/formula_installer.rb:209:in `verify_deps_exist'
/opt/homebrew/Library/Homebrew/formula_installer.rb:200:in `prelude'
/opt/homebrew/Library/Homebrew/cmd/install.rb:420:in `install_formula'
/opt/homebrew/Library/Homebrew/cmd/install.rb:324:in `block in install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:322:in `each'
/opt/homebrew/Library/Homebrew/cmd/install.rb:322:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:122:in `<main>'
`

 I was trying to ignore dependencies but this not allow to use application because of `sshfs` which also has issue

**Comment by d7561985** [comment]
Fix:
