### ISSUE TITLE
telepresence failed to launch when replacing an "Init:Error" pod

### ISSUE THREAD

**Issue by bts-verta** [telepresenceio/telepresence#1719]
### What were you trying to do?

launch telepresence (pod that was to be replaced was in 'Init:Error' state)

### What did you expect to happen?

successful launch.

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)
telepresence failed to launch, and telepresence pod was stuck in "init:error" state as well (needed to refresh deploy to remove)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--swap-deployment', 'deployment--deployment-api', '--expose', '3000', '--also-proxy', '10.0.0.0/8', '--env-json', 'telepresence-env.json', '--mount', '/Users/btsomogyi/telepresence_mounts/deployment--deployment-api']`
Version: `0.109`
Python version: `3.9.4 (default, Apr  5 2021, 01:49:30) 
[Clang 12.0.0 (clang-1200.0.32.29)]`
kubectl version: `Client Version: v1.19.7 // Server Version: v1.17.12-eks-7684af`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Darwin Blues-MacBook-Pro.local 19.6.0 Darwin Kernel Version 19.6.0: Mon Apr 12 20:57:45 PDT 2021; root:xnu-6153.141.28.1~1/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 65, in main
    remote_info = start_proxy(runner)
  File "/usr/local/bin/telepresence/telepresence/proxy/operation.py", line 271, in act
    wait_for_pod(runner, self.remote_info)
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 140, in wait_for_pod
    raise RuntimeError(
RuntimeError: Pod isn't starting or can't be found: {'conditions': [{'lastProbeTime': None, 'lastTransitionTime': '2021-05-08T15:48:16Z', 'message': 'containers with incomplete status: [migrate]', 'reason': 'ContainersNotInitialized', 'status': 'False', 'type': 'Initialized'}, {'lastProbeTime': None, 'lastTransitionTime': '2021-05-08T15:48:16Z', 'message': 'containers with unready status: [deployment--deployment-api]', 'reason': 'ContainersNotReady', 'status': 'False', 'type': 'Ready'}, {'lastProbeTime': None, 'lastTransitionTime': '2021-05-08T15:48:16Z', 'message': 'containers with unready status: [deployment--deployment-api]', 'reason': 'ContainersNotReady', 'status': 'False', 'type': 'ContainersReady'}, {'lastProbeTime': None, 'lastTransitionTime': '2021-05-08T15:48:16Z', 'status': 'True', 'type': 'PodScheduled'}], 'containerStatuses': [{'image': 'datawire/telepresence-k8s:0.109', 'imageID': '', 'lastState': {}, 'name': 'deployment--deployment-api', 'ready': False, 'restartCount': 0, 'started': False, 'state': {'waiting': {'reason': 'PodInitializing'}}}], 'hostIP': '10.3.26.208', 'initContainerStatuses': [{'containerID': 'docker://86c1fdb9765eca9e6846fa3e5f379e3ccd685657b6234c4b570164040dc6ae00', 'image': '493416687123.dkr.ecr.us-east-1.amazonaws.com/services/deployment/deployment-api:bts_scan-reconciler-2021-05-08-15-38-40-7eb466944db427a03cc29c381ad13a6eaa2dca17', 'imageID': 'docker-pullable://493416687123.dkr.ecr.us-east-1.amazonaws.com/services/deployment/deployment-api@sha256:69a51a4bfdecaf62bab9097be42c274b06960460e2223ce8c1067af494a223dd', 'lastState': {}, 'name': 'migrate', 'ready': False, 'restartCount': 0, 'state': {'terminated': {'containerID': 'docker://86c1fdb9765eca9e6846fa3e5f379e3ccd685657b6234c4b570164040dc6ae00', 'exitCode': 2, 'finishedAt': '2021-05-08T15:48:19Z', 'reason': 'Error', 'startedAt': '2021-05-08T15:48:19Z'}}}], 'phase': 'Failed', 'podIP': '10.3.110.110', 'podIPs': [{'ip': '10.3.110.110'}], 'qosClass': 'Burstable', 'startTime': '2021-05-08T15:48:16Z'}

```

Logs:

```
--namespace bts get pod deployment--deplo-e5f6e6e097894a698fd0c82d40dd788a -o json
 191.6 TEL | [112] captured in 5.18 secs.
 191.9 TEL | [113] Capturing: kubectl --context engine-dev --namespace bts get pod deployment--deplo-e5f6e6e097894a698fd0c82d40dd788a -o json
 192.1 TEL | [113] captured in 0.25 secs.
 192.4 TEL | [114] Capturing: kubectl --context engine-dev --namespace bts get pod deployment--deplo-e5f6e6e097894a698fd0c82d40dd788a -o json
 192.6 TEL | [114] captured in

**Comment by cindymullins-dw** [comment]
V1 is no longer supported.  The latest release of Telepresence is available [here](https://www.getambassador.io/docs/telepresence/latest/install).
