### ISSUE TITLE
getting started - first time installed and running telepresence error

### ISSUE THREAD

**Issue by Pavel-Durov** [telepresenceio/telepresence#1726]
### What were you trying to do?

trying out telepresence :)

### What did you expect to happen?

to run telepresence as described in Get started section: https://www.telepresence.io/

### What happened instead?
Im reporting this bug (I hope that Automatically included information is useful)

### Automatically included information

Command line: `['/usr/bin/telepresence']`
Version: `0.109`
Python version: `3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0]`
kubectl version: `Client Version: v1.19.4 // Server Version: v1.18.9-eks-d1db3c`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux kimchi-pc 5.8.0-50-generic #56~20.04.1-Ubuntu SMP Mon Apr 12 21:46:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

```
Background process (sshuttle) exited with return code 1. Command was:
  sshuttle-telepresence -v --dns --method nat -e 'ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oConnectTimeout=5' -r telepresence@127.0.0.1:33743 --to-ns 127.0.0.1:9053 10.100.0.0/16 172.24.2.0/23

Recent output was:
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/home/kimchi/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    File "/home/kimchi/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    File "/usr/libexec/sshuttle-telepresence/__main__.py", line 79, in <module>
    File "/usr/libexec/sshuttle-telepresence/.bootstrap/pex/pex_bootstrapper.py", line 406, in bootstrap_pex
    File "/usr/libexec/sshuttle-telepresence/.bootstrap/pex/pex.py", line 497, in execute
  LookupError: unknown encoding: ascii
```

Logs:

```
Traceback (most recent call last):
  34.2  42 |   File "/home/kimchi/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
  34.2  42 |   File "/home/kimchi/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
  34.2  42 |   File "/usr/libexec/sshuttle-telepresence/__main__.py", line 79, in <module>
  34.2  42 |   File "/usr/libexec/sshuttle-telepresence/.bootstrap/pex/pex_bootstrapper.py", line 406, in bootstrap_pex
  34.2  42 |   File "/usr/libexec/sshuttle-telepresence/.bootstrap/pex/pex.py", line 497, in execute
  34.2  42 | LookupError: unknown encoding: ascii
  34.2 TEL | Wait for vpn-tcp connection: hellotelepresence-3
  34.2 TEL | [49] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-3")'
  34.2 TEL | [42] sshuttle: exit 1
  34.2 TEL | [49] exit 1 in 0.03 secs.
  34.2 TEL | [50] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-3.a.sanity.check.telepresence.io")'
  34.3 TEL | [50] captured in 0.07 secs.

```

**Comment by donnyyung** [comment]
Hey @Pavel-Durov , we've actually open-sourced a new version of Telepresence. Have you had a chance to give it a shot? You can find the docs for it here: https://www.getambassador.io/docs/telepresence/latest/quick-start/ and we're working on getting the docs on telepresence.io soon so that it's more apparent that this is the version one should try.

**Comment by Pavel-Durov** [comment]
I'll have a go 
Thanks :)

**Comment by thallgren** [comment]
Closing this in favor of v2.
