### ISSUE TITLE
telepresence --swap-deployment fails on pod init

### ISSUE THREAD

**Issue by aelath** [telepresenceio/telepresence#1729]
### What were you trying to do?

Trying to develop Spinnaker's gate application locally and run it against my development spinnaker cluster running in EKS.

### What did you expect to happen?

Successfully start a proxy pod and replace a running application pod.

### What happened instead?

Telepresence command hung for several minutes before error message and stacktrace got printed to the cli.
I was watching pods in my dev ns for the proxy pod to come online... but it looked like it error'd out on pod init while trying to pull the image. Apparently the backoff didn't help, as it couldn't succeed.
Mostly just sending this along, hoping its helpful to someone.

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--context', 'eks-dev', '--namespace', 'jacob-dev', '--swap-deployment', 'spin-gate', '--env-file', 'gate-armory.env']`
Version: `0.108`
Python version: `3.9.1 (default, Dec 10 2020, 10:36:35) 
[Clang 12.0.0 (clang-1200.0.32.27)]`
kubectl version: `Client Version: v1.19.2 // Server Version: v1.18.9-eks-d1db3c`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Darwin Jacobs-MacBook-Pro.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 65, in main
    remote_info = start_proxy(runner)
  File "/usr/local/bin/telepresence/telepresence/proxy/operation.py", line 271, in act
    wait_for_pod(runner, self.remote_info)
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 140, in wait_for_pod
    raise RuntimeError(
RuntimeError: Pod isn't starting or can't be found: {'conditions': [{'lastProbeTime': None, 'lastTransitionTime': '2021-05-13T19:11:25Z', 'message': 'containers with incomplete status: [policy-engine-install]', 'reason': 'ContainersNotInitialized', 'status': 'False', 'type': 'Initialized'}, {'lastProbeTime': None, 'lastTransitionTime': '2021-05-13T19:11:25Z', 'message': 'containers with unready status: [gate]', 'reason': 'ContainersNotReady', 'status': 'False', 'type': 'Ready'}, {'lastProbeTime': None, 'lastTransitionTime': '2021-05-13T19:11:25Z', 'message': 'containers with unready status: [gate]', 'reason': 'ContainersNotReady', 'status': 'False', 'type': 'ContainersReady'}, {'lastProbeTime': None, 'lastTransitionTime': '2021-05-13T19:11:25Z', 'status': 'True', 'type': 'PodScheduled'}], 'containerStatuses': [{'image': 'datawire/telepresence-k8s:0.108', 'imageID': '', 'lastState': {}, 'name': 'gate', 'ready': False, 'restartCount': 0, 'started': False, 'state': {'waiting': {'reason': 'PodInitializing'}}}], 'hostIP': '10.0.40.100', 'initContainerStatuses': [{'image': 'docker.io/armory/policy-engine-plugin:1.1.0-snapshot.uncommitted.add.button.entitlements.controller.3a5f780', 'imageID': '', 'lastState': {}, 'name': 'policy-engine-install', 'ready': False, 'restartCount': 0, 'state': {'waiting': {'message': 'Back-off pulling image "docker.io/armory/policy-engine-plugin:1.1.0-snapshot.uncommitted.add.button.entitlements.controller.3a5f780"', 'reason': 'ImagePullBackOff'}}}], 'phase': 'Pending', 'podIP': '10.0.44.248', 'podIPs': [{'ip': '10.0.44.248'}], 'qosClass': 'BestEffort', 'startTime': '2021-05-13T19:11:25Z'}

```

Logs:

```
ctl --context eks-dev --namespace jacob-dev get pod spin-gate-03f03ebabd3c4cd9a81fb579f18abd0b -o json
 189.2 TEL | [124] Running: sudo -n echo -n
 189.2 TEL | [124] ran in 0.03 secs.
 189.4 TEL | [123] captured in 0.96 secs.
 189.6 TEL | [125] Capturing: kubectl --context eks-dev --namespace jacob-dev get pod spin-gate-03f03ebabd3c4cd9a81fb579f18abd0b -o json
 190.5 TEL | [125] captured in 0.88 secs.
 190.7 TEL | [126] Capturing: kubectl --context eks-dev --namespace jacob-dev get pod spin-gate-03f03ebabd3c4cd9a81fb579f18abd0b -o json
 191.6 TEL | [126] captured in 0.89 secs.
 191.9 TEL | [127] Capturing: kubectl --context eks-dev --namespace jacob-dev get pod spin-gate-03f03ebabd3c4cd9a81fb579f18abd0b -o json
 192.8 TEL | [127] captured in 0.90 secs.
 193.0 TEL | [128] Capturing: kubectl --context eks-dev --namespace jacob-dev get pod spin-gate-03f03ebabd3c4cd9a81fb579f18abd0b -o json
 193.9 TEL | [128] captured in 0.89 secs.
 193.9 TEL | END SP

**Comment by aelath** [comment]
Alternating `Init:ErrImagePull` and `Init:ImagePullBackOff` being shown in the STATUS section. Makes sense that this would fail.

**Comment by donnyyung** [comment]
Hey there, I see you are using legacy Telepresence.  Have you tried giving https://www.getambassador.io/docs/telepresence/latest/quick-start/ a shot (there's also a link to the installation).

**Comment by cindymullins-dw** [comment]
V1 (legacy Telepresence) has been deprecated. You can try the latest version at our [QuickStart here](https://www.getambassador.io/docs/telepresence/latest/quick-start).
