### ISSUE TITLE
when run "telepresence", this error occurs: "KeyError: 'command'"

### ISSUE THREAD

**Issue by chenmeng1996** [telepresenceio/telepresence#1746]
### What were you trying to do?
I want to run telepresence in local macbook, and k8s cluster is in remote.

### What did you expect to happen?
Command "telepresence" can be successful.

### What happened instead?
Before this error,  there is another error. I solve this bu running command `sudo apt install socat` on the remote matchine. But the following error arise:

### Automatically included information

Command line: `['/usr/local/bin/telepresence']`
Version: `0.109`
Python version: `3.9.1 (default, Feb  3 2021, 07:04:15) 
[Clang 12.0.0 (clang-1200.0.32.29)]`
kubectl version: `Client Version: v1.19.7 // Server Version: v1.14.8-180+7b9d41a78b6862`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Darwin C02CN0UDMD6V 19.6.0 Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 81, in main
    user_process = launch(
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 111, in launch
    return launch_vpn(
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 136, in launch_vpn
    connect_sshuttle(runner, remote_info, also_proxy, ssh)
  File "/usr/local/bin/telepresence/telepresence/outbound/vpn.py", line 73, in connect_sshuttle
    ] + get_proxy_cidrs(runner, remote_info, hosts_or_ips),
  File "/usr/local/bin/telepresence/telepresence/outbound/cidr.py", line 122, in get_proxy_cidrs
    context_cache.lookup("serviceCIDRs", lambda: serviceCIDR(runner))
  File "/usr/local/bin/telepresence/telepresence/runner/cache.py", line 102, in lookup
    value = function()
  File "/usr/local/bin/telepresence/telepresence/outbound/cidr.py", line 122, in <lambda>
    context_cache.lookup("serviceCIDRs", lambda: serviceCIDR(runner))
  File "/usr/local/bin/telepresence/telepresence/outbound/cidr.py", line 237, in serviceCIDR
    serviceCIDR = cluster_serviceCIDR(runner)
  File "/usr/local/bin/telepresence/telepresence/outbound/cidr.py", line 262, in cluster_serviceCIDR
    for param in container["command"]:
KeyError: 'command'

```

Logs:

```
env.py:29(get_remote_env)
   4.5 TEL | [20] Capturing: kubectl --context jin --namespace default exec telepresence-1621849054-360103-2922-5db79c7468-2sxx7 --container telepresence-1621849054-360103-2922 -- python3 podinfo.py
   4.5  15 | Handling connection for 52307
   5.0 TEL | [20] captured in 0.50 secs.
   5.0 TEL | END SPAN remote_env.py:29(get_remote_env)    0.5s
   5.0 TEL | BEGIN SPAN mount.py:30(mount_remote_volumes)
   5.0 TEL | [21] Running: sshfs -p 52307 -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oConnectTimeout=5 telepresence@127.0.0.1:/ /tmp/tel-wvzn_6gy/fs
   5.3  15 | Handling connection for 52307
   5.8 TEL | [21] ran in 0.79 secs.
   5.8 TEL | END SPAN mount.py:30(mount_remote_volumes)    0.8s
   5.8 TEL | BEGIN SPAN vpn.py:62(connect_sshuttle)
   5.8 TEL | BEGIN SPAN cidr.py:113(get_proxy_cidrs)
   5.8 TEL | [22] Capturing: kubectl --context jin --namespace default get pods -n kube-system -o json
   6.1 TEL | [22] captured in 0.26 secs.

```

**Comment by chenmeng1996** [comment]
I can run the command `telepresence --swap-deployment hello-world --docker-run --rm -it hello-dev` successful, but command  `telepresence` is always failed.

So I try [telepresence v2](https://github.com/telepresenceio/telepresence/tree/release/v2) which is rewrite by golang. I followerd DEVELOPING.md to compile, build image and push to my docker hub. Then run command `telepresence connect`, it is successful.

**Comment by cindymullins-dw** [comment]
V1 is no longer supported.  We recommend upgrading to the [latest version](https://www.getambassador.io/docs/telepresence/latest/quick-start).
