### ISSUE TITLE
Useing openVPN and telepresencs 

### ISSUE THREAD

**Issue by arning627** [telepresenceio/telepresence#1760]
### What were you trying to do?

(please tell us)

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence']`
Version: `0.109`
Python version: `3.9.5 (default, May  4 2021, 03:36:27) 
[Clang 12.0.0 (clang-1200.0.32.29)]`
kubectl version: `Client Version: v1.19.3 // Server Version: v1.18.8-aliyun.1`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Darwin guoningdeMacBook-Pro.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 81, in main
    user_process = launch(
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 111, in launch
    return launch_vpn(
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 136, in launch_vpn
    connect_sshuttle(runner, remote_info, also_proxy, ssh)
  File "/usr/local/bin/telepresence/telepresence/outbound/vpn.py", line 110, in connect_sshuttle
    raise RuntimeError("vpn-tcp tunnel did not connect")
RuntimeError: vpn-tcp tunnel did not connect

```

Logs:

```
| c : DNS request from ('172.28.44.130', 50459) to None: 53 bytes
  42.3  11 | 2021-05-28T07:48:55+0000 [stdout#info] Result for b'hellotelepresence-11.isoftstone.com' is ['127.0.0.1']
  43.1 TEL | [43] timed out after 5.01 secs.
  43.1 TEL | [44] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-11.a.sanity.check.telepresence.io")'
  43.1  19 | c : DNS request from ('172.28.44.130', 61077) to None: 69 bytes
  43.1  11 | 2021-05-28T07:48:56+0000 [stdout#info] Sanity check: b'hellotelepresence-11.a.sanity.check.telepresence.io'
  44.1 TEL | [44] timed out after 1.01 secs.
  44.2  19 | c : DNS request from ('172.28.44.130', 61077) to None: 69 bytes
  44.2  11 | 2021-05-28T07:48:57+0000 [stdout#info] Sanity check: b'hellotelepresence-11.a.sanity.check.telepresence.io'
  44.3  19 | c : DNS request from ('172.28.44.130', 61815) to None: 53 bytes
  44.3  11 | 2021-05-28T07:48:57+0000 [stdout#info] Result for b'hellotelepresence-11.isoftstone.com' is ['127.0.0.1']

```

**Comment by thallgren** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
