### ISSUE TITLE
SSH to the cluster failed to start.

### ISSUE THREAD

**Issue by naty88** [telepresenceio/telepresence#1765]
### What were you trying to do?

I wanted to connect to Kubernetes service to start a cron job

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/bin/telepresence']`
Version: `0.109`
Python version: `3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0]`
kubectl version: `Client Version: v1.21.1 // Server Version: v1.18.9-eks-d1db3c`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Linux nataliia-XMG-CORE-REN-E21 5.8.0-53-generic #60~20.04.1-Ubuntu SMP Thu May 6 09:52:46 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 68, in main
    socks_port, ssh = do_connect(runner, remote_info)
  File "/usr/bin/telepresence/telepresence/connect/connect.py", line 117, in do_connect
    return connect(
  File "/usr/bin/telepresence/telepresence/connect/connect.py", line 70, in connect
    raise RuntimeError("SSH to the cluster failed to start. See logfile.")
RuntimeError: SSH to the cluster failed to start. See logfile.

```

Logs:

```
tTimeout=5 -q -p 40859 telepresence@127.0.0.1 /bin/true
 129.8 TEL | [130] exit 255 in 0.01 secs.
 130.0 TEL | [131] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oConnectTimeout=5 -q -p 40859 telepresence@127.0.0.1 /bin/true
 130.0 TEL | [131] exit 255 in 0.01 secs.
 130.0 TEL | SSH timed out. Pod info follows.
 130.0 TEL | [132] Running: kubectl --context production --namespace topic-clustering describe pod telepresence-1622534912-703652-19160
 131.0  15 | Forwarding from 127.0.0.1:40859 -> 8022
 131.0  15 | Forwarding from [::1]:40859 -> 8022
 134.2  14 | 2021-06-01T08:10:46+0000 [Poll#error] Failed to contact Telepresence client:
 134.2  14 | 2021-06-01T08:10:46+0000 [Poll#error] An error occurred while connecting: 99: Address not available.
 134.2  14 | 2021-06-01T08:10:46+0000 [Poll#warn] Perhaps it's time to exit?
 140.0 TEL | [132] timed out after 10.01 secs.
 141.6 TEL | [133] Running: sudo -n echo -n
 141.6 TEL | [133] ran in 0.01 secs.

```

**Comment by thallgren** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
