### ISSUE TITLE
Undefined symbol: COMP_get_type, version OPENSSL_1_1_0 in Ubuntu 20.04

### ISSUE THREAD

**Issue by lpinto-axway** [telepresenceio/telepresence#1780]
Getting this error where running telepresence 0.109 on Ubuntu 20.04.1 LTS

> Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/bin/telepresence/__main__.py", line 2, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/bin/telepresence/telepresence/main.py", line 23, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/bin/telepresence/telepresence/startup.py", line 17, in <module>
  File "/usr/lib/python3.8/ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: /usr/lib/python3.8/lib-dynload/_ssl.cpython-38-x86_64-linux-gnu.so: undefined symbol: COMP_get_type, version OPENSSL_1_1_0

**Comment by lpinto-axway** [comment]
The issue was due to a misconfigured ld library resolved by unsetting LD_LIBRARY_PATH.
