### ISSUE TITLE
telepresence failed to start

### ISSUE THREAD

**Issue by sjones-vcd** [telepresenceio/telepresence#1828]
### What were you trying to do?

(please tell us)

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/bin/telepresence', '--mount', '/tmp/coordinator', '--swap-deployment', 'vcdc-coordinator-sjones-rest-frontend:rest-frontend', '--also-proxy', '10.161.0.0/16', '--env-json', '/home/sjones/telepresence/coordinator_env.json']`
Version: `0.109`
Python version: `3.8.5 (default, May 27 2021, 13:30:53) 
[GCC 9.3.0]`
kubectl version: `Client Version: v1.21.1 // Server Version: v1.18.16`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Linux ubuntu 5.4.0-77-generic #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 65, in main
    remote_info = start_proxy(runner)
  File "/usr/bin/telepresence/telepresence/proxy/operation.py", line 271, in act
    wait_for_pod(runner, self.remote_info)
  File "/usr/bin/telepresence/telepresence/proxy/remote.py", line 140, in wait_for_pod
    raise RuntimeError(
RuntimeError: Pod isn't starting or can't be found: {'conditions': [{'lastProbeTime': None, 'lastTransitionTime': '2021-06-29T17:51:29Z', 'status': 'True', 'type': 'Initialized'}, {'lastProbeTime': None, 'lastTransitionTime': '2021-06-29T17:51:29Z', 'message': 'containers with unready status: [rest-frontend]', 'reason': 'ContainersNotReady', 'status': 'False', 'type': 'Ready'}, {'lastProbeTime': None, 'lastTransitionTime': '2021-06-29T17:51:29Z', 'message': 'containers with unready status: [rest-frontend]', 'reason': 'ContainersNotReady', 'status': 'False', 'type': 'ContainersReady'}, {'lastProbeTime': None, 'lastTransitionTime': '2021-06-29T17:51:29Z', 'status': 'True', 'type': 'PodScheduled'}], 'containerStatuses': [{'containerID': 'docker://be77d59b2c439a7ef06f8b4f452d980fe3e66aafde21a7c1ce5d6f0cf2b38596', 'image': 'vmwaresaas.jfrog.io/cds-docker/vcdc/vcdc-container-monitor:073020', 'imageID': 'docker-pullable://vmwaresaas.jfrog.io/cds-docker/vcdc/vcdc-container-monitor@sha256:021fb3fd00e9d59e64b4c3964e4451f7a25dc1056889bbcab093adde89bddd41', 'lastState': {}, 'name': 'monitor', 'ready': True, 'restartCount': 0, 'started': True, 'state': {'running': {'startedAt': '2021-06-29T17:51:31Z'}}}, {'containerID': 'docker://6b7daf344f2a4f546ef80b0176bdcfd37b0712301006da6bea75d205243dd152', 'image': 'vmwaresaas.jfrog.io/cds-docker/vcdc/ws-tcp-proxy:20210105', 'imageID': 'docker-pullable://vmwaresaas.jfrog.io/cds-docker/vcdc/ws-tcp-proxy@sha256:3064d419d251d3c93921d3d74f390a6b0d236c083e5d72218652d5f6448bf1a3', 'lastState': {}, 'name': 'nats-proxy', 'ready': True, 'restartCount': 0, 'started': True, 'state': {'running': {'startedAt': '2021-06-29T17:51:35Z'}}}, {'containerID': 'docker://72e18048c96706b4196cca0cf6ad7a98718db3fe62331f86d4b677a936349bf1', 'image': 'vmwaresaas.jfrog.io/cds-docker/datawire/telepresence-k8s:0.109', 'imageID': 'docker-pullable://vmwaresaas.jfrog.io/cds-docker/datawire/telepresence-k8s@sha256:1aedf1ba88ad958cb1d0912ce5cee6e86a98ebff87a3e4ce4d8c0c9aa6332f72', 'lastState': {}, 'name': 'rest-frontend', 'ready': False, 'restartCount': 0, 'started': False, 'state': {'terminated': {'containerID': 'docker://72e18048c96706b4196cca0cf6ad7a98718db3fe62331f86d4b677a936349bf1', 'exitCode': 1, 'finishedAt': '2021-06-29T17:51:35Z', 'message': 'Could not load host key: /etc/ssh/ssh_host_rsa_key\r\nCould not load host key: /etc/ssh/ssh_host_dsa_key\r\nCould not load host key: /etc/ssh/ssh_host_ecdsa_key\r\nCould not load host key: /etc/ssh/ssh_host_ed25519_key\r\nsshd: no hostkeys available -- exiting.\r\n', 'reason': 'Error', 'startedAt': '2021-06-29T17:51:34Z'}}}], 'hostIP': '10.30.113.110

**Comment by thallgren** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
