### ISSUE TITLE
used  vpn ,console output this

### ISSUE THREAD

**Issue by arning627** [telepresenceio/telepresence#1834]
### What were you trying to do?

(please tell us)

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence']`
Version: `0.109`
Python version: `3.9.5 (default, May  4 2021, 03:36:27) 
[Clang 12.0.0 (clang-1200.0.32.29)]`
kubectl version: `Client Version: v1.19.3 // Server Version: v1.18.8-aliyun.1`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Darwin guoningdeMacBook-Pro.local 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 81, in main
    user_process = launch(
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 111, in launch
    return launch_vpn(
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 136, in launch_vpn
    connect_sshuttle(runner, remote_info, also_proxy, ssh)
  File "/usr/local/bin/telepresence/telepresence/outbound/vpn.py", line 110, in connect_sshuttle
    raise RuntimeError("vpn-tcp tunnel did not connect")
RuntimeError: vpn-tcp tunnel did not connect

```

Logs:

```
port socket; socket.gethostbyname("hellotelepresence-8.a.sanity.check.telepresence.io")'
  51.7  31 | c : DNS request from ('172.28.45.18', 57111) to None: 68 bytes
  51.7  12 | 2021-07-02T02:25:58+0000 [stdout#info] Sanity check: b'hellotelepresence-8.a.sanity.check.telepresence.io'
  52.7 TEL | [50] timed out after 1.00 secs.
  52.7  31 | c : DNS request from ('172.28.45.18', 57111) to None: 68 bytes
  52.8  12 | 2021-07-02T02:25:59+0000 [stdout#info] Sanity check: b'hellotelepresence-8.a.sanity.check.telepresence.io'
  52.9  31 | c : DNS request from ('172.28.45.18', 49872) to None: 52 bytes
  52.9  12 | 2021-07-02T02:25:59+0000 [stdout#info] Result for b'hellotelepresence-8.isoftstone.com' is ['127.0.0.1']
  53.2  31 | c : Accept TCP: 10.20.82.193:65191 -> 192.168.1.9:8848.
  53.2  31 | c : Accept TCP: 10.20.82.193:65193 -> 192.168.8.118:8848.
  53.2  31 | c : Accept TCP: 10.20.82.193:65194 -> 192.168.1.3:8848.
  53.9  31 | c : Accept TCP: 10.20.82.193:65195 -> 192.168.8.118:8848.

```

**Comment by thallgren** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
