### ISSUE TITLE
Error while running telepresence 

### ISSUE THREAD

**Issue by mbaliuk-lohika-tix** [telepresenceio/telepresence#1838]
### What were you trying to do?

(please tell us)

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--swap-deployment', 'orchestration', '--namespace', 'ng-orchestration-pr-414-2', '--env-json', 'ng-orchestration-pr-414-2.json']`
Version: `0.109`
Python version: `3.8.2 (default, Dec 21 2020, 15:06:04) 
[Clang 12.0.0 (clang-1200.0.32.29)]`
kubectl version: `Client Version: v1.21.1 // Server Version: v1.18.10`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Darwin odl2103029 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 65, in main
    remote_info = start_proxy(runner)
  File "/usr/local/bin/telepresence/telepresence/proxy/operation.py", line 271, in act
    wait_for_pod(runner, self.remote_info)
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 140, in wait_for_pod
    raise RuntimeError(
RuntimeError: Pod isn't starting or can't be found: {'conditions': [{'lastProbeTime': None, 'lastTransitionTime': '2021-07-05T11:42:53Z', 'message': "0/37 nodes are available: 29 Insufficient cpu, 4 node(s) didn't match node selector, 8 Too many pods.", 'reason': 'Unschedulable', 'status': 'False', 'type': 'PodScheduled'}], 'phase': 'Pending', 'qosClass': 'Burstable'}

```

Logs:

```
d7c19530d1 -o json
 188.2 TEL | [212] captured in 0.31 secs.
 188.4 TEL | [213] Capturing: kubectl --context corvette --namespace ng-orchestration-pr-414-2 get pod orchestration-422407a6ac574019bdd476d7c19530d1 -o json
 188.6 TEL | [214] Running: sudo -n echo -n
 188.6 TEL | [214] ran in 0.04 secs.
 188.7 TEL | [213] captured in 0.30 secs.
 189.0 TEL | [215] Capturing: kubectl --context corvette --namespace ng-orchestration-pr-414-2 get pod orchestration-422407a6ac574019bdd476d7c19530d1 -o json
 189.4 TEL | [215] captured in 0.44 secs.
 189.7 TEL | [216] Capturing: kubectl --context corvette --namespace ng-orchestration-pr-414-2 get pod orchestration-422407a6ac574019bdd476d7c19530d1 -o json
 190.0 TEL | [216] captured in 0.31 secs.
 190.2 TEL | [217] Capturing: kubectl --context corvette --namespace ng-orchestration-pr-414-2 get pod orchestration-422407a6ac574019bdd476d7c19530d1 -o json
 190.6 TEL | [217] captured in 0.35 secs.
 190.6 TEL | END SPAN remote.py:109(wait_for_pod)  180.4s

```

**Comment by cindymullins-dw** [comment]
Telepresence v1 V1 is no longer supported. The latest version is available [here](https://www.getambassador.io/docs/telepresence/latest/install). Please let us know if issues persist on newer versions.
