### ISSUE TITLE
bug faced while trying to connect to local cluster

### ISSUE THREAD

**Issue by archita-sarda** [telepresenceio/telepresence#1868]
### What were you trying to do?

(please tell us)

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence']`
Version: `0.104`
Python version: `3.7.7 (default, Mar 10 2020, 15:43:27) 
[Clang 10.0.0 (clang-1000.11.45.5)]`
kubectl version: `Client Version: v1.18.1 // Server Version: v1.15.12`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin CLPT0996 17.7.0 Darwin Kernel Version 17.7.0: Wed Apr 24 21:17:24 PDT 2019; root:xnu-4570.71.45~1/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 65, in main
    remote_info = start_proxy(runner)
  File "/usr/local/bin/telepresence/telepresence/proxy/__init__.py", line 138, in start_proxy
    run_id=run_id,
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 144, in get_remote_info
    runner, deployment_name, deployment_type, run_id=run_id
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 91, in get_deployment_json
    return json.loads(output)["items"][0]
IndexError: list index out of range

```

Logs:

```
 --ignore-not-found svc,deploy --selector=telepresence=87d6ce72692f47d599638eae00d19910
   2.3   9 | No resources found
   2.3 TEL | [9] ran in 0.16 secs.
   2.3 TEL | [10] Running: kubectl --context kind-cc-local --namespace default run --restart=Always --limits=cpu=1000m,memory=256Mi --requests=cpu=25m,memory=64Mi telepresence-1626293141-8591301-35147 --image=datawire/telepresence-k8s:0.104 --labels=telepresence=87d6ce72692f47d599638eae00d19910
   2.4  10 | pod/telepresence-1626293141-8591301-35147 created
   2.4 TEL | [10] ran in 0.14 secs.
   2.4 TEL | END SPAN deployment.py:108(create_new_deployment)    0.3s
   2.4 TEL | BEGIN SPAN remote.py:142(get_remote_info)
   2.4 TEL | BEGIN SPAN remote.py:75(get_deployment_json)
   2.4 TEL | [11] Capturing: kubectl --context kind-cc-local --namespace default get deployment -o json --selector=telepresence=87d6ce72692f47d599638eae00d19910
   2.5 TEL | [11] captured in 0.12 secs.
   2.5 TEL | END SPAN remote.py:75(get_deployment_json)    0.1s

```

**Comment by cindymullins-dw** [comment]
V1 of Telepresence is no longer supported.  The latest version is available [here](https://www.getambassador.io/docs/telepresence/latest/install).  Please let us know if issues persist on newer versions.
