### ISSUE TITLE
Crash occurred in v2.3.7 telepresence

### ISSUE THREAD

**Issue by vsimon** [telepresenceio/telepresence#1919]
on Big Sur. Noticing I’m no longer able to quit with v2.3.7. It was succeeding on v2.3.4. No sudo.

```
❯ telepresence quit
Telepresence Root Daemon is already stopped
telepresence: error: connection error: desc = "transport: error while dialing: dial unix /tmp/telepresence-connector.socket: connect: connection refused"; this usually means that the process has terminated ungracefully

❯ telepresence uninstall -a
Launching Telepresence Root Daemon
Telepresence Root Daemon quitting... done
telepresence: error: connection error: desc = "transport: error while dialing: dial unix /tmp/telepresence-connector.socket: connect: connection refused"; this usually means that the process has terminated ungracefully
~
❯ telepresence connect
Launching Telepresence Root Daemon
Telepresence Root Daemon quitting... done
telepresence: error: connection error: desc = "transport: error while dialing: dial unix /tmp/telepresence-connector.socket: connect: connection refused"; this usually means that the process has terminated ungracefully
```

Not being able to quit, feels like a regression. In v2.3.4 it seemed quit worked more reliably.

The last interesting thing in connector.log is

```
2021/07/24 08:03:55.5777 error   connector/server-grpc/conn=2/manager->daemon : goroutine "/connector/server-grpc/conn=2/manager->daemon" exited with error: rpc error: code = Unavailable desc = error reading from server: EOF
2021/07/24 08:03:55.5777 error   connector/background-manager/agent-watcher : manager.WatchAgents recv: rpc error: code = Unavailable desc = error reading from server: EOF (from pkg/client/connector/userd_trafficmgr/agents.go:65)
2021/07/24 08:03:55.5780 info    connector/server-grpc/conn=2:shutdown_logger : shutting down (gracefully)...
2021/07/24 08:03:55.5777 error   connector/background-manager/intercept-port-forward : reading port-forwards from manager: manager.WatchIntercepts recv: rpc error: code = Unavailable desc = error reading from server: EOF (from pkg/client/connector/userd_trafficmgr/intercept.go:192)
2021/07/24 08:03:55.5777 error   connector/background-manager/remain : rpc error: code = Unavailable desc = error reading from server: EOF (from pkg/client/connector/userd_trafficmgr/traffic_manager.go:394)
2021/07/24 08:03:55.5777 debug   connector/background-manager : k8sPortForwardDialer.Dial(ctx, "svc/traffic-manager.ambassador:8081") (from pkg/dnet/kpfconn.go:82)
2021/07/24 08:03:55.5782 debug   connector/background-manager : kates.Get(svc traffic-manager.ambassador) (from pkg/dnet/kpfconn.go:123)
panic: the server doesn't have a resource type "svc"
goroutine 1114 [running]:
github.com/datawire/ambassador/pkg/kates.(*Client).cliForResource(0xc000203b60, 0xc00087c078, 0x1, 0x27c34c0)
        github.com/datawire/ambassador@v1.13.7-0.20210527054604-663dfb393e59/pkg/kates/client.go:581 +0x25c
github.com/datawire/ambassador/pkg/kates.(*Client).Get.func1(0xc000203b60, 0xc00087c078, 0x2a38a20, 0xc000626a80, 0xc00025e1a8, 0xc00025e1b8, 0x0, 0x0)
        github.com/datawire/ambassador@v1.13.7-0.20210527054604-663dfb393e59/pkg/kates/client.go:702 +0xa5
github.com/datawire/ambassador/pkg/kates.(*Client).Get(0xc000203b60, 0x2a38a20, 0xc000626a80, 0x27c34c0, 0xc00087c068, 0x27c34c0, 0xc00087c068, 0x0, 0xc000a85180)
        github.com/datawire/ambassador@v1.13.7-0.20210527054604-663dfb393e59/pkg/kates/client.go:712 +0xd5
github.com/telepresenceio/telepresence/v2/pkg/dnet.(*k8sPortForwardDialer).resolve(0xc000a379e0, 0x2a38a20, 0xc000626a80, 0xc00092e570, 0x23, 0x1, 0x1, 0xc000d13030, 0x635a6b5e)
        github.com/telepresenceio/telepresence/v2/pkg/dnet/kpfconn.go:124 +0x518
github.com/telepresenceio/telepresence/v2/pkg/dnet.(*k8sPortForwardDialer).Dial(0xc000a379e0, 0x2a38a20, 0xc000626a80, 0xc00092e570, 0x23, 0x1014d1b, 0xc000a42eb8, 0xc000d13148, 0x10)
        github.com/telepresenceio/telepresence/v2/pkg/dnet/kpfconn.go:84 +0xe5
google.golang.org/grpc/internal/transport.dial(0x2a38a20, 0xc000626a80, 0xc000a62000, 0xc00092e570, 0x23, 0xc00092e570, 0x23, 0x0, 0x0, 0x0, ...)
        google.golang.org/grpc@v1.38.0/internal/transport/http2_client.go:156 +0x11f
google.golang.org/grpc/internal/transport.newHTTP2Client(0x2a38a20, 0xc000626a80, 0x2a389a0, 0xc000a8c3c0, 0xc00092e570, 0x23, 0xc00092e570, 0x23, 0x0, 0x0, ...)
        google.golang.org/grpc@v1.38.0/internal/transport/http2_client.go:195 +0x15e
google.golang.org/grpc/internal/transport.NewClientTransport(...)
        google.golang.org/grpc@v1.38.0/internal/transport/transport.go:580
google.golang.org/grpc.(*addrConn).createTransport(0xc000fc8580, 0xc00092e570, 0x23, 0xc00092e570, 0x23, 0x0, 0x0, 0x0, 0x0, 0x27e699c, ...)
        google.golang.org/grpc@v1.38.0/clientconn.go:1323 +0x40f
google.golang.org/grpc.(*addrConn).tryAllAddrs(0xc000fc8580, 0xc0010a68c0, 0x1, 0x1, 0xc03728dbe26e83a0, 0x1c470958eaf9, 0x35ffd20, 0x2a52ee0, 0xc0008945a0, 0x0, ...)
        google.golang.org/grpc@v1.38.0/clientconn.go:1253 +0x38d
google.golang.org/grpc.(*addrConn).resetTransport(0xc000fc8580)
        google.golang.org/grpc@v1.38.0/clientconn.go:1168 +0x23f
created by google.golang.org/grpc.(*addrConn).connect
        google.golang.org/grpc@v1.38.0/clientconn.go:844 +0x12a
```

*WORKAROUND*: 

`rm /tmp/telepresence-connector.socket`

**Comment by thallgren** [comment]
The crash seems to indicate some kind of permission problem when reading from the cluster. There is indeed a resource type "svc", but you're not allowed to read it. Perhaps this [StackOverflow issue](https://stackoverflow.com/questions/51308341/error-the-server-doesnt-have-a-resource-type-svc) can be helpful to find the root problem.

That said, `telepresence` should not crash with a panic when this happens.

**Comment by thallgren** [comment]
I created https://github.com/emissary-ingress/emissary/issues/3634 for the panic.

**Comment by vsimon** [comment]
> There is indeed a resource type "svc", but you're not allowed to read it.

I don't think this was/is a very deterministic error from my perspective. The user in kubecontext had the 'cluster-admin' role so it should have been permissive. TP was connected for an extended period of time over 8+ hours, when I returned, this error was in the connector logs and could not quit/connect anymore.

After deleting the socket file, I resumed being connected and it's working fine for the time being. 

Thanks for addressing the crash in the event the resource type can't be read in any case.

**Comment by vsimon** [comment]
Second occurrence. Note there is also an error `AssumeRole operation: Signature expired`. I am assuming a role to access the cluster, the session I believe expires every 12 hours.

```
2021/07/26 02:05:37.3960 error   connector/server-grpc/conn=2/manager->daemon : goroutine "/connector/server-grpc/conn=2/manager->daemon" exited with error: rpc error: code = Unavailable desc = error reading from server: EOF
2021/07/26 02:05:37.3959 debug   connector/background-manager : k8sPortForwardDialer.Dial(ctx, "svc/traffic-manager.ambassador:8081") (from pkg/dnet/kpfconn.go:82)
2021/07/26 02:05:37.3960 error   connector/background-manager/intercept-port-forward : reading port-forwards from manager: manager.WatchIntercepts recv: rpc error: code = Unavailable desc = error reading from server: EOF (from pkg/client/connector/userd_trafficmgr/intercept.go:192)
2021/07/26 02:05:37.3959 error   connector/background-manager/remain : rpc error: code = Unavailable desc = error reading from server: EOF (from pkg/client/connector/userd_trafficmgr/traffic_manager.go:394)
2021/07/26 02:05:37.3960 error   connector/background-manager/agent-watcher : manager.WatchAgents recv: rpc error: code = Unavailable desc = error reading from server: EOF (from pkg/client/connector/userd_trafficmgr/agents.go:65)
2021/07/26 02:05:37.3963 info    connector/server-grpc/conn=2:shutdown_logger : shutting down (gracefully)...
2021/07/26 02:05:37.3964 debug   connector/background-manager : kates.Get(svc traffic-manager.ambassador) (from pkg/dnet/kpfconn.go:123)
2021/07/26 02:35:34.8796 error   connector/server-grpc/conn=2/daemon->manager : goroutine "/connector/server-grpc/conn=2/daemon->manager" exited with error: EOF
2021/07/26 02:35:34.8797 info    connector/server-grpc/conn=2:shutdown_status :   final goroutine statuses:
2021/07/26 02:35:34.8798 info    connector/server-grpc/conn=2:shutdown_status :     /connector/server-grpc/conn=2/daemon->manager: exited with error
2021/07/26 02:35:34.8798 info    connector/server-grpc/conn=2:shutdown_status :     /connector/server-grpc/conn=2/manager->daemon: exited with error

An error occurred (SignatureDoesNotMatch) when calling the AssumeRole operation: Signature expired: 20210726T090537Z is now earlier than 20210726T092035Z (20210726T093535Z - 15 min.)
panic: the server doesn't have a resource type "svc"

goroutine 1269 [running]:
github.com/datawire/ambassador/pkg/kates.(*Client).cliForResource(0xc0002d5320, 0xc00051c218, 0x1, 0x27c34c0)
        github.com/datawire/ambassador@v1.13.7-0.20210527054604-663dfb393e59/pkg/kates/client.go:581 +0x25c
github.com/datawire/ambassador/pkg/kates.(*Client).Get.func1(0xc0002d5320, 0xc00051c218, 0x2a38a20, 0xc00026f620, 0xc0005f81a8, 0xc0005f81b8, 0x0, 0x0)
        github.com/datawire/ambassador@v1.13.7-0.20210527054604-663dfb393e59/pkg/kates/client.go:702 +0xa5
github.com/datawire/ambassador/pkg/kates.(*Client).Get(0xc0002d5320, 0x2a38a20, 0xc00026f620, 0x27c34c0, 0xc00051c210, 0x27c34c0, 0xc00051c210, 0x0, 0x0)
        github.com/datawire/ambassador@v1.13.7-0.20210527054604-663dfb393e59/pkg/kates/client.go:712 +0xd5
github.com/telepresenceio/telepresence/v2/pkg/dnet.(*k8sPortForwardDialer).resolve(0xc00069d560, 0x2a38a20, 0xc00026f620, 0xc0000496b0, 0x23, 0x1, 0x1, 0x24dcfe0, 0x7)
        github.com/telepresenceio/telepresence/v2/pkg/dnet/kpfconn.go:124 +0x518
github.com/telepresenceio/telepresence/v2/pkg/dnet.(*k8sPortForwardDialer).Dial(0xc00069d560, 0x2a38a20, 0xc00026f620, 0xc0000496b0, 0x23, 0x1014d1b, 0xc000b919f8, 0xc0006ab148, 0x10)
        github.com/telepresenceio/telepresence/v2/pkg/dnet/kpfconn.go:84 +0xe5
google.golang.org/grpc/internal/transport.dial(0x2a38a20, 0xc00026f620, 0xc0005edb10, 0xc0000496b0, 0x23, 0xc0000496b0, 0x23, 0x0, 0x0, 0x0, ...)
        google.golang.org/grpc@v1.38.0/internal/transport/http2_client.go:156 +0x11f
google.golang.org/grpc/internal/transport.newHTTP2Client(0x2a38a20, 0xc00026f620, 0x2a389a0, 0xc000b364c0, 0xc0000496b0, 0x23, 0xc0000496b0, 0x23, 0x0, 0x0, ...)
        google.golang.org/grpc@v1.38.0/internal/transport/http2_client.go:195 +0x15e
google.golang.org/grpc/internal/transport.NewClientTransport(...)
        google.golang.org/grpc@v1.38.0/internal/transport/transport.go:580
google.golang.org/grpc.(*addrConn).createTransport(0xc000bf9600, 0xc0000496b0, 0x23, 0xc0000496b0, 0x23, 0x0, 0x0, 0x0, 0x0, 0x27e699c, ...)
        google.golang.org/grpc@v1.38.0/clientconn.go:1323 +0x40f
google.golang.org/grpc.(*addrConn).tryAllAddrs(0xc000bf9600, 0xc0006bb0c0, 0x1, 0x1, 0xc037bc9d57973710, 0x5f6b34f9d11, 0x35ffd20, 0x2a52ee0, 0xc00000a780, 0x0, ...)
        google.golang.org/grpc@v1.38.0/clientconn.go:1253 +0x38d
google.golang.org/grpc.(*addrConn).resetTransport(0xc000bf9600)
        google.golang.org/grpc@v1.38.0/clientconn.go:1168 +0x23f
created by google.golang.org/grpc.(*addrConn).connect
        google.golang.org/grpc@v1.38.0/clientconn.go:844 +0x12a
```

**Comment by vsimon** [comment]
Another occurrence, this looks related to MFA expiring? `aws-vault: error: exec: Failed to get credentials for XXXXXXXX: AccessDenied: MultiFactorAuthentication failed with invalid MFA one time pass code.` 

```
2021/07/27 08:30:19.5346 debug   connector/background-manager : k8sPortForwardDialer.Dial(ctx, "svc/traffic-manager.ambassador:8081") (from pkg/dnet/kpfconn.go:82)
2021/07/27 08:30:19.5375 debug   connector/background-manager : kates.Get(svc traffic-manager.ambassador) (from pkg/dnet/kpfconn.go:123)
2021/07/27 08:30:19.5353 error   connector/background-manager/remain : rpc error: code = Unavailable desc = error reading from server: EOF (from pkg/client/connector/userd_trafficmgr/traffic_manager.go:394)
2021/07/27 08:30:19.5361 error   connector/server-grpc/conn=2/manager->daemon : goroutine "/connector/server-grpc/conn=2/manager->daemon" exited with error: rpc error: code = Unavailable desc = error reading from server: EOF
2021/07/27 08:30:19.5369 error   connector/background-manager/intercept-port-forward : reading port-forwards from manager: manager.WatchIntercepts recv: rpc error: code = Unavailable desc = error reading from server: EOF (from pkg/client/connector/userd_trafficmgr/intercept.go:192)
2021/07/27 08:30:19.5364 error   connector/background-manager/agent-watcher : manager.WatchAgents recv: rpc error: code = Unavailable desc = error reading from server: EOF (from pkg/client/connector/userd_trafficmgr/agents.go:65)
2021/07/27 08:30:19.5522 info    connector/server-grpc/conn=2:shutdown_logger : shutting down (gracefully)...
2021/07/27 08:30:21.2930 error   connector/server-grpc/conn=2/daemon->manager : goroutine "/connector/server-grpc/conn=2/daemon->manager" exited with error: EOF
2021/07/27 08:30:21.2936 info    connector/server-grpc/conn=2:shutdown_status :   final goroutine statuses:
2021/07/27 08:30:21.2936 info    connector/server-grpc/conn=2:shutdown_status :     /connector/server-grpc/conn=2/daemon->manager: exited with error
2021/07/27 08:30:21.2937 info    connector/server-grpc/conn=2:shutdown_status :     /connector/server-grpc/conn=2/manager->daemon: exited with error

Error when retrieving credentials from custom-process: aws-vault: error: exec: Failed to get credentials for XXXXXXXX: AccessDenied: MultiFactorAuthentication failed with invalid MFA one time pass code.
        status code: 403, request id: 90599235-d43c-4fea-a38b-c094463250f4

panic: the server doesn't have a resource type "svc"

goroutine 1203 [running]:
github.com/datawire/ambassador/pkg/kates.(*Client).cliForResource(0xc000180720, 0xc000a5e230, 0x1, 0x27c34c0)
        github.com/datawire/ambassador@v1.13.7-0.20210527054604-663dfb393e59/pkg/kates/client.go:581 +0x25c
github.com/datawire/ambassador/pkg/kates.(*Client).Get.func1(0xc000180720, 0xc000a5e230, 0x2a38a20, 0xc000c81860, 0xc000bf61a8, 0xc000bf61b8, 0x0, 0x0)
        github.com/datawire/ambassador@v1.13.7-0.20210527054604-663dfb393e59/pkg/kates/client.go:702 +0xa5
github.com/datawire/ambassador/pkg/kates.(*Client).Get(0xc000180720, 0x2a38a20, 0xc000c81860, 0x27c34c0, 0xc000a5e228, 0x27c34c0, 0xc000a5e228, 0x0, 0x0)
        github.com/datawire/ambassador@v1.13.7-0.20210527054604-663dfb393e59/pkg/kates/client.go:712 +0xd5
github.com/telepresenceio/telepresence/v2/pkg/dnet.(*k8sPortForwardDialer).resolve(0xc000181da0, 0x2a38a20, 0xc000c81860, 0xc00043a5a0, 0x23, 0x1, 0x1, 0x24dcfe0, 0x1)
        github.com/telepresenceio/telepresence/v2/pkg/dnet/kpfconn.go:124 +0x518
github.com/telepresenceio/telepresence/v2/pkg/dnet.(*k8sPortForwardDialer).Dial(0xc000181da0, 0x2a38a20, 0xc000c81860, 0xc00043a5a0, 0x23, 0x1014d1b, 0xc00076eac8, 0xc0007e3148, 0x10)
        github.com/telepresenceio/telepresence/v2/pkg/dnet/kpfconn.go:84 +0xe5
google.golang.org/grpc/internal/transport.dial(0x2a38a20, 0xc000c81860, 0xc0009d7a20, 0xc00043a5a0, 0x23, 0xc00043a5a0, 0x23, 0x0, 0x0, 0x0, ...)
        google.golang.org/grpc@v1.38.0/internal/transport/http2_client.go:156 +0x11f
google.golang.org/grpc/internal/transport.newHTTP2Client(0x2a38a20, 0xc000c81860, 0x2a389a0, 0xc0003c6e80, 0xc00043a5a0, 0x23, 0xc00043a5a0, 0x23, 0x0, 0x0, ...)
        google.golang.org/grpc@v1.38.0/internal/transport/http2_client.go:195 +0x15e
google.golang.org/grpc/internal/transport.NewClientTransport(...)
        google.golang.org/grpc@v1.38.0/internal/transport/transport.go:580
google.golang.org/grpc.(*addrConn).createTransport(0xc000156dc0, 0xc00043a5a0, 0x23, 0xc00043a5a0, 0x23, 0x0, 0x0, 0x0, 0x0, 0x27e699c, ...)
        google.golang.org/grpc@v1.38.0/clientconn.go:1323 +0x40f
google.golang.org/grpc.(*addrConn).tryAllAddrs(0xc000156dc0, 0xc00048d100, 0x1, 0x1, 0xc0382787dfdb5d70, 0x4bc1744e22b, 0x35ffd20, 0x2a52ee0, 0xc000fd23c0, 0x0, ...)
        google.golang.org/grpc@v1.38.0/clientconn.go:1253 +0x38d
google.golang.org/grpc.(*addrConn).resetTransport(0xc000156dc0)
        google.golang.org/grpc@v1.38.0/clientconn.go:1168 +0x23f
created by google.golang.org/grpc.(*addrConn).connect
        google.golang.org/grpc@v1.38.0/clientconn.go:844 +0x12a
```

**Comment by vsimon** [comment]
```
W0728 08:33:16.540031   46902 reflector.go:436] k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167: watch of *unstructured.Unstructured ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented t
he request from succeeding
2021/07/28 08:33:27.1748 error   connector/background-manager/remain : rpc error: code = NotFound desc = Session "d9dc943e-a18d-43e8-8eef-8f1f67cea009" not found (from pkg/client/connector/userd_trafficmgr/traffic_manager.go:394)
2021/07/28 08:33:27.1747 error   connector/background-manager/agent-watcher : manager.WatchAgents recv: EOF (from pkg/client/connector/userd_trafficmgr/agents.go:65)
2021/07/28 08:33:27.1748 error   connector/background-manager/intercept-port-forward : reading port-forwards from manager: manager.WatchIntercepts recv: EOF (from pkg/client/connector/userd_trafficmgr/intercept.go:192)
2021/07/28 08:33:27.8885 error   connector/background-manager/remain : rpc error: code = NotFound desc = Session "d9dc943e-a18d-43e8-8eef-8f1f67cea009" not found (from pkg/client/connector/userd_trafficmgr/traffic_manager.go:394)
2021/07/28 08:33:27.8885 error   connector/background-manager/intercept-port-forward : reading port-forwards from manager: manager.WatchIntercepts recv: EOF (from pkg/client/connector/userd_trafficmgr/intercept.go:192)
2021/07/28 08:33:27.8885 error   connector/background-manager/agent-watcher : manager.WatchAgents recv: EOF (from pkg/client/connector/userd_trafficmgr/agents.go:65)
2021/07/28 08:34:08.9491 error   connector/background-manager/remain : rpc error: code = NotFound desc = Session "d9dc943e-a18d-43e8-8eef-8f1f67cea009" not found (from pkg/client/connector/userd_trafficmgr/traffic_manager.go:394)
2021/07/28 08:34:08.9491 error   connector/background-manager/agent-watcher : manager.WatchAgents recv: EOF (from pkg/client/connector/userd_trafficmgr/agents.go:65)
2021/07/28 08:34:08.9491 error   connector/background-manager/intercept-port-forward : reading port-forwards from manager: manager.WatchIntercepts recv: EOF (from pkg/client/connector/userd_trafficmgr/intercept.go:192)
2021/07/28 08:34:09.0342 error   connector/background-manager/remain : rpc error: code = NotFound desc = Session "d9dc943e-a18d-43e8-8eef-8f1f67cea009" not found (from pkg/client/connector/userd_trafficmgr/traffic_manager.go:394)
2021/07/28 08:34:09.4418 error   connector/background-manager/agent-watcher : manager.WatchAgents recv: EOF (from pkg/client/connector/userd_trafficmgr/agents.go:65)
2021/07/28 08:34:09.4419 error   connector/background-manager/intercept-port-forward : reading port-forwards from manager: manager.WatchIntercepts recv: EOF (from pkg/client/connector/userd_trafficmgr/intercept.go:192)
2021/07/28 08:34:10.3744 error   connector/background-manager/agent-watcher : manager.WatchAgents recv: EOF (from pkg/client/connector/userd_trafficmgr/agents.go:65)
2021/07/28 08:34:10.3744 error   connector/background-manager/intercept-port-forward : reading port-forwards from manager: manager.WatchIntercepts recv: EOF (from pkg/client/connector/userd_trafficmgr/intercept.go:192)
2021/07/28 08:34:11.7695 error   connector/background-manager/remain : rpc error: code = NotFound desc = Session "d9dc943e-a18d-43e8-8eef-8f1f67cea009" not found (from pkg/client/connector/userd_trafficmgr/traffic_manager.go:394)
2021/07/28 08:34:12.2022 error   connector/background-manager/intercept-port-forward : reading port-forwards from manager: manager.WatchIntercepts recv: EOF (from pkg/client/connector/userd_trafficmgr/intercept.go:192)
2021/07/28 08:34:12.2022 error   connector/background-manager/agent-watcher : manager.WatchAgents recv: EOF (from pkg/client/connector/userd_trafficmgr/agents.go:65)
2021/07/28 08:34:15.3434 error   connector/background-manager/intercept-port-forward : reading port-forwards from manager: manager.WatchIntercepts recv: EOF (from pkg/client/connector/userd_trafficmgr/intercept.go:192)
2021/07/28 08:34:15.3434 error   connector/background-manager/agent-watcher : manager.WatchAgents recv: EOF (from pkg/client/connector/userd_trafficmgr/agents.go:65)
...
2021/07/28 09:12:25.8209 error   connector/background-manager/intercept-port-forward : reading port-forwards from manager: manager.WatchIntercepts recv: EOF (from pkg/client/connector/userd_trafficmgr/intercept.go:192)
2021/07/28 09:12:27.2557 error   connector/background-manager/remain : rpc error: code = NotFound desc = Session "d9dc943e-a18d-43e8-8eef-8f1f67cea009" not found (from pkg/client/connector/userd_trafficmgr/traffic_manager.go:394)
2021/07/28 10:12:32.1171 error   connector/background-manager/remain : rpc error: code = Unavailable desc = error reading from server: EOF (from pkg/client/connector/userd_trafficmgr/traffic_manager.go:394)
2021/07/28 10:12:32.1170 debug   connector/background-manager : k8sPortForwardDialer.Dial(ctx, "svc/traffic-manager.ambassador:8081") (from pkg/dnet/kpfconn.go:82)
2021/07/28 10:12:32.1170 error   connector/background-manager/agent-watcher : manager.WatchAgents recv: rpc error: code = Unavailable desc = error reading from server: EOF (from pkg/client/connector/userd_trafficmgr/agents.go:65)
2021/07/28 10:12:32.1184 debug   connector/background-manager : kates.Get(svc traffic-manager.ambassador) (from pkg/dnet/kpfconn.go:123)
2021/07/28 10:12:32.1171 error   connector/background-manager/intercept-port-forward : reading port-forwards from manager: manager.WatchIntercepts recv: rpc error: code = Unavailable desc = error reading from server: EOF (from pkg/client/connector/userd_trafficmgr/intercept.go:192)
2021/07/28 10:12:32.1170 error   connector/server-grpc/conn=2/manager->daemon : goroutine "/connector/server-grpc/conn=2/manager->daemon" exited with error: rpc error: code = Unavailable desc = error reading from server: EOF
2021/07/28 10:12:32.1186 info    connector/server-grpc/conn=2:shutdown_logger : shutting down (gracefully)...
W0728 10:13:04.120717   46902 transport.go:260] Unable to cancel request for *exec.roundTripper
2021/07/28 15:46:21.9076 error   connector/server-grpc/conn=2/daemon->manager : goroutine "/connector/server-grpc/conn=2/daemon->manager" exited with error: EOF
2021/07/28 15:46:21.9083 info    connector/server-grpc/conn=2:shutdown_status :   final goroutine statuses:
2021/07/28 15:46:21.9084 info    connector/server-grpc/conn=2:shutdown_status :     /connector/server-grpc/conn=2/daemon->manager: exited with error
2021/07/28 15:46:21.9084 info    connector/server-grpc/conn=2:shutdown_status :     /connector/server-grpc/conn=2/manager->daemon: exited with error
panic: the server doesn't have a resource type "svc"

goroutine 683 [running]:
github.com/datawire/ambassador/pkg/kates.(*Client).cliForResource(0xc0003dfd40, 0xc000528300, 0x1, 0x27c34c0)
        github.com/datawire/ambassador@v1.13.7-0.20210527054604-663dfb393e59/pkg/kates/client.go:581 +0x25c
github.com/datawire/ambassador/pkg/kates.(*Client).Get.func1(0xc0003dfd40, 0xc000528300, 0x2a38a20, 0xc0006d3920, 0xc0009281a8, 0xc0009281b8, 0x0, 0x0)
        github.com/datawire/ambassador@v1.13.7-0.20210527054604-663dfb393e59/pkg/kates/client.go:702 +0xa5
github.com/datawire/ambassador/pkg/kates.(*Client).Get(0xc0003dfd40, 0x2a38a20, 0xc0006d3920, 0x27c34c0, 0xc00000e008, 0x27c34c0, 0xc00000e008, 0x0, 0x0)
        github.com/datawire/ambassador@v1.13.7-0.20210527054604-663dfb393e59/pkg/kates/client.go:712 +0xd5
github.com/telepresenceio/telepresence/v2/pkg/dnet.(*k8sPortForwardDialer).resolve(0xc000d2b4a0, 0x2a38a20, 0xc0006d3920, 0xc0008d0780, 0x23, 0x1, 0x1, 0xc0000343e0, 0x20)
        github.com/telepresenceio/telepresence/v2/pkg/dnet/kpfconn.go:124 +0x518
github.com/telepresenceio/telepresence/v2/pkg/dnet.(*k8sPortForwardDialer).Dial(0xc000d2b4a0, 0x2a38a20, 0xc0006d3920, 0xc0008d0780, 0x23, 0x1014d1b, 0xc0007a8f48, 0xc000937148, 0x10)
        github.com/telepresenceio/telepresence/v2/pkg/dnet/kpfconn.go:84 +0xe5
google.golang.org/grpc/internal/transport.dial(0x2a38a20, 0xc0006d3920, 0xc0009b02d0, 0xc0008d0780, 0x23, 0xc0008d0780, 0x23, 0x0, 0x0, 0x0, ...)
        google.golang.org/grpc@v1.38.0/internal/transport/http2_client.go:156 +0x11f
google.golang.org/grpc/internal/transport.newHTTP2Client(0x2a38a20, 0xc0006d3920, 0x2a389a0, 0xc000790800, 0xc0008d0780, 0x23, 0xc0008d0780, 0x23, 0x0, 0x0, ...)
        google.golang.org/grpc@v1.38.0/internal/transport/http2_client.go:195 +0x15e
google.golang.org/grpc/internal/transport.NewClientTransport(...)
        google.golang.org/grpc@v1.38.0/internal/transport/transport.go:580
google.golang.org/grpc.(*addrConn).createTransport(0xc000e7e580, 0xc0008d0780, 0x23, 0xc0008d0780, 0x23, 0x0, 0x0, 0x0, 0x0, 0x27e699c, ...)
        google.golang.org/grpc@v1.38.0/clientconn.go:1323 +0x40f
google.golang.org/grpc.(*addrConn).tryAllAddrs(0xc000e7e580, 0xc000c8f480, 0x1, 0x1, 0xc03881e506f6fd50, 0x21298339efd6, 0x35ffd20, 0x2a52ee0, 0xc00000a960, 0x0, ...)
        google.golang.org/grpc@v1.38.0/clientconn.go:1253 +0x38d
google.golang.org/grpc.(*addrConn).resetTransport(0xc000e7e580)
        google.golang.org/grpc@v1.38.0/clientconn.go:1168 +0x23f
created by google.golang.org/grpc.(*addrConn).connect
        google.golang.org/grpc@v1.38.0/clientconn.go:844 +0x12a
```

**Comment by cindymullins-dw** [comment]
Telepresence quit issue is resolved.  The intercept should also persist on newer versions such that it will recognize the existing connection even after periods of inactivity.

**Comment by arvinmoj** [comment]
You can solve the problem by changing and executing these commands:

-Reconnect telepresence
`telepresence quit`

-Use the your kube config 
`export KUBECONFIG=/Users/<user>/.kube/<config>`

-Connect telepresence
`telepresence connect --context <context-name> --namespace <app-namespcae>`
