### ISSUE TITLE
Issue when running telepresense

### ISSUE THREAD

**Issue by Abhijit070590** [telepresenceio/telepresence#2150]
### What were you trying to do?

(please tell us)

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--namespace', 'mercari-admin-mod-jp-dev', '--new-deployment', 'abhijit-local', '--run-shell']`
Version: `0.109`
Python version: `3.9.6 (default, Jun 29 2021, 05:25:02) 
[Clang 12.0.5 (clang-1205.0.22.9)]`
kubectl version: `Client Version: v1.19.7 // Server Version: v1.19.13-gke.1200`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Darwin C02FD35NMD6T 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 81, in main
    user_process = launch(
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 111, in launch
    return launch_vpn(
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 136, in launch_vpn
    connect_sshuttle(runner, remote_info, also_proxy, ssh)
  File "/usr/local/bin/telepresence/telepresence/outbound/vpn.py", line 110, in connect_sshuttle
    raise RuntimeError("vpn-tcp tunnel did not connect")
RuntimeError: vpn-tcp tunnel did not connect

```

Logs:

```
: DNS request from ('172.31.192.54', 49168) to None: 69 bytes
  70.2  14 | 2021-10-12T05:54:59+0000 [stdout#info] Sanity check: b'hellotelepresence-10.a.sanity.check.telepresence.io'
  70.3  32 | c : DNS request from ('172.31.192.54', 53562) to None: 46 bytes
  70.4  14 | 2021-10-12T05:55:00+0000 [stdout#info] Result for b'hellotelepresence-10.openvpn' is ['127.0.0.1']
  70.7  32 | c : DNS request from ('172.31.192.54', 54331) to None: 38 bytes
  70.7  32 | c : DNS request from ('172.31.192.54', 55859) to None: 28 bytes
  70.8  14 | 2021-10-12T05:55:00+0000 [stdout#info] A query: b'beacons.gcp.gvt2.com'
  70.8  14 | 2021-10-12T05:55:00+0000 [stdout#info] A query: b'google.com'
  70.9  14 | 2021-10-12T05:55:00+0000 [stdout#info] Result for b'google.com' is ['172.217.31.142']
  70.9 TEL | (proxy checking local liveness)
  70.9  14 | 2021-10-12T05:55:00+0000 [stdout#info] Result for b'beacons.gcp.gvt2.com' is ['172.217.31.163']
  71.1  14 | 2021-10-12T05:55:00+0000 [Poll#info] Checkpoint

```

**Comment by cindymullins-dw** [comment]
V1 has been deprecated.  Please let us know if you encounter issues on more recent v2 versions.
