### ISSUE TITLE
Telepresence is blocking private network requests

### ISSUE THREAD

**Issue by jiezhang0917** [telepresenceio/telepresence#2201]
**Describe the bug**
2 days ago I did a telepresence intercept and left it there. Today when I try to call a private url with vpn connected, it ended up with timeout error.

**To Reproduce**
This issue happend to me and my colleague several times. It's hard to say which way would trigger it.
Possible steps to reproduce the behavior:
1. Intercept a service with telepresence.
2. Leave it there for one day, try to call a private url and see what you get.
3. Delete the container that's used for the intercept. And wait for another day.
4. Try to call a url in the private network again.
5. See error

**Expected behavior**
At least tell us what's happening with a warning or notice. So we know what to do.

**Versions (please complete the following information):**
 - Client: v2.4.5 (api v3) Root Daemon: v2.4.5 (api v3)
 - Macos Bigsur
 - EKS

**Additional context**
When check the daemon log, I saw 
```
2021-11-04 06:33:22.0201 error   daemon/server-router/MGR stream : goroutine "/daemon/server-router/MGR stream" exited with error: read from MuxTunnel failed: rpc error: code = Unavailable desc = error reading from server: EOF
2021-11-04 06:33:22.0206 info    daemon/server-router:shutdown_logger : shutting down (gracefully)...
2021-11-04 12:33:28.3789 error   daemon/server-router/TUN reader : failed to send control packet: EOF
2021-11-04 12:33:34.4088 error   daemon/server-router/TUN reader : failed to send control packet: EOF
2021-11-04 12:34:30.6473 error   daemon/server-router/TUN reader : failed to send control packet: EOF
2021-11-04 12:34:38.6823 error   daemon/server-router/TUN reader : failed to send control packet: EOF
...
```
And in the connector log, I saw
```
2021-11-03 17:52:32.2199 debug   connector/background-manager/intercept-port-forward : search paths posted successfully
2021-11-03 19:32:10.0606 debug   connector/background-manager : k8sPortForwardDialer.Dial(ctx, "svc/traffic-manager.ambassador:8081")
2021-11-03 19:32:10.0606 error   connector/background-manager/remain : rpc error: code = Unavailable desc = error reading from server: EOF
2021-11-03 19:32:10.0606 error   connector/background-manager/agent-watcher : manager.WatchAgents recv: rpc error: code = Unavailable desc = error reading from server: EOF
2021-11-03 19:32:10.0606 error   connector/background-manager/intercept-port-forward : reading port-forwards from manager: manager.WatchIntercepts recv: rpc error: code = Unavailable desc = error reading from server: EOF
2021-11-03 19:32:10.0606 error   connector/server-grpc/conn=2/manager->daemon : goroutine "/connector/server-grpc/conn=2/manager->daemon" exited with error: rpc error: code = Unavailable desc = error reading from server: EOF
2021-11-03 19:32:10.0607 debug   connector/background-manager : kates.Get(svc traffic-manager.ambassador)
2021-11-03 19:32:10.0609 info    connector/server-grpc/conn=2:shutdown_logger : shutting down (gracefully)...
2021-11-03 19:32:12.2550 debug   connector/background-manager : k8sPortForwardDialer.dial(ctx, traffic-manager-5f7984b44c-vtpm9.ambassador, 8081)
2021-11-03 19:32:12.2551 debug   connector/background-manager : k8sPortForwardDialer.spdyDial(ctx, Pod./traffic-manager-5f7984b44c-vtpm9.ambassador)
2021-11-03 19:32:12.6060 error   connector/background-manager/intercept-port-forward : reading port-forwards from manager: EOF
2021-11-03 19:32:12.8496 error   connector/background-manager/intercept-port-forward : reading port-forwards from manager: EOF
2021-11-04 06:33:19.5182 debug   connector/background-manager : k8sPortForwardDialer.Dial(ctx, "svc/traffic-manager.ambassador:8081")
2021-11-04 06:33:19.5182 error   connector/background-manager/agent-watcher : manager.WatchAgents recv: rpc error: code = Unavailable desc = error reading from server: EOF
2021-11-04 06:33:19.5182 error   connector/background-manager/intercept-port-forward : reading port-forwards from manager: manager.WatchIntercepts recv: rpc error: code = Unavailable desc = error reading from server: EOF
2021-11-04 06:33:19.5182 error   connector/background-manager/remain : rpc error: code = Unavailable desc = error reading from server: EOF
2021-11-04 06:33:19.5192 debug   connector/background-manager : kates.Get(svc traffic-manager.ambassador)
E1104 06:33:20.592700   81604 reflector.go:138] k8s.io/client-go@v0.21.0/tools/cache/reflector.go:167: Failed to watch *unstructured.Unstructured: can't watch namespace: the server has asked for the client to provide credentials
panic: Unauthorized

goroutine 123 [running]:
github.com/datawire/ambassador/v2/pkg/kates.(*Client).cliForResource(0x90, 0xc00000e248)
	github.com/datawire/ambassador/v2@v2.0.2-rc.1.0.20210915144712-7bc28ed11dfc/pkg/kates/client.go:581 +0x1f3
github.com/datawire/ambassador/v2/pkg/kates.(*Client).Get.func1(0xc0004645a0, 0xc00000e248, {0x2d6a0d8, 0xc000464060}, 0xc000f72220, 0xc000f72238)
	github.com/datawire/ambassador/v2@v2.0.2-rc.1.0.20210915144712-7bc28ed11dfc/pkg/kates/client.go:702 +0xf3
github.com/datawire/ambassador/v2/pkg/kates.(*Client).Get(0x2d6a110, {0x2d6a0d8, 0xc000464060}, {0x2a6f420, 0xc000bcc000}, {0x2a6f420, 0xc000bcc000})
	github.com/datawire/ambassador/v2@v2.0.2-rc.1.0.20210915144712-7bc28ed11dfc/pkg/kates/client.go:712 +0xb2
github.com/telepresenceio/telepresence/v2/pkg/dnet.(*k8sPortForwardDialer).resolve(0xc00080d860, {0x2d6a0d8, 0xc000464060}, {0xc000a7f380, 0xc00102d090})
	github.com/telepresenceio/telepresence/v2/pkg/dnet/kpfconn.go:128 +0x4a5
github.com/telepresenceio/telepresence/v2/pkg/dnet.(*k8sPortForwardDialer).Dial(0xc00080d860, {0x2d6a0d8, 0xc000464060}, {0xc000a7f380, 0x23})
	github.com/telepresenceio/telepresence/v2/pkg/dnet/kpfconn.go:84 +0xae
google.golang.org/grpc/internal/transport.dial({0x2d6a0d8, 0xc000464060}, 0xc000d58260, {{0xc000a7f380, 0x23}, {0xc000a7f380, 0x23}, 0x0, 0x0, {0x0, ...}}, ...)
	google.golang.org/grpc@v1.38.0/internal/transport/http2_client.go:156 +0x1d9
google.golang.org/grpc/internal/transport.newHTTP2Client({_, _}, {_, _}, {{0xc000a7f380, 0x23}, {0xc000a7f380, 0x23}, 0x0, 0x0, ...}, ...)
	google.golang.org/grpc@v1.38.0/internal/transport/http2_client.go:195 +0x175
google.golang.org/grpc/internal/transport.NewClientTransport(...)
	google.golang.org/grpc@v1.38.0/internal/transport/transport.go:580
google.golang.org/grpc.(*addrConn).createTransport(0xc0005de2c0, {{0xc000a7f380, 0x23}, {0xc000a7f380, 0x23}, _, _, {_, _}}, {{0x2a98317, ...}, ...}, ...)
	google.golang.org/grpc@v1.38.0/clientconn.go:1323 +0x439
google.golang.org/grpc.(*addrConn).tryAllAddrs(0xc0005de2c0, {0xc00093d340, 0x1, 0x0}, {0x0, 0xc0010626a8, 0x3e42b40})
	google.golang.org/grpc@v1.38.0/clientconn.go:1253 +0x4d9
google.golang.org/grpc.(*addrConn).resetTransport(0xc0005de2c0)
	google.golang.org/grpc@v1.38.0/clientconn.go:1168 +0x265
created by google.golang.org/grpc.(*addrConn).connect
	google.golang.org/grpc@v1.38.0/clientconn.go:844 +0x147
```

The `failed to send control packet` in the daemon log just continues forever.
I was thinking maybe it's because my auth with eks was expired. So I did the auth again but nothing changed.

I know that by running `telepresence quit` the issue will go way, but we need to know why it happens and how to avoid it.

Thank you for your help!

**Comment by josecv** [comment]
hi @jiezhang0917 could you retry this with the latest version of telepresence? We've put in some fixes to make it more resilient to network interruptions that can happen when you leave an intercept open overnight
