### ISSUE TITLE
Failing test on OpenShift - envFrom support

### ISSUE THREAD

**Issue by itamarst** [telepresenceio/telepresence#248]
tests/test_run.py::NativeEndToEndTests::test_environmentvariables fails with:

```
Traceback (most recent call last):
  File "envvariables.py", line 33, in <module>
    main()
  File "envvariables.py", line 26, in main
    check_custom_env()
  File "envvariables.py", line 19, in check_custom_env
    assert os.environ["EXAMPLE_ENVFROM"] == "foobar"
  File "/home/itamarst/Datawire/telepresence/virtualenv/lib/python3.5/os.py", line 725, in __getitem__
    raise KeyError(key) from None
KeyError: 'EXAMPLE_ENVFROM'
```

**Comment by donnyyung** [comment]
While this test no longer exists for Telepresence 2, we should probably ensure our current tests do work on an open shift cluster.
