### ISSUE TITLE
Panic running `telepresence dashboard` on Windows

### ISSUE THREAD

**Issue by mausch** [telepresenceio/telepresence#2861]
`> telepresence dashboard`

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x217f86c]

goroutine 1 [running]:
github.com/telepresenceio/telepresence/v2/pkg/client/cli/cliutil.(*UserDaemon).Quit(0x30485a8?, {0x30485a8?, 0xc00084ac60?}, 0x2a?, {0x0?, 0x1?, 0x1?})
        <autogenerated>:1 +0x2c
github.com/telepresenceio/telepresence/v2/pkg/client/cli/cliutil.installTelepresencePro({0x30485a8, 0xc00084ac60}, {0xc000594280, 0x43}, {0x3066768, 0x0})
        github.com/telepresenceio/telepresence/v2/pkg/client/cli/cliutil/systema.go:215 +0x55c
github.com/telepresenceio/telepresence/v2/pkg/client/cli/cliutil.getTelepresencePro({0x30485a8, 0xc00084ac60}, {0x3066768, 0x0})
        github.com/telepresenceio/telepresence/v2/pkg/client/cli/cliutil/systema.go:184 +0x525
github.com/telepresenceio/telepresence/v2/pkg/client/cli/cliutil.EnsureLoggedIn({0x30485a8, 0xc00084ac60}, {0x0, 0x0})
        github.com/telepresenceio/telepresence/v2/pkg/client/cli/cliutil/systema.go:36 +0x6d
github.com/telepresenceio/telepresence/v2/pkg/client/cli.dashboardCommand.func1(0xc00051ec80, {0x0?, 0x0?, 0x0?})
        github.com/telepresenceio/telepresence/v2/pkg/client/cli/cmds_misc.go:124 +0x97
github.com/telepresenceio/telepresence/v2/pkg/client/cli/output.(*output).runE.func1(0xc00051ec80, {0x4fded70, 0x0, 0x0})
        github.com/telepresenceio/telepresence/v2/pkg/client/cli/output/output.go:91 +0x271
github.com/spf13/cobra.(*Command).execute(0xc00051ec80, {0x4fded70, 0x0, 0x0})
        github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xc000271900)
        github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.5.0/command.go:918
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        github.com/spf13/cobra@v1.5.0/command.go:911
main.main()
        github.com/telepresenceio/telepresence/v2/cmd/telepresence/main.go:75 +0x6b3
```

For reference:

`> telepresence status`

```
Root Daemon: Running
  Version   : v2.8.5 (api 3)
User Daemon: Running
  Version         : v2.8.5 (api 3)
  Executable      : C:\telepresence\telepresence.exe
  Install ID      : 4ff1f6af-8bd2-455a-870c-ea0f3aeae47e
  Ambassador Cloud:
    Status      : Logged out
    User ID     :
    Account ID  :
    User Name   :
    Email       :
    Account Name:
  Status            : Not connected
  Kubernetes server :
  Kubernetes context:
  Intercepts        : 0 total
```

**Comment by thallgren** [comment]
This was fixed in 2.9.0.
