### ISSUE TITLE
Daemon segfault

### ISSUE THREAD

**Issue by simonklb** [telepresenceio/telepresence#2963]
**Describe the bug**

My intercept stopped working without anything obvious popping up. When I was trying to restart the intercept I got this:

```
telepresence intercept: error: connection error: desc = "transport: error while dialing: dial unix /var/run/telepresence-daemon.socket: connect: connection refused" (socket rm failed with remove /var/run/telepresence-daemon.socket: permission denied); this usually means that the process has terminated ungracefully
```

This is the dump from the daemon log:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x17dfa3b]

goroutine 66993 [running]:
github.com/telepresenceio/telepresence/v2/pkg/tunnel.readLoop({0x2629b68, 0xc000b31e30}, {0x262f648, 0xc000858e70})
	github.com/telepresenceio/telepresence/v2/pkg/tunnel/dialer.go:294 +0x3db
github.com/telepresenceio/telepresence/v2/pkg/tunnel.(*dialer).streamToConnLoop(0x0?, {0x2629b68?, 0xc000b31e30?}, 0x0?)
	github.com/telepresenceio/telepresence/v2/pkg/tunnel/dialer.go:239 +0x6e
created by github.com/telepresenceio/telepresence/v2/pkg/tunnel.(*dialer).Start.func1
	github.com/telepresenceio/telepresence/v2/pkg/tunnel/dialer.go:143 +0xaaf
```

**Versions (please complete the following information):**

```
$ telepresence version
Client         : v2.9.5
Root Daemon    : v2.9.5
User Daemon    : v2.9.5
```

**Comment by thallgren** [comment]
Fix released in 2.14.0.
