### ISSUE TITLE
KeyError: 'clusterIP' when starting telepresence in a cluster that has ExternalName service

### ISSUE THREAD

**Issue by leonth** [telepresenceio/telepresence#351]
### What were you trying to do?

`telepresence --run-shell` for a GKE cluster

### What did you expect to happen?

Telepresence starts

### What happened instead?

The below error occured. The offending service is:

```
 {
    "apiVersion": "v1",
    "kind": "Service",
    "metadata": {
      "annotations": {},
      "creationTimestamp": "2017-10-24T10:30:00Z",
      "name": "test-service",
      "namespace": "default",
      "resourceVersion": "1974810",
      "selfLink": "/api/v1/namespaces/default/services/test-service",
      "uid": "49d91f00-b8a6-11e7-8324-42010a940008"
    },
    "spec": {
      "externalName": "[redacted]",
      "ports": [
        {
          "name": "80",
          "port": 80,
          "protocol": "TCP",
          "targetPort": 8080
        }
      ],
      "sessionAffinity": "None",
      "type": "ExternalName"
    },
    "status": {
      "loadBalancer": {}
    }
  },
```

### Automatically included information

Command line: `['/usr/bin/telepresence', '--run-shell']`
Version: `0.67`
Python version: `3.6.3 (default, Oct 24 2017, 14:48:20) 
[GCC 7.2.0]`
kubectl version: `Client Version: v1.8.2`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux leon-laptop 4.9.60-1-MANJARO #1 SMP PREEMPT Thu Nov 2 13:08:20 UTC 2017 x86_64 GNU/Linux`
Traceback:

```
Traceback (most recent call last):
  File "/usr/bin/telepresence", line 257, in call_f
    return f(*args, **kwargs)
  File "/usr/bin/telepresence", line 2363, in go
    runner, remote_info, args, env, subprocesses, socks_port, ssh
  File "/usr/bin/telepresence", line 2105, in run_local_command
    connect_sshuttle(runner, remote_info, args, subprocesses, env, ssh)
  File "/usr/bin/telepresence", line 1868, in connect_sshuttle
    runner, args, remote_info, env["KUBERNETES_SERVICE_HOST"]
  File "/usr/bin/telepresence", line 1802, in get_proxy_cidrs
    service_ips = get_service_ips()
  File "/usr/bin/telepresence", line 1798, in get_service_ips
    svc["spec"]["clusterIP"] for svc in services
  File "/usr/bin/telepresence", line 1799, in <listcomp>
    if svc["spec"]["clusterIP"] != "None"
KeyError: 'clusterIP'

```

Logs:

```
27-7286472-959', 'env'],)...
   5.2 TL | [19] captured.
   5.2 TL | [20] Running: (['sshfs', '-p', '33805', '-F', '/dev/null', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', 'telepresence@localhost:/', '/tmp/tmpdii39bjm'],)...
   5.2 14 | Handling connection for 33805
   5.5 TL | [20] ran.
   5.5 TL | [21] Capturing: (['kubectl', '--context', 'gke_sirclo-1152_asia-southeast1-a_staging2', '--namespace', 'default', 'exec', '--container=telepresence-1510890627-7286472-959', 'telepresence-1510890627-7286472-959-86b5866755-fhs6x', '--', 'python3', '-c', '\nimport socket, sys, json\n\nresult = []\nfor host in sys.argv[1:]:\n    result.append(socket.gethostbyname(host))\nsys.stdout.write(json.dumps(result))\nsys.stdout.flush()\n'],)...
   6.1 TL | [21] captured.
   6.1 TL | [22] Capturing: (['kubectl', 'get', 'nodes', '-o', 'json'],)...
   6.3 TL | [22] captured.
   6.3 TL | [23] Capturing: (['kubectl', 'get', 'services', '-o', 'json'],)...
   6.5 TL | [23] captured.

```

**Comment by ark3** [comment]
Thank you for the bug report! This may have been fixed with #329. Can you please try again with the latest version of Telepresence?
