### ISSUE TITLE
Telepresence could report Docker k8s-proxy image pull failures with less incidental complexity

### ISSUE THREAD

**Issue by exarkun** [telepresenceio/telepresence#403]
Sometimes Telepresence fails to operate because Docker wasn't able to get the Telepresence proxy image on Kubernetes.  The Telepresence client eventually times out and reports a `RuntimeError` with traceback something like this:

```
Looks like there's a bug in our code. Sorry about that!

Here's the traceback:

Traceback (most recent call last):
  File "/Users/distiller/project/telepresence/cli.py", line 73, in call_f
    return f(*args, **kwargs)
  File "/Users/distiller/project/telepresence/main.py", line 480, in go
    runner, args
  File "/Users/distiller/project/telepresence/main.py", line 297, in start_proxy
    run_id=run_id,
  File "/Users/distiller/project/telepresence/remote.py", line 209, in get_remote_info
    wait_for_pod(runner, remote_info)
  File "/Users/distiller/project/telepresence/remote.py", line 129, in wait_for_pod
    "Pod isn't starting or can't be found: {}".format(pod["status"])
RuntimeError: Pod isn't starting or can't be found: {'conditions': [{'lastProbeTime': None, 'lastTransitionTime': '2018-01-11T12:23:41Z', 'status': 'True', 'type': 'Initialized'}, {'lastProbeTime': None, 'lastTransitionTime': '2018-01-11T12:23:41Z', 'message': 'containers with unready status: [testing-9cde671-494-83\
92241001129-5904]', 'reason': 'ContainersNotReady', 'status': 'False', 'type': 'Ready'}, {'lastProbeTime': None, 'lastTransitionTime': '2018-01-11T12:23:41Z', 'status': 'True', 'type': 'PodScheduled'}], 'containerStatuses': [{'image': 'gcr.io/datawireio/telepresence-k8s:0.72-124-g9cde671', 'imageID': '', 'lastState'\
: {}, 'name': 'testing-9cde671-494-8392241001129-5904', 'ready': False, 'restartCount': 0, 'state': {'waiting': {'message': 'rpc error: code = 2 desc = failed to register layer: rename /var/lib/docker/image/overlay/layerdb/tmp/layer-286041440 /var/lib/docker/image/overlay/layerdb/sha256/ad2a5d7d7f2189b643fc984c7ef4d\
8e3593cdc76ff2980a0b0644ac0419fdc80: directory not empty', 'reason': 'ErrImagePull'}}}], 'hostIP': '10.128.0.11', 'phase': 'Pending', 'podIP': '10.0.0.78', 'qosClass': 'Burstable', 'startTime': '2018-01-11T12:23:41Z'}
```

This is a bunch of noise which can be sorted through to find a (hypothetically) useful piece of information.  Specifically, the pod is stuck `Pending` because:

```
{'message': 'rpc error: code = 2 desc = failed to register layer: rename /var/lib/docker/image/overlay/layerdb/tmp/layer-286041440 /var/lib/docker/image/overlay/layerdb/sha256/ad2a5d7d7f2189b643fc984c7ef4d8e3593cdc76ff2980a0b0644ac0419fdc80: directory not empty', 'reason': 'ErrImagePull'}
```

If Telepresence highlighted this information and skipped the Python traceback, it would be easier to recognize this type of failure and (presumably) take the necessary corrective action (which likely often lies beyond Telepresence's responsibilties).

I'd suggest that the pod name, status, image, and `.waiting.message` are useful information.

**Comment by donnyyung** [comment]
We should still do this in Telepresence 2, sometimes telepresence fails to pull an image for the agent or manager and we should make that information more apparent to the user.
