### ISSUE TITLE
Crash trying to --swap-deployment

### ISSUE THREAD

**Issue by ghost** [telepresenceio/telepresence#406]
### What were you trying to do
Following the instructions here: `https://www.telepresence.io/tutorials/kubernetes` When I get to this command `telepresence --swap-deployment hello-world --expose 8000 --run python3 -m http.server 8000` I am met with the following error response:

```
$ telepresence --swap-deployment hello-world --expose 8000 --run python3 -m http.server 8000
Starting proxy with method 'vpn-tcp', which has the following limitations: All processes are affected, only one telepresence can run per machine, and you can't use other VPNs. You may need to add cloud hosts with --also-proxy. For a full
 list of method limitations see https://telepresence.io/reference/methods.html
Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.


Looks like there's a bug in our code. Sorry about that!

Here's the traceback:

Traceback (most recent call last):
  File "/usr/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/cli.py", line 73, in call_f
    return f(*args, **kwargs)
  File "/usr/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/main.py", line 480, in go
    runner, args
  File "/usr/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/main.py", line 274, in start_proxy
    runner, args
  File "/usr/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/deployment.py", line 126, in swap_deployment
    apply_json(new_deployment_json)
  File "/usr/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/deployment.py", line 105, in apply_json
    input=json.dumps(json_config).encode("utf-8")
  File "/usr/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/runner.py", line 130, in check_kubectl
    self.kubectl(context, namespace, kubectl_args), **kwargs
  File "/usr/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/runner.py", line 84, in check_call
    raise CalledProcessError(retcode, args)
subprocess.CalledProcessError: Command '(['kubectl', '--context', 'dev-tesseract', '--namespace', 'default', 'apply', '-f', '-'],)' returned non-zero exit status 1
```

Logfile:

```
$ cat telepresence.log 
   0.0 TL | Telepresence launched at Fri Jan 12 13:02:09 2018
   0.0 TL |   ['/usr/bin/telepresence', '--swap-deployment', 'hello-world', '--expose', '8000', '--run', 'python3', '-m', 'http.server', '8000']
   0.0 TL | Scout info: {'latest_version': '0.72', 'notices': [], 'application': 'telepresence'}
   0.0 TL | Context: dev-tesseract, namespace: default, kubectl_command: kubectl
   0.0 TL | [1] Capturing: (['kubectl', '--context', 'dev-tesseract', 'cluster-info'],)...
   0.2 TL | [1] captured.
   0.2 TL | [2] Capturing: (['ssh', '-V'],)...
   0.2 TL | [2] captured.
   0.2 TL | [3] Capturing: (['which', 'torsocks'],)...
   0.2 TL | [3] captured.
   0.2 TL | [4] Capturing: (['which', 'sshfs'],)...
   0.2 TL | [4] captured.
   0.2 TL | [5] Capturing: (['which', 'conntrack'],)...
   0.2 TL | [5] captured.
   0.2 TL | [6] Capturing: (['kubectl', '--context', 'dev-tesseract', '--namespace', 'default', 'get', 'deployment', '-o', 'json', '--export', 'hello-world'],)...
   0.4 TL | [6] captured.
   0.4 TL | [7] Running: (['kubectl', '--context', 'dev-tesseract', '--namespace', 'default', 'delete', 'deployment', 'hello-world'],)...
   4.0 7 | deployment "hello-world" deleted
   4.0 TL | [7] ran.
   4.0 TL | [8] Running: (['kubectl', '--context', 'dev-tesseract', '--namespace', 'default', 'apply', '-f', '-'],)...
   4.3 TL | [8] exit 1.
   6.1 TL | [9] Running: (['kubectl', '--context', 'dev-tesseract', '--namespace', 'default', 'delete', 'deployment', 'hello-world'],)...
   6.5 TL | [9] exit 1.
   6.6 9 | Error from server (NotFound): deployments.extensions "hello-world" not found
```

Also, the CLI claims to report the 'last few lines' of the log file captured above, but it does not and actually omits quite valuable data at the very end of the above output:
```
And here are the last few lines of the logfile (see ./telepresence.log for the complete logs):

   0.0 TL |   ['/usr/bin/telepresence', '--swap-deployment', 'hello-world', '--expose', '8000', '--run', 'python3', '-m', 'http.server', '8000']
   0.0 TL | Scout info: {'latest_version': '0.72', 'application': 'telepresence', 'notices': []}
   0.0 TL | Context: dev-tesseract, namespace: default, kubectl_command: kubectl
   0.0 TL | [1] Capturing: (['kubectl', '--context', 'dev-tesseract', 'cluster-info'],)...
   0.2 TL | [1] captured.
   0.2 TL | [2] Capturing: (['ssh', '-V'],)...
   0.2 TL | [2] captured.
   0.2 TL | [3] Capturing: (['which', 'torsocks'],)...
   0.2 TL | [3] captured.
   0.2 TL | [4] Capturing: (['which', 'sshfs'],)...
   0.2 TL | [4] captured.
   0.2 TL | [5] Capturing: (['which', 'conntrack'],)...
   0.2 TL | [5] captured.
   0.2 TL | [6] Capturing: (['kubectl', '--context', 'dev-tesseract', '--namespace', 'default', 'get', 'deployment', '-o', 'json', '--export', 'hello-world'],)...
   0.4 TL | [6] captured.
   0.4 TL | [7] Running: (['kubectl', '--context', 'dev-tesseract', '--namespace', 'default', 'delete', 'deployment', 'hello-world'],)...
   6.4 7 | deployment "hello-world" deleted
   6.4 TL | [7] ran.
   6.4 TL | [8] Running: (['kubectl', '--context', 'dev-tesseract', '--namespace', 'default', 'apply', '-f', '-'],)...
```

Have verified that the hello-world deployment and service are successfully created before running `telepresence`.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
