### ISSUE TITLE
If remote container failed to start then we can't replace it

### ISSUE THREAD

**Issue by snowe2010** [telepresenceio/telepresence#408]
### What were you trying to do?
Replace a remote image in order to debug why it wouldn't start. 

### What did you expect to happen?
Be able to replace the deployment (not the pod, which is what didn't start)

### What happened instead?

Telepresence failed after 2 minutes 17 seconds with the below stacktrace. 

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--swap-deployment', 'iam-service', '--expose', '9008:9008', '--run-shell']`
Version: `0.73`
Python version: `3.6.4 (default, Jan  6 2018, 11:51:15) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]`
kubectl version: `Client Version: v1.8.4`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin ip-172-16-8-243.ec2.internal 16.7.0 Darwin Kernel Version 16.7.0: Mon Nov 13 21:56:25 PST 2017; root:xnu-3789.72.11~1/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/telepresence/0.73/libexec/lib/python3.6/site-packages/telepresence/cli.py", line 73, in call_f
    return f(*args, **kwargs)
  File "/usr/local/Cellar/telepresence/0.73/libexec/lib/python3.6/site-packages/telepresence/main.py", line 480, in go
    runner, args
  File "/usr/local/Cellar/telepresence/0.73/libexec/lib/python3.6/site-packages/telepresence/main.py", line 297, in start_proxy
    run_id=run_id,
  File "/usr/local/Cellar/telepresence/0.73/libexec/lib/python3.6/site-packages/telepresence/remote.py", line 217, in get_remote_info
    format(deployment_name)
RuntimeError: Telepresence pod not found for Deployment 'iam-service'.

```

Logs:

```
ackend'} (phase Running)...
 123.0 TL | Labels don't match.
 124.0 TL | [98] Capturing: (['kubectl', '--context', 'gke_canvas-hybrid-188116_us-central1-a_test-test', '--namespace', 'default', 'get', 'pod', '-o', 'json', '--export'],)...
 124.4 TL | [98] captured.
 124.4 TL | Checking {'app': 'borrower-wallet', 'pod-template-hash': '3173997543', 'tier': 'backend'} (phase Running)...
 124.4 TL | Labels don't match.
 124.4 TL | Checking {'app': 'gateway', 'pod-template-hash': '3427589088', 'tier': 'backend'} (phase Running)...
 124.4 TL | Labels don't match.
 124.4 TL | Checking {'app': 'lp-server', 'pod-template-hash': '2230239955', 'tier': 'backend'} (phase Running)...
 124.4 TL | Labels don't match.
 124.4 TL | Checking {'app': 'postgres', 'pod-template-hash': '2236162861', 'tier': 'backend'} (phase Running)...
 124.4 TL | Labels don't match.
 124.4 TL | Checking {'app': 'rabbitmq', 'pod-template-hash': '390430409', 'tier': 'backend'} (phase Running)...
 124.4 TL | Labels don't match.

```

**Comment by snowe2010** [comment]
```
❯ k get all                                                                                                                                                                                           (develop|✚1)
NAME                     DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/borrower-wallet   1         1         1            1           1h
deploy/gateway           1         1         1            1           1h
deploy/iam-service       0         0         0            0           1m
deploy/lp-server         1         1         1            1           1h
deploy/postgres          1         1         1            1           1h
deploy/rabbitmq          1         1         1            1           1h

NAME                            DESIRED   CURRENT   READY     AGE
rs/borrower-wallet-3173997543   1         1         1         1h
rs/gateway-3427589088           1         1         1         1h
rs/lp-server-2230239955         1         1         1         1h
rs/postgres-2236162861          1         1         1         1h
rs/rabbitmq-390430409           1         1         1         1h

NAME                     DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/borrower-wallet   1         1         1            1           1h
deploy/gateway           1         1         1            1           1h
deploy/iam-service       0         0         0            0           1m
deploy/lp-server         1         1         1            1           1h
deploy/postgres          1         1         1            1           1h
deploy/rabbitmq          1         1         1            1           1h

NAME                                  READY     STATUS    RESTARTS   AGE
po/borrower-wallet-3173997543-pw9x2   1/1       Running   0          1h
po/gateway-3427589088-b9233           1/1       Running   0          1h
po/lp-server-2230239955-cf45k         1/1       Running   0          1h
po/postgres-2236162861-z7k8m          1/1       Running   0          1h
po/rabbitmq-390430409-f5s95           1/1       Running   0          1h
```

**Comment by ark3** [comment]
Thanks for the report. Work done by @ofpiyush for #363 may address this. Let me get back to you.

**Comment by ofpiyush** [comment]
The current work on #363 addresses it a little indirectly.

I plan to add more direct fixes with some health checks from the pod back to one's local, but that's not in the current PR #407

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
