### ISSUE TITLE
Try to run telepresence in IOS High Sierra 10.13.2

### ISSUE THREAD

**Issue by reinodenoia** [telepresenceio/telepresence#430]
I tried to start telepresence in IOS high Sierra and it shows me this message

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--method', 'inject-tcp', '--swap-deployment', 'dashboard', '--expose', '44555:80']`
Version: `0.73`
Python version: `3.6.4 (default, Jan 23 2018, 18:53:11) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]`
kubectl version: `Client Version: v1.8.3`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin Mac-mini-de-Maria.local 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/telepresence/0.73/libexec/lib/python3.6/site-packages/telepresence/cli.py", line 73, in call_f
    return f(*args, **kwargs)
  File "/usr/local/Cellar/telepresence/0.73/libexec/lib/python3.6/site-packages/telepresence/main.py", line 493, in go
    runner, remote_info, args, env, subprocesses, socks_port, ssh
  File "/usr/local/Cellar/telepresence/0.73/libexec/lib/python3.6/site-packages/telepresence/local.py", line 151, in run_local_command
    setup_torsocks(runner, env, socks_port, unsupported_tools_path)
  File "/usr/local/Cellar/telepresence/0.73/libexec/lib/python3.6/site-packages/telepresence/local.py", line 114, in setup_torsocks
    raise RuntimeError("SOCKS network proxying failed to start...")
RuntimeError: SOCKS network proxying failed to start...

```

Logs:

```
ket; socket.socket().connect(('google.com', 80))"],)...
  31.1 55 | Traceback (most recent call last):
  31.1 55 |   File "<string>", line 1, in <module>
  31.1 55 | socket.gaierror: [Errno 4] Non-recoverable failure in name resolution
1516907090 PERROR torsocks[33626]: recv socks5 data: Connection reset by peer (in recv_data_impl() at socks5.c:79)
  31.4 56 | Traceback (most recent call last):
  31.4 56 |   File "<string>", line 1, in <module>
  31.4 56 | socket.gaierror: [Errno 4] Non-recoverable failure in name resolution
  31.4 TL | [56] exit 1.
  31.5 TL | [57] Running: (['torsocks', 'python3', '-c', "import socket; socket.socket().connect(('google.com', 80))"],)...
1516907090 PERROR torsocks[33636]: recv socks5 data: Connection reset by peer (in recv_data_impl() at socks5.c:79)
  31.8 TL | [57] exit 1.
  31.8 57 | Traceback (most recent call last):
  31.8 57 |   File "<string>", line 1, in <module>
  31.8 57 | socket.gaierror: [Errno 4] Non-recoverable failure in name resolution

```

**Comment by ark3** [comment]
Is that on Minikube?

**Comment by reinodenoia** [comment]
Yes, minikube version: v0.23.0

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
