### ISSUE TITLE
Telepresence bug

### ISSUE THREAD

**Issue by Moez23** [telepresenceio/telepresence#444]
### What were you trying to do?

(please tell us)

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below)

### Automatically included information

Command line: `['/usr/bin/telepresence', '--swap-deployment', 'frontend', '--run-shell']`
Version: `0.68`
Python version: `3.5.2+ (default, Sep 22 2016, 12:18:14) 
[GCC 6.2.0 20160927]`
kubectl version: `Client Version: v1.8.3`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Linux atlas 4.8.0-59-generic #64-Ubuntu SMP Thu Jun 29 19:38:34 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
Traceback:

```
Traceback (most recent call last):
  File "/usr/bin/telepresence", line 257, in call_f
    return f(*args, **kwargs)
  File "/usr/bin/telepresence", line 2370, in go
    runner, args
  File "/usr/bin/telepresence", line 1533, in start_proxy
    run_id=run_id,
  File "/usr/bin/telepresence", line 898, in get_remote_info
    wait_for_pod(runner, remote_info)
  File "/usr/bin/telepresence", line 1050, in wait_for_pod
    "Pod isn't starting or can't be found: {}".format(pod["status"])
RuntimeError: Pod isn't starting or can't be found: {'containerStatuses': [{'restartCount': 0, 'imageID': '', 'image': 'datawire/telepresence-k8s:0.68', 'state': {'waiting': {'reason': 'ContainerCreating'}}, 'name': 'frontend', 'lastState': {}, 'ready': False}], 'startTime': '2018-02-01T10:29:12Z', 'conditions': [{'lastProbeTime': None, 'type': 'Initialized', 'lastTransitionTime': '2018-02-01T10:29:12Z', 'status': 'True'}, {'lastProbeTime': None, 'type': 'Ready', 'lastTransitionTime': '2018-02-01T10:29:12Z', 'reason': 'ContainersNotReady', 'message': 'containers with unready status: [frontend]', 'status': 'False'}, {'lastProbeTime': None, 'type': 'PodScheduled', 'lastTransitionTime': '2018-02-01T10:29:12Z', 'status': 'True'}], 'hostIP': '192.168.99.100', 'phase': 'Pending', 'qosClass': 'BestEffort'}

```

Logs:

```
, 'pod', 'frontend-8449cb4745-kdrjs', '-o', 'json'],)...
 124.4 TL | [324] captured.
 124.6 TL | [325] Capturing: (['kubectl', '--context', 'minikube', '--namespace', 'default', 'get', 'pod', 'frontend-8449cb4745-kdrjs', '-o', 'json'],)...
 124.7 TL | [325] captured.
 125.0 TL | [326] Capturing: (['kubectl', '--context', 'minikube', '--namespace', 'default', 'get', 'pod', 'frontend-8449cb4745-kdrjs', '-o', 'json'],)...
 125.1 TL | [326] captured.
 125.4 TL | [327] Capturing: (['kubectl', '--context', 'minikube', '--namespace', 'default', 'get', 'pod', 'frontend-8449cb4745-kdrjs', '-o', 'json'],)...
 125.5 TL | [327] captured.
 125.7 TL | [328] Capturing: (['kubectl', '--context', 'minikube', '--namespace', 'default', 'get', 'pod', 'frontend-8449cb4745-kdrjs', '-o', 'json'],)...
 125.9 TL | [328] captured.
 126.1 TL | [329] Capturing: (['kubectl', '--context', 'minikube', '--namespace', 'default', 'get', 'pod', 'frontend-8449cb4745-kdrjs', '-o', 'json'],)...
 126.2 TL | [329] captured.

```

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
