### ISSUE TITLE
limitations of multiple `telepresence` instances

### ISSUE THREAD

**Issue by blak3mill3r** [telepresenceio/telepresence#447]
### What were you trying to do?

Launch multiple `telepresence` instances simultaneously, specifically: one instance of `telepresence` with `--method=vpn-tcp` and then one (or more) with `--docker-run`.

### What did you expect to happen?

This actually works and is quite valuable. The problem is, it only works if I first launch the `--docker-run` one, and then launch the `--method=vpn-tcp` one. If I launch them in the other order, then it fails.

I was just checking on #387 (:+1:), and in the process of doing that, I installed `telepresence` from git, as in

```bash
hub clone datawire/telepresence
cd telepresence
git checkout 0.75
sudo env PREFIX=~/tpinstall ./install.sh
```

Here is precisely how I am launching it:

```bash
~/tpinstall/bin/telepresence              \
  --namespace dev         \
  --swap-deployment ropes \
  --docker-run -it        \
    -w /ropes             \
    -v $(pwd):/ropes      \
    -v ~/.m2:/root/.m2    \
    --publish 3449:3449   \
    --publish 7887:7887   \
    --publish 7888:7888   \
  clojure:lein-2.7.1      \
    /bin/bash -e lein repl
```

And the other VPN instance is launched more or less like this

```
telepresence                                                                  \
   --namespace dev                                                            \
   --also-proxy bunch                        \
   --also-proxy of                        \
   --also-proxy things                        \
```

If I launch the two in the order they are listed above, then it works which is *very powerful*.
If I launch them in the opposite order, it looks like the second instance, the `--docker-run` one, cannot find what it needs on the other end ... ?

Here is the console output when the `--docker-run` one bails:

```
And here are the last few lines of the logfile (see ./telepresence.log for the complete logs):

  30.8 41 | c : Connected.
  30.8 41 | firewall manager: setting up.
  30.8 41 | >> iptables -t nat -N sshuttle-12300
  30.8 41 | >> iptables -t nat -F sshuttle-12300
  30.8 41 | >> iptables -t nat -I OUTPUT 1 -j sshuttle-12300
  30.8 41 | >> iptables -t nat -I PREROUTING 1 -j sshuttle-12300
  30.8 41 | >> iptables -t nat -A sshuttle-12300 -j RETURN --dest 127.0.0.1/32 -p tcp
  30.8 41 | >> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 100.96.6.0/24 -p tcp --to-ports 12300 -m ttl ! --ttl 42
  30.8 41 | >> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 100.96.0.0/24 -p tcp --to-ports 12300 -m ttl ! --ttl 42
  30.8 41 | >> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 100.96.7.0/24 -p tcp --to-ports 12300 -m ttl ! --ttl 42
  30.8 41 | >> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 100.96.2.0/24 -p tcp --to-ports 12300 -m ttl ! --ttl 42
  30.8 41 | >> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 100.96.8.0/24 -p tcp --to-ports 12300 -m ttl ! --ttl 42
  30.8 41 | >> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 100.96.1.0/24 -p tcp --to-ports 12300 -m ttl ! --ttl 42
  30.8 41 | >> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 100.64.0.0/13 -p tcp --to-ports 12300 -m ttl ! --ttl 42
  30.8 41 | >> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 192.168.1.1/32 -p udp --dport 53 --to-ports 12300 -m ttl ! --ttl 42
  30.8 41 | >> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 224.0.0.252/32 -p udp --dport 5355 --to-ports 12300 -m ttl ! --ttl 42
  30.8 41 | conntrack v1.4.4 (conntrack-tools): 0 flow entries have been deleted.
  34.8 42 | Failed to connect to proxy in remote cluster.
  34.8 42 | [INFO  tini (1)] Main child exited normally (with status '1')
  35.1 TL | [42] exit 1.

Would you like to file an issue in our issue tracker? We'd really appreciate the help improving our product. [Y/n]: y

```

### Automatically included information

Command line: `['/home/blake/tpinstall/bin/telepresence', '--namespace', 'dev', '--swap-deployment', 'ropes', '--docker-run', '-it', '-w', '/ropes', '-v', '/home/blake/w/iris/iris-ropes:/ropes', '-v', '/home/blake/.m2:/root/.m2', '--publish', '3449:3449', '--publish', '7887:7887', '--publish', '7888:7888', 'clojure:lein-2.7.1', '/bin/bash', '-e', 'lein', 'repl']`
Version: `0.71`
Python version: `3.5.2 (default, Nov 17 2017, 02:29:51) 
[GCC 4.9.2]`
kubectl version: `Client Version: v1.8.3`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Linux manticore 3.16.0-4-amd64 #1 SMP Debian 3.16.51-2 (2017-12-03) x86_64 GNU/Linux`
Traceback:

```
Traceback (most recent call last):
  File "/home/blake/tpinstall/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/cli.py", line 73, in call_f
    return f(*args, **kwargs)
  File "/home/blake/tpinstall/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/main.py", line 489, in go
    ssh,
  File "/home/blake/tpinstall/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/container.py", line 133, in run_docker_command
    TELEPRESENCE_LOCAL_IMAGE, "wait"
  File "/home/blake/tpinstall/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/runner.py", line 84, in check_call
    raise CalledProcessError(retcode, args)
subprocess.CalledProcessError: Command '(['docker', 'run', '--network=container:telepresence-1517985013-8189452-11701', '--rm', 'datawire/telepresence-local:0.71', 'wait'],)' returned non-zero exit status 1

```

Logs:

```
 | >> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 100.96.2.0/24 -p tcp --to-ports 12300 -m ttl ! --ttl 42
  30.8 41 | >> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 100.96.8.0/24 -p tcp --to-ports 12300 -m ttl ! --ttl 42
  30.8 41 | >> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 100.96.1.0/24 -p tcp --to-ports 12300 -m ttl ! --ttl 42
  30.8 41 | >> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 100.64.0.0/13 -p tcp --to-ports 12300 -m ttl ! --ttl 42
  30.8 41 | >> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 192.168.1.1/32 -p udp --dport 53 --to-ports 12300 -m ttl ! --ttl 42
  30.8 41 | >> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 224.0.0.252/32 -p udp --dport 5355 --to-ports 12300 -m ttl ! --ttl 42
  30.8 41 | conntrack v1.4.4 (conntrack-tools): 0 flow entries have been deleted.
  34.8 42 | Failed to connect to proxy in remote cluster.
  34.8 42 | [INFO  tini (1)] Main child exited normally (with status '1')
  35.1 TL | [42] exit 1.

```

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
