### ISSUE TITLE
Telepresence fails to start with latest Docker for Mac integrated Kubernetes cluster 

### ISSUE THREAD

**Issue by danielbryantuk** [telepresenceio/telepresence#449]
### What were you trying to do?

Use telepresence with a local Docker for Mac Kubernetes cluster

### What did you expect to happen?

For it to work :-)

### What happened instead?

I received the following error

### Automatically included information

Command line: `['/usr/local/bin/telepresence']`
Version: `0.75`
Python version: `3.6.4 (default, Jan 12 2018, 13:27:19) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]`
kubectl version: `Client Version: v1.8.6`
oc version: `oc v1.4.1+3f9807a
kubernetes v1.4.0+776c994
features: Basic-Auth

Server https://localhost:6443
kubernetes v1.9.2`
OS: `Darwin workbox 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/telepresence/0.75/libexec/lib/python3.6/site-packages/telepresence/cli.py", line 73, in call_f
    return f(*args, **kwargs)
  File "/usr/local/Cellar/telepresence/0.75/libexec/lib/python3.6/site-packages/telepresence/main.py", line 493, in go
    runner, remote_info, args, env, subprocesses, socks_port, ssh
  File "/usr/local/Cellar/telepresence/0.75/libexec/lib/python3.6/site-packages/telepresence/local.py", line 154, in run_local_command
    connect_sshuttle(runner, remote_info, args, subprocesses, env, ssh)
  File "/usr/local/Cellar/telepresence/0.75/libexec/lib/python3.6/site-packages/telepresence/vpn.py", line 241, in connect_sshuttle
    get_hellotelepresence()
  File "/usr/local/Cellar/telepresence/0.75/libexec/lib/python3.6/site-packages/telepresence/vpn.py", line 230, in get_hellotelepresence
    format(next(counter))
  File "/usr/local/Cellar/telepresence/0.75/libexec/lib/python3.6/site-packages/telepresence/runner.py", line 95, in get_output
    result = str(check_output(*args, **kwargs).strip(), "utf-8")
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['python3', '-c', "import socket; socket.gethostbyname('hellotelepresence86')"]' returned non-zero exit status 1.

```

Logs:

```
c', "import socket; socket.gethostbyname('hellotelepresence83')"],)...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
  31.5 TL | [115] Capturing: (['python3', '-c', "import socket; socket.gethostbyname('hellotelepresence84')"],)...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
  31.7 TL | [116] Capturing: (['python3', '-c', "import socket; socket.gethostbyname('hellotelepresence85')"],)...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
  31.9 TL | [117] Capturing: (['python3', '-c', "import socket; socket.gethostbyname('hellotelepresence86')"],)...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

```

**Comment by ark3** [comment]
Thanks for the bug report. This looks like an incompatibility between the vpn-tcp method and Kubernetes for Docker for Mac. It's a familiar error, something I see with Minikube on Mac from some people. However, I'm unable to reproduce it on my setup, Docker for Mac Version 18.02.0-ce-rc2-mac51 (22446) on MacOS High Sierra 10.13.3 (17D47).

---

Internal notes:
```shell
$ kubectl config current-context 
docker-for-desktop

$ kubectl version --short
Client Version: v1.9.2
Server Version: v1.9.2

$ docker version
Client:
 Version:       18.02.0-ce-rc2
 API version:   1.36
 Go version:    go1.9.3
 Git commit:    f968a2c
 Built: Thu Feb  1 00:03:15 2018
 OS/Arch:       darwin/amd64
 Experimental:  true
 Orchestrator:  kubernetes

Server:
 Engine:
  Version:      18.02.0-ce-rc2
  API version:  1.36 (minimum version 1.12)
  Go version:   go1.9.3
  Git commit:   f968a2c
  Built:        Thu Feb  1 00:10:36 2018
  OS/Arch:      linux/amd64
  Experimental: true

$ kubectl get svc,deploy,po
NAME             TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
svc/kubernetes   ClusterIP   10.96.0.1       <none>        443/TCP        25m
svc/qotm         NodePort    10.101.129.74   <none>        80:31773/TCP   1s

NAME          DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/qotm   3         3         3            3           21m

NAME                       READY     STATUS    RESTARTS   AGE
po/qotm-6b6f99b9d8-kbtjr   1/1       Running   0          21m
po/qotm-6b6f99b9d8-mjv7t   1/1       Running   0          21m
po/qotm-6b6f99b9d8-t58xn   1/1       Running   0          21m

$ telepresence --docker-run --rm -it fedora:latest curl qotm
Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.

Guessing that Services IP range is 10.96.0.0/12. Services started after this point will be inaccessible if are outside this range; restart telepresence if you can't access a new Service.

{
  "hostname": "qotm-6b6f99b9d8-t58xn", 
  "ok": true, 
  "quote": "The last sentence you read is often sensible nonsense.", 
  "time": "2018-02-07T17:38:41.666810", 
  "version": "1.1"
}

$ telepresence --method inject-tcp --run curl qotm
Starting proxy with method 'inject-tcp', which has the following limitations: Go programs, static binaries, suid programs, and custom DNS implementations are not supported. For a full list of method limitations see https://telepresence.io/reference/methods.html
Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.

No traffic is being forwarded from the remote Deployment to your local machine. You can use the --expose option to specify which ports you want to forward.

{
  "hostname": "qotm-6b6f99b9d8-kbtjr", 
  "ok": true, 
  "quote": "Abstraction is ever present.", 
  "time": "2018-02-07T17:39:30.813048", 
  "version": "1.1"
}

$ telepresence --method vpn-tcp --run curl qotm
Starting proxy with method 'vpn-tcp', which has the following limitations: All processes are affected, only one telepresence can run per machine, and you can't use other VPNs. You may need to add cloud hosts with --also-proxy. For a full list of method limitations see https://telepresence.io/reference/methods.html
Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.

No traffic is being forwarded from the remote Deployment to your local machine. You can use the --expose option to specify which ports you want to forward.

Guessing that Services IP range is 10.96.0.0/12. Services started after this point will be inaccessible if are outside this range; restart telepresence if you can't access a new Service.

{
  "hostname": "qotm-6b6f99b9d8-kbtjr", 
  "ok": true, 
  "quote": "A small mercy is nothing at all?", 
  "time": "2018-02-07T18:29:09.464912", 
  "version": "1.1"
}
```

**Comment by ark3** [comment]
For search: Docker for Mac with Kubernetes

**Comment by donnyyung** [comment]
We should try using telepresence on a docker-for-mac cluster, tagging this as a v2 issue until we verify it does / does not work.
