### ISSUE TITLE
Docker Device Does Not Exist (Windows)

### ISSUE THREAD

**Issue by nightmare6m** [telepresenceio/telepresence#467]
I have just installed telepresence, and I am getting an error when running the code from the tutorial:
telepresence --swap-deployment qotm --docker-run --rm -it -v $(pwd):/service qotm-dev:latest

I am using windows 10 with the Linux tools and Minikube. The error is:
````
Looks like there's a bug in our code. Sorry about that!

Here's the traceback:

Traceback (most recent call last):
  File "/usr/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/cli.py", line 73, in call_f
    return f(*args, **kwargs)
  File "/usr/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/main.py", line 480, in go
    runner, args
  File "/usr/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/main.py", line 300, in start_proxy
    processes, socks_port, ssh = connect(runner, remote_info, args)
  File "/usr/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/main.py", line 164, in connect
    runner.get_output(["ip", "addr", "show", "dev", "docker0"])
  File "/usr/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/runner.py", line 95, in get_output
    result = str(check_output(*args, **kwargs).strip(), "utf-8")
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ip', 'addr', 'show', 'dev', 'docker0']' returned non-zero exit status 1


And here are the last few lines of the logfile (see ./telepresence.log for the complete logs):

   4.6 TL | Checking {'pod-template-hash': '1054534432', 'run': 'alpine'} (phase Running)...
   4.6 TL | Labels don't match.
   4.6 TL | Checking {'pod-template-hash': '3118463468', 'app': 'cp-kafka-connect'} (phase Running)...
   4.6 TL | Labels don't match.
   4.6 TL | Checking {'pod-template-hash': '1838643528', 'app': 'cp-schema-registry'} (phase Running)...
   4.6 TL | Labels don't match.
   4.6 TL | Checking {'pod-template-hash': '2268685881', 'app': 'kafka'} (phase Running)...
   4.6 TL | Labels don't match.
   4.6 TL | Checking {'pod-template-hash': '1673236039', 'telepresence': '8516276a-bd7d-49e1-875c-32445e01e866', 'run'
   4.6 TL | Looks like we've found our pod!
   4.6 TL | [10] Capturing: (['kubectl', '--context', 'minikube', '--namespace', 'default', 'get', 'pod', 'qotm-5bc767
   4.8 TL | [10] captured.
   5.1 TL | [11] Capturing: (['kubectl', '--context', 'minikube', '--namespace', 'default', 'get', 'pod', 'qotm-5bc767
   5.3 TL | [11] captured.
   5.6 TL | [12] Capturing: (['kubectl', '--context', 'minikube', '--namespace', 'default', 'get', 'pod', 'qotm-5bc767
   5.8 TL | [12] captured.
   5.8 TL | [13] Launching: (['kubectl', '--context', 'minikube', '--namespace', 'default', 'logs', '-f', 'qotm-5bc767
   5.8 TL | [14] Launching: (['kubectl', '--context', 'minikube', '--namespace', 'default', 'port-forward', 'qotm-5bc7
   5.9 TL | [15] Capturing: (['ip', 'addr', 'show', 'dev', 'docker0'],)...
Device "docker0" does not exist.
```
Can you give me any clue what's wrong or where I can find more information?

Thank you

**Comment by ark3** [comment]
That looks like a hole in our Windows support with the container method. Telepresence is trying to figure out an IP address for Docker so that it can have `socat` listen there and push connections to the Kubernetes cluster (via `kubectl port-forward`). Can you suggest how to figure out where to bind? 

With Docker for Mac, we have Telepresence bind to an alias of lo0, though we should transition to using `docker.for.mac.host.internal` (#224).

**Comment by ark3** [comment]
Can you help me work through some of these details? First step would be to determine whether fixing #224 would solve the problem in your setup. 

On your system, do containers have access to `host.docker.internal` as an address to talk to the host? E.g., on my machine running Docker for Mac, I see

```shell
mac$ docker run --rm -it --entrypoint "" datawire/telepresence-local:0.88 nslookup host.docker.internal
nslookup: can't resolve '(null)': Name does not resolve

Name:      host.docker.internal
Address 1: 192.168.65.2
```

but on my Linux workstation that fails:
```shell
ubuntu$ docker run --rm -it --entrypoint "" datawire/telepresence-local:0.88 nslookup host.docker.internal
nslookup: can't resolve '(null)': Name does not resolve

nslookup: can't resolve 'host.docker.internal': Name does not resolve
```

Back to the Mac, I can then run a service in another window, say `python3 -m http.server`, and then access it from Docker by `wget`ting the address `http://host.docker.internal:8000`. 

```shell
mac$ docker run --rm -it --entrypoint "" datawire/telepresence-local:0.88 wget -qO- http://host.docker.internal:8000/
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Directory listing for /</title>
</head>
<body>
<h1>Directory listing for /</h1>
<hr>
<ul>
</ul>
<hr>
</body>
</html>
```

If this works on your setup, then fixing #224 will solve your problem. Please let me know.

Thanks for your help.

**Comment by Keidrych** [comment]
Here's the result of running this in WSL looks like it works fine.

WSL accesses docker through the filesystem port and network adaption have been legacy for quite some time (before Mac I believe) so firing #224  should solve the problem unless I'm missing something

```
❯ docker run --rm -it --entrypoint "" datawire/telepresence-local:0.88 wget -qO-                                                                                                                                       http://host.docker.internal:8000/
Unable to find image 'datawire/telepresence-local:0.88' locally
0.88: Pulling from datawire/telepresence-local
605ce1bd3f31: Pull complete
15ed40e916bd: Pull complete
71f5a8ce0324: Pull complete
24a32b4a1569: Pull complete
29810ec95bb6: Pull complete
73c30b252b8f: Pull complete
Digest: sha256:3774d574ffe2bbc9d0c7de157202de54de25e5bb6c49cd94428b724fc6a004d3
Status: Downloaded newer image for datawire/telepresence-local:0.88
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/st                                                                                                                                      rict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Directory listing for /</title>
</head>
<body>
<h1>Directory listing for /</h1>
<hr>
<ul>
<li><a href=".dockerignore">.dockerignore</a></li>
<li><a href=".git/">.git/</a></li>
<li><a href=".gitignore">.gitignore</a></li>
<li><a href=".travis.yml">.travis.yml</a></li>
<li><a href="Dockerfile">Dockerfile</a></li>
<li><a href="k8s/">k8s/</a></li>
<li><a href="kubernetes/">kubernetes/</a></li>
<li><a href="LICENSE">LICENSE</a></li>
<li><a href="Makefile">Makefile</a></li>
<li><a href="qotm/">qotm/</a></li>
<li><a href="README.md">README.md</a></li>
<li><a href="requirements.txt">requirements.txt</a></li>
<li><a href="service.yaml">service.yaml</a></li>
<li><a href="telepresence.log">telepresence.log</a></li>
<li><a href="travis-build.sh">travis-build.sh</a></li>
</ul>
<hr>
</body>
</html>
```

**Comment by ark3** [comment]
Excellent, thank you! This will help us up-prioritize #224 and hopefully let us get farther here.

**Comment by ark3** [comment]
Telepresence 0.95 includes #726, and thus does not mess around with Docker devices and bridges. As such, this is no longer an issue. Closing.
