### ISSUE TITLE
Repeated crashes on start

### ISSUE THREAD

**Issue by rushilagr** [telepresenceio/telepresence#489]
### What were you trying to do?

telepresence --swap-deployment admin --expose 3000:3000 --run-shell

### What did you expect to happen?

As usual, expected a new container proxied to the local shell.

### What happened instead?

Repeated crashes a minute or so after executing command.

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--swap-deployment', 'admin', '--expose', '3000:3000', '--run-shell']`
Version: `0.73`
Python version: `3.6.4 (default, Jan 26 2018, 15:19:32) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]`
kubectl version: `Client Version: v1.8.1`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin Rushils-MacBook-Pro.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/telepresence/0.73/libexec/lib/python3.6/site-packages/telepresence/cli.py", line 73, in call_f
    return f(*args, **kwargs)
  File "/usr/local/Cellar/telepresence/0.73/libexec/lib/python3.6/site-packages/telepresence/main.py", line 493, in go
    runner, remote_info, args, env, subprocesses, socks_port, ssh
  File "/usr/local/Cellar/telepresence/0.73/libexec/lib/python3.6/site-packages/telepresence/local.py", line 154, in run_local_command
    connect_sshuttle(runner, remote_info, args, subprocesses, env, ssh)
  File "/usr/local/Cellar/telepresence/0.73/libexec/lib/python3.6/site-packages/telepresence/vpn.py", line 236, in connect_sshuttle
    get_hellotelepresence()
  File "/usr/local/Cellar/telepresence/0.73/libexec/lib/python3.6/site-packages/telepresence/vpn.py", line 230, in get_hellotelepresence
    format(next(counter))
  File "/usr/local/Cellar/telepresence/0.73/libexec/lib/python3.6/site-packages/telepresence/runner.py", line 95, in get_output
    result = str(check_output(*args, **kwargs).strip(), "utf-8")
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'python3': 'python3'

```

Logs:

```
] Capturing: (['kubectl', '--context', 'gke_upheo-cc58a_asia-east1-a_upheo-prod', '--namespace', 'default', 'exec', '--container=master', 'admin-5985f78578-4dhw8', '--', 'python3', '-c', '\nimport socket, sys, json\n\nresult = []\nfor host in sys.argv[1:]:\n    result.append(socket.gethostbyname(host))\nsys.stdout.write(json.dumps(result))\nsys.stdout.flush()\n'],)...
  19.7 TL | [23] captured.
  19.7 TL | [24] Capturing: (['kubectl', 'get', 'nodes', '-o', 'json'],)...
  20.6 TL | [24] captured.
  20.6 TL | [25] Capturing: (['kubectl', 'get', 'services', '-o', 'json'],)...
  21.4 TL | [25] captured.
  21.4 TL | [26] Launching: (['sshuttle-telepresence', '-v', '--dns', '--method', 'auto', '-e', 'ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -F /dev/null', '--to-ns', '127.0.0.1:9053', '-r', 'telepresence@localhost:65131', '10.32.0.0/24', '10.35.240.0/20'],)...
  21.4 TL | [27] Capturing: (['python3', '-c', "import socket; socket.gethostbyname('hellotelepresence0')"],)...

```

**Comment by rushilagr** [comment]
Re-installing using this didnt' work
```
brew install telepresence
```

But Re-install with this fixed it
```
brew install socat datawire/blackbird/telepresence
```

**Comment by ark3** [comment]
Folks on Homebrew may have to `brew upgrade python` as well. This is due to a change in Homebrew's Python support.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
