### ISSUE TITLE
Error when attempting to use telepresence. 

### ISSUE THREAD

**Issue by nafeger** [telepresenceio/telepresence#499]
I got a message saying there was a bug and I should submit a bug report:
```

19:28:18.297 [ERROR] [system.err] Mounting remote volumes failed, they will be unavailable in this session. If you are running on Windows Subystem for Linux then see https://github.com/datawire/telepresence/issues/115, otherwise please report a bug, attaching telepresence.log to the bug report: https://github.com/datawire/telepresence/issues/new
19:28:18.297 [QUIET] [system.out]
19:28:18.299 [QUIET] [system.out] Looks like there's a bug in our code. Sorry about that!
19:28:18.300 [QUIET] [system.out]
19:28:18.300 [QUIET] [system.out] Here's the traceback:
19:28:18.300 [QUIET] [system.out]
19:28:18.300 [QUIET] [system.out] Traceback (most recent call last):
19:28:18.301 [QUIET] [system.out]   File "/usr/local/Cellar/telepresence/0.75/libexec/lib/python3.6/site-packages/telepresence/cli.py", line 73, in call_f
19:28:18.301 [QUIET] [system.out]     return f(*args, **kwargs)
19:28:18.301 [QUIET] [system.out]   File "/usr/local/Cellar/telepresence/0.75/libexec/lib/python3.6/site-packages/telepresence/main.py", line 493, in go
19:28:18.301 [QUIET] [system.out]     runner, remote_info, args, env, subprocesses, socks_port, ssh
19:28:18.301 [QUIET] [system.out]   File "/usr/local/Cellar/telepresence/0.75/libexec/lib/python3.6/site-packages/telepresence/local.py", line 154, in run_local_command
19:28:18.301 [QUIET] [system.out]     connect_sshuttle(runner, remote_info, args, subprocesses, env, ssh)
19:28:18.301 [QUIET] [system.out]   File "/usr/local/Cellar/telepresence/0.75/libexec/lib/python3.6/site-packages/telepresence/vpn.py", line 241, in connect_sshuttle
19:28:18.302 [QUIET] [system.out]     get_hellotelepresence()
19:28:18.302 [QUIET] [system.out]   File "/usr/local/Cellar/telepresence/0.75/libexec/lib/python3.6/site-packages/telepresence/vpn.py", line 230, in get_hellotelepresence
19:28:18.303 [QUIET] [system.out]     format(next(counter))
19:28:18.303 [QUIET] [system.out]   File "/usr/local/Cellar/telepresence/0.75/libexec/lib/python3.6/site-packages/telepresence/runner.py", line 95, in get_output
19:28:18.304 [QUIET] [system.out]     result = str(check_output(*args, **kwargs).strip(), "utf-8")
19:28:18.304 [QUIET] [system.out]   File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 336, in check_output
19:28:18.304 [QUIET] [system.out]     **kwargs).stdout
19:28:18.304 [QUIET] [system.out]   File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 418, in run
19:28:18.304 [QUIET] [system.out]     output=stdout, stderr=stderr)
19:28:18.304 [QUIET] [system.out] subprocess.CalledProcessError: Command '['python3', '-c', "import socket; socket.gethostbyname('hellotelepresence6')"]' returned non-zero exit status 1.
19:28:18.305 [QUIET] [system.out]
19:28:18.305 [QUIET] [system.out]
19:28:18.305 [QUIET] [system.out] And here are the last few lines of the logfile (see ./telepresence.log for the complete logs):
19:28:18.305 [QUIET] [system.out]
19:28:18.306 [QUIET] [system.out]  194.3 145 | c : DNS request from ('10.55.55.220', 64570) to None: 50 bytes
19:28:18.306 [QUIET] [system.out]  194.3 133 | 2018-03-10T01:28:16+0000 [stdout#info] A query: b'www.us-east-1.prodaa.netflix.com'
19:28:18.306 [QUIET] [system.out]  195.0 133 | 2018-03-10T01:28:16+0000 [-] DNSDatagramProtocol starting on 30481
19:28:18.306 [QUIET] [system.out]  195.0 133 | 2018-03-10T01:28:16+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7f11cc36f780>
19:28:18.307 [QUIET] [system.out]  195.0 133 | 2018-03-10T01:28:16+0000 [-] (UDP Port 31572 Closed)
19:28:18.307 [QUIET] [system.out]  195.0 133 | 2018-03-10T01:28:16+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7f11cc36fb38>
19:28:18.307 [QUIET] [system.out]  195.1 139 | debug1: client_input_global_request: rtype keepalive@openssh.com want_reply 1
19:28:18.307 [QUIET] [system.out]  195.4 137 | debug1: client_input_global_request: rtype keepalive@openssh.com want_reply 1
19:28:18.310 [QUIET] [system.out]  196.0 133 | 2018-03-10T01:28:17+0000 [-] DNSDatagramProtocol starting on 40604
19:28:18.316 [QUIET] [system.out]  196.0 133 | 2018-03-10T01:28:17+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7f11cc36fba8>
19:28:18.318 [QUIET] [system.out]  196.0 133 | 2018-03-10T01:28:17+0000 [-] (UDP Port 2664 Closed)
19:28:18.319 [QUIET] [system.out]  196.0 133 | 2018-03-10T01:28:17+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7f11cc359550>
19:28:18.320 [QUIET] [system.out]  196.0 138 | debug1: client_input_global_request: rtype keepalive@openssh.com want_reply 1
19:28:18.321 [QUIET] [system.out]  196.1 139 | debug1: client_input_global_request: rtype keepalive@openssh.com want_reply 1
19:28:18.323 [QUIET] [system.out]  196.2 145 | c : DNS request from ('10.55.55.220', 56001) to None: 30 bytes
19:28:18.326 [QUIET] [system.out]  196.2 133 | 2018-03-10T01:28:18+0000 [stdout#info] A query: b'www.hulu.com'
19:28:18.326 [QUIET] [system.out]  196.4 137 | debug1: client_input_global_request: rtype keepalive@openssh.com want_reply 1
19:28:18.328 [QUIET] [system.out] Traceback (most recent call last):
19:28:18.343 [QUIET] [system.out]   File "<string>", line 1, in <module>
19:28:18.345 [QUIET] [system.out] socket.gaierror: [Errno 8] nodename nor servname provided, or not known

```

[telepresence.log](https://github.com/datawire/telepresence/files/1798948/telepresence.log)

**Comment by nafeger** [comment]
Something i noticed in the logs:

```  50.0 137 | debug1: key_load_public: No such file or directory
  50.0 137 | debug1: identity file /Users/nfeger/.ssh/id_rsa type -1
  50.0 137 | debug1: key_load_public: No such file or directory
  50.0 137 | debug1: identity file /Users/nfeger/.ssh/id_rsa-cert type -1
  50.0 137 | debug1: key_load_public: No such file or directory
  50.0 137 | debug1: identity file /Users/nfeger/.ssh/id_dsa type -1
  50.0 137 | debug1: key_load_public: No such file or directory
  50.0 137 | debug1: identity file /Users/nfeger/.ssh/id_dsa-cert type -1
  50.0 137 | debug1: key_load_public: No such file or directory
  50.0 137 | debug1: identity file /Users/nfeger/.ssh/id_ecdsa type -1
  50.0 137 | debug1: key_load_public: No such file or directory
  50.0 137 | debug1: identity file /Users/nfeger/.ssh/id_ecdsa-cert type -1
  50.0 137 | debug1: key_load_public: No such file or directory
  50.0 137 | debug1: identity file /Users/nfeger/.ssh/id_ed25519 type -1
  50.0 137 | debug1: key_load_public: No such file or directory
  50.0 137 | debug1: identity file /Users/nfeger/.ssh/id_ed25519-cert type -1
  50.0 137 | debug1: Local version string SSH-2.0-OpenSSH_7.6
```

I do not keep my ssh key in ~/.ssh as I have personal and work keys, so polling for this or using the ~/.ssh/config file might be helpful

**Comment by nafeger** [comment]
okay one more log. I didn't setup the proper environment variables for telepresence to know about minikube, so I did that and got a slightly different error:

```19:39:39.683 [QUIET] [system.out]
19:39:39.683 [QUIET] [system.out] Looks like there's a bug in our code. Sorry about that!
19:39:39.683 [QUIET] [system.out]
19:39:39.683 [QUIET] [system.out] Here's the traceback:
19:39:39.684 [QUIET] [system.out]
19:39:39.686 [QUIET] [system.out] Traceback (most recent call last):
19:39:39.686 [QUIET] [system.out]   File "/usr/local/Cellar/telepresence/0.75/libexec/lib/python3.6/site-packages/telepresence/cli.py", line 73, in call_f
19:39:39.687 [QUIET] [system.out]     return f(*args, **kwargs)
19:39:39.687 [QUIET] [system.out]   File "/usr/local/Cellar/telepresence/0.75/libexec/lib/python3.6/site-packages/telepresence/main.py", line 480, in go
19:39:39.688 [QUIET] [system.out]     runner, args
19:39:39.688 [QUIET] [system.out]   File "/usr/local/Cellar/telepresence/0.75/libexec/lib/python3.6/site-packages/telepresence/main.py", line 297, in start_proxy
19:39:39.688 [QUIET] [system.out]     run_id=run_id,
19:39:39.688 [QUIET] [system.out]   File "/usr/local/Cellar/telepresence/0.75/libexec/lib/python3.6/site-packages/telepresence/remote.py", line 207, in get_remote_info
19:39:39.688 [QUIET] [system.out]     wait_for_pod(runner, remote_info)
19:39:39.688 [QUIET] [system.out]   File "/usr/local/Cellar/telepresence/0.75/libexec/lib/python3.6/site-packages/telepresence/remote.py", line 129, in wait_for_pod
19:39:39.688 [QUIET] [system.out]     "Pod isn't starting or can't be found: {}".format(pod["status"])
19:39:39.689 [QUIET] [system.out] RuntimeError: Pod isn't starting or can't be found: {'conditions': [{'lastProbeTime': None, 'lastTransitionTime': '2018-03-10T01:37:40Z', 'message': 'containers with incomplete status: [ic-service ic-environment]', 'reason': 'ContainersNotInitialized', 'status': 'False', 'type': 'Initialized'}, {'lastProbeTime': None, 'lastTransitionTime': '2018-03-10T01:37:40Z', 'message': 'containers with unready status: [files-upload-service]', 'reason': 'ContainersNotReady', 'status': 'False', 'type': 'Ready'}, {'lastProbeTime': None, 'lastTransitionTime': '2018-03-10T01:37:40Z', 'status': 'True', 'type': 'PodScheduled'}], 'containerStatuses': [{'image': 'datawire/telepresence-k8s:0.75', 'imageID': '', 'lastState': {}, 'name': 'files-upload-service', 'ready': False, 'restartCount': 0, 'state': {'waiting': {'reason': 'PodInitializing'}}}], 'hostIP': '192.168.64.33', 'initContainerStatuses': [{'containerID': 'docker://ee5d091d913584c47a877dc0729cd4f21b1217121dce001d742d4e18f575326a', 'image': 'schoology-docker.jfrog.io/commons-consul:0.1.40', 'imageID': 'docker-pullable://schoology-docker.jfrog.io/commons-consul@sha256:8924                                                                                                                                       15279ff55e4225800c58bc887097e137cbc6848faed0befef749ed828dcd', 'lastState': {}, 'name': 'ic-service', 'ready': False, 'restartCount': 0, 'state': {'running': {'startedAt': '2018-03-10T01:37:52Z'}}}, {'image': 'schoology-docker.jfrog.io/commons-consul:0.1.40', 'imageID': '', 'lastState': {}, 'name': 'ic-environment', 'ready': False, 'restartCount': 0, 'state': {'waiting': {'reason': 'PodInitializing'}}}], 'phase': 'Pending', 'podIP': '172.17.0.28', 'qosClass': 'BestEffort', 'startTime': '2018-03-10T01:37:40Z'}
19:39:39.705 [QUIET] [system.out]
19:39:39.721 [QUIET] [system.out]
19:39:39.721 [QUIET] [system.out] And here are the last few lines of the logfile (see ./telepresence.log for the complete logs):
19:39:39.722 [QUIET] [system.out]
19:39:39.722 [QUIET] [system.out]  124.9 TL | [250] Capturing: (['kubectl', '--v=4', '--context', 'minikube', '--namespace', 'default', 'get', 'pod', 'files-files-upload-service-6d694f8944-bfn72', '-o', 'json'],)...
19:39:39.754 [QUIET] [system.out]  125.0 TL | [250] captured.
19:39:39.754 [QUIET] [system.out]  125.2 TL | [251] Capturing: (['kubectl', '--v=4', '--context', 'minikube', '--namespace', 'default', 'get', 'pod', 'files-files-upload-service-6d694f8944-bfn72', '-o', 'json'],)...
19:39:39.754 [QUIET] [system.out]  125.4 TL | [251] captured.
19:39:39.777 [QUIET] [system.out]  125.7 TL | [252] Capturing: (['kubectl', '--v=4', '--context', 'minikube', '--namespace', 'default', 'get', 'pod', 'files-files-upload-service-6d694f8944-bfn72', '-o', 'json'],)...
19:39:39.777 [QUIET] [system.out]  126.0 TL | [252] captured.
19:39:39.777 [QUIET] [system.out]  126.3 TL | [253] Capturing: (['kubectl', '--v=4', '--context', 'minikube', '--namespace', 'default', 'get', 'pod', 'files-files-upload-service-6d694f8944-bfn72', '-o', 'json'],)...
19:39:39.777 [QUIET] [system.out]  126.5 TL | [253] captured.
19:39:39.777 [QUIET] [system.out]  126.8 TL | [254] Capturing: (['kubectl', '--v=4', '--context', 'minikube', '--namespace', 'default', 'get', 'pod', 'files-files-upload-service-6d694f8944-bfn72', '-o', 'json'],)...
19:39:39.777 [QUIET] [system.out]  126.9 TL | [254] captured.
19:39:39.778 [QUIET] [system.out]  127.2 TL | [255] Capturing: (['kubectl', '--v=4', '--context', 'minikube', '--namespace', 'default', 'get', 'pod', 'files-files-upload-service-6d694f8944-bfn72', '-o', 'json'],)...
19:39:39.778 [QUIET] [system.out]  127.3 TL | [255] captured.
19:39:39.778 [QUIET] [system.out]  127.5 TL | [256] Capturing: (['kubectl', '--v=4', '--context', 'minikube', '--namespace', 'default', 'get', 'pod', 'files-files-upload-service-6d694f8944-bfn72', '-o', 'json'],)...
19:39:39.778 [QUIET] [system.out]  127.7 TL | [256] captured.
19:39:39.778 [QUIET] [system.out]  127.9 TL | [257] Capturing: (['kubectl', '--v=4', '--context', 'minikube', '--namespace', 'default', 'get', 'pod', 'files-files-upload-service-6d694f8944-bfn72', '-o', 'json'],)...
19:39:39.778 [QUIET] [system.out]  128.0 TL | [257] captured.
19:39:39.778 [QUIET] [system.out]  128.3 TL | [258] Capturing: (['kubectl', '--v=4', '--context', 'minikube', '--namespace', 'default', 'get', 'pod', 'files-files-upload-service-6d694f8944-bfn72', '-o', 'json'],)...
19:39:39.779 [QUIET] [system.out]  128.4 TL | [258] captured.
19:39:39.779 [QUIET] [system.out]  128.7 TL | [259] Capturing: (['kubectl', '--v=4', '--context', 'minikube', '--namespace', 'default', 'get', 'pod', 'files-files-upload-service-6d694f8944-bfn72', '-o', 'json'],)...
19:39:39.779 [QUIET] [system.out]  128.8 TL | [259] captured.
19:39:39.779 [QUIET] [system.out]
```
[telepresence.log](https://github.com/datawire/telepresence/files/1798961/telepresence.log)

**Comment by nafeger** [comment]
For posterity this is a 2015 macbook pro, running 10.13.3 os x, minikube

```
nfeger@MacBook-Pro ~/ws/files (test)*$ minikube version
minikube version: v0.25.0
```


```nfeger@MacBook-Pro ~/ws/files (test)*$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2018-01-26T19:04:38Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by ark3** [comment]
Thanks for the detailed bug report. Have you gotten a simpler command to work? How about on a less heavily-loaded cluster? It looks like Telepresence's deployment is not starting.

**Comment by nafeger** [comment]
So I am able to get a telepresence shell working: 

```
nfeger@MacBook-Pro ~/ws/files (test)*$ telepresence --run-shell
Starting proxy with method 'vpn-tcp', which has the following limitations: All processes are affected, only one telepresence can run per machine, and you can't use other VPNs. You may need to add cloud hosts with --also-proxy. For a full list of method limitations see https://telepresence.io/reference/methods.html
Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.

No traffic is being forwarded from the remote Deployment to your local machine. You can use the --expose option to specify which ports you want to forward.

Guessing that Services IP range is 10.96.0.0/12. Services started after this point will be inaccessible if are outside this range; restart telepresence if you can't access a new Service.

@minikube|nfeger@MacBook-Pro ~/ws/files $ curl -X GET http://files-files-metadata-service:9089/healthcheck
{"cassandraHealthCheck":{"healthy":true,"message":"cassandra is running Cassandra 3.11.2"},"consul":{"healthy":true},"deadlocks":{"healthy":true},"thriftServerHealthCheck":{"healthy":true}}
```

**Comment by nafeger** [comment]
[telepresence.log](https://github.com/datawire/telepresence/files/1829691/telepresence.log)

Here is a log file, of me trying to run the gradle command from inside of telepresence. If I'm reading it right it seems like it's having trouble finding the deployment. 

Here is a copy of the deployment: 

```
kubectl get deployment files-files-metadata-service -o yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-03-20T13:41:45Z
  generation: 1
  labels:
    app: files-metadata-service
    chart: files-metadata-service-0.3.5
    context: files
    heritage: Tiller
    release: files
  name: files-files-metadata-service
  namespace: default
  resourceVersion: "40357"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/files-files-metadata-service
  uid: 6e4c70ff-2c44-11e8-95b7-ea90d8533e3e
spec:
  replicas: 1
  selector:
    matchLabels:
      app: files-metadata-service
      release: files
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: files-metadata-service
        release: files
    spec:
      containers:
      - env:
        - name: CONSUL_AGENT_HOST
          value: envy-base-consul
        - name: CONSUL_AGENT_PORT
          value: "8500"
        image: schoology-docker.jfrog.io/file-metadata-service:1.5.5
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthcheck
            port: 9089
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: files-metadata-service
        ports:
        - containerPort: 10089
          name: thrift
          protocol: TCP
        - containerPort: 9089
          name: admin
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - {}
      initContainers:
      - command:
        - bin/SyncConsulKV
        - --consul-agent-host
        - envy-base-consul
        - --consul-agent-port
        - "8500"
        - --key-prefix
        - platform/file/metadata-service
        - --yaml
        - /work-dir/service.yaml
        image: schoology-docker.jfrog.io/commons-consul:0.1.40
        imagePullPolicy: IfNotPresent
        name: ic-service
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /work-dir
          name: service
      - command:
        - bin/SyncConsulKV
        - --consul-agent-host
        - envy-base-consul
        - --consul-agent-port
        - "8500"
        - --key-prefix
        - shared
        - --yaml
        - /work-dir/environment.yaml
        image: schoology-docker.jfrog.io/commons-consul:0.1.40
        imagePullPolicy: IfNotPresent
        name: ic-environment
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /work-dir
          name: environment
      - env:
        - name: CONSUL_AGENT_HOST
          value: envy-base-consul
        - name: CONSUL_AGENT_PORT
          value: "8500"
        image: schoology-docker.jfrog.io/file-metadata-schema-cassandra:1.5.5
        imagePullPolicy: IfNotPresent
        name: apply-schema
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: service.yaml
            path: service.yaml
          name: files-files-metadata-service
        name: service
      - configMap:
          defaultMode: 420
          items:
          - key: environment.yaml
            path: environment.yaml
          name: files-files-metadata-service
        name: environment
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-03-20T13:41:45Z
    lastUpdateTime: 2018-03-20T13:41:45Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

```

Then after running the telepresence command 
```
telepresence --verbose --swap-deployment files-files-metadata-service --expose 8104 --expose 10089 --expose 9089 --run ./gradlew runFileMetadataServiceServer
```

**Comment by ark3** [comment]
Telepresence swaps your deployment successfully. It then loops over all pods to try to find the one with the correct telepresence label. The log file shows that Telepresence is looking for `'telepresence': '78590861-055e-4d01-b745-7bcfb5cbbdeb'`. Oddly, the label that keeps coming back is `'telepresence': 'f23739ee-2c88-46fa-ad22-a3d1752b229c'`. It's as if there's another Telepresence command running somewhere that's fighting this one, and this one lost.

I'm not sure what's going on. Can you try again and pass along the log file once more? I'm sorry that I don't have a better answer yet.

**Comment by nafeger** [comment]
[telepresence.log](https://github.com/datawire/telepresence/files/1830226/telepresence.log)

Here's another log, I tried to clear out and redeploy anything that I might have tried to swap previously and the error seems different now.

Seems like nothing has the telepresence label now:
```
nfeger@MacBook-Pro ~/envy (PE-21883-rest-of-files)*$ kubectl get deployment -l 'telepresence'
No resources found.
```

**Comment by ark3** [comment]
What's the error? The swap, pod-finding, etc. all worked in this trace. The error is not apparent.

I see you're using Minikube. You *may* run into DNS loop issues depending on how your local DNS is set up. I see this problem on my Mac when I'm on the WeWork network at the office, but not on the Comcast network at home. We're working on it...

If you have DNS problems, you can try using a non-local cluster (e.g., [Kubernaut](https://github.com/datawire/kubernaut#quick-start)) or use `--method inject-tcp`, which should work fine with Java code.

**Comment by nafeger** [comment]
So I thought that the process would continue to run in the terminal and I
would see it's output, but it seems like the service is just ending with no
output. But perhaps I'm doing something incorrectly to start the service.

**Comment by ark3** [comment]
Is `gradlew` a shell script? I suspect it starts with `#!/bin/sh` or `#!/usr/bin/env sh` or similar, which _on MacOS_ will cause the inject-tcp method to fail. See [the limitations doc](https://www.telepresence.io/reference/methods.html#limitations---method-inject-tcp) for more information.

**Comment by nafeger** [comment]
Okay I think i finally got this working!

You definitely cannot run gradlew at all. However, this command:

```telepresence --verbose --method=inject-tcp --swap-deployment files-files-metadata-service --expose 9089 --expose 10089 --expose 8089 --run-shell``` will open up a set of ports and swap out a deployment dropping you in a shell.

Then you can mess with your JavaExec command in gradle:

```task runFileMetadataServiceServer(type: JavaExec) {

... Some command stuff here...
   // Add this line:
    println commandLine.join(" ")
}```

Grabbing that command line you can paste it into a text file like:
```
java ARGS ARGS ARGS
```

I needed to add an additional argument:

```
   -Djava.net.preferIPv4Stack=true
```

and boom, my service started.
