### ISSUE TITLE
Telepresence fails when running from a Docker container

### ISSUE THREAD

**Issue by ericbn** [telepresenceio/telepresence#521]
This is the Dockerfile for the image I'm using:

```
FROM ubuntu:xenial

RUN apt-get update && \
    apt-get install -y curl sudo && \
    curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && \
    chmod +x ./kubectl && \
    mv ./kubectl /usr/local/bin/kubectl && \
    curl -s https://packagecloud.io/install/repositories/datawireio/telepresence/script.deb.sh | bash && \
    apt-get install --no-install-recommends -y telepresence
```

When running `telepresence --namespace my-namespace`, this is what I get:

```
Starting proxy with method 'vpn-tcp', which has the following limitations: All processes are affected, only one telepresence can run per machine, and you can't use other VPNs. You may need to add cloud hosts with --also-proxy. For a full list of method limitations see https://telepresence.io/reference/methods.html
Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.

No traffic is being forwarded from the remote Deployment to your local machine. You can use the --expose option to specify which ports you want to forward.

Guessing that Services IP range is 10.111.192.0/19. Services started after this point will be inaccessible if are outside this range; restart telepresence if you can't access a new Service.


Looks like there's a bug in our code. Sorry about that!

Here's the traceback:

Traceback (most recent call last):
  File "/usr/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/cli.py", line 73, in call_f
    return f(*args, **kwargs)
  File "/usr/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/main.py", line 493, in go
    runner, remote_info, args, env, subprocesses, socks_port, ssh
  File "/usr/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/local.py", line 154, in run_local_command
    connect_sshuttle(runner, remote_info, args, subprocesses, env, ssh)
  File "/usr/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/vpn.py", line 241, in connect_sshuttle
    get_hellotelepresence()
  File "/usr/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/vpn.py", line 230, in get_hellotelepresence
    format(next(counter))
  File "/usr/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/runner.py", line 95, in get_output
    result = str(check_output(*args, **kwargs).strip(), "utf-8")
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['python3', '-c', "import socket; socket.gethostbyname('hellotelepresence35')"]' returned non-zero exit status 1


And here are the last few lines of the logfile (see ./telepresence.log for the complete logs):

  90.1 TL | [80] Capturing: (['python3', '-c', "import socket; socket.gethostbyname('hellotelepresence31')"],)...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
socket.gaierror: [Errno -2] Name or service not known
  90.3 TL | [81] Capturing: (['python3', '-c', "import socket; socket.gethostbyname('hellotelepresence32')"],)...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
socket.gaierror: [Errno -2] Name or service not known
  90.6 TL | [82] Capturing: (['python3', '-c', "import socket; socket.gethostbyname('hellotelepresence33')"],)...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
socket.gaierror: [Errno -2] Name or service not known
  90.8 TL | [83] Capturing: (['python3', '-c', "import socket; socket.gethostbyname('hellotelepresence34')"],)...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
socket.gaierror: [Errno -2] Name or service not known
  91.1 TL | [84] Capturing: (['python3', '-c', "import socket; socket.gethostbyname('hellotelepresence35')"],)...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
socket.gaierror: [Errno -2] Name or service not known
```

**EDIT:** I'm starting the container in privileged mode with `docker run --rm -it --privileged my-image`, otherwise telepresence would fail with `fuse: device not found, try 'modprobe fuse' first`

**Comment by richarddli** [comment]
Can you provide more details on what you're trying to do, and how you're trying to do it? Error messages, etc?

**Comment by ericbn** [comment]
@richarddli, I mistakenly hit Cmd-Enter and submitted the issue before being able to add the description. I just updated it. Let me know if more info is needed.

**Comment by ark3** [comment]
What Telepresence command are you running? What is your Kubernetes cluster (local/remote, version)? There are known problems with running the vpn-tcp method from within a container, but the inject-tcp method works well.

**Comment by ericbn** [comment]
@ark3, I'm running `telepresence --namespace my-namespace --run-shell` (or simply `telepresence --namespace my-namespace` that seems to have the same effect)

I tried inject-tcp and got mixed results. It either failed or, when succeeded, it lost the connection after a few minutes.

Failed with:
```
# telepresence --namespace my-namespace --method inject-tcp --run-shell
Starting proxy with method 'inject-tcp', which has the following limitations: Go programs, static binaries, suid programs, and custom DNS implementations are not supported. For a full list of method limitations see https://telepresence.io/reference/methods.html
Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.

No traffic is being forwarded from the remote Deployment to your local machine. You can use the --expose option to specify which ports you want to forward.


Looks like there's a bug in our code. Sorry about that!

Here's the traceback:

Traceback (most recent call last):
  File "/usr/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/cli.py", line 73, in call_f
    return f(*args, **kwargs)
  File "/usr/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/main.py", line 493, in go
    runner, remote_info, args, env, subprocesses, socks_port, ssh
  File "/usr/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/local.py", line 151, in run_local_command
    setup_torsocks(runner, env, socks_port, unsupported_tools_path)
  File "/usr/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/local.py", line 114, in setup_torsocks
    raise RuntimeError("SOCKS network proxying failed to start...")
RuntimeError: SOCKS network proxying failed to start...


And here are the last few lines of the logfile (see ./telepresence.log for the complete logs):

  78.4 123 |   File "<string>", line 1, in <module>
  78.4 123 | socket.gaierror: [Errno -4] Non-recoverable failure in name resolution
  78.4 TL | [124] Running: (['torsocks', 'python3', '-c', "import socket; socket.socket().connect(('google.com', 80))"],)...
[Mar 22 00:24:43] PERROR torsocks[2588]: socks5 libc connect: Connection refused (in socks5_connect() at socks5.c:185)
  78.5 TL | [124] exit 1.
  78.6 124 | Traceback (most recent call last):
  78.6 124 |   File "<string>", line 1, in <module>
  78.6 124 | socket.gaierror: [Errno -4] Non-recoverable failure in name resolution
  78.6 TL | [125] Running: (['torsocks', 'python3', '-c', "import socket; socket.socket().connect(('google.com', 80))"],)...
[Mar 22 00:24:43] PERROR torsocks[2591]: socks5 libc connect: Connection refused (in socks5_connect() at socks5.c:185)
  78.6 TL | [125] exit 1.
  78.7 125 | Traceback (most recent call last):
  78.7 125 |   File "<string>", line 1, in <module>
  78.7 125 | socket.gaierror: [Errno -4] Non-recoverable failure in name resolution
  78.7 TL | [126] Running: (['torsocks', 'python3', '-c', "import socket; socket.socket().connect(('google.com', 80))"],)...
[Mar 22 00:24:43] PERROR torsocks[2594]: socks5 libc connect: Connection refused (in socks5_connect() at socks5.c:185)
  78.8 TL | [126] exit 1.
  78.8 126 | Traceback (most recent call last):
  78.8 126 |   File "<string>", line 1, in <module>
  78.8 126 | socket.gaierror: [Errno -4] Non-recoverable failure in name resolution
```

or lost connection with:
```
Proxy to Kubernetes exited. This is typically due to a lost connection.
exit
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/local.py", line 163, in terminate_if_alive
    mount_cleanup()
  File "/usr/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/remote.py", line 271, in cleanup
    sudo_prefix + ["fusermount", "-z", "-u", mount_dir]
  File "/usr/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/runner.py", line 84, in check_call
    raise CalledProcessError(retcode, args)
subprocess.CalledProcessError: Command '(['fusermount', '-z', '-u', '/tmp/tmpwrt05sv1'],)' returned non-zero exit status 1
```

**Comment by ericbn** [comment]
Here's our Kubernetes remote server version:

> Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.5+coreos.0", GitCommit:"b8e596026feda7b97f4337b115d1a9a250afa8ac", GitTreeState:"clean", BuildDate:"2017-12-12T11:01:08Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by ark3** [comment]
Thanks for your help debugging this. In a networking sense, where is your cluster relative to your container? I'm trying to understand the specifics of the network. 

Can you pass along a gist reference to the telepresence.log from a failing inject-tcp attempt? 

When things succeed, if only for a few minutes, does Telepresence work correctly during that time? For example, are you able to `curl` services in your cluster? E.g.,

```shell
root@39a043ae7c00:~# telepresence --method inject-tcp --run curl -sk https://kubernetes/api/
Starting proxy with method 'inject-tcp', which has the following limitations: Go programs, static binaries, suid programs, and custom DNS implementations are not supported. For a full list of method limitations see https://telepresence.io/reference/methods.html
Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.
 
No traffic is being forwarded from the remote Deployment to your local machine. You can use the --expose option to specify which ports you want to forward.

Mounting remote volumes failed, they will be unavailable in this session. If you are running on Windows Subystem for Linux then see https://github.com/datawire/telepresence/issues/115, otherwise please report a bug, attaching telepresence.log to the bug report: https://github.com/datawire/telepresence/issues/new
{
  "kind": "APIVersions",
  "versions": [
    "v1"
  ],
  "serverAddressByClientCIDRs": [
    {
      "clientCIDR": "0.0.0.0/0",
      "serverAddress": "35.184.xx.xx"
    }
  ]
}root@39a043ae7c00:~# 
```

Note that I'm using an unprivileged container, which is why volume mounting fails. However, this is not a fatal error for Telepresence (because it cannot work on Windows).

**Comment by ericbn** [comment]
The container and the Kubernetes cluster are separated by a VPN connection. When I got the lost connection error, the VPN connection was up and working.

When things succeeded, yes I was able to connect to services running in my cluster.

(I'm afraid the telepresence.log reveals too much about our cluster, which I have to avoid disclosing)

**Comment by ark3** [comment]
I should have remembered this sooner: It turns out that issue #306 talks about running the default (vpn-tcp) method in a container. Please try `apt install iptables` to get past the current error and let me know how it goes. That'll require a privileged container, of course. This is assuming the VPN you just mentioned is running on the Docker daemon host, i.e. not in the container. Otherwise, the underlying `sshuttle` and your VPN will step on each other.

More generally, we still have some thinking to do around the issue of clusters that require a VPN to gain access.

**Comment by ark3** [comment]
Regarding your VPN and network configuration, here is what I'm picturing. There is a private network that contains traditional service hosts  (for Postgres, Kafka, etc.) and a set of Kubernetes nodes. Developers use the VPN client to gain access to this network, at which point they can run tools against those hosts (`psql`, `kubectl`). However, they do not have direct network access to the internals of the Kubernetes cluster, so they cannot, for example, directly reach pod IP addresses. This is what prompts the use of Telepresence.

Is that roughly correct? I want to understand how a typical setup might look so that we can support it better.

Thank you!

**Comment by ericbn** [comment]
@ark3, the scenario you describe is roughly correct. Fortunately we're not being much creative here!  :- )

To able to use a non-privileged container, and also to connect to services from Go applications are requirements we have on our side. So I'll be pausing the assessment of telepresence until we're able to work on them. Thanks for your support!
