### ISSUE TITLE
Telepresence exception created trying to proxy kubernetes

### ISSUE THREAD

**Issue by FrankelJb** [telepresenceio/telepresence#571]
### What were you trying to 

I was trying to run `telepresence` for the first time against a kubernetes cluster using:
`telepresence --deployment myserver --expose 8080 --run-shell`

### What did you expect to happen?

I expected the `telepresence` proxy to be started.

### What happened instead?

The application threw a long exception and the stack trace is below.

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--deployment', 'autocomplete', '--expose', '8080', '--run-shell']`
Version: `0.81`
Python version: `3.6.5 (default, Mar 30 2018, 06:41:53) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]`
kubectl version: `Client Version: v1.8.6 // Server Version: v1.8.8-gke.0`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin MacBook-Pro.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/telepresence/0.81/libexec/lib/python3.6/site-packages/telepresence/remote.py", line 87, in get_deployment_json
    stderr=STDOUT
  File "/usr/local/Cellar/telepresence/0.81/libexec/lib/python3.6/site-packages/telepresence/runner.py", line 277, in get_kubectl
    self.kubectl(context, namespace, args), stderr=stderr
  File "/usr/local/Cellar/telepresence/0.81/libexec/lib/python3.6/site-packages/telepresence/runner.py", line 234, in get_output
    track, "Capturing", "captured", out_cb, err_cb, args, **kwargs
  File "/usr/local/Cellar/telepresence/0.81/libexec/lib/python3.6/site-packages/telepresence/runner.py", line 212, in run_command
    raise CalledProcessError(retcode, args)
subprocess.CalledProcessError: Command '['kubectl', '--context', 'gke_evocative-reef-200110_europe-west1-b_autocomplete', '--namespace', 'default', 'get', 'deployment', '-o', 'json', '--export', 'autocomplete']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/telepresence/0.81/libexec/lib/python3.6/site-packages/telepresence/cli.py", line 74, in call_f
    return f(*args, **kwargs)
  File "/usr/local/Cellar/telepresence/0.81/libexec/lib/python3.6/site-packages/telepresence/main.py", line 494, in go_too
    runner, args
  File "/usr/local/Cellar/telepresence/0.81/libexec/lib/python3.6/site-packages/telepresence/main.py", line 304, in start_proxy
    run_id=run_id,
  File "/usr/local/Cellar/telepresence/0.81/libexec/lib/python3.6/site-packages/telepresence/remote.py", line 161, in get_remote_info
    run_id=run_id
  File "/usr/local/Cellar/telepresence/0.81/libexec/lib/python3.6/site-packages/telepresence/remote.py", line 103, in get_deployment_json
    deployment_name, str(e.stdout, "utf-8")
TypeError: decoding to str: need a bytes-like object, NoneType found

```

Logs:

```
o: {'latest_version': '0.81', 'application': 'telepresence', 'notices': []}
   0.1 TEL | Context: gke_evocative-reef-200110_europe-west1-b_autocomplete, namespace: default, kubectl_command: kubectl
   0.1 TEL | [4] Capturing: kubectl --context gke_evocative-reef-200110_europe-west1-b_autocomplete cluster-info
   0.8   1 | Client Version: v1.8.6
   0.8   1 | Server Version: v1.8.8-gke.0
   0.8 TEL | [1] exit 0
   5.4 TEL | [4] captured in 5.39 secs.
   5.4 TEL | [5] Capturing: ssh -V
   5.6 TEL | [6] Capturing: which torsocks
   5.6 TEL | [7] Capturing: which sshfs
   5.6 TEL | BEGIN SPAN main.py:232(start_proxy)
   5.6 TEL | BEGIN SPAN remote.py:154(get_remote_info)
   5.6 TEL | BEGIN SPAN remote.py:72(get_deployment_json)
   5.6 TEL | [8] Capturing: kubectl --context gke_evocative-reef-200110_europe-west1-b_autocomplete --namespace default get deployment -o json --export autocomplete
   6.4 TEL | [8] exit 1 in 0.87 secs.
   6.4 TEL | END SPAN remote.py:72(get_deployment_json)    0.9s

```

**Comment by ark3** [comment]
Sorry about the crash. Telepresence is running `kubectl [...] get deployment [...] autocomplete` and failing. Can you run that command manually to see why it's failing? Does the `autocomplete` deployment exist? Do things work as expected if you try a simpler setup, such as using `--new-deployment` (the default)?

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
