### ISSUE TITLE
Fast development workflow guide breaks on OpenShift

### ISSUE THREAD

**Issue by concaf** [telepresenceio/telepresence#581]
I was trying out telepresence for the first time, and the docs pointed me to - https://www.telepresence.io/tutorials/docker

The docs say that there is native support for OpenShift, so I was trying it on on my local minishift.

The QOTM example fails on OpenShift because it relies on the UID of the user while OpenShift randomizes the UID for every run.

```console
$ oc logs qotm-1536849512-lrhnp                                                       2018-04-11 08:49:01 QotM 1.3 INFO: initializing on qotm-1536849512-lrhnp:5000
2018-04-11 08:49:01 QotM 1.3 INFO:  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)                                   2018-04-11 08:49:01 QotM 1.3 INFO:  * Restarting with stat     
2018-04-11 08:49:01 QotM 1.3 INFO: initializing on qotm-1536849512-lrhnp:5000                                                  
2018-04-11 08:49:01 QotM 1.3 WARNING:  * Debugger is active! 
Traceback (most recent call last):                                         
  File "qotm/qotm.py", line 237, in <module>                                                                                   
    main()                                                                   
  File "qotm/qotm.py", line 226, in main                                                                                       
    app.run(debug=True, host="0.0.0.0", port=PORT)                
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 841, in run            
    run_simple(host, port, self, **options)                               
  File "/usr/local/lib/python3.6/site-packages/werkzeug/serving.py", line 676, in run_simple
    application = DebuggedApplication(application, use_evalex)
  File "/usr/local/lib/python3.6/site-packages/werkzeug/debug/__init__.py", line 254, in __init__
    if self.pin is None:
  File "/usr/local/lib/python3.6/site-packages/werkzeug/debug/__init__.py", line 264, in _get_pin
    self._pin, self._pin_cookie = get_pin_and_cookie_name(self.app)
  File "/usr/local/lib/python3.6/site-packages/werkzeug/debug/__init__.py", line 144, in get_pin_and_cookie_name
    username = getpass.getuser()
  File "/usr/local/lib/python3.6/getpass.py", line 169, in getuser
    return pwd.getpwuid(os.getuid())[0]
KeyError: 'getpwuid(): uid not found: 1000110000'
```

I then need to run something like - `oc adm policy add-scc-to-user anyuid -n telepresence -z default` to make this work.

Was just curious if the maintainers would be interested to modify the image to support running on OpenShift natively - the changes would be along the lines of https://docs.openshift.com/enterprise/3.2/creating_images/guidelines.html#openshift-enterprise-specific-guidelines

**Comment by richarddli** [comment]
Sorry about that! We did have OpenShift working, but it's possible that OpenShift has changed (our CI tests run against straight Kubernetes). Would be happy to take a PR. Also cc: @mhausenblas who is an informal OpenShift maintainer too ;-).

**Comment by mhausenblas** [comment]
Thanks @containscafeine for raising this issue, the detailed description and even providing a solution, much appreciated! Now, @richarddli it would obviously be good to actually test against OpenShift proper in the CI. Let me know how I can help.

**Comment by richarddli** [comment]
Is there a way to get access to an OpenShift cluster that we can use (we can't run Minishift in CircleCI). Michael, I know you had introduced me to someone (Jason Dobies) and they didn't have a program yet that would fit our needs. I can ping him again (this was October 2017).

**Comment by richarddli** [comment]
I've created #584 to track the CI issue.

**Comment by ark3** [comment]
The crash is a variant of https://bugs.python.org/issue10496. It occurs inside Flask, or really Werkzeug. We need to fix QotM.

**Comment by ark3** [comment]
One approach: https://github.com/chmouel/simple-dockerfile/blob/with-mysql/app.py#L24
