### ISSUE TITLE
Crash when running telepresence

### ISSUE THREAD

**Issue by pankaj-chhabra** [telepresenceio/telepresence#599]
### What were you trying to do?

(please tell us)

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--new-deployment', 'myserver', '--expose', '8080', '--run-shell']`
Version: `0.83`
Python version: `3.6.5 (default, Mar 30 2018, 06:41:53) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]`
kubectl version: `Client Version: v1.9.1 // Server Version: v1.8.0`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin Pankajs-MBP.hsd1.ca.comcast.net 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/telepresence/0.83/libexec/lib/python3.6/site-packages/telepresence/cli.py", line 74, in call_f
    return f(*args, **kwargs)
  File "/usr/local/Cellar/telepresence/0.83/libexec/lib/python3.6/site-packages/telepresence/main.py", line 494, in go_too
    runner, args
  File "/usr/local/Cellar/telepresence/0.83/libexec/lib/python3.6/site-packages/telepresence/main.py", line 271, in start_proxy
    args.deployment, run_id = create_new_deployment(runner, args)
  File "/usr/local/Cellar/telepresence/0.83/libexec/lib/python3.6/site-packages/telepresence/deployment.py", line 85, in create_new_deployment
    runner.get_kubectl(args.context, args.namespace, command)
  File "/usr/local/Cellar/telepresence/0.83/libexec/lib/python3.6/site-packages/telepresence/runner.py", line 292, in get_kubectl
    self.kubectl(context, namespace, args), stderr=stderr
  File "/usr/local/Cellar/telepresence/0.83/libexec/lib/python3.6/site-packages/telepresence/runner.py", line 249, in get_output
    track, "Capturing", "captured", out_cb, err_cb, args, **kwargs
  File "/usr/local/Cellar/telepresence/0.83/libexec/lib/python3.6/site-packages/telepresence/runner.py", line 227, in run_command
    raise CalledProcessError(retcode, args)
subprocess.CalledProcessError: Command '['kubectl', '--context', 'minikube', '--namespace', 'default', 'run', '--restart=Always', '--limits=cpu=100m,memory=256Mi', '--requests=cpu=25m,memory=64Mi', 'myserver', '--image=datawire/telepresence-k8s:0.83', '--labels=telepresence=d3b140e2-98e3-4002-80c8-cafeb93d3157', '--port=8080', '--expose', '--env=TELEPRESENCE_NAMESERVER=8.8.8.8']' returned non-zero exit status 1.

```

Logs:

```
: kubectl
   0.1 TEL | Looks like we're in a local VM, e.g. minikube.
   0.1 TEL | [4] Capturing: kubectl --context minikube cluster-info
   0.1   1 | Client Version: v1.9.1
   0.1   1 | Server Version: v1.8.0
   0.1 TEL | [1] exit 0
   0.1 TEL | [5] Capturing: ssh -V
   0.2 TEL | [6] Capturing: which torsocks
   0.2 TEL | [7] Capturing: which sshfs
   0.2 TEL | BEGIN SPAN main.py:232(start_proxy)
   0.2 TEL | BEGIN SPAN deployment.py:33(create_new_deployment)
   0.2 TEL | [8] Capturing: kubectl --context minikube --namespace default delete --ignore-not-found svc,deploy --selector=telepresence=d3b140e2-98e3-4002-80c8-cafeb93d3157
   0.3 TEL | [9] Capturing: kubectl --context minikube --namespace default run --restart=Always --limits=cpu=100m,memory=256Mi --requests=cpu=25m,memory=64Mi myserver --image=datawire/telepresence-k8s:0.83 --labels=telepresence=d3b140e2-98e3-4002-80c8-cafeb93d3157 --port=8080 --expose --env=TELEPRESENCE_NAMESERVER=8.8.8.8
   0.4 TEL | [9] exit 1 in 0.10 secs.

```

**Comment by ark3** [comment]
Sorry about the crash. It seems that last `kubectl` command (labeled `[9]` in the logs) failed with no apparent output. Could you try running it manually and let us know what happens? Thanks for your help.
