### ISSUE TITLE
Telepresence doesnt resolve the kubernetes service names intermittently on MAC

### ISSUE THREAD

**Issue by vijay-js** [telepresenceio/telepresence#602]
If I start the telepresence with default method in the shell like so 

telepresence --swap-deployment service

Intermittently - the shell would not be able to resolve the kubernetes service names i.e I am not unable to connect to postgres service by service name. This happens intermittently on version 0.82. 

When I try to resolve service name it fails with the error 
** nodename nor servname provided, or not known**

Below is part of  the stack trace 

```
  42.3 TEL | [27] ran in 12.33 secs.
  42.3 TEL | END SPAN remote.py:240(mount_remote_volumes)   12.3s
  52.3 TEL | BEGIN SPAN vpn.py:245(connect_sshuttle)
  52.3 TEL | BEGIN SPAN vpn.py:70(get_proxy_cidrs)
  52.3 TEL | END SPAN vpn.py:70(get_proxy_cidrs)    0.0s
  52.3 TEL | [28] Launching: sshuttle-telepresence -v --dns --method auto -e 'ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -F /dev/null' --to-ns 127.0.0.1:9053 -r telepresence@localhost:57157 10.40.2.0/24 10.43.240.0/20 10.40.1.0/24 10.40.3.0/24
  52.3 TEL | BEGIN SPAN vpn.py:287(connect_sshuttle,sshuttle-wait)
  52.3 TEL | [29] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence0'"'"')'
  52.4  29 | Traceback (most recent call last):
  52.4  29 |   File "<string>", line 1, in <module>
  52.4  29 | socket.gaierror: [Errno 8] nodename nor servname provided, or not known
  52.4 TEL | [29] exit 1 in 0.10 secs.
  52.5  28 | Starting sshuttle proxy.
  52.5 TEL | [30] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence1'"'"')'
  52.6  30 | Traceback (most recent call last):
  52.6  30 |   File "<string>", line 1, in <module>
  52.6  30 | socket.gaierror: [Errno 8] nodename nor servname provided, or not known
  52.6 TEL | [30] exit 1 in 0.09 secs.
  52.7 TEL | [31] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence2'"'"')'
  52.7  28 | firewall manager: Starting firewall with Python version 3.6.5
  52.8  28 | firewall manager: ready method name pf.
  52.8  28 | IPv6 enabled: True
  52.8  28 | UDP enabled: False
  52.8  28 | DNS enabled: True
  52.8  28 | TCP redirector listening on ('::1', 12300, 0, 0).
  52.8  28 | TCP redirector listening on ('127.0.0.1', 12300).
  52.8  28 | DNS listening on ('::1', 12300, 0, 0).
  52.8  28 | DNS listening on ('127.0.0.1', 12300).
  52.8  28 | Starting client with Python version 3.6.5
  52.8  28 | c : connecting to server...
  52.8  15 | Handling connection for 57157
  52.8  31 | Traceback (most recent call last):
  52.8  31 |   File "<string>", line 1, in <module>
  52.8  31 | socket.gaierror: [Errno 8] nodename nor servname provided, or not known
  52.8 TEL | [31] exit 1 in 0.10 secs.
  52.9 TEL | [32] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence3'"'"')'
  53.0  32 | Traceback (most recent call last):
  53.0  32 |   File "<string>", line 1, in <module>
  53.0  32 | socket.gaierror: [Errno 8] nodename nor servname provided, or not known
  53.0 TEL | [32] exit 1 in 0.10 secs.
  53.1 TEL | [33] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence4'"'"')'
  53.2  33 | Traceback (most recent call last):
  53.2  33 |   File "<string>", line 1, in <module>
  53.2  33 | socket.gaierror: [Errno 8] nodename nor servname provided, or not known
  53.3 TEL | [33] exit 1 in 0.10 secs.
  53.4 TEL | [34] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence5'"'"')'
  53.4  34 | Traceback (most recent call last):
  53.4  34 |   File "<string>", line 1, in <module>
  53.4  34 | socket.gaierror: [Errno 8] nodename nor servname provided, or not known
  53.5 TEL | [34] exit 1 in 0.09 secs.
  53.6 TEL | [35] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence6'"'"')'
  53.6  35 | Traceback (most recent call last):
  53.6  35 |   File "<string>", line 1, in <module>
  53.6  35 | socket.gaierror: [Errno 8] nodename nor servname provided, or not known
  53.7 TEL | [35] exit 1 in 0.10 secs.
  53.8 TEL | [36] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence7'"'"')'
  53.8  36 | Traceback (most recent call last):
  53.8  36 |   File "<string>", line 1, in <module>
  53.8  36 | socket.gaierror: [Errno 8] nodename nor servname provided, or not known
  53.9 TEL | [36] exit 1 in 0.10 secs.
  54.0 TEL | [37] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence8'"'"')'
  54.1  37 | Traceback (most recent call last):
  54.1  37 |   File "<string>", line 1, in <module>
  54.1  37 | socket.gaierror: [Errno 8] nodename nor servname provided, or not known
  54.1 TEL | [37] exit 1 in 0.10 secs.
  54.2 TEL | [38] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence9'"'"')'
  54.2  28 | Warning: Permanently added '[localhost]:57157' (ECDSA) to the list of known hosts.
  54.3  38 | Traceback (most recent call last):
  54.3  38 |   File "<string>", line 1, in <module>
  54.3  38 | socket.gaierror: [Errno 8] nodename nor servname provided, or not known
  54.3 TEL | [38] exit 1 in 0.10 secs.
  54.4 TEL | [39] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence10'"'"')'
  54.5  39 | Traceback (most recent call last):
  54.5  39 |   File "<string>", line 1, in <module>
  54.5  39 | socket.gaierror: [Errno 8] nodename nor servname provided, or not known
  54.5 TEL | [39] exit 1 in 0.10 secs.
  54.6 TEL | [40] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence11'"'"')'
  54.7  40 | Traceback (most recent call last):
  54.7  40 |   File "<string>", line 1, in <module>
  54.7  40 | socket.gaierror: [Errno 8] nodename nor servname provided, or not known
  54.7 TEL | [40] exit 1 in 0.10 secs.
  54.8 TEL | [41] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence12'"'"')'
  54.9  41 | Traceback (most recent call last):
  54.9  41 |   File "<string>", line 1, in <module>
  54.9  41 | socket.gaierror: [Errno 8] nodename nor servname provided, or not known
  54.9 TEL | [41] exit 1 in 0.10 secs.
  55.0 TEL | [42] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence13'"'"')'
  55.1  42 | Traceback (most recent call last):
  55.1  42 |   File "<string>", line 1, in <module>
  55.1  42 | socket.gaierror: [Errno 8] nodename nor servname provided, or not known
  55.1 TEL | [42] exit 1 in 0.10 secs.
  55.2 TEL | [43] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence14'"'"')'
  55.3  43 | Traceback (most recent call last):
  55.3  43 |   File "<string>", line 1, in <module>
  55.3  43 | socket.gaierror: [Errno 8] nodename nor servname provided, or not known
  55.3 TEL | [43] exit 1 in 0.10 secs.
  55.4 TEL | [44] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence15'"'"')'
  55.5  44 | Traceback (most recent call last):
  55.5  44 |   File "<string>", line 1, in <module>
  55.5  44 | socket.gaierror: [Errno 8] nodename nor servname provided, or not known
  55.5 TEL | [44] exit 1 in 0.10 secs.
  55.6 TEL | [45] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence16'"'"')'
  55.7  28 | Starting server with Python version 3.6.1
  55.7  28 |  s: latency control setting = True
  55.7  28 |  s: available routes:
  55.7  28 |  s:   2/10.40.3.0/24
  55.7  28 | c : Connected.
  55.7  45 | Traceback (most recent call last):
  55.7  45 |   File "<string>", line 1, in <module>
  55.7  45 | socket.gaierror: [Errno 8] nodename nor servname provided, or not known
  55.7  28 | firewall manager: setting up.
  55.7  28 | >> pfctl -s Interfaces -i lo -v
  55.7 TEL | [45] exit 1 in 0.10 secs.

```

**Comment by ark3** [comment]
We are working on a DNS-related issue in Telepresence on the Mac with the default method (vpn-tcp) in #560. We will address this issue in the next release. I'm not sure whether you're seeing the same issue, but could you please try the workaround mentioned in https://github.com/datawire/telepresence/issues/560#issuecomment-382130657 as a test? 

Thanks for your help.

**Comment by vijay-js** [comment]
If the work around is clearing the cache by running
```
sudo killall -HUP mDNSResponder
```
Unfortunately this also is working intermittently only

**Comment by Adverbly** [comment]
Another workaround that I use is to just use the service's ip instead of it's name. I found that nslookup still works so you can run that to get the service ip.

**Comment by Lugghawk** [comment]
I found that during the install call, because I needed `sudo` to call it, the `~/.pex` directory was owned by root. Above the copied part of the stacktrace I found this:

```
 20.3  36 | PermissionError: [Errno 13] Permission denied: '/Users/me/.pex/install'
```

After chowning that directory and its contents to me, the process worked fine for me.

**Comment by willaustin** [comment]
We're experiencing this as well. Clearing the cache fixed the issue for us. I think this is more of an issue with Mac caching DNS.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
