### ISSUE TITLE
Add option to use a bridge other than docker0

### ISSUE THREAD

**Issue by mingfang** [telepresenceio/telepresence#647]
On my cluster I use a bridge named kbr0 instead of the default docker0.
Telepresence is not working because it's hardcoded to use docker0.
I need an option to change the bridge.

**Comment by ark3** [comment]
Are you getting “No interface for docker found” from Telepresence?

**Comment by mingfang** [comment]
Here is the entire error
```
telepresence --docker-run -i -t alpine /bin/sh
Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.


Looks like there's a bug in our code. Sorry about that!

Here's the traceback:

Traceback (most recent call last):
  File "/usr/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/cli.py", line 87, in call_f
    return f(*args, **kwargs)
  File "/usr/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/main.py", line 79, in main
    subprocesses, socks_port, ssh = connect(runner, remote_info, args)
  File "/usr/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/proxy.py", line 84, in connect
    runner.get_output(["ip", "addr", "show", "dev", "docker0"])
  File "/usr/share/telepresence/libexec/lib/python3.5/site-packages/telepresence/runner.py", line 193, in get_output
    raise CalledProcessError(cpe_exc.returncode, cpe_exc.cmd, output)
subprocess.CalledProcessError: Command '['ip', 'addr', 'show', 'dev', 'docker0']' returned non-zero exit status 1


And here are the last few lines of the logfile (see /mnt/ceph/deploy/telepresence.log for the complete logs):

   2.9 TEL | [18] Capturing: kubectl --context default --namespace default get pod telepresence-1526604364-6290517-1167298-7ccf5944fc-448hx -o json
   3.3 TEL | [19] Capturing: kubectl --context default --namespace default get pod telepresence-1526604364-6290517-1167298-7ccf5944fc-448hx -o json
   3.6 TEL | [20] Capturing: kubectl --context default --namespace default get pod telepresence-1526604364-6290517-1167298-7ccf5944fc-448hx -o json
   4.0 TEL | [21] Capturing: kubectl --context default --namespace default get pod telepresence-1526604364-6290517-1167298-7ccf5944fc-448hx -o json
   4.4 TEL | [22] Capturing: kubectl --context default --namespace default get pod telepresence-1526604364-6290517-1167298-7ccf5944fc-448hx -o json
   4.7 TEL | [23] Capturing: kubectl --context default --namespace default get pod telepresence-1526604364-6290517-1167298-7ccf5944fc-448hx -o json
   5.0 TEL | [24] Capturing: kubectl --context default --namespace default get pod telepresence-1526604364-6290517-1167298-7ccf5944fc-448hx -o json
   5.4 TEL | [25] Capturing: kubectl --context default --namespace default get pod telepresence-1526604364-6290517-1167298-7ccf5944fc-448hx -o json
   5.7 TEL | [26] Capturing: kubectl --context default --namespace default get pod telepresence-1526604364-6290517-1167298-7ccf5944fc-448hx -o json
   6.0 TEL | [27] Capturing: kubectl --context default --namespace default get pod telepresence-1526604364-6290517-1167298-7ccf5944fc-448hx -o json
   6.4 TEL | [28] Capturing: kubectl --context default --namespace default get pod telepresence-1526604364-6290517-1167298-7ccf5944fc-448hx -o json
   6.5 TEL | END SPAN remote.py:122(wait_for_pod)    5.8s
   6.5 TEL | END SPAN remote.py:164(get_remote_info)    5.9s
   6.5 TEL | END SPAN proxy.py:150(start_proxy)    6.1s
   6.5 TEL | BEGIN SPAN proxy.py:42(connect)
   6.5 TEL | [29] Launching: kubectl --context default --namespace default logs -f telepresence-1526604364-6290517-1167298-7ccf5944fc-448hx --container telepresence-1526604364-6290517-1167298
   6.5 TEL | [30] Launching: kubectl --context default --namespace default port-forward telepresence-1526604364-6290517-1167298-7ccf5944fc-448hx 40432:8022
   6.5 TEL | [31] Capturing: ip addr show dev docker0
   6.5  31 | Device "docker0" does not exist.
   6.5 TEL | [31] exit 1 in 0.00 secs.

Would you like to file an issue in our issue tracker? You'll be able to review and edit before anything is posted to the public. We'd really appreciate the help improving our product. [Y/n]:
```

**Comment by ark3** [comment]
Gotcha, thanks. 

Note to self: http://murat1985.github.io/kubernetes/cni/2016/05/14/netns-and-cni.html

**Comment by ark3** [comment]
Telepresence 0.95 includes #726, and thus does not use docker0 or a network-level bridge any longer. As such, this is no longer an issue. Closing.
