### ISSUE TITLE
Ensure Telepresence quick start works on OpenShift

### ISSUE THREAD

**Issue by ghost** [telepresenceio/telepresence#663]
I followed the [OpenShift example for using Telepresence for local development](https://blog.openshift.com/telepresence-local-development/), however, the local development part does not work for me:
```
$ oc new-app --docker-image=datawire/hello-world --name=hello-world
[...]
$ oc expose service hello-world
[...]
$ telepresence --swap-deployment hello-world --expose 8000
Starting proxy with method 'vpn-tcp', which has the following limitations: All processes are affected, only one telepresence can run per machine, and you can't use other VPNs. You may need to add cloud hosts with --also-proxy. For a full list of method limitations see https://telepresence.io/reference/methods.html
Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.

Forwarding remote port 8000 to local port 8000.

[sudo] ...
Guessing that Services IP range is 172.30.0.0/16. Services started after this point will be inaccessible if are outside this range; restart telepresence if you can't access a new Service.                                                                                     

@myproject/192-168-42-26:8443/developer|bash-4.4$ python3 helloworld.py
Proxy to Kubernetes exited. This is typically due to a lost connection.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/share/telepresence/libexec/lib64/python3.6/site-packages/telepresence/mount.py", line 82, in cleanup
    sudo_prefix + ["fusermount", "-z", "-u", mount_dir]
  File "/usr/share/telepresence/libexec/lib64/python3.6/site-packages/telepresence/runner.py", line 168, in check_call
    track, "Running", "ran", out_cb, err_cb, args, **kwargs
  File "/usr/share/telepresence/libexec/lib64/python3.6/site-packages/telepresence/runner.py", line 157, in run_command
    raise CalledProcessError(retcode, args)
subprocess.CalledProcessError: Command '['fusermount', '-z', '-u', '/tmp/tmpu8kts5av']' returned non-zero exit status 1.
```

Afterwards, the same command will fail with another error:
```
$ telepresence --swap-deployment hello-world --expose 8000
Starting proxy with method 'vpn-tcp', which has the following limitations: All processes are affected, only one telepresence can run per machine, and you can't use other VPNs. You may need to add cloud hosts with --also-proxy. For a full list of method limitations see https://telepresence.io/reference/methods.html
Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.

Error from server (NotFound): pods "hello-world-1-t7ng2" not found
[ ... repeats infinitely ... ]
$ oc get pods
NAME                  READY     STATUS    RESTARTS   AGE
hello-world-2-w8s68   1/1       Running   0          19m
```

OpenShift was installed via MiniShift.

```
$ minishift version
minishift v1.17.0+f974f0c
$ oc version
oc v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.42.26:8443
openshift v3.9.0+46ff3a0-18
kubernetes v1.9.1+a0ce1bc657
$ telepresence --version
0.88
```

**Comment by donnyyung** [comment]
We should validate that our quickstart for Telepresence works on OpenShift clusters
