### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by killoblanco** [telepresenceio/telepresence#665]
### What were you trying to do?
connect to telepresence

### What did you expect to happen?
be connected to telepresece

### What happened instead?
it broken

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--swap-deployment', 'api-gateway-deployment', '--expose', '6378', '--run', 'npm', 'run', 'dev']`
Version: `0.88`
Python version: `3.6.5 (default, Apr 25 2018, 14:23:58) 
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]`
kubectl version: `Client Version: v1.8.6 // Server Version: v1.9.7-gke.0`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin Kamilos-MacBook-Pro.local 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/telepresence/0.88/libexec/lib/python3.6/site-packages/telepresence/cli.py", line 87, in call_f
    return f(*args, **kwargs)
  File "/usr/local/Cellar/telepresence/0.88/libexec/lib/python3.6/site-packages/telepresence/main.py", line 110, in main
    mount_dir
  File "/usr/local/Cellar/telepresence/0.88/libexec/lib/python3.6/site-packages/telepresence/local.py", line 167, in run_local_command
    connect_sshuttle(runner, remote_info, args, subprocesses, env, ssh)
  File "/usr/local/Cellar/telepresence/0.88/libexec/lib/python3.6/site-packages/telepresence/vpn.py", line 313, in connect_sshuttle
    get_hellotelepresence()
  File "/usr/local/Cellar/telepresence/0.88/libexec/lib/python3.6/site-packages/telepresence/vpn.py", line 297, in get_hellotelepresence
    format(next(counter))
  File "/usr/local/Cellar/telepresence/0.88/libexec/lib/python3.6/site-packages/telepresence/runner.py", line 193, in get_output
    raise CalledProcessError(cpe_exc.returncode, cpe_exc.cmd, output)
subprocess.CalledProcessError: Command '['python3', '-c', "import socket; socket.gethostbyname('hellotelepresence65')"]' returned non-zero exit status 1.

```

Logs:

```
 socket; socket.gethostbyname('"'"'hellotelepresence63'"'"')'
  57.1 108 | Traceback (most recent call last):
  57.1 108 |   File "<string>", line 1, in <module>
  57.1 108 | socket.gaierror: [Errno 8] nodename nor servname provided, or not known
  57.1 TEL | [108] exit 1 in 0.08 secs.
  57.2 TEL | [109] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence64'"'"')'
  57.6 109 | Traceback (most recent call last):
  57.6 109 |   File "<string>", line 1, in <module>
  57.6 109 | socket.gaierror: [Errno 8] nodename nor servname provided, or not known
  57.6 TEL | [109] exit 1 in 0.41 secs.
  58.7 TEL | [110] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence65'"'"')'
  59.0  16 | Handling connection for 64611
  59.2 110 | Traceback (most recent call last):
  59.2 110 |   File "<string>", line 1, in <module>
  59.2 110 | socket.gaierror: [Errno 8] nodename nor servname provided, or not known
  59.2 TEL | [110] exit 1 in 0.47 secs.

```

**Comment by ark3** [comment]
Sorry about the crash! Can you link to a gist of the full telepresence.log? That will help us figure out what went wrong. Thanks for your help.
