### ISSUE TITLE
Running Hello World example in OpenShift(MiniShift)

### ISSUE THREAD

**Issue by lordofthejars** [telepresenceio/telepresence#666]
Currently, I am following https://blog.openshift.com/telepresence-local-development/ with telepresence 0.88, minishift 1.13.1, Openshift 3.9 and oc client and kubectl installed.

The problem that I am facing is that when I run _telepresence --swap-deployment hello-world --expose 8000_ then it seems that everything works as expected:

_Forwarding remote port 8000 to local port 8000.

Password:
Guessing that Services IP range is 172.30.0.0/16. Services started after this point will be inaccessible if are outside this range; restart telepresence if you can't access a new Service.

@myproject/192-168-64-38:8443/developer|bash-3.2_ 

But after 10 seconds I get:

_Proxy to Kubernetes exited. This is typically due to a lost connection.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/Cellar/telepresence/0.88/libexec/lib/python3.6/site-packages/telepresence/mount.py", line 85, in cleanup
    runner.get_output(sudo_prefix + ["umount", "-f", mount_dir])
  File "/usr/local/Cellar/telepresence/0.88/libexec/lib/python3.6/site-packages/telepresence/runner.py", line 193, in get_output
    raise CalledProcessError(cpe_exc.returncode, cpe_exc.cmd, output)
subprocess.CalledProcessError: Command '['umount', '-f', '/tmp/tmpvq8wkd5r']' returned non-zero exit status 1._

I don't know if someone else has faced the same problem, or if the problem is that Minishift and Telepresence do not work pretty well together.

Thank you very much.

**Comment by lordofthejars** [comment]
@ mhausenblas this is the problem I found when running telepresence with OpenShift.
