### ISSUE TITLE
Telepresence crashes when running the tutorial,

### ISSUE THREAD

**Issue by hbouvier** [telepresenceio/telepresence#668]
### What were you trying to do?

trying the tutorial
```
kubectl run myservice --image=datawire/hello-world --port=8000 --expose
telepresence --run-shell
```

### What did you expect to happen?

have a shell to `curl` the myservice

### What happened instead?

**There was a Kaboom, an earth shattering kaboom**

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--run-shell']`
Version: `0.88`
Python version: `3.6.5 (default, Apr 25 2018, 14:22:56) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]`
kubectl version: `Client Version: v1.9.6 // Server Version: v1.9.4`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin BB-8.local 15.6.0 Darwin Kernel Version 15.6.0: Tue Jan 30 11:45:51 PST 2018; root:xnu-3248.73.8~1/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/telepresence/0.88/libexec/lib/python3.6/site-packages/telepresence/cli.py", line 87, in call_f
    return f(*args, **kwargs)
  File "/usr/local/Cellar/telepresence/0.88/libexec/lib/python3.6/site-packages/telepresence/main.py", line 110, in main
    mount_dir
  File "/usr/local/Cellar/telepresence/0.88/libexec/lib/python3.6/site-packages/telepresence/local.py", line 167, in run_local_command
    connect_sshuttle(runner, remote_info, args, subprocesses, env, ssh)
  File "/usr/local/Cellar/telepresence/0.88/libexec/lib/python3.6/site-packages/telepresence/vpn.py", line 313, in connect_sshuttle
    get_hellotelepresence()
  File "/usr/local/Cellar/telepresence/0.88/libexec/lib/python3.6/site-packages/telepresence/vpn.py", line 297, in get_hellotelepresence
    format(next(counter))
  File "/usr/local/Cellar/telepresence/0.88/libexec/lib/python3.6/site-packages/telepresence/runner.py", line 193, in get_output
    raise CalledProcessError(cpe_exc.returncode, cpe_exc.cmd, output)
subprocess.CalledProcessError: Command '['python3', '-c', "import socket; socket.gethostbyname('hellotelepresence4')"]' returned non-zero exit status 1.

```

Logs:

```
.13:9200: deleting (590 remain)
  56.3  32 | c : SW#309:10.0.1.7:63456: deleting (593 remain)
  56.3  32 | c : SW'unknown':Mux#312: deleting (592 remain)
  56.9  32 | c : SW#287:10.0.1.7:63431: deleting (591 remain)
  56.9  32 | c : SW'unknown':Mux#290: deleting (590 remain)
  57.0  32 |  s: SW'unknown':Mux#305: deleting (589 remain)
  57.0  32 |  s: SW#299:10.98.254.13:9200: deleting (588 remain)
  57.0  32 |  s: SW'unknown':Mux#290: deleting (587 remain)
  57.0  32 |  s: SW#284:10.98.254.13:9200: deleting (586 remain)
  57.0  32 |  s: SW'unknown':Mux#281: deleting (585 remain)
  57.0  32 |  s: SW#275:10.98.254.13:9200: deleting (584 remain)
  57.0  32 |  s: SW'unknown':Mux#312: deleting (583 remain)
  57.0  32 |  s: SW#306:10.98.254.13:9200: deleting (582 remain)
  57.0  37 | Traceback (most recent call last):
  57.0  37 |   File "<string>", line 1, in <module>
  57.0  37 | socket.gaierror: [Errno 8] nodename nor servname provided, or not known
  57.0 TEL | [37] exit 1 in 5.15 secs.

```

**Comment by ark3** [comment]
Sorry about the crash! A shattered earth/Telepresence session is not good for anyone. 😉 

Judging by the bit of the log that gets posted, it looks like `sshuttle` is busy doing something unusual while Telepresence is trying to get DNS working. 

1. Can you pass me more/all of your telepresence.log as a Gist link? 
2. Is there anything interesting or unusual about your network setup? 
3. We want to get the default (vpn-tcp) method working, but can you try the other methods as a sanity check? E.g., `telepresence --run-shell --method inject-tcp`

Thanks for your help.
