### ISSUE TITLE
Telepresence does not respect CLI options for context and namespace.

### ISSUE THREAD

**Issue by asheidan** [telepresenceio/telepresence#683]
### What were you trying to do?

Trying to replace a pod in a deployment

### What did you expect to happen?

(see above)

### What happened instead?

Telepresence tried to run kubectl get pods -o json without context and namespace eventhough I hade supplied them on the command-line.

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--context', 'ucp-prod-cluster', '--namespace', 'playground', '--swap-deployment', 'playground-distribution-erik-web:distribution-portal', '--expose', '80', '--docker-run', '-i', '-t', '-v=/Users/emieri/Documents/Codemill/Pro7/telepresence-wrapper/.license:/ucp/license-secrets', '-v=/Users/emieri/Documents/Codemill/Pro7/telepresence-wrapper/.pycharm_helpers:/root/.pycharm_helpers', '-e', 'PORTAL_ROLE=webdev', '-p', '2222:22', 'portal-telepresence', '/docker-entrypoint.sh']`
Version: `0.89`
Python version: `3.6.5 (default, Apr 27 2018, 15:03:36) 
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]`
kubectl version: `Client Version: v1.10.4 // Server Version: v1.9.6`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin skrutten.local 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/telepresence/0.89/libexec/lib/python3.6/site-packages/telepresence/vpn.py", line 172, in podCIDRs
    runner.kubectl_cmd, "get", "nodes", "-o", "json"
  File "/usr/local/Cellar/telepresence/0.89/libexec/lib/python3.6/site-packages/telepresence/runner.py", line 193, in get_output
    raise CalledProcessError(cpe_exc.returncode, cpe_exc.cmd, output)
subprocess.CalledProcessError: Command '['kubectl', 'get', 'nodes', '-o', 'json']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/telepresence/0.89/libexec/lib/python3.6/site-packages/telepresence/cli.py", line 87, in call_f
    return f(*args, **kwargs)
  File "/usr/local/Cellar/telepresence/0.89/libexec/lib/python3.6/site-packages/telepresence/main.py", line 105, in main
    mount_dir,
  File "/usr/local/Cellar/telepresence/0.89/libexec/lib/python3.6/site-packages/telepresence/container.py", line 107, in run_docker_command
    runner, args, remote_info, remote_env["KUBERNETES_SERVICE_HOST"]
  File "/usr/local/Cellar/telepresence/0.89/libexec/lib/python3.6/site-packages/telepresence/vpn.py", line 92, in get_proxy_cidrs
    ).lookup("podCIDRs", lambda: podCIDRs(runner))
  File "/usr/local/Cellar/telepresence/0.89/libexec/lib/python3.6/site-packages/telepresence/cache.py", line 106, in lookup
    value = function()
  File "/usr/local/Cellar/telepresence/0.89/libexec/lib/python3.6/site-packages/telepresence/vpn.py", line 92, in <lambda>
    ).lookup("podCIDRs", lambda: podCIDRs(runner))
  File "/usr/local/Cellar/telepresence/0.89/libexec/lib/python3.6/site-packages/telepresence/vpn.py", line 180, in podCIDRs
    runner.kubectl_cmd, "get", "pods", "-o", "json"
  File "/usr/local/Cellar/telepresence/0.89/libexec/lib/python3.6/site-packages/telepresence/runner.py", line 193, in get_output
    raise CalledProcessError(cpe_exc.returncode, cpe_exc.cmd, output)
subprocess.CalledProcessError: Command '['kubectl', 'get', 'pods', '-o', 'json']' returned non-zero exit status 1.

```

Logs:

```
2T11:41:21+0000 [Poll#info] Checkpoint
 161.2 TEL | (proxy checking local liveness)
 161.3  28 | 2018-06-12T11:41:51+0000 [Poll#info] Checkpoint
 180.8  36 | Unable to connect to the server: dial tcp 192.168.99.101:8443: i/o timeout
 180.8 TEL | [36] exit 1 in 120.07 secs.
 180.8 TEL | Failed to get nodes: Command '['kubectl', 'get', 'nodes', '-o', 'json']' returned non-zero exit status 1.
 180.8 TEL | [37] Capturing: kubectl get pods -o json
 191.2 TEL | (proxy checking local liveness)
 191.2  28 | 2018-06-12T11:42:21+0000 [Poll#info] Checkpoint
 221.2 TEL | (proxy checking local liveness)
 221.2  28 | 2018-06-12T11:42:51+0000 [Poll#info] Checkpoint
 251.2

**Comment by ark3** [comment]
Yup, this is #365. I'm sorry we haven't fixed this yet. I expect to touch this code as part of my work on #264 and will likely be able to fix it at the same time. Thanks for the bug report.

**Comment by ark3** [comment]
The `kubectl` stuff should have been fixed in #706. Release coming soon...
