### ISSUE TITLE
No such file or directory: 'sshuttle-telepresence'

### ISSUE THREAD

**Issue by Gawen** [telepresenceio/telepresence#697]
Hey!

### What were you trying to do?

I was following [this tutorial](https://www.telepresence.io/tutorials/docker), executing the following command on my GCP Kubernetes cluster.

```bash
telepresence --docker-run -i -t alpine /bin/sh
```

The same traceback appears even if running `telepresence` without any arguments.

```bash
telepresence
```

### What did you expect to happen?

`/bin/sh` prompt appears.

### What happened instead?

Traceback was raised.

Note the following appeared in the log. I don't know if this is important.

```
sudo: no tty present and no askpass program specified
```

### Automatically included information

Command line: `['/opt/telepresence/telepresence-venv/bin/telepresence']`
Version: `0.88`
Python version: `3.6.5 (default, May 11 2018, 04:00:52) 
[GCC 8.1.0]`
kubectl version: `Client Version: v1.10.0 // Server Version: v1.8.10-gke.0`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux XXX 4.17.2-1-ARCH #1 SMP PREEMPT Sat Jun 16 11:08:59 UTC 2018 x86_64 GNU/Linux`
Traceback:

```
Traceback (most recent call last):
  File "/opt/telepresence/telepresence-venv/lib/python3.6/site-packages/telepresence/cli.py", line 87, in call_f
    return f(*args, **kwargs)
  File "/opt/telepresence/telepresence-venv/lib/python3.6/site-packages/telepresence/main.py", line 110, in main
    mount_dir
  File "/opt/telepresence/telepresence-venv/lib/python3.6/site-packages/telepresence/local.py", line 167, in run_local_command
    connect_sshuttle(runner, remote_info, args, subprocesses, env, ssh)
  File "/opt/telepresence/telepresence-venv/lib/python3.6/site-packages/telepresence/vpn.py", line 281, in connect_sshuttle
    runner, args, remote_info, env["KUBERNETES_SERVICE_HOST"]
  File "/opt/telepresence/telepresence-venv/lib/python3.6/site-packages/telepresence/runner.py", line 208, in popen
    track, out_cb, err_cb, args, done=done, **kwargs
  File "/opt/telepresence/telepresence-venv/lib/python3.6/site-packages/telepresence/runner.py", line 138, in launch_command
    process = launch_command(args, out_cb, err_cb, **kwargs)
  File "/opt/telepresence/telepresence-venv/lib/python3.6/site-packages/telepresence/runner.py", line 274, in launch_command
    process = Popen(args, **kwargs)
  File "/usr/lib64/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sshuttle-telepresence': 'sshuttle-telepresence'

```

Logs:

```
ol object at 0x7f0fa204a0b8>
  12.9  14 | 2018-07-03T16:00:41+0000 [-] Loaded.
  13.1  14 | 2018-07-03T16:00:41+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 18.4.0 (/usr/bin/python3.6 3.6.1) starting up.
  13.1  14 | 2018-07-03T16:00:41+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.epollreactor.EPollReactor.
  13.8 TEL | [25] captured in 1.68 secs.
  13.8 TEL | END SPAN mount.py:36(mount_remote_volumes)    1.7s
  13.9 TEL | BEGIN SPAN vpn.py:258(connect_sshuttle)
  13.9 TEL | BEGIN SPAN vpn.py:84(get_proxy_cidrs)
  13.9 TEL | END SPAN vpn.py:84(get_proxy_cidrs)    0.0s
  13.9 TEL | [26] Launching: sshuttle-telepresence -v --dns --method nat -e 'ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -F /dev/null' --to-ns 127.0.0.1:9053 -r telepresence@localhost:42575 10.32.7.0/24 10.32.4.0/24 10.35.240.0/20 10.32.6.0/24
  13.9 TEL | [26] [Errno 2] No such file or directory: 'sshuttle-telepresence': 'sshuttle-telepresence'

```

**Comment by Gawen** [comment]
Not reproduced with version v0.90 built from the source.

**Comment by jtyers** [comment]
Just for the benefit of others getting this issue, I encountered it on `telepresence v0.88` (the version in the Arch Linux community repo, at the time of writing). Installing `telepresence-git` from AUR (`v0.92-23-gae861e8` currently) fixes the issue.
