### ISSUE TITLE
subprocess.CalledProcessError: Command '['python3', '-c', "import socket; socket.gethostbyname('hellotelepresence95')"]' returned non-zero exit status 1

### ISSUE THREAD

**Issue by rizdaputra** [telepresenceio/telepresence#715]
### What were you trying to do?

run `telepresence`

### Automatically included information

Command line: `['/usr/local/bin/telepresence']`
Version: `0.90-41-g6ec4c30`
Python version: `3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0]`
kubectl version: `Client Version: v1.8.6 // Server Version: v1.9.6-gke.1`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux putra-Lenovo-IdeaPad-Z410 4.15.0-22-generic #24-Ubuntu SMP Wed May 16 12:15:17 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 129, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 95, in main
    runner, remote_info, args, env, socks_port, ssh
  File "/usr/local/bin/telepresence/telepresence/local.py", line 168, in run_local_command
    connect_sshuttle(runner, remote_info, args, env, ssh)
  File "/usr/local/bin/telepresence/telepresence/vpn.py", line 304, in connect_sshuttle
    get_hellotelepresence()
  File "/usr/local/bin/telepresence/telepresence/vpn.py", line 288, in get_hellotelepresence
    format(next(counter))
  File "/usr/local/bin/telepresence/telepresence/runner.py", line 223, in get_output
    raise CalledProcessError(cpe_exc.returncode, cpe_exc.cmd, output)
subprocess.CalledProcessError: Command '['python3', '-c', "import socket; socket.gethostbyname('hellotelepresence95')"]' returned non-zero exit status 1.

```

Logs:

```
ot known
  45.5 TEL | [121] exit 1 in 0.11 secs.
  45.6 TEL | [122] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence93'"'"')'
  45.7 122 | Traceback (most recent call last):
  45.7 122 |   File "<string>", line 1, in <module>
  45.7 122 | socket.gaierror: [Errno -2] Name or service not known
  45.7 TEL | [122] exit 1 in 0.11 secs.
  45.8 TEL | [123] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence94'"'"')'
  45.9 123 | Traceback (most recent call last):
  45.9 123 |   File "<string>", line 1, in <module>
  45.9 123 | socket.gaierror: [Errno -2] Name or service not known
  45.9 TEL | [123] exit 1 in 0.11 secs.
  47.0 TEL | [124] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence95'"'"')'
  47.1 124 | Traceback (most recent call last):
  47.1 124 |   File "<string>", line 1, in <module>
  47.1 124 | socket.gaierror: [Errno -2] Name or service not known
  47.1 TEL | [124] exit 1 in 0.12 secs.

```

**Comment by ark3** [comment]
Sorry about the crash! I'll need to see more of the log file to diagnose this. Could you pass along telepresence.log as a gist? Thanks!
