### ISSUE TITLE
Swapping deployment with localhost docker-compose running container.

### ISSUE THREAD

**Issue by Bedotech** [telepresenceio/telepresence#718]
### What were you trying to do?

Just swapping a deployment

### What did you expect to happen?

to swap the deploy

### What happened instead?

open this windows and exit.

### Automatically included information

Command line: `['/opt/telepresence/telepresence-venv/bin/telepresence', '--namespace', 'criptalia-dev', '--swap-deployment', 'harvey-development', '--expose', '80']`
Version: `0.88`
Python version: `3.6.6 (default, Jun 27 2018, 13:11:40) 
[GCC 8.1.1 20180531]`
kubectl version: `Client Version: v1.9.5 // Server Version: v1.9.5`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux bedotech 4.14.57-1-MANJARO #1 SMP PREEMPT Sun Jul 22 19:25:51 UTC 2018 x86_64 GNU/Linux`
Traceback:

```
Traceback (most recent call last):
  File "/opt/telepresence/telepresence-venv/lib/python3.6/site-packages/telepresence/cli.py", line 87, in call_f
    return f(*args, **kwargs)
  File "/opt/telepresence/telepresence-venv/lib/python3.6/site-packages/telepresence/main.py", line 110, in main
    mount_dir
  File "/opt/telepresence/telepresence-venv/lib/python3.6/site-packages/telepresence/local.py", line 167, in run_local_command
    connect_sshuttle(runner, remote_info, args, subprocesses, env, ssh)
  File "/opt/telepresence/telepresence-venv/lib/python3.6/site-packages/telepresence/vpn.py", line 281, in connect_sshuttle
    runner, args, remote_info, env["KUBERNETES_SERVICE_HOST"]
  File "/opt/telepresence/telepresence-venv/lib/python3.6/site-packages/telepresence/runner.py", line 208, in popen
    track, out_cb, err_cb, args, done=done, **kwargs
  File "/opt/telepresence/telepresence-venv/lib/python3.6/site-packages/telepresence/runner.py", line 138, in launch_command
    process = launch_command(args, out_cb, err_cb, **kwargs)
  File "/opt/telepresence/telepresence-venv/lib/python3.6/site-packages/telepresence/runner.py", line 274, in launch_command
    process = Popen(args, **kwargs)
  File "/usr/lib64/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sshuttle-telepresence': 'sshuttle-telepresence'

```

Logs:

```
TEL | [45] Running: kubectl delete service telepresence-1533117114-1866117-13219
  28.1  45 | service "telepresence-1533117114-1866117-13219" deleted
  28.1 TEL | [46] Running: kubectl delete service telepresence-1533117114-728544-13219
  28.7  46 | service "telepresence-1533117114-728544-13219" deleted
  28.7 TEL | [47] Running: kubectl delete service telepresence-1533117115-676629-13219
  29.5  47 | service "telepresence-1533117115-676629-13219" deleted
  29.5 TEL | [48] Running: kubectl delete service telepresence-1533117116-1909664-13219
  30.1  48 | service "telepresence-1533117116-1909664-13219" deleted
  30.1 TEL | END SPAN vpn.py:84(get_proxy_cidrs)    9.7s
  30.1 TEL | [49] Launching: sshuttle-telepresence -v --dns --method nat -e 'ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -F /dev/null' --to-ns 127.0.0.1:9053 -r telepresence@localhost:44423 172.16.0.0/16
  30.1 TEL | [49] [Errno 2] No such file or directory: 'sshuttle-telepresence': 'sshuttle-telepresence'

```

**Comment by Bedotech** [comment]
Ok, archlinux aur package problem i guess...

**Comment by ark3** [comment]
Sorry about that. We need to call out Arch Linux explicitly on the installation page. People keep running into this issue due to the incomplete package that's out there.
