### ISSUE TITLE
Error while running curl through telepresence (High Sierra) against OCP cluster

### ISSUE THREAD

**Issue by cvicens** [telepresenceio/telepresence#725]
### What were you trying to do?

OCP (v3.10) cluster running here: starter-ca-central-1.openshift.com

telepresence --run curl http://timeline:8080/timeline/0001/trever

### What did you expect to happen?

JSON object returned from nodejs REST endpoint

### What happened instead?

(please tell us - the traceback is automatically included, see below)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--run', 'curl', 'http://timeline:8080/timeline/0001/trever']`
Version: `0.90`
Python version: `3.7.0 (default, Aug  4 2018, 09:54:04) 
[Clang 9.0.0 (clang-900.0.39.2)]`
kubectl version: `Client Version: v1.9.0 // Server Version: v1.10.0+b81c8f8`
oc version: `oc v3.9.33 // kubernetes v1.9.1+a0ce1bc657 // features: Basic-Auth //  // Server https://api.starter-ca-central-1.openshift.com:443 // openshift v3.10.27 // kubernetes v1.10.0+b81c8f8`
OS: `Darwin cvicensa-mbp.home 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/telepresence/0.90/libexec/lib/python3.7/site-packages/telepresence/cli.py", line 87, in call_f
    return f(*args, **kwargs)
  File "/usr/local/Cellar/telepresence/0.90/libexec/lib/python3.7/site-packages/telepresence/main.py", line 110, in main
    mount_dir
  File "/usr/local/Cellar/telepresence/0.90/libexec/lib/python3.7/site-packages/telepresence/local.py", line 167, in run_local_command
    connect_sshuttle(runner, remote_info, args, subprocesses, env, ssh)
  File "/usr/local/Cellar/telepresence/0.90/libexec/lib/python3.7/site-packages/telepresence/vpn.py", line 281, in connect_sshuttle
    runner, args, remote_info, env["KUBERNETES_SERVICE_HOST"]
  File "/usr/local/Cellar/telepresence/0.90/libexec/lib/python3.7/site-packages/telepresence/vpn.py", line 97, in get_proxy_cidrs
    ).lookup("serviceCIDR", lambda: serviceCIDR(runner))
  File "/usr/local/Cellar/telepresence/0.90/libexec/lib/python3.7/site-packages/telepresence/cache.py", line 106, in lookup
    value = function()
  File "/usr/local/Cellar/telepresence/0.90/libexec/lib/python3.7/site-packages/telepresence/vpn.py", line 97, in <lambda>
    ).lookup("serviceCIDR", lambda: serviceCIDR(runner))
  File "/usr/local/Cellar/telepresence/0.90/libexec/lib/python3.7/site-packages/telepresence/vpn.py", line 226, in serviceCIDR
    "--tcp=3000"
  File "/usr/loca

**Comment by ark3** [comment]
Sorry about the crash! It looks like the crash report was clipped short. Can you please paste the full traceback from the command prompt? Also helpful would be the telepresence.log file. Thank you.

**Comment by cvicens** [comment]
Apparently I cannot reproduce the problem any more... I've found another one (I'll open a separate issue) but this one can be closed.

Thanks!
