### ISSUE TITLE
No such file or directory: 'bash--norc': 'bash--norc'

### ISSUE THREAD

**Issue by Josh-West-Bose** [telepresenceio/telepresence#738]
### What were you trying to do?

Use Telepresence

### What did you expect to happen?

Telepresence to work

### What happened instead?

Telepresence exited with an error

### Automatically included information

Command line: `['/usr/bin/telepresence', '--method', 'vpn-tcp', '--namespace', 'core-platform-telepresence']`
Version: `0.91`
Python version: `3.6.6 (default, Jul 19 2018, 16:29:00) 
[GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]`
kubectl version: `Client Version: v1.8.15 // Server Version: v1.8.15`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux jupiter 4.17.14-102.fc27.x86_64 #1 SMP Wed Aug 15 12:26:40 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
Traceback:

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 129, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 78, in main
    runner, remote_info, env, socks_port, ssh, mount_dir
  File "/usr/bin/telepresence/telepresence/outbound/__init__.py", line 60, in launch
    runner_, remote_info, command, args.also_proxy, env, ssh
  File "/usr/bin/telepresence/telepresence/outbound/local.py", line 123, in launch_vpn
    process = Popen(command, env=env)
  File "/usr/lib64/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'bash--norc': 'bash--norc'

```

Logs:

```
DIRECT --dest 224.0.0.252/32 -p udp --dport 5355 --to-ports 12300 -m ttl ! --ttl 42
  12.4  25 | conntrack v1.4.4 (conntrack-tools): 0 flow entries have been deleted.
  12.4  25 | c : DNS request from ('10.0.0.128', 47962) to None: 37 bytes
  12.5  17 | 2018-08-19T00:36:01+0000 [stdout#info] Set DNS suffix we filter out to: [()]
  12.5  17 | 2018-08-19T00:36:01+0000 [stdout#info] Result for b'hellotelepresence15' is ['127.0.0.1']
  13.5 TEL | [42] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence16'"'"')'
  13.5  25 | c : DNS request from ('10.0.0.128', 54031) to None: 57 bytes
  13.5  17 | 2018-08-19T00:36:02+0000 [stdout#info] Set DNS suffix we filter out to: [(b'hsd1', b'ma', b'comcast', b'net'), ()]
  13.5  17 | 2018-08-19T00:36:02+0000 [stdout#info] Result for b'hellotelepresence16.hsd1.ma.comcast.net' is ['127.0.0.1']
  13.5 TEL | END SPAN vpn.py:277(connect_sshuttle,sshuttle-wait)    4.8s
  13.5 TEL | END SPAN vpn.py:236(connect_sshuttle)    4.8s

```

**Comment by Josh-West-Bose** [comment]
Note:  Telepresence is working just fine with 0.90

**Comment by ark3** [comment]
Sorry, a typo crept into the 0.91 refactor and exposed a hole in our testing. Please use `--run bash` as a workaround.
