### ISSUE TITLE
cannot use in max os x

### ISSUE THREAD

**Issue by ermazi** [telepresenceio/telepresence#739]
### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--run-shell']`
Version: `0.91`
Python version: `3.7.0 (default, Jul 23 2018, 20:22:55) 
[Clang 9.1.0 (clang-902.0.39.2)]`
kubectl version: `Client Version: v1.10.6 // Server Version: v1.10.3`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin wangshubindeMacBook-Pro.local 17.7.0 Darwin Kernel Version 17.7.0: Fri Jul  6 19:54:51 PDT 2018; root:xnu-4570.71.3~2/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/telepresence/0.91/libexec/lib/python3.7/site-packages/telepresence/cli.py", line 129, in crash_reporting
    yield
  File "/usr/local/Cellar/telepresence/0.91/libexec/lib/python3.7/site-packages/telepresence/main.py", line 78, in main
    runner, remote_info, env, socks_port, ssh, mount_dir
  File "/usr/local/Cellar/telepresence/0.91/libexec/lib/python3.7/site-packages/telepresence/outbound/__init__.py", line 60, in launch
    runner_, remote_info, command, args.also_proxy, env, ssh
  File "/usr/local/Cellar/telepresence/0.91/libexec/lib/python3.7/site-packages/telepresence/outbound/local.py", line 123, in launch_vpn
    process = Popen(command, env=env)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1499, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'bash--norc': 'bash--norc'

```

Logs:

```
]
  99.0 TEL | [207] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence8'"'"')'
  99.1 198 | c : DNS request from ('192.168.31.66', 58124) to None: 36 bytes
  99.1 188 | 2018-08-20T11:10:18+0000 [stdout#info] Result for b'hellotelepresence8' is ['127.0.0.1']
  99.1 TEL | [208] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence9'"'"')'
  99.2 198 | c : DNS request from ('192.168.31.66', 54139) to None: 36 bytes
  99.2 188 | 2018-08-20T11:10:18+0000 [stdout#info] Result for b'hellotelepresence9' is ['127.0.0.1']
 100.2 TEL | [209] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence10'"'"')'
 100.3 198 | c : DNS request from ('192.168.31.66', 49944) to None: 37 bytes
 100.3 188 | 2018-08-20T11:10:19+0000 [stdout#info] Result for b'hellotelepresence10' is ['127.0.0.1']
 100.3 TEL | END SPAN vpn.py:277(connect_sshuttle,sshuttle-wait)    2.8s
 100.3 TEL | END SPAN vpn.py:236(connect_sshuttle)    3.2s

```

**Comment by ermazi** [comment]
solved. maybe run-shell cannot find my shell, when i replace it with /bin/bash.
successful.

**Comment by ark3** [comment]
Sorry, a typo crept into the 0.91 refactor and exposed a hole in our testing. Please use `--run bash` as a workaround. I'll close this one and keep #738.
