### ISSUE TITLE
Telepresence crashing when launching

### ISSUE THREAD

**Issue by unludo** [telepresenceio/telepresence#741]
### What were you trying to do?

start telepresence on a pod

### What did you expect to happen?

start successfully as it always had

### What happened instead?

Telepresence crashing indicating "Looks like there's a bug in our code. Sorry about that!"

Also the pod appears as crashed in the cluster, with telepresence as a container.

(please tell us - the traceback is automatically included, see below)

### Automatically included information

Command line: `['/usr/bin/telepresence', '--swap-deployment', 'controller', '--run-shell', '--also-proxy', '10.0.0.0/8']`
Version: `0.91`
Python version: `3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609]`
kubectl version: `Client Version: v1.9.7 // Server Version: v1.10.5-gke.4`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Linux llepenn-OptiPlex-5050 4.15.0-32-generic #35~16.04.1-Ubuntu SMP Fri Aug 10 21:54:34 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
Traceback:

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 129, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 61, in main
    remote_info = start_proxy(runner)
  File "/usr/bin/telepresence/telepresence/proxy/__init__.py", line 90, in start_proxy
    run_id=run_id,
  File "/usr/bin/telepresence/telepresence/proxy/remote.py", line 205, in get_remote_info
    wait_for_pod(runner, remote_info)
  File "/usr/bin/telepresence/telepresence/proxy/remote.py", line 136, in wait_for_pod
    "Pod isn't starting or can't be found: {}".format(pod["status"])
RuntimeError: Pod isn't starting or can't be found: {'containerStatuses': [{'name': 'controller', 'state': {'waiting': {'message': 'Back-off 1m20s restarting failed container=controller pod=controller-30a10881c8e74b08845d7e4418112007-6cfd4894f-44dhm_default(5aa7f207-a516-11e8-9ace-42010a8402ee)', 'reason': 'CrashLoopBackOff'}}, 'imageID': 'docker.io/datawire/telepresence-k8s@sha256:911e8d920b0f778aac6faa9c9b2cf8b631fb62cce6a591dc192263bf0a24c0b4', 'containerID': 'containerd://6c4600cbf6ce748139a1a13761485461d5e45b42168fc96323c1aba8ef818d79', 'image': 'docker.io/datawire/telepresence-k8s:0.91', 'restartCount': 4, 'lastState': {'terminated': {'message': "/usr/src/app/run.sh: line 7: can't create /etc/passwd: Permission denied\n", 'reason': 'Error', 'containerID': 'containerd://6c4600cbf6ce748139a1a13761485461d5e45b42168fc96323c1aba8ef818d79', 'startedAt': '2018-08-21T07:48:24Z', 'exitCode': 1, 'finishedAt': '2018-08-21T07:48:24Z'}}, 'ready': False}, {'name': 'istio-proxy', 'state': {'running': {'startedAt': '2018-08-21T07:46:55Z'}}, 'imageID': 'docker.io/istio/proxyv2@sha256:77915a0b8c88cce11f04caf88c9ee30300d5ba1fe13146ad5ece9abf8826204c', 'containerID': 'containerd://a94ea0a87f2eec56fc91245eb9409f771a4ac9b14c9f839e0210c0612ef708d9', 'image': 'docker.io/istio/proxyv2:1.0.0', 'restartCount': 0, 'lastState': {}, 'ready': True}], 'conditions': [{'type': 'Initialized', 'lastTransitionTime': '2018-08-21T07:46:48Z', 'lastProbeTime': None, 'status': 'True'}, {'message': 'containers with unready status: [controller]', 'lastProbeTime': None, 'reason': 'ContainersNotReady', 'lastTransitionTime': '2018-08-21T07:46:46Z', 'type': 'Ready', 'status': 'False'}, {'type': 'PodScheduled', 'lastTransitionTime': '2018-08-21T07:46:46Z', 'lastProbeTime': None, 'status': 'True'}], 'hostIP': '10.132.0.6', 'startTime': '2018-08-21T07:46:46Z', 'qosClass': 'Burstable', 'podIP': '10.56.4.14', 'phase': 'Running', 'initContainerStatuses': [{'name': 'istio-init', 'state': {'terminated': {'containerID': 'containerd://9fde2eadd85ee43275e6c2e8bb63ea3308668cdac29488132742c1ba226d3639', 'reason': 'Completed', 'startedAt': '2018-08-21T07:46:47Z', 'exitCode': 0, 'finishedAt': '2018-08-21T07:46:47Z'}}, 'imageID': 'docker.io/istio/proxy_init@sha256:345c40053b53b7cc70d12fb94379e5aa0befd979a99db80833cde671bd1f9fad', 'containerID': 'containerd://9fde2eadd85ee43275e6c2e8bb63ea3308668cdac29488132742c1ba226d3639', 'image': 'docker.io/istio/proxy_init:1.0.0', 'restartCount': 0, 'lastState': {}, 'ready': True}]}

```

Logs:

```
8112007-6cfd4894f-44dhm -o json
 123.6 TEL | [218] Capturing: kubectl --context gke_livehub-ci_euro

**Comment by ark3** [comment]
Sorry about the crash. This is due to #723. Telepresence needs to be able to write to the pod's filesystem.

**Comment by ark3** [comment]
Just to clarify, you're seeing the same crash, `Pod isn't starting or can't be found`, with `/usr/src/app/run.sh: line 7: can't create /etc/passwd: Permission denied` in the crash message?

**Comment by unludo** [comment]
That's what I find in the logs of the telepresence pod if I wait before terminating telepresence.
I join a log file of a session with dns resolution errors. Currently I have no clue why telepresence stopped working for us.
[telepresence.log](https://github.com/telepresenceio/telepresence/files/2315242/telepresence.log)

**Comment by ark3** [comment]
I did not understand your last message. That log file shows a successful connection with a 1.9.6-gke.2 cluster. Was that the point, that the older cluster still works?

**Comment by unludo** [comment]
I finally figured out that the issue was coming from enabling the alpha features on GKE clusters. Without it, everything is working fine.
Thx for your help :)

**Comment by ark3** [comment]
Okay, great. I'm glad you have things running. Please let us know if you run into any trouble. Would you like to close this issue?

**Comment by brunovlucena** [comment]
What Alpha Features are generating the issue? I have the same problem.
`/usr/src/app/run.sh: line 7: can't create /etc/passwd: Permission denied`

**Comment by unludo** [comment]
@brunovlucena it's when creating the GKE cluster. We do it through the gcloud create cluster command which takes an optional parameter '-alpha' (or similar as it is from memory). You may look for GKE alpha features and see what it corresponds to.

**Comment by ark3** [comment]
@brunovlucena The error message you've mentioned looks familiar. Can you please try the `0.94-36-gf8e3b12` image off of the master branch? It (or a descendant based on feedback) will end up in 0.95.

For example:

    TELEPRESENCE_VERSION=0.94-36-gf8e3b12 telepresence -m inject-tcp --run curl -sk https://kubernetes.default/api

Thank you.
