### ISSUE TITLE
Issue with bash--norc on telepresence 0.91

### ISSUE THREAD

**Issue by tylerwince** [telepresenceio/telepresence#743]
### What were you trying to do?

Starting `telepresence` with no arguments

### What did you expect to happen?

Open a telepresence shell to run some commands using cluster DNS

### What happened instead?

Traceback shown below

### Automatically included information

Command line: `['/usr/local/bin/telepresence']`
Version: `0.91`
Python version: `3.7.0 (default, Jul 23 2018, 20:24:19) 
[Clang 9.0.0 (clang-900.0.39.2)]`
kubectl version: `Client Version: v1.11.2 // Server Version: v1.10.6-gke.1`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/telepresence/0.91/libexec/lib/python3.7/site-packages/telepresence/cli.py", line 129, in crash_reporting
    yield
  File "/usr/local/Cellar/telepresence/0.91/libexec/lib/python3.7/site-packages/telepresence/main.py", line 78, in main
    runner, remote_info, env, socks_port, ssh, mount_dir
  File "/usr/local/Cellar/telepresence/0.91/libexec/lib/python3.7/site-packages/telepresence/outbound/__init__.py", line 60, in launch
    runner_, remote_info, command, args.also_proxy, env, ssh
  File "/usr/local/Cellar/telepresence/0.91/libexec/lib/python3.7/site-packages/telepresence/outbound/local.py", line 123, in launch_vpn
    process = Popen(command, env=env)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1499, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'bash--norc': 'bash--norc'

```

Logs:

```
8-21T15:07:38+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 18.7.0 (/usr/bin/python3.6 3.6.1) starting up.
  24.6  25 | 2018-08-21T15:07:38+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.epollreactor.EPollReactor.
  24.6  36 | c : DNS request from ('192.168.0.18', 54143) to None: 37 bytes
  24.7  25 | 2018-08-21T15:07:38+0000 [stdout#info] Set DNS suffix we filter out to: [()]
  24.7  25 | 2018-08-21T15:07:38+0000 [stdout#info] Result for b'hellotelepresence18' is ['127.0.0.1']
  24.7 TEL | [55] captured in 1.11 secs.
  25.7 TEL | [56] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence19'"'"')'
  25.7  36 | c : DNS request from ('192.168.0.18', 64554) to None: 37 bytes
  25.8  25 | 2018-08-21T15:07:39+0000 [stdout#info] Result for b'hellotelepresence19' is ['127.0.0.1']
  25.8 TEL | END SPAN vpn.py:277(connect_sshuttle,sshuttle-wait)    5.2s
  25.8 TEL | END SPAN vpn.py:236(connect_sshuttle)    6.1s

```

**Comment by ark3** [comment]
Sorry about the crash! A typo crept into the 0.91 refactor and exposed a hole in our testing. Please use `--run bash` as a workaround until we get the next release out. I'm going to close this issue and keep #738.
