### ISSUE TITLE
Unable to start telepresence proxy using --run-shel

### ISSUE THREAD

**Issue by antoniozaragoza-arundo** [telepresenceio/telepresence#747]
### What were you trying to do?

Start telepresence proxy using the --run-shell option

### What did you expect to happen?

Telepresence to start successfully

### What happened instead?

Got exceptions on console

### Automatically included information

Command line: `['/usr/bin/telepresence', '--run-shell', '--verbose', '--expose', '5432:5432']`
Version: `0.91`
Python version: `3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0]`
kubectl version: `Client Version: v1.11.2 // Server Version: v1.9.6`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux arundoSupport-VirtualBox 4.15.0-32-generic #35-Ubuntu SMP Fri Aug 10 17:58:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
Traceback:

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 129, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 78, in main
    runner, remote_info, env, socks_port, ssh, mount_dir
  File "/usr/bin/telepresence/telepresence/outbound/__init__.py", line 60, in launch
    runner_, remote_info, command, args.also_proxy, env, ssh
  File "/usr/bin/telepresence/telepresence/outbound/local.py", line 123, in launch_vpn
    process = Popen(command, env=env)
  File "/home/antonioz/anaconda3/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/home/antonioz/anaconda3/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'bash--norc': 'bash--norc'

```

Logs:

```
shuttle-12300 -j REDIRECT --dest 127.0.0.53/32 -p udp --dport 53 --to-ports 12300 -m ttl ! --ttl 42
  23.4  33 | >> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 224.0.0.252/32 -p udp --dport 5355 --to-ports 12300 -m ttl ! --ttl 42
  23.4  33 | conntrack v1.4.4 (conntrack-tools): 0 flow entries have been deleted.
  23.4 TEL | [59] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence25'"'"')'
  23.5  33 | c : DNS request from ('127.0.0.1', 42170) to None: 59 bytes
  24.4  30 | debug1: client_input_global_request: rtype keepalive@openssh.com want_reply 1
  24.4  29 | debug1: client_input_global_request: rtype keepalive@openssh.com want_reply 1
  24.6 TEL | [60] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence26'"'"')'
  24.7  33 | c : DNS request from ('127.0.0.1', 51664) to None: 59 bytes
  25.1 TEL | END SPAN vpn.py:277(connect_sshuttle,sshuttle-wait)    6.2s
  25.1 TEL | END SPAN vpn.py:236(connect_sshuttle)    6.2s

```

**Comment by ark3** [comment]
Sorry about the crash. This is fixed in release 0.92, or you can work around this by using `--run bash` instead of `--run-shell`.
