### ISSUE TITLE
telepresence --new-deployment got errors

### ISSUE THREAD

**Issue by dfang** [telepresenceio/telepresence#748]
### What were you trying to do?

Following this tutorial,
https://dev.to/kelseyevans/rapid-development-of-kubernetes-services-with-telepresence-7cd

telepresence --new-deployment hello-world --expose 8090

### What happened instead?
command output
```
T: Invoking sudo. Please enter your sudo password.
Password:
T: Starting proxy with method 'vpn-tcp', which has the following limitations: All processes are
T: affected, only one telepresence can run per machine, and you can't use other VPNs. You may need
T: to add cloud hosts and headless services with --also-proxy. For a full list of method limitations
T:  see https://telepresence.io/reference/methods.html
T: Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for
T: details.

Looks like there's a bug in our code. Sorry about that!

Here's the traceback:

Traceback (most recent call last):
  File "/usr/local/Cellar/telepresence/0.92/libexec/lib/python3.7/site-packages/telepresence/cli.py", line 129, in crash_reporting
    yield
  File "/usr/local/Cellar/telepresence/0.92/libexec/lib/python3.7/site-packages/telepresence/main.py", line 61, in main
    remote_info = start_proxy(runner)
  File "/usr/local/Cellar/telepresence/0.92/libexec/lib/python3.7/site-packages/telepresence/proxy/__init__.py", line 84, in start_proxy
    runner_, deployment_arg, image_name, args.expose, add_custom_ns
  File "/usr/local/Cellar/telepresence/0.92/libexec/lib/python3.7/site-packages/telepresence/proxy/deployment.py", line 81, in create_new_deployment
    runner.get_output(runner.kubectl(command))
  File "/usr/local/Cellar/telepresence/0.92/libexec/lib/python3.7/site-packages/telepresence/runner/__init__.py", line 329, in get_output
    raise CalledProcessError(cpe_exc.returncode, cpe_exc.cmd, output)
subprocess.CalledProcessError: Command '['kubectl', '--context', 'minikube', '--namespace', 'default', 'run', '--restart=Always', '--limits=cpu=100m,memory=256Mi', '--requests=cpu=25m,memory=64Mi', 'hello-world', '--image=datawire/telepresence-k8s:0.92', '--labels=telepresence=f8e8ef9a3c034d63b0d340b0a28cd938', '--port=8090', '--expose', '--env=TELEPRESENCE_NAMESERVER=8.8.8.8']' returned non-zero exit status 1.


And here are the last few lines of the logfile (see /private/tmp/telepresence-test/telepresence.log for the complete logs):

   0.4 TEL | Command: kubectl 1.8.6
   0.4 TEL | Context: minikube, namespace: default, version: 1.10.0
   0.4 TEL | Looks like we're in a local VM, e.g. minikube.
   0.4 TEL | END SPAN startup.py:57(__init__)    0.3s
   0.4 TEL | [5] Capturing: ssh -V
   0.4 TEL | [6] Running: sudo -n echo -n
   0.4   6 | sudo: a password is required
   0.4 TEL | [6] exit 1 in 0.03 secs.
   0.4 >>> | Invoking sudo. Please enter your sudo password.
   0.4 TEL | [7] Running: sudo echo -n
   3.6 TEL | [7] ran in 3.15 secs.
   3.6 >>> | Starting proxy with method 'vpn-tcp', which has the following limitations: All processes are affected, only one telepresence can run per machine, and you can't use other VPNs. You may need to add cloud hosts and headless services with --also-proxy. For a full list of method limitations see https://telepresence.io/reference/methods.html
   3.6 >>> | Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.
   3.6 TEL | [8] Capturing: kubectl --context minikube --namespace default get pods telepresence-connectivity-check --ignore-not-found
   4.9 TEL | Scout info: {'latest_version': '0.92', 'application': 'telepresence', 'notices': []}
   4.9 TEL | BEGIN SPAN deployment.py:44(create_new_deployment)
   4.9 TEL | [9] Capturing: kubectl --context minikube --namespace default delete --ignore-not-found svc,deploy --selector=telepresence=f8e8ef9a3c034d63b0d340b0a28cd938
   5.1 TEL | [10] Capturing: kubectl --context minikube --namespace default run --restart=Always --limits=cpu=100m,memory=256Mi --requests=cpu=25m,memory=64Mi hello-world --image=datawire/telepresence-k8s:0.92 --labels=telepresence=f8e8ef9a3c034d63b0d340b0a28cd938 --port=8090 --expose --env=TELEPRESENCE_NAMESERVER=8.8.8.8
   5.2  10 | Error from server (AlreadyExists): deployments.extensions "hello-world" already exists
   5.2 TEL | [10] exit 1 in 0.13 secs.

Would you like to file an issue in our issue tracker? You'll be able to review and edit before anything is posted to the public. We'd really appreciate the help improving our product. [Y/n]: y
T: Exit cleanup in progress
```

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--new-deployment', 'hello-world', '--expose', '8090']`
Version: `0.92`
Python version: `3.7.0 (default, Aug 17 2018, 21:14:48) 
[Clang 9.1.0 (clang-902.0.39.2)]`
kubectl version: `Client Version: v1.8.6 // Server Version: v1.10.0`
oc version: `oc v3.10.0+dd10d17 // kubernetes v1.10.0+b81c8f8 // features: Basic-Auth //  // Server https://192.168.64.28:8443 // kubernetes v1.10.0`
OS: `Darwin fangs-MacBook-Pro.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/telepresence/0.92/libexec/lib/python3.7/site-packages/telepresence/cli.py", line 129, in crash_reporting
    yield
  File "/usr/local/Cellar/telepresence/0.92/libexec/lib/python3.7/site-packages/telepresence/main.py", line 61, in main
    remote_info = start_proxy(runner)
  File "/usr/local/Cellar/telepresence/0.92/libexec/lib/python3.7/site-packages/telepresence/proxy/__init__.py", line 84, in start_proxy
    runner_, deployment_arg, image_name, args.expose, add_custom_ns
  File "/usr/local/Cellar/telepresence/0.92/libexec/lib/python3.7/site-packages/telepresence/proxy/deployment.py", line 81, in create_new_deployment
    runner.get_output(runner.kubectl(command))
  File "/usr/local/Cellar/telepresence/0.92/libexec/lib/python3.7/site-packages/telepresence/runner/__init__.py", line 329, in get_output
    raise CalledProcessError(cpe_exc.returncode, cpe_exc.cmd, output)
subprocess.CalledProcessError: Command '['kubectl', '--context', 'minikube', '--namespace', 'default', 'run', '--restart=Always', '--limits=cpu=100m,memory=256Mi', '--requests=cpu=25m,memory=64Mi', 'hello-world', '--image=datawire/telepresence-k8s:0.92', '--labels=telepresence=f8e8ef9a3c034d63b0d340b0a28cd938', '--port=8090', '--expose', '--env=TELEPRESENCE_NAMESERVER=8.8.8.8']' returned non-zero exit status 1.

```

Logs:

```
ENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.
   3.6 TEL | [8] Capturing: kubectl --context minikube --namespace default get pods telepresence-connectivity-check --ignore-not-found
   4.9 TEL | Scout info: {'latest_version': '0.92', 'application': 'telepresence', 'notices': []}
   4.9 TEL | BEGIN SPAN deployment.py:44(create_new_deployment)
   4.9 TEL | [9] Capturing: kubectl --context minikube --namespace default delete --ignore-not-found svc,deploy --selector=telepresence=f8e8ef9a3c034d63b0d340b0a28cd938
   5.1 TEL | [10] Capturing: kubectl --context minikube --namespace default run --restart=Always --limits=cpu=100m,memory=256Mi --requests=cpu=25m,memory=64Mi hello-world --image=datawire/telepresence-k8s:0.92 --labels=telepresence=f8e8ef9a3c034d63b0d340b0a28cd938 --port=8090 --expose --env=TELEPRESENCE_NAMESERVER=8.8.8.8
   5.2  10 | Error from server (AlreadyExists): deployments.extensions "hello-world" already exists
   5.2 TEL | [10] exit 1 in 0.13 secs.

```

**Comment by ark3** [comment]
Sorry about the crash. This is happening because there is already a "hello-world" deployment in the cluster. Telepresence should have returned an error message.

**Comment by dfang** [comment]
thanks !  i noticed `AlreadyExists` in the log in the end. but this is unfriendly for new users, an error message is better.
