### ISSUE TITLE
Can't connect to cluster

### ISSUE THREAD

**Issue by endrec** [telepresenceio/telepresence#763]
### What were you trying to do?

I was trying to connect to my k8s cluster, where telepresence worked previously.

### What did you expect to happen?

I was expecting an established connection.

### What happened instead?

`telepresence` hangs, until I kill the process. `telepresence --verbose` complains about certificates (`shortcut_restmapper.go:81] Error loading discovery information: an error on the server ("Error: 'x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"svc-cat-ca\")'`), then dies.

### Automatically included information

Command line: `['/usr/bin/telepresence', '--verbose']`
Version: `0.90`
Python version: `3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0]`
kubectl version: `Client Version: v1.9.6 // Server Version: v1.9.6`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux endre-laptop 4.15.0-32-generic #35-Ubuntu SMP Fri Aug 10 17:58:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
Traceback:

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 87, in call_f
    return f(*args, **kwargs)
  File "/usr/bin/telepresence/telepresence/main.py", line 76, in main
    remote_info = start_proxy(runner, args)
  File "/usr/bin/telepresence/telepresence/proxy.py", line 222, in start_proxy
    run_id=run_id,
  File "/usr/bin/telepresence/telepresence/remote.py", line 171, in get_remote_info
    run_id=run_id
  File "/usr/bin/telepresence/telepresence/remote.py", line 107, in get_deployment_json
    stderr=STDOUT
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

Logs:

```
                  "lastTransitionTime": "2018-08-29T14:58:31Z",
   3.3  11 |                         "lastUpdateTime": "2018-08-29T14:58:31Z",
   3.3  11 |                         "message": "Deployment has minimum availability.",
   3.3  11 |                         "reason": "MinimumReplicasAvailable",
   3.3  11 |                         "status": "True",
   3.3  11 |                         "type": "Available"
   3.3  11 |                     }
   3.3  11 |                 ],
   3.3  11 |                 "observedGeneration": 1,
   3.3  11 |                 "replicas": 1,
   3.3  11 |                 "unavailableReplicas": 1,
   3.3  11 |                 "updatedReplicas": 1
   3.3  11 |             }
   3.3  11 |         }
   3.3  11 |     ],
   3.3  11 |     "kind": "List",
   3.3  11 |     "metadata": {
   3.3  11 |         "resourceVersion": "",
   3.3  11 |         "selfLink": ""
   3.3  11 |     }
   3.3  11 | }
   3.4 TEL | END SPAN remote.py:82(get_deployment_json)    0.5s

```

**Comment by endrec** [comment]
Had no isues with `kubectl`, but it seems the issue was caused by something in my cluster, after restarting the whole cluster, telepresence started to work again.
