### ISSUE TITLE
bug!

### ISSUE THREAD

**Issue by xing-kenny** [telepresenceio/telepresence#770]
### What were you trying to do?

(please tell us)

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below)

### Automatically included information

Command line: `['/usr/local/bin/telepresence']`
Version: `0.92`
Python version: `3.7.0 (default, Aug 22 2018, 15:22:56) 
[Clang 9.0.0 (clang-900.0.39.2)]`
kubectl version: `Client Version: v1.11.2 // Server Version: v1.11.1`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin 013deiMac.local 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/telepresence/0.92/libexec/lib/python3.7/site-packages/telepresence/cli.py", line 129, in crash_reporting
    yield
  File "/usr/local/Cellar/telepresence/0.92/libexec/lib/python3.7/site-packages/telepresence/main.py", line 48, in main
    launch = outbound.setup(runner, args)
  File "/usr/local/Cellar/telepresence/0.92/libexec/lib/python3.7/site-packages/telepresence/outbound/__init__.py", line 99, in setup
    return setup_vpn(runner, args)
  File "/usr/local/Cellar/telepresence/0.92/libexec/lib/python3.7/site-packages/telepresence/outbound/__init__.py", line 46, in setup_vpn
    runner.require_sudo()
  File "/usr/local/Cellar/telepresence/0.92/libexec/lib/python3.7/site-packages/telepresence/runner/__init__.py", line 196, in require_sudo
    self.check_call(["sudo", "-n", "echo", "-n"])
  File "/usr/local/Cellar/telepresence/0.92/libexec/lib/python3.7/site-packages/telepresence/runner/__init__.py", line 304, in check_call
    track, "Running", "ran", out_cb, err_cb, args, **kwargs
  File "/usr/local/Cellar/telepresence/0.92/libexec/lib/python3.7/site-packages/telepresence/runner/__init__.py", line 285, in _run_command
    process = self._launch_command(track, out_cb, err_cb, args, **kwargs)
  File "/usr/local/Cellar/telepresence/0.92/libexec/lib/python3.7/site-packages/telepresence/runner/__init__.py", line 270, in _launch_command
    process = _launch_command(args, out_cb, err_cb, **kwargs)
  File "/usr/local/Cellar/telepresence/0.92/libexec/lib/python3.7/site-packages/telepresence/runner/__init__.py", line 469, in _launch_command
    process = Popen(args, **kwargs)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1499, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sudo': 'sudo'

```

Logs:

```
Not available
```

**Comment by ark3** [comment]
Sorry about the crash. Is there an executable `sudo` binary in `/usr/bin`? Is `/usr/bin` in your shell's `PATH`? Thank you for helping us with this.
