### ISSUE TITLE
Unable to run telepresence in my local machine

### ISSUE THREAD

**Issue by slim-hmidi** [telepresenceio/telepresence#772]
### What were you trying to do?

run the pod of my service locally with : 
```bash
telepresence --swap-deployment frontend --run-shell
```

### What did you expect to happen?

Succeed to open the service locally.

### What happened instead?
Failed to connect to the pod.

### Automatically included information

Command line: `['/usr/bin/telepresence', '--swap-deployment', 'frontend', '--run-shell']`
Version: `0.90`
Python version: `3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0]`
kubectl version: `Client Version: v1.9.3 // Server Version: v1.9.4`
oc version: `(error: [Errno 20] Not a directory: 'oc')`
OS: `Linux OptiPlex-3020 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
Traceback:

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 87, in call_f
    return f(*args, **kwargs)
  File "/usr/bin/telepresence/telepresence/main.py", line 49, in main
    session.kube_info, session.runner = analyze_args(session)
  File "/usr/bin/telepresence/telepresence/startup.py", line 162, in analyze_args
    runner = Runner(output, kube_info.command, args.verbose)
  File "/usr/bin/telepresence/telepresence/runner.py", line 65, in __init__
    self.cache = Cache.load(os.path.join(cache_dir, "cache.json"))
  File "/usr/bin/telepresence/telepresence/cache.py", line 43, in load
    cache = json.load(f)
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

Logs:

```
   0.0 TEL | Telepresence 0.90 launched at Wed Sep  5 14:36:40 2018
   0.0 TEL |   /usr/bin/telepresence --swap-deployment frontend --run-shell
   0.3 TEL | Context: minikube, namespace: default, kubectl_command: kubectl
   0.3 TEL | [1] Launching: kubectl version --short
   0.3 TEL | [2] Launching: oc version
   0.3 TEL | [2] [Errno 20] Not a directory: 'oc'
   0.3 TEL | [3] Launching: uname -a
   0.3   3 | Linux OptiPlex-3020 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
   0.3 TEL | Python 3.6.5 (default, Apr  1 2018, 05:46:30)
   0.3 TEL | [GCC 7.3.0]
   0.3 TEL | [3] exit 0

```

**Comment by ark3** [comment]
Sorry about the crash! Please upgrade your copy of Telepresence. This crash has been fixed as of 0.91.
