### ISSUE TITLE
Error after fresh install

### ISSUE THREAD

**Issue by pjfila** [telepresenceio/telepresence#794]
### What were you trying to do?

Just run telepresence for the first time after fresh instal (via brew as stated on the webpage)

### What did you expect to happen?

print out help or something sensible

### What happened instead?

Stack trace with error

### Automatically included information

Command line: `['/usr/local/bin/telepresence']`
Version: `0.93`
Python version: `3.7.0 (default, Oct  2 2018, 09:20:07) 
[Clang 10.0.0 (clang-1000.11.45.2)]`
kubectl version: `(error: [Errno 2] No such file or directory: 'kubectl': 'kubectl')`
oc version: `oc v3.10.0+dd10d17 // kubernetes v1.10.0+b81c8f8 // features: Basic-Auth //  // Server https://192.168.99.100:8443 // openshift v3.10.0+fd501dd-48 // kubernetes v1.10.0+b81c8f8`
OS: `Darwin 900619528 17.7.0 Darwin Kernel Version 17.7.0: Fri Jul  6 19:54:51 PDT 2018; root:xnu-4570.71.3~2/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 129, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 43, in main
    runner.kubectl = KubeInfo(runner, args)
  File "/usr/local/bin/telepresence/telepresence/startup.py", line 153, in __init__
    self.in_local_vm = self._check_if_in_local_vm(runner)
  File "/usr/local/bin/telepresence/telepresence/startup.py", line 185, in _check_if_in_local_vm
    if ip and ip in runner.kubectl.server:
AttributeError: 'NoneType' object has no attribute 'server'

```

Logs:

```
Not available
```

**Comment by pjfila** [comment]
Duplicate of https://github.com/telepresenceio/telepresence/issues/781
