### ISSUE TITLE
got below error while running telepresence

### ISSUE THREAD

**Issue by sakomws** [telepresenceio/telepresence#800]
### What were you trying to do?

(please tell us)

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below)

### Automatically included information

Command line: `['/usr/local/bin/telepresence']`
Version: `0.93`
Python version: `3.7.0 (default, Sep 18 2018, 18:47:22) 
[Clang 9.1.0 (clang-902.0.39.2)]`
kubectl version: `Client Version: v1.12.0 // Server Version: v1.10.0`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin OSX-0485.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 129, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 61, in main
    remote_info = start_proxy(runner)
  File "/usr/local/bin/telepresence/telepresence/proxy/__init__.py", line 90, in start_proxy
    run_id=run_id,
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 200, in get_remote_info
    wait_for_pod(runner, remote_info)
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 132, in wait_for_pod
    "Pod isn't starting or can't be found: {}".format(pod["status"])
RuntimeError: Pod isn't starting or can't be found: {'conditions': [{'lastProbeTime': None, 'lastTransitionTime': '2018-10-10T01:38:29Z', 'message': '0/1 nodes are available: 1 Insufficient memory.', 'reason': 'Unschedulable', 'status': 'False', 'type': 'PodScheduled'}], 'phase': 'Pending', 'qosClass': 'Burstable'}

```

Logs:

```
ff9648c-zthtx -o json
 119.4 TEL | [359] Capturing: kubectl --context minikube --namespace default get pod telepresence-1539135508-76258-20069-54bff9648c-zthtx -o json
 119.7 TEL | [360] Capturing: kubectl --context minikube --namespace default get pod telepresence-1539135508-76258-20069-54bff9648c-zthtx -o json
 120.0 TEL | [361] Capturing: kubectl --context minikube --namespace default get pod telepresence-1539135508-76258-20069-54bff9648c-zthtx -o json
 120.4 TEL | [362] Capturing: kubectl --context minikube --namespace default get pod telepresence-1539135508-76258-20069-54bff9648c-zthtx -o json
 120.7 TEL | [363] Capturing: kubectl --context minikube --namespace default get pod telepresence-1539135508-76258-20069-54bff9648c-zthtx -o json
 120.8 TEL | [364] Running: sudo -n echo -n
 121.1 TEL | [365] Capturing: kubectl --context minikube --namespace default get pod telepresence-1539135508-76258-20069-54bff9648c-zthtx -o json
 121.2 TEL | END SPAN remote.py:111(wait_for_pod)  119.8s

```

**Comment by SpencerWoo** [comment]
I had this error.  `0/1 nodes are available: 1 Insufficient memory.` resolved by increasing memory and CPU

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
