### ISSUE TITLE
Swap minikube deploy with docker image failed

### ISSUE THREAD

**Issue by maraisf** [telepresenceio/telepresence#802]
### What were you trying to do?
created a docker image from the project Dockerfile with
`docker build -t mobile-api-dev .`

Then ran the swap
`telepresence --swap-deployment mobile-api --docker-run --rm -it -v $(pwd):/service mobile-api-dev:latest`

### What did you expect to happen?
Expected the minikube deployment to be swapped out with the docker image

### What happened instead?
Did not work as expected

### Automatically included information
Command line: `['/usr/local/bin/telepresence', '--swap-deployment', 'mobile-api', '--docker-run', '--rm', '-it', '-v', '/Users/francoismarais:/service', 'mobile-api-dev:latest']`
Version: `0.92`
Python version: `3.7.0 (default, Sep 18 2018, 18:47:22) 
[Clang 9.1.0 (clang-902.0.39.2)]`
kubectl version: `Client Version: v1.8.7 // Server Version: v1.9.0`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin Francois-Marais-Mac.wifi.hq.superbalist.com 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/telepresence/0.92/libexec/lib/python3.7/site-packages/telepresence/cli.py", line 129, in crash_reporting
    yield
  File "/usr/local/Cellar/telepresence/0.92/libexec/lib/python3.7/site-packages/telepresence/main.py", line 61, in main
    remote_info = start_proxy(runner)
  File "/usr/local/Cellar/telepresence/0.92/libexec/lib/python3.7/site-packages/telepresence/proxy/__init__.py", line 90, in start_proxy
    run_id=run_id,
  File "/usr/local/Cellar/telepresence/0.92/libexec/lib/python3.7/site-packages/telepresence/proxy/remote.py", line 205, in get_remote_info
    wait_for_pod(runner, remote_info)
  File "/usr/local/Cellar/telepresence/0.92/libexec/lib/python3.7/site-packages/telepresence/proxy/remote.py", line 136, in wait_for_pod
    "Pod isn't starting or can't be found: {}".format(pod["status"])
RuntimeError: Pod isn't starting or can't be found: {'conditions': [{'lastProbeTime': None, 'lastTransitionTime': '2018-10-12T09:31:35Z', 'status': 'True', 'type': 'Initialized'}, {'lastProbeTime': None, 'lastTransitionTime': '2018-10-12T09:31:35Z', 'message': 'containers with unready status: [mobile-api]', 'reason': 'ContainersNotReady', 'status': 'False', 'type': 'Ready'}, {'lastProbeTime': None, 'lastTransitionTime': '2018-10-12T09:31:35Z', 'status': 'True', 'type': 'PodScheduled'}], 'containerStatuses': [{'containerID': 'docker://a6deeebd561699f4f1b5565fdf6aa4ca9c5bcb515e32475d6b4bf48ff2a7c7ab', 'image': 'datawire/telepresence-k8s:0.92', 'imageID': 'docker-pullable://datawire/telepresence-k8s@sha256:0fe11f7d0b2a28d681a36ef090e0519475245b7a22fdf66d3174c54365c14730', 'lastState': {'terminated': {'containerID': 'docker://a6deeebd561699f4f1b5565fdf6aa4ca9c5bcb515e32475d6b4bf48ff2a7c7ab', 'exitCode': 127, 'finishedAt': '2018-10-12T09:33:09Z', 'message': '/bin/sh: /usr/src/app/run.sh: not found\n', 'reason': 'Error', 'startedAt': '2018-10-12T09:33:09Z'}}, 'name': 'mobile-api', 'ready': False, 'restartCount': 4, 'state': {'waiting': {'message': 'Back-off 1m20s restarting failed container=mobile-api pod=mobile-api-664b7cc3118c4b4480ef62e405ad1b53-8474cd6747-z5t66_default(9ce2b2bf-ce01-11e8-9c6c-4ea83c42836e)', 'reason': 'CrashLoopBackOff'}}}], 'hostIP': '192.168.64.34', 'phase': 'Running', 'podIP': '172.17.0.8', 'qosClass': 'BestEffort', 'startTime': '2018-10-12T09:31:35Z'}

```

Logs:

```
747-z5t66 -o json
 121.8 TEL | [314] Capturing: kubectl --context minikube --namespace default get pod mobile-api-664b7cc3118c4b4480ef62e405ad1b53-8474cd6747-z5t66 -o json
 122.2 TEL | [315] Capturing: kubectl --context minikube --namespace default get pod mobile-api-664b7cc3118c4b4480ef62e405ad1b53-8474cd6747-z5t66 -o json
 122.6 TEL | [316] Capturing: kubectl --context minikube --namespace default get pod mobile-api-664b7cc3118c4b4480ef62e405ad1b53-8474cd6747-z5t66 -o json
 123.0 TEL | [317] Capturing: kubectl --context minikube --namespace default get pod mobile-api-664b7cc3118c4b4480ef62e405ad1b53-8474cd6747-z5t66 -o json
 123.4 TEL | [318] Capturing: kubectl --context minikube --namespace default get pod mobile-api-664b7cc3118c4b4480ef62e405ad1b53

**Comment by ark3** [comment]
In the crash error I see:

    "lastState": {
        "terminated": {
            "containerID": "docker://a6deeebd561699f4f1b5565fdf6aa4ca9c5bcb515e32475d6b4bf48ff2a7c7ab",
            "exitCode": 127,
            "finishedAt": "2018-10-12T09:33:09Z",
            "message": "/bin/sh: /usr/src/app/run.sh: not found\n",
            "reason": "Error",
            "startedAt": "2018-10-12T09:33:09Z",
        }
    },

That's odd. The Telepresence image for the proxy pod is crashing with `/bin/sh: /usr/src/app/run.sh: not found`. Yet I can run that same image (`datawire/telepresence-k8s:0.92`) just fine. 

I'm not sure what's going on. Let me ponder some more.

**Comment by maraisf** [comment]
Thanks for the response, let me know if I need to run anything on my side
