### ISSUE TITLE
Error trying to swap deployments

### ISSUE THREAD

**Issue by tomasAlabes** [telepresenceio/telepresence#813]
### What were you trying to do?

`telepresence --swap-deployment graphql-server --expose 3000 --run NODE_ENV=prod yarn watch:dev`

But I had ```T: Mount error was: mount_osxfuse: the file system is not available (2)```
 
I installed macos fuse 3.8.2 and retried (I'm using the latest mojave)

### What did you expect to happen?

Swap deployment with my local run

### What happened instead?

Trace above.

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--swap-deployment', 'graphql-server', '--expose', '3000', '--run', 'NODE_ENV=prod', 'yarn', 'watch:dev']`
Version: `0.92`
Python version: `3.7.0 (default, Jun 29 2018, 20:13:13) 
[Clang 9.1.0 (clang-902.0.39.2)]`
kubectl version: `Client Version: v1.11.2 // Server Version: v1.11.1-2+e49fe6296d12ea`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin dhcp-10-211-119-57.usdhcp.oraclecorp.com 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64 i386 MacBookPro12,1 Darwin`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/telepresence/0.92/libexec/lib/python3.7/site-packages/telepresence/cli.py", line 129, in crash_reporting
    yield
  File "/usr/local/Cellar/telepresence/0.92/libexec/lib/python3.7/site-packages/telepresence/main.py", line 78, in main
    runner, remote_info, env, socks_port, ssh, mount_dir
  File "/usr/local/Cellar/telepresence/0.92/libexec/lib/python3.7/site-packages/telepresence/outbound/__init__.py", line 60, in launch
    runner_, remote_info, command, args.also_proxy, env, ssh
  File "/usr/local/Cellar/telepresence/0.92/libexec/lib/python3.7/site-packages/telepresence/outbound/local.py", line 123, in launch_vpn
    process = Popen(command, env=env)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1499, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'NODE_ENV=prod': 'NODE_ENV=prod'

```

Logs:

```
-c 'import socket; socket.gethostbyname('"'"'hellotelepresence8'"'"')'
   9.9  28 | c : DNS request from ('10.211.119.57', 53658) to None: 50 bytes
   9.9  18 | 2018-10-26T21:35:08+0000 [stdout#info] Result for b'hellotelepresence8.us.oracle.com' is ['127.0.0.1']
   9.9 TEL | [38] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence9'"'"')'
  10.0  28 | c : DNS request from ('10.211.119.57', 50810) to None: 50 bytes
  10.0  18 | 2018-10-26T21:35:08+0000 [stdout#info] Result for b'hellotelepresence9.us.oracle.com' is ['127.0.0.1']
  11.0 TEL | [39] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence10'"'"')'
  11.1  28 | c : DNS request from ('10.211.119.57', 57385) to None: 51 bytes
  11.1  18 | 2018-10-26T21:35:09+0000 [stdout#info] Result for b'hellotelepresence10.us.oracle.com' is ['127.0.0.1']
  11.1 TEL | END SPAN vpn.py:277(connect_sshuttle,sshuttle-wait)    2.5s
  11.1 TEL | END SPAN vpn.py:236(connect_sshuttle)    2.5s

```

**Comment by tomasAlabes** [comment]
Never mind...I had to read the error, it wasn't understanding the `NODE_ENV=prod` part...
