### ISSUE TITLE
I can't start telepresence on my arch linux

### ISSUE THREAD

**Issue by yagi5** [telepresenceio/telepresence#821]
I have installed telepresence on my arch linux from AUR.
Now, it says

```
$ telepresence --namespace "my-namespace" --run-shell
T: Starting proxy with method 'vpn-tcp', which has the following limitations: All processes are affected, only one telepresence can
T: run per machine, and you can't use other VPNs. You may need to add cloud hosts and headless services with --also-proxy. For a
T: full list of method limitations see https://telepresence.io/reference/methods.html
T: Required dependencies not found in your PATH:
T:   fusermount
T: Required for volume mounts
T: Please see https://www.telepresence.io/reference/install#dependencies for more information.
```

There is no `fusermount` command, but 

```
$ which fusermount3
/usr/bin/fusermount3
```

How can I use it?

**Comment by LukeShu** [comment]
As I commented on AUR: It has a missing dependency on the `fuse2` package. You can work around this by adding that to the `depends()`, or just by manually installing it.

Cc: @starkers (the AUR packager)

**Comment by starkers** [comment]
OK I've added `fuse2` into the deps list. (I hadn't noticed it was needed as I already had it installed)

@yagi5 could check that the AUR `telepresence` is working for you please?

Thanks

**Comment by yagi5** [comment]
@starkers @LukeShu 

Thank you for checking!
I have tried `pacman -S fuse2` and executed telepresence, but it failed.
Here is the full output.

```
$ telepresence --namespace "my-namespace" --run-shell
T: Starting proxy with method 'vpn-tcp', which has the following limitations: All processes are affected, only one telepresence can run per machine, and you can't use other
T: VPNs. You may need to add cloud hosts and headless services with --also-proxy. For a full list of method limitations see https://telepresence.io/reference/methods.html
T: Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.
T: No traffic is being forwarded from the remote Deployment to your local machine. You can use the --expose option to specify which ports you want to forward.
T: Mounting remote volumes failed, they will be unavailable in this session. If you are running on Windows Subystem for Linux then see
T: https://github.com/datawire/telepresence/issues/115, otherwise please report a bug, attaching telepresence.log to the bug report:
T: https://github.com/datawire/telepresence/issues/new
T: Mount error was: fuse: device not found, try 'modprobe fuse' first
Looks like there's a bug in our code. Sorry about that!
Here's the traceback:
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 129, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 78, in main
    runner, remote_info, env, socks_port, ssh, mount_dir
  File "/usr/local/bin/telepresence/telepresence/outbound/__init__.py", line 60, in launch
    runner_, remote_info, command, args.also_proxy, env, ssh
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 120, in launch_vpn
    connect_sshuttle(runner, remote_info, also_proxy, ssh)
  File "/usr/local/bin/telepresence/telepresence/outbound/vpn.py", line 287, in connect_sshuttle
    get_hellotelepresence()
  File "/usr/local/bin/telepresence/telepresence/outbound/vpn.py", line 273, in get_hellotelepresence
    format(next(counter))
  File "/usr/local/bin/telepresence/telepresence/runner/__init__.py", line 368, in get_output
    raise CalledProcessError(cpe_exc.returncode, cpe_exc.cmd, output)
subprocess.CalledProcessError: Command '['python3', '-c', "import socket; socket.gethostbyname('hellotelepresence105')"]' returned non-zero exit status 1.
And here are the last few lines of the logfile (see /home/ygnmhdtt/telepresence.log for the complete logs):
  25.9 TEL | [126] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence102'"'"')'
  26.0 126 | Traceback (most recent call last):
  26.0 126 |   File "<string>", line 1, in <module>
  26.0 126 | socket.gaierror: [Errno -2] Name or service not known
  26.0 TEL | [126] exit 1 in 0.06 secs.
  26.1 TEL | [127] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence103'"'"')'
  26.1 127 | Traceback (most recent call last):
  26.1 127 |   File "<string>", line 1, in <module>
  26.1 127 | socket.gaierror: [Errno -2] Name or service not known
  26.1 TEL | [127] exit 1 in 0.08 secs.
  26.2 TEL | [128] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence104'"'"')'
  26.4 128 | Traceback (most recent call last):
  26.4 128 |   File "<string>", line 1, in <module>
  26.4 128 | socket.gaierror: [Errno -2] Name or service not known
  26.5 TEL | [128] exit 1 in 0.20 secs.
  26.5 TEL | [129] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence105'"'"')'
  26.5 129 | Traceback (most recent call last):
  26.5 129 |   File "<string>", line 1, in <module>
  26.5 129 | socket.gaierror: [Errno -2] Name or service not known
  26.5 TEL | [129] exit 1 in 0.08 secs.
Would you like to file an issue in our issue tracker? You'll be able to review and edit before anything is posted to the public. We'd really appreciate the help improving our product. [Y/n]: n
T: Exit cleanup in progress
```

**Comment by LukeShu** [comment]
To me, that looks like you upgraded your kernel, but didn't reboot (check by seeing if `cat /proc/version` and `pacman -Q linux` agree); I suspect that rebooting would fix it.

>     Looks like there's a bug in our code. Sorry about that!

A common theme in the telepresence code is that we crash instead of printing a real error message ("crash instead of error" is one of the more common tags in the issue tracker).  So there is a bug in our code, but it's not (necessarily) what's causing the issue.

**Comment by yagi5** [comment]
Sorry for late reply.

>  that looks like you upgraded your kernel, but didn't reboot
It was correct. They showed different versions.

> I suspect that rebooting would fix it.
I tried rebooting and it worked fine. Thanks!!
