### ISSUE TITLE
Telepresence pod cannot start on GKE with ContainerD

### ISSUE THREAD

**Issue by aaron-trout** [telepresenceio/telepresence#828]
### What were you trying to do?

Use telepresence on a GKE cluster with ContainerD.

### What did you expect to happen?

Telepresence works

### What happened instead?

Remote telepresence pod fails to start

```bash
$ kubectl logs --selector telepresence
/usr/src/app/run.sh: line 7: can't create /etc/passwd: Permission denied
```

### Automatically included information

Command line: `['/usr/local/bin/telepresence']`
Version: `0.93`
Python version: `3.7.1 (default, Nov  6 2018, 18:46:03) 
[Clang 10.0.0 (clang-1000.11.45.5)]`
kubectl version: `Client Version: v1.12.2 // Server Version: v1.11.2-gke.15`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin Aarons-2-Nutmeg-Mac.local 18.2.0 Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 129, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 64, in main
    socks_port, ssh = do_connect(runner, remote_info)
  File "/usr/local/bin/telepresence/telepresence/connect/__init__.py", line 158, in do_connect
    return connect(runner_, remote_info, is_container_mode, args.expose)
  File "/usr/local/bin/telepresence/telepresence/connect/__init__.py", line 115, in connect
    ssh.wait()
  File "/usr/local/bin/telepresence/telepresence/connect/ssh.py", line 79, in wait
    raise RuntimeError("SSH isn't starting.")
RuntimeError: SSH isn't starting.

```

Logs:

```
failed to execute portforward in network namespace "/var/run/netns/cni-8878cf7b-1215-e285-2570-b2251868c8ff": socat command returns error: exit status 1, stderr: "2018/11/09 11:38:37 socat[5417] E connect(5, AF=2 127.0.0.1:8022, 16): Connection refused\n"
  66.2 TEL | [175] exit 255 in 0.05 secs.
  66.5 TEL | [176] Running: ssh -F /dev/null -q -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -p 61993 telepresence@localhost /bin/true
  66.5  77 | Handling connection for 61993
  66.5  77 | E1109 11:38:38.111081   23377 portforward.go:331] an error occurred forwarding 61993 -> 8022: error forwarding port 8022 to pod 56b89ba3ad51cd199a3a3881d3f35bd645a277ce5f8866319f91c10d96765e44, uid : failed to execute portforward in network namespace "/var/run/netns/cni-8878cf7b-1215-e285-2570-b2251868c8ff": socat command returns error: exit status 1, stderr: "2018/11/09 11:38:38 socat[5424] E connect(5, AF=2 127.0.0.1:8022, 16): Connection refused\n"
  66.5 TEL | [176] exit 255 in 0.05 secs.

```

## Steps to reproduce

1. Create a GKE cluster with `1.11.2-gke.15` and ContainerD:

```bash
$ gcloud container clusters create telepresence --cluster-version 1.11.2-gke.15 --num-nodes 1 --image-type COS_CONTAINERD
...
NAME          LOCATION        MASTER_VERSION  MASTER_IP       MACHINE_TYPE   NODE_VERSION   NUM_NODES  STATUS
telepresence  europe-west1-c  1.11.2-gke.15   35.241.219.101  n1-standard-1  1.11.2-gke.15  1          RUNNING
$ gcloud container clusters get-credentials telepresence
Fetching cluster endpoint and auth data.
kubeconfig entry generated for telepresence.
```

2. Try to use telepresence with default options:

```bash
$ telepresence
T: Invoking sudo. Please enter your sudo password.
Password:
T: Starting proxy with method 'vpn-tcp', which has the following limitations: All processes are affected, only one telepresence can run per machine, and you can't use other VPNs. You may need to add cloud hosts and headless services with --also-proxy. For a full list of
T: method limitations see https://telepresence.io/reference/methods.html
T: Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.

Looks like there's a bug in our code. Sorry about that!

Here's the traceback:

Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 129, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 64, in main
    socks_port, ssh = do_connect(runner, remote_info)
  File "/usr/local/bin/telepresence/telepresence/connect/__init__.py", line 158, in do_connect
    return connect(runner_, remote_info, is_container_mode, args.expose)
  File "/usr/local/bin/telepresence/telepresence/connect/__init__.py", line 115, in connect
    ssh.wait()
  File "/usr/local/bin/telepresence/telepresence/connect/ssh.py", line 79, in wait
    raise RuntimeError("SSH isn't starting.")
RuntimeError: SSH isn't starting.
```

**Comment by ark3** [comment]
I haven't had time to replicate your setup exactly, but I may have fixed the permission issue you found. If you have a moment, can you please try the `0.94-36-gf8e3b12` image off of the master branch? It (or a descendant based on feedback) will end up in 0.95.

For example:

    TELEPRESENCE_VERSION=0.94-36-gf8e3b12 telepresence -m inject-tcp --run curl -sk https://kubernetes.default/api

Thank you.
