### ISSUE TITLE
Teleprecence crash on linux

### ISSUE THREAD

**Issue by Bedotech** [telepresenceio/telepresence#832]
### What were you trying to do?

I have tried to swap a deployment on minikube

### What did you expect to happen?

the deployment is swapped

### What happened instead?

The application crash

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--swap-deployment', 'obms-minikube', '--expose', '8080']`
Version: `0.90`
Python version: `3.7.1 (default, Oct 22 2018, 10:41:28) 
[GCC 8.2.1 20180831]`
kubectl version: `Client Version: v1.12.2 // Server Version: v1.10.0`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux bedotech 4.18.17-1-MANJARO #1 SMP PREEMPT Sun Nov 4 18:19:14 UTC 2018 x86_64 GNU/Linux`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 87, in call_f
    return f(*args, **kwargs)
  File "/usr/local/bin/telepresence/telepresence/main.py", line 110, in main
    mount_dir
  File "/usr/local/bin/telepresence/telepresence/local.py", line 167, in run_local_command
    connect_sshuttle(runner, remote_info, args, subprocesses, env, ssh)
  File "/usr/local/bin/telepresence/telepresence/vpn.py", line 313, in connect_sshuttle
    get_hellotelepresence()
  File "/usr/local/bin/telepresence/telepresence/vpn.py", line 297, in get_hellotelepresence
    format(next(counter))
  File "/usr/local/bin/telepresence/telepresence/runner.py", line 193, in get_output
    raise CalledProcessError(cpe_exc.returncode, cpe_exc.cmd, output)
subprocess.CalledProcessError: Command '['python3', '-c', "import socket; socket.gethostbyname('hellotelepresence78')"]' returned non-zero exit status 1.

```

Logs:

```
ot known
 156.4 TEL | [143] exit 1 in 0.16 secs.
 156.5 TEL | [144] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence76'"'"')'
 156.6 144 | Traceback (most recent call last):
 156.6 144 |   File "<string>", line 1, in <module>
 156.6 144 | socket.gaierror: [Errno -2] Name or service not known
 156.6 TEL | [144] exit 1 in 0.13 secs.
 156.7 TEL | [145] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence77'"'"')'
 156.9 145 | Traceback (most recent call last):
 156.9 145 |   File "<string>", line 1, in <module>
 156.9 145 | socket.gaierror: [Errno -2] Name or service not known
 156.9 TEL | [145] exit 1 in 0.13 secs.
 158.1 TEL | [146] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence78'"'"')'
 158.2 146 | Traceback (most recent call last):
 158.2 146 |   File "<string>", line 1, in <module>
 158.2 146 | socket.gaierror: [Errno -2] Name or service not known
 158.2 TEL | [146] exit 1 in 0.14 secs.

```

`python3` exists in my path.

**Comment by Bedotech** [comment]
Probably my fault, after a reboot of my machine everything goes alright
