### ISSUE TITLE
Telepresence crashes

### ISSUE THREAD

**Issue by galosa** [telepresenceio/telepresence#862]
### What were you trying to do?

swapping deployment 

### What did you expect to happen?

it works fine until it crashes

### What happened instead?

after some time it crashes 

(please tell us - the traceback is automatically included, see below)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--namespace', 'norm', '--swap-deployment', 'norm-consumer']`
Version: `0.93`
Python version: `3.7.1 (default, Nov  6 2018, 18:45:35) 
[Clang 10.0.0 (clang-1000.11.45.5)]`
kubectl version: `Client Version: v1.12.0 // Server Version: v1.10.5`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin Gals-MacBook-Pro.local 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 129, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 61, in main
    remote_info = start_proxy(runner)
  File "/usr/local/bin/telepresence/telepresence/proxy/__init__.py", line 90, in start_proxy
    run_id=run_id,
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 200, in get_remote_info
    wait_for_pod(runner, remote_info)
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 132, in wait_for_pod
    "Pod isn't starting or can't be found: {}".format(pod["status"])
RuntimeError: Pod isn't starting or can't be found: {'conditions': [{'lastProbeTime': None, 'lastTransitionTime': '2018-12-09T12:02:50Z', 'message': 'containers with incomplete status: [wait-for-services]', 'reason': 'ContainersNotInitialized', 'status': 'False', 'type': 'Initialized'}, {'lastProbeTime': None, 'lastTransitionTime': '2018-12-09T12:02:50Z', 'message': 'containers with unready status: [consumer]', 'reason': 'ContainersNotReady', 'status': 'False', 'type': 'Ready'}, {'lastProbeTime': None, 'lastTransitionTime': '2018-12-09T12:02:50Z', 'status': 'True', 'type': 'PodScheduled'}], 'containerStatuses': [{'image': 'datawire/telepresence-k8s:0.93', 'imageID': '', 'lastState': {}, 'name': 'consumer', 'ready': False, 'restartCount': 0, 'state': {'waiting': {'reason': 'PodInitializing'}}}], 'hostIP': '172.20.38.37', 'initContainerStatuses': [{'image': 'opsfleet/depends-on', 'imageID': '', 'lastState': {}, 'name': 'wait-for-services', 'ready': False, 'restartCount': 0, 'state': {'waiting': {'reason': 'PodInitializing'}}}], 'phase': 'Pending', 'qosClass': 'Burstable', 'startTime': '2018-12-09T12:02:50Z'}

```

Logs:

```
 get pod norm-consumer-5ad35cb50c114167b5acfd44b3e5e674-6f744bf65d-hzcd2 -o json
 137.7 TEL | [74] captured in 1.74 secs.
 138.0 TEL | [75] Capturing: kubectl --context dev-k8s.bigpanda.io --namespace norm get pod norm-consumer-5ad35cb50c114167b5acfd44b3e5e674-6f744bf65d-hzcd2 -o json
 139.7 TEL | [75] captured in 1.73 secs.
 140.0 TEL | [76] Capturing: kubectl --context dev-k8s.bigpanda.io --namespace norm get pod norm-consumer-5ad35cb50c114167b5acfd44b3e5e674-6f744bf65d-hzcd2 -o json
 141.7 TEL | [76] captured in 1.74 secs.
 142.0 TEL | [77] Capturing: kubectl --context dev-k8s.bigpanda.io --namespace norm get pod norm-consumer-5ad35cb50c114167b5acfd44b3e5e674-6f744bf65d-hzcd2 -o json
 143.8 TEL | [77] captured in 1.81 secs.
 144.0 TEL | [78] Capturing: kubectl --context dev-k8s.bigpanda.io --namespace norm get pod norm-consumer-5ad35cb50c114167b5acfd44b3e5e674-6f744bf65d-hzcd2 -o json
 145.8 TEL | [78] captured in 1.77 secs.
 145.8 TEL | END SPAN remote.py:111(wait_for_pod)  120.7s

```

**Comment by ark3** [comment]
Looks like the proxy pod doesn't start. Are you able to run a non-swap command successfully? E.g.,

    telepresence --run curl -sk https://kubernetes.default/api

Also, does the deployment you are swapping have any special properties? Init containers or strict resource limits or ...?
