### ISSUE TITLE
Telepresence crashes if the user command is not found (vpn-tcp)

### ISSUE THREAD

**Issue by ark3** [telepresenceio/telepresence#869]
E.g., 

```shell
$ telepresence --run asdf
T: Starting proxy with method 'vpn-tcp', which has the following limitations:  
T: All processes are affected, only one telepresence can run per machine, and 
T: you can't use other VPNs. You may need to add cloud hosts and headless 
T: services with --also-proxy. For a full list of method limitations see 
T: https://telepresence.io/reference/methods.html
T: Volumes are rooted at $TELEPRESENCE_ROOT. See 
T: https://telepresence.io/howto/volumes.html for details.

T: No traffic is being forwarded from the remote Deployment to your local      
T: machine. You can use the --expose option to specify which ports you want to 
T: forward.


Looks like there's a bug in our code. Sorry about that!

Traceback (most recent call last):
  File "/home/ark3/datawire/telepresence/telepresence/cli.py", line 131, in crash_reporting
    yield
  File "/home/ark3/datawire/telepresence/telepresence/main.py", line 84, in main
    runner, remote_info, env, socks_port, ssh, mount_dir, pod_info
  File "/home/ark3/datawire/telepresence/telepresence/outbound/setup.py", line 66, in launch
    runner_, remote_info, command, args.also_proxy, env, ssh
  File "/home/ark3/datawire/telepresence/telepresence/outbound/local.py", line 122, in launch_vpn
    process = Popen(command, env=env)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'asdf'                 

[...]
```

**Comment by ark3** [comment]
I suspect there's an older issue for this problem, but I could not find it...
