### ISSUE TITLE
Telepresence VPN-TCP can't connect after upgrade to 0.96

### ISSUE THREAD

**Issue by ricardocamposilva** [telepresenceio/telepresence#879]
Hello.
Yesterday I have upgraded my telepresence client version from 0.95 to 0.96, and after that I'm getting vpn connection errors, but I have libraries that can't use with "inject-tcp" method (gRPC)
Follow the traceback below:

```
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 131, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 84, in main
    runner, remote_info, env, socks_port, ssh, mount_dir, pod_info
  File "/usr/bin/telepresence/telepresence/outbound/setup.py", line 73, in launch
    runner_, remote_info, command, args.also_proxy, env, ssh
  File "/usr/bin/telepresence/telepresence/outbound/local.py", line 120, in launch_vpn
    connect_sshuttle(runner, remote_info, also_proxy, ssh)
  File "/usr/bin/telepresence/telepresence/outbound/vpn.py", line 290, in connect_sshuttle
    raise RuntimeError("vpn-tcp tunnel did not connect")
RuntimeError: vpn-tcp tunnel did not connect


Here are the last few lines of the logfile (see /home/ricardo/Documents/projects/CAOS/gaia-web/telepresence.log for the complete logs):

  43.6  25 | 2018-12-18T17:33:33+0000 [stdout#info] A query: b'localhost'
  43.6  25 | 2018-12-18T17:33:33+0000 [stdout#info] RESOLVING b'localhost.default.svc.cluster.local'
  43.6  25 | 2018-12-18T17:33:33+0000 [DNSDatagramProtocol (UDP)] DNSDatagramProtocol starting on 6753
  43.6  25 | 2018-12-18T17:33:33+0000 [DNSDatagramProtocol (UDP)] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7f9b079cd0f0>
  43.6  25 | 2018-12-18T17:33:33+0000 [stdout#info] FAILED to lookup b'localhost.default.svc.cluster.local' ([Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DNSNameError'>: <Message id=41340 rCode=3 maxSize=0 flags=answer,recDes,recAv queries=[Query('localhost.default.svc.cluster.local', 1, 1)] authority=[<RR name=cluster.local type=SOA class=IN ttl=60s auth=False>]>
  43.6  25 | 2018-12-18T17:33:33+0000 [stdout#info] ]), trying b'localhost'
  43.6  25 | 2018-12-18T17:33:33+0000 [-] (UDP Port 17243 Closed)
  43.6  25 | 2018-12-18T17:33:33+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7f9b079cd6d8>
  43.6  25 | 2018-12-18T17:33:33+0000 [stdout#info] FAILED to lookup b'localhost.default.svc.cluster.local' ([Failure instance: Traceback (failure with no frames): <class 'twisted.names.error.DNSNameError'>: <Message id=2980 rCode=3 maxSize=0 flags=answer,recDes,recAv queries=[Query('localhost.default.svc.cluster.local', 1, 1)] authority=[<RR name=cluster.local type=SOA class=IN ttl=60s auth=False>]>
  43.6  25 | 2018-12-18T17:33:33+0000 [stdout#info] ]), trying b'localhost'
  43.6  25 | 2018-12-18T17:33:33+0000 [-] (UDP Port 6753 Closed)
  43.6  25 | 2018-12-18T17:33:33+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7f9b079cd0f0>
```

**Comment by ark3** [comment]
Sorry we broke things for you with the new release! Could you please pass along the full telepresence.log as a [Gist](https://gist.github.com/)? Feel free to hide any sensitive data using search-and-replace. Thank you!

**Comment by ricardocamposilva** [comment]
@ark3 thanks for your attention, follow the gist as required.

https://gist.github.com/ricardocamposilva/be3a00ad98d35fa7915180c2f8af6de3

**Comment by ark3** [comment]
It looks like there's a bad interaction between a new sanity check I added, slow DNS lookups, and Tel's DNS-loop prevention. Sorry to break things. I'll release a fix soon.

**Comment by jshearer** [comment]
Any idea when this fix will get included in a release? I just got caught by this too.

Thanks! :)

**Comment by ricardocamposilva** [comment]
> Any idea when this fix will get included in a release? I just got caught by this too.
> 
> Thanks! :)

@jshearer I made a rollback to keep using without this issue, if you don't use any library that use direct injection you could use --method inject-tcp, for me it doesn't work properly because I use gRPC, but it's in my plans to be removed to use telepresence freely

**Comment by ark3** [comment]
@jshearer Could I take a look at your crash log too? The change I have in mind might or might not fix the above.
