### ISSUE TITLE
Telepresence fails to start with RuntimeError: SSH isn't starting. in log

### ISSUE THREAD

**Issue by Dimss** [telepresenceio/telepresence#885]
### What were you trying to do?
Trying to start telepresence and connect to the OpenShift cluster

### What did you expect to happen?
telepresence should start successfully 

### What happened instead?
telepresence fail to start with `RuntimeError: SSH isn't starting.` 

### Automatically included information

Command line: `['/usr/local/bin/telepresence']`
Version: `0.96`
Python version: `3.7.1 (default, Nov  6 2018, 18:45:35) 
[Clang 10.0.0 (clang-1000.11.45.5)]`
kubectl version: `Client Version: v1.12.2 // Server Version: v1.11.0+d4cacc0`
oc version: `oc v3.11.0+0cbc58b // kubernetes v1.11.0+d4cacc0 // features: Basic-Auth //  // Server https://master.europe-north1-a.c.dimitry-218810.internal:8443 // openshift v3.11.51 // kubernetes v1.11.0+d4cacc0`
OS: `Darwin dimasmac 18.2.0 Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 131, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 70, in main
    socks_port, ssh = do_connect(runner, remote_info)
  File "/usr/local/bin/telepresence/telepresence/connect/connect.py", line 99, in do_connect
    return connect(runner_, remote_info, is_container_mode, args.expose)
  File "/usr/local/bin/telepresence/telepresence/connect/connect.py", line 57, in connect
    ssh.wait()
  File "/usr/local/bin/telepresence/telepresence/connect/ssh.py", line 82, in wait
    raise RuntimeError("SSH isn't starting.")
RuntimeError: SSH isn't starting.

```

Logs:

```
ling connection for 51894
  36.8  41 | Connection to 127.0.0.1 closed by remote host.
  36.8 TEL | [41] exit 255 in 1.32 secs.
  37.1 TEL | [42] Running: ssh -F /dev/null -q -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -p 51894 telepresence@127.0.0.1 /bin/true
  37.1  20 | Handling connection for 51894
  38.6  42 | Connection to 127.0.0.1 closed by remote host.
  38.6 TEL | [42] exit 255 in 1.51 secs.
  38.8 TEL | [43] Running: ssh -F /dev/null -q -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -p 51894 telepresence@127.0.0.1 /bin/true
  38.8  20 | Handling connection for 51894
  40.3  43 | Connection to 127.0.0.1 closed by remote host.
  40.3 TEL | [43] exit 255 in 1.43 secs.
  40.5 TEL | [44] Running: ssh -F /dev/null -q -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -p 51894 telepresence@127.0.0.1 /bin/true
  40.5  20 | Handling connection for 51894
  41.8  44 | Connection to 127.0.0.1 closed by remote host.
  41.8 TEL | [44] exit 255 in 1.25 secs.

```

**Comment by ark3** [comment]
The Telepresence pod does not require root (UID 0) unless you want to expose a low-numbered port. However, it does require being able to run as UID 1000, which is arbitrary, but [hard-coded](https://github.com/telepresenceio/telepresence/blob/0.96/k8s-proxy/Dockerfile#L43).

Does OpenShift run the pod with a randomly-generated UID? We don't have a lot of experience with OpenShift, so I might have misunderstood what's going on.

**Comment by Dimss** [comment]
@ark3, by default OpenShift will pickup random UID to run the process inside container. This is a default behaviour of default `Secure Container Context (SCC)` policy.  
So, to run the Telepresence pod inside OpenShift, you ether should not hard code the UID or specify somewhere in the docs that in case of OpenShift, user will have to create a custom SCC which will allow anyuid for the container.

**Comment by JCzz** [comment]
Same here

```
Looks like there's a bug in our code. Sorry about that!

Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 131, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 84, in main
    runner, remote_info, env, socks_port, ssh, mount_dir, pod_info
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 95, in launch
    mount_dir, pod_info
  File "/usr/local/bin/telepresence/telepresence/outbound/container.py", line 153, in run_docker_command
    local_ssh.wait()
  File "/usr/local/bin/telepresence/telepresence/connect/ssh.py", line 82, in wait
    raise RuntimeError("SSH isn't starting.")
RuntimeError: SSH isn't starting.


Here are the last few lines of the logfile (see /Users/christian/Development/projects/appsyouwear/golang/facebookgo/telepresence.log for the complete logs):

  34.7  20 | Traceback (most recent call last):
  34.7  20 |   File "/usr/bin/entrypoint.py", line 130, in <module>
  34.7  20 |     main()
  34.7  20 |   File "/usr/bin/entrypoint.py", line 65, in main
  34.7  20 |     proxy(loads(sys.argv[2]))
  34.7  20 |   File "/usr/bin/entrypoint.py", line 81, in proxy
  34.7  20 |     ssh.wait()
  34.7  20 |   File "/usr/lib/python3.6/site-packages/telepresence/connect/ssh.py", line 82, in wait
  34.7  20 |     raise RuntimeError("SSH isn't starting.")
  34.7  20 | RuntimeError: SSH isn't starting.
  34.7  20 | [INFO  tini (1)] Main child exited normally (with status '1')
  35.0 TEL | [20] exit 1

```
