### ISSUE TITLE
bug automatically generated by telepresence

### ISSUE THREAD

**Issue by ghost** [telepresenceio/telepresence#893]
### What were you trying to do?

(please tell us)

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--namespace', 'dev', '--also-proxy', '172.21.0.0/16']`
Version: `0.92`
Python version: `3.7.0 (default, Aug 22 2018, 15:22:33) 
[Clang 9.1.0 (clang-902.0.39.2)]`
kubectl version: `Client Version: v1.11.2 // Server Version: v1.11.6`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin SeungyupuiiMac2 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/telepresence/0.92/libexec/lib/python3.7/site-packages/telepresence/cli.py", line 129, in crash_reporting
    yield
  File "/usr/local/Cellar/telepresence/0.92/libexec/lib/python3.7/site-packages/telepresence/main.py", line 78, in main
    runner, remote_info, env, socks_port, ssh, mount_dir
  File "/usr/local/Cellar/telepresence/0.92/libexec/lib/python3.7/site-packages/telepresence/outbound/__init__.py", line 60, in launch
    runner_, remote_info, command, args.also_proxy, env, ssh
  File "/usr/local/Cellar/telepresence/0.92/libexec/lib/python3.7/site-packages/telepresence/outbound/local.py", line 121, in launch_vpn
    connect_sshuttle(runner, remote_info, also_proxy, ssh)
  File "/usr/local/Cellar/telepresence/0.92/libexec/lib/python3.7/site-packages/telepresence/outbound/vpn.py", line 290, in connect_sshuttle
    get_hellotelepresence()
  File "/usr/local/Cellar/telepresence/0.92/libexec/lib/python3.7/site-packages/telepresence/outbound/vpn.py", line 274, in get_hellotelepresence
    format(next(counter))
  File "/usr/local/Cellar/telepresence/0.92/libexec/lib/python3.7/site-packages/telepresence/runner/__init__.py", line 329, in get_output
    raise CalledProcessError(cpe_exc.returncode, cpe_exc.cmd, output)
subprocess.CalledProcessError: Command '['python3', '-c', "import socket; socket.gethostbyname('hellotelepresence23')"]' returned non-zero exit status 1.

```

Logs:

```
 0x7f3616c206a0>
  17.1  19 | 2019-01-08T04:36:06+0000 [-] Loaded.
  17.1  19 | 2019-01-08T04:36:06+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 18.7.0 (/usr/bin/python3.6 3.6.1) starting up.
  17.1  19 | 2019-01-08T04:36:06+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.epollreactor.EPollReactor.
  17.2  28 | c : DNS request from ('192.168.2.195', 50547) to None: 37 bytes
  17.2  19 | 2019-01-08T04:36:06+0000 [stdout#info] Set DNS suffix we filter out to: [()]
  17.2  19 | 2019-01-08T04:36:06+0000 [stdout#info] Result for b'hellotelepresence22' is ['127.0.0.1']
  17.3 TEL | [51] captured in 3.06 secs.
  18.3 TEL | [52] Capturing: python3 -c 'import socket; socket.gethostbyname('"'"'hellotelepresence23'"'"')'
  18.3  52 | Traceback (most recent call last):
  18.3  52 |   File "<string>", line 1, in <module>
  18.3  52 | socket.gaierror: [Errno 8] nodename nor servname provided, or not known
  18.3 TEL | [52] exit 1 in 0.04 secs.

```

**Comment by ark3** [comment]
Sorry about the crash! Could you please try again with the latest version? If that fails too, I would appreciate a link to the full log as a [Gist](https://gist.github.com). Thank you.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
