### ISSUE TITLE
ssh doesn't start  while running telepresence in swap deploment mode

### ISSUE THREAD

**Issue by ishan-puranik** [telepresenceio/telepresence#894]
### What were you trying to do?

trying to run telepresence for swap deployment

### What did you expect to happen?

run well as in previous instances

### What happened instead?

It didn't work, unlike previous instances. Gave me an error indicating that ssh isn't starting

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--swap-deployment', 'dm-dsm-ncn-706', '--method', 'vpn-tcp', '--expose', '8090:80', '--also-proxy', 'master.commerce.dev.niki.ai', '--also-proxy', '169.254.169.254', '--also-proxy', 'redis.dev.niki.ai', '--env-json', 'dm.json']`
Version: `0.93`
Python version: `3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]`
kubectl version: `Client Version: v1.13.1 // Server Version: v1.10.6`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux lenovoadmin-ThinkPad-E470 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 129, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 64, in main
    socks_port, ssh = do_connect(runner, remote_info)
  File "/usr/local/bin/telepresence/telepresence/connect/__init__.py", line 158, in do_connect
    return connect(runner_, remote_info, is_container_mode, args.expose)
  File "/usr/local/bin/telepresence/telepresence/connect/__init__.py", line 115, in connect
    ssh.wait()
  File "/usr/local/bin/telepresence/telepresence/connect/ssh.py", line 79, in wait
    raise RuntimeError("SSH isn't starting.")
RuntimeError: SSH isn't starting.

```

Logs:

```
in/true
 289.2 TEL | [131] exit 255 in 0.02 secs.
 289.5 TEL | [132] Running: ssh -F /dev/null -q -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -p 38769 telepresence@localhost /bin/true
 289.5 TEL | [132] exit 255 in 0.02 secs.
 289.8 TEL | [133] Running: ssh -F /dev/null -q -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -p 38769 telepresence@localhost /bin/true
 289.8 TEL | [133] exit 255 in 0.01 secs.
 290.0 TEL | [134] Running: ssh -F /dev/null -q -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -p 38769 telepresence@localhost /bin/true
 290.0 TEL | [134] exit 255 in 0.02 secs.
 290.3 TEL | [135] Running: ssh -F /dev/null -q -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -p 38769 telepresence@localhost /bin/true
 290.3 TEL | [135] exit 255 in 0.02 secs.
 290.6 TEL | [136] Running: ssh -F /dev/null -q -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -p 38769 telepresence@localhost /bin/true
 290.6 TEL | [136] exit 255 in 0.01 secs.

```

**Comment by ishan-puranik** [comment]
I tried the suggestions on removing stuff from /etc/hosts but, it didn't work

**Comment by ishan-puranik** [comment]
I tried the latest version of telepresence as well and that produced the same error as well

**Comment by ishan-puranik** [comment]
This was resolved on changing the network the system was on.
