### ISSUE TITLE
telepresence crash

### ISSUE THREAD

**Issue by KirillMoizik** [telepresenceio/telepresence#919]
### What were you trying to do?

telepresence --swap-deployment core-server-mobile-deployment  --docker-run -i -t alpine /bin/sh

### What did you expect to happen?

expected to get an interactive shell in the context of the running pod (secrets, env etc)

### What happened instead?

 process stuck and didn't connect

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--swap-deployment', 'core-server-mobile-deployment', '--docker-run', '-i', '-t', 'alpine', '/bin/sh']`
Version: `0.97`
Python version: `3.7.2 (default, Jan 13 2019, 12:50:01) 
[Clang 10.0.0 (clang-1000.11.45.5)]`
kubectl version: `Client Version: v1.10.0 // Server Version: v1.10.11`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin ip-10-64-20-25.ec2.internal 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 130, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 77, in main
    runner, remote_info, env, socks_port, ssh, mount_dir, pod_info
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 95, in launch
    mount_dir, pod_info
  File "/usr/local/bin/telepresence/telepresence/outbound/container.py", line 168, in run_docker_command
    TELEPRESENCE_LOCAL_IMAGE, "wait"
  File "/usr/local/bin/telepresence/telepresence/runner/runner.py", line 346, in check_call
    track, "Running", "ran", out_cb, err_cb, args, **kwargs
  File "/usr/local/bin/telepresence/telepresence/runner/runner.py", line 335, in _run_command
    raise CalledProcessError(retcode, args)
subprocess.CalledProcessError: Command '['docker', 'run', '--network=container:telepresence-1549380728-442745-30479', '--rm', 'datawire/telepresence-local:0.97', 'wait']' returned non-zero exit status 1.

```

Logs:

```
e: 54 bytes
  68.5  41 | c : DNS request from ('172.17.0.2', 49394) to None: 54 bytes
  68.7  41 | c : DNS request from ('172.17.0.2', 60433) to None: 54 bytes
  69.0  41 | c : DNS request from ('172.17.0.2', 34971) to None: 54 bytes
  69.5  41 | c : DNS request from ('172.17.0.2', 40636) to None: 54 bytes
  69.8  41 | c : DNS request from ('172.17.0.2', 47318) to None: 54 bytes
  70.1  41 | c : DNS request from ('172.17.0.2', 36527) to None: 54 bytes
  70.4  41 | c : DNS request from ('172.17.0.2', 55687) to None: 54 bytes
  70.7  41 | c : DNS request from ('172.17.0.2', 45611) to None: 54 bytes
  71.0  41 | c : DNS request from ('172.17.0.2', 39955) to None: 54 bytes
  71.2  41 | c : DNS request from ('172.17.0.2', 49209) to None: 54 bytes
  71.6  41 | c : DNS request from ('172.17.0.2', 58677) to None: 54 bytes
  71.9  46 | Failed to connect to proxy in remote cluster.
  71.9  46 | [INFO  tini (1)] Main child exited normally (with status '1')
  72.2 TEL | [46] exit 1 in 30.93 secs.

```

**Comment by ark3** [comment]
Sorry about the crash. Can you please pass along the entire telepresence.log file as a [Gist](https://gist.github.com/)? Thank you.
