### ISSUE TITLE
crash for unknown reason

### ISSUE THREAD

**Issue by farnsworth2008** [telepresenceio/telepresence#941]
### What were you trying to do?

Just trying to launch telepresence.

### What did you expect to happen?

It usually works but this morning it did not.

### What happened instead?

It crashed :( 

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--expose', '8083', '--swap-deployment', 'medlio-shimmer', '--env-json', 'medlio-shimmer-main/telepresence.json']`
Version: `0.97`
Python version: `3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 03:13:28) 
[Clang 6.0 (clang-600.0.57)]`
kubectl version: `Client Version: v1.11.3 // Server Version: v1.11.5`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin eu2-179.finevpn.com 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64`

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 130, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 77, in main
    runner, remote_info, env, socks_port, ssh, mount_dir, pod_info
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 73, in launch
    runner_, remote_info, command, args.also_proxy, env, ssh
  File "/usr/local/bin/telepresence/telepresence/outbound/local.py", line 121, in launch_vpn
    connect_sshuttle(runner, remote_info, also_proxy, ssh)
  File "/usr/local/bin/telepresence/telepresence/outbound/vpn.py", line 295, in connect_sshuttle
    raise RuntimeError("vpn-tcp tunnel did not connect")
RuntimeError: vpn-tcp tunnel did not connect

```

Logs:

```
 sshuttle-12300 -f /dev/stdin
  37.4  36 | >> pfctl -E
  37.5  36 | c : DNS request from ('92.240.245.179', 51877) to None: 69 bytes
  37.8  16 | 2019-02-26T14:51:44+0000 [stdout#info] Sanity check: b'hellotelepresence-12.a.sanity.check.telepresence.io'
  38.5  36 | c : DNS request from ('92.240.245.179', 51877) to None: 69 bytes
  38.8  16 | 2019-02-26T14:51:45+0000 [stdout#info] Sanity check: b'hellotelepresence-12.a.sanity.check.telepresence.io'
  43.5  36 | c : DNS request from ('92.240.245.179', 51877) to None: 69 bytes
  43.8  16 | 2019-02-26T14:51:50+0000 [stdout#info] Sanity check: b'hellotelepresence-12.a.sanity.check.telepresence.io'
  44.2 TEL | (proxy checking local liveness)
  44.5  16 | 2019-02-26T14:51:50+0000 [Poll#info] Checkpoint
  47.5  36 | c : DNS request from ('92.240.245.179', 51877) to None: 69 bytes
  47.8  16 | 2019-02-26T14:51:54+0000 [stdout#info] Sanity check: b'hellotelepresence-12.a.sanity.check.telepresence.io'
  63.5 TEL | [38] Running: sudo -n echo -n

```

**Comment by farnsworth2008** [comment]
This was because I was running a VPN.
