### ISSUE TITLE
Can't start telepresence after MacOS upgrade

### ISSUE THREAD

**Issue by dodalovic** [telepresenceio/telepresence#962]
```
uname -a
Darwin macbookpro-dod.local 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64
```

```
telepresence
T: Starting proxy with method 'vpn-tcp', which has the following limitations: All processes are affected, only one telepresence can run per machine, and you can't use other VPNs. You
T: may need to add cloud hosts and headless services with --also-proxy. For a full list of method limitations see https://telepresence.io/reference/methods.html
T: Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.
T: Starting network proxy to cluster using new Deployment telepresence-1553603199-500542-5653

Looks like there's a bug in our code. Sorry about that!

Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 130, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 60, in main
    remote_info = start_proxy(runner)
  File "/usr/local/bin/telepresence/telepresence/proxy/__init__.py", line 104, in start_proxy
    run_id=run_id,
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 156, in get_remote_info
    runner, deployment_name, deployment_type, run_id=run_id
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 101, in get_deployment_json
    stderr=STDOUT
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)


Here are the last few lines of the logfile (see /mls/docs/telepresence.log for the complete logs):

   1.5 TEL | Scout info: {'latest_version': '0.97', 'application': 'telepresence', 'notices': []}
   1.5 TEL | BEGIN SPAN deployment.py:61(create_new_deployment)
   1.5 >>> | Starting network proxy to cluster using new Deployment telepresence-1553603199-500542-5653
   1.5 TEL | [9] Capturing: kubectl --context mls-dev-cloud --namespace mip-playground delete --ignore-not-found svc,deploy --selector=telepresence=13a43acf25ea40c8a0142e810d2997e8
   2.1 TEL | [10] Capturing: kubectl --context mls-dev-cloud --namespace mip-playground run --restart=Always --limits=cpu=100m,memory=256Mi --requests=cpu=25m,memory=64Mi telepresence-1553603199-500542-5653 --image=datawire/telepresence-k8s:0.97 --labels=telepresence=13a43acf25ea40c8a0142e810d2997e8
   2.4  10 | kubectl run --generator=deployment/apps.v1 is DEPRECATED and will be removed in a future version. Use kubectl run --generator=run-pod/v1 or kubectl create instead.
   2.6  10 | deployment.apps/telepresence-1553603199-500542-5653 created
   2.6 TEL | END SPAN deployment.py:61(create_new_deployment)    1.1s
   2.6 TEL | BEGIN SPAN remote.py:154(get_remote_info)
   2.6 TEL | BEGIN SPAN remote.py:78(get_deployment_json)
   2.6 TEL | [11] Capturing: kubectl --context mls-dev-cloud --namespace mip-playground get deployment -o json --export --selector=telepresence=13a43acf25ea40c8a0142e810d2997e8
   2.8 TEL | END SPAN remote.py:78(get_deployment_json)    0.2s

Would you like to file an issue in our issue tracker? You'll be able to review and edit before anything is posted to the public. We'd really appreciate the help improving our product. [Y/n]: ^CT: Exit cleanup in progress
T: Cleaning up Deployment telepresence-1553603199-500542-5653
Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 130, in crash_reporting
  File "/usr/local/bin/telepresence/telepresence/main.py", line 60, in main
  File "/usr/local/bin/telepresence/telepresence/proxy/__init__.py", line 104, in start_proxy
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 156, in get_remote_info
  File "/usr/local/bin/telepresence/telepresence/proxy/remote.py", line 101, in get_deployment_json
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/telepresence/__main__.py", line 3, in <module>
  File "/usr/local/bin/telepresence/telepresence/main.py", line 87, in run_telepresence
  File "/usr/local/bin/telepresence/telepresence/main.py", line 80, in main
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 151, in crash_reporting
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 104, in report_crash
KeyboardInterrupt
```

```
telepresence --version
0.97
```

**Comment by edclement** [comment]
if you're using `kubectl` 1.14.0 this is probably a dup of #963

**Comment by ark3** [comment]
Handling this in #966
