### ISSUE TITLE
c

### ISSUE THREAD

**Issue by denistiago** [telepresenceio/telepresence#974]
### What were you trying to do?

(please tell us)

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--namespace', 'mip-ppr', '--run-shell', '--method', 'vpn-tcp']`
Version: `0.90`
Python version: `3.6.5 (default, Jun 17 2018, 12:13:06) 
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]`
kubectl version: `Client Version: v1.9.0 // Server Version: v1.13.3`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin macbook-dsi.office.mls 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/telepresence/0.90/libexec/lib/python3.6/site-packages/telepresence/cli.py", line 87, in call_f
    return f(*args, **kwargs)
  File "/usr/local/Cellar/telepresence/0.90/libexec/lib/python3.6/site-packages/telepresence/main.py", line 49, in main
    session.kube_info, session.runner = analyze_args(session)
  File "/usr/local/Cellar/telepresence/0.90/libexec/lib/python3.6/site-packages/telepresence/startup.py", line 162, in analyze_args
    runner = Runner(output, kube_info.command, args.verbose)
  File "/usr/local/Cellar/telepresence/0.90/libexec/lib/python3.6/site-packages/telepresence/runner.py", line 65, in __init__
    self.cache = Cache.load(os.path.join(cache_dir, "cache.json"))
  File "/usr/local/Cellar/telepresence/0.90/libexec/lib/python3.6/site-packages/telepresence/cache.py", line 43, in load
    cache = json.load(f)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

Logs:

```
   0.0 TEL | Telepresence 0.90 launched at Mon Apr  1 18:17:07 2019
   0.0 TEL |   /usr/local/bin/telepresence --namespace mip-ppr --run-shell --method vpn-tcp
   0.4 TEL | Context: production, namespace: mip-ppr, kubectl_command: kubectl
   0.4 TEL | [1] Launching: kubectl version --short
   0.4 TEL | [2] Launching: oc version
   0.4 TEL | [2] [Errno 2] No such file or directory: 'oc': 'oc'
   0.4 TEL | [3] Launching: uname -a
   0.4 TEL | Python 3.6.5 (default, Jun 17 2018, 12:13:06)
   0.4 TEL | [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]

```

**Comment by ark3** [comment]
Sorry about the crash! I believe this bug has been fixed. Can you please try the latest version of Telepresence?

**Comment by denistiago** [comment]
Working now. Thanks
